#!/usr/bin/env bash
#-x (debug) -v (verbose)
. function.sh || exit

usage()
{
	echot "\
usage: FileInfo FILE
	Display information about the specified file"
	exit $1
}

args()
{
	unset -v file
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			*)
				! IsOption "$1" && [[ ! $file ]] && { file="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	[[ ! $file ]] && MissingOperand "file"							# missing argument
	[[ ! -f "$file" ]] && { EchoErr "FileInfo: cannot access \`$file\`: No such file"; return 1; }
	args=("$@")
}

init() { :; }
run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }

cdCommand() { echo "/tmp"; }

# Notes:
# - GetFunction - get a function case-insensitive

# oneCommand - return results and set in parent using ScriptEval
oneCommand() 
{  
	vars=(a b c files); local a=1 b=2 c=3 files=("file 1.txt" "file 2.txt")
	ScriptReturn $show "${vars[@]}"
}

twoCommand() {  ElevationRequired; echo "command=$command"; }
threeCommand() { ! IsElevated && { sudo --hide template three; return; }; echo "command=$command"; }

subCommand()
{
	# detailed sub command: see SqlServer
	local command; CheckSubCommand sub "$1"; shift
	local name="$1"; shift; [[ ! $name ]] && MissingOperand "name"; 
	[[ $# != 0 ]] && UnknownOption "$1"
	Sub${command}Command "$@"
}

SubOneCommand() { echo "command=Sub$command args=${#args[@]} file=\"$file\" server=\"$server\" interactive=$interactive verbose=$verbose test=$test"; }
SubTwoCommand() { echo "command=Sub$command"; }

argCommand()
{
	GetArg "$@"; shift $?
	echo "\$#=$# arg1=$arg1 arg2=$arg2"
	args=("$@")
}

GetArg()
{
	[[ $# == 0 ]] && MissingOperand "arg1"; arg1="$1"; shift
	[[ "$arg1" == "more" ]] && { [[ $# == 0 ]] && MissingOperand "arg2"; arg2="$1"; shift; }
	return $(( ${#args[@]} - $# ))
}

returnVarsCommand()
{
	vars=( vsName vsVersion vsDir vsPath vsHelp vsIde vsRegistryKey vsVars vsData ) 
	ScriptReturn $show "${vars[@]}" # -s|--show
}

run "$@"
