#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|signin|start|startup](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

	case "$PLATFORM" in
		mac) program="TBD";;
		win) program="$UADATA/1Password/app/8/1Password.exe";;
		*) unset program;;
	esac

	return 0
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsTaskRunning "$(GetFileName "$program")"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }

signinCommand()
{
	local url; url="$(credential get 1Password url --fallback)" || return
	local email; email="$(credential get 1Password email --fallback)" || return
	local key; key="$(credential get 1Password SecretKey --fallback)" || return
	op signin "$url" "$email" "$key" --cache || return
}

									 
ScriptRun "$@"
