#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... configure|pe
Windows Application and Development Kit utilities"
}

usageVerbose()
{
	ScriptUsageEcho "
Locations:
			application: $adkDir
				   PE dir: $peDir
	 	 cloud PE dir: $cloudDir

Configuration:
	Windows Version: $winVer"
}

init() 
{
	# variables
	winVersion="22581"
	adkDir="$P32/Windows Kits/10/Assessment and Deployment Kit"
	cloudDir="$(ConfigGet confDir)/WinPE"
	imageManager="$adkDir/Deployment Tools/WSIM/imgmgr.exe" 
	peDir="$DATA/appdataw/WinPE"
	winPeDir="$WIN_ROOT/WinPE_amd64"

	# validate
	ScriptOnlyWin || return
	if [[ ! -d "$adkDir" ]]; then
		EchoErr "adk: the Windows Assessment and Deployment Kit is not installed"
		exit 1
	fi

	# configure
	[[ ! -d "$peDir" ]] && { ${G}mkdir --parents "$peDir" || return; }

	return 0
}

#
# configure command
#

configureUsage()
{
	echot "Usage: $(ScriptName) configure
Configure the unattended Windows installation file"
}

configureCommand()
{
	checkCloudDir || return
	getNetBootPeDir || return

	# copy catalog files
	local dir="$peDir/configure"; 
	[[ ! -d "$dir" ]] && { ${G}mkdir --parents "$dir" || return; }
	[[ ! -f "$dir/install_Windows 10 Pro.clg" ]] && { cp "$cloudDir/configure/"*.clg "$dir" || return; }
	[[ ! -f "$dir/install.wim" ]] && { CopyFileProgress "$nbDir/appdata/netbootxyz/windows/$winVersion/sources/install.wim" "$dir" || return; }

	# run the image manager
	pushd "$cloudDir/configure" || return
	"$imageManager" autounattend.xml -d distribution
	popd || return

	# copy the new unattend.xml file
	cp "$cloudDir/configure/autounattend.xml" "$nbDir/appdata/netbootxyz/windows/$winVersion" || return
}

#
# pe command
#

peCommitCommand() { pe commit; }
peDiscardCommand() { pe discard; }
peIsoCommand() { pe iso; }
peMountCommand() { pe mount; }

peUsage()
{
	echot "Usage: $(ScriptName) pe [make|bak|commit|discard|mount|iso|copy|nbcopy](make)

	make 			perform all the steps to make and deploy the WinPE image
	copy 			Copy and extract the WinPE ISO to the appdata directory for better disk performance
	nbcopy 		Copy the extracted the WinPE ISO to the netboot.xyz asset directory"
}

peCommand() { peMakeCommand; }

peMakeCommand()
{
	if [[ ! -d "$winPeDir" ]]; then
		hilight "Creating pe directory..."
		pe create || return
	fi

	hilight "Mounting boot image..."
	pe mount || return

	if IsElevated; then
		echo "Make modifications then exit this shell..."
		( cd "$winPeDir/mount"; zsh; )
	else
		start --elevate wt.exe -d "$winPeDir/mount"
		pause "Make modifications in the elevated terminal then press any key to continue..."
	fi

	if ! ask "Do you want to commit the changes to the boot image" -dr n; then
		hilight "Discarding changes to the boot image..."
		pe discard || return		
		exit 1
	fi	 
	
	hilight "Commiting changes to the boot image..."
	pe commit || return

	hilight "Creating the boot ISO..."
	pe iso || return

	hilight "Copying and extracting the PE image to $peDir..."
	peCopyCommand || return

	hilight "Updating the netboot.xyz WinPE image..."
	peNbcopyCommand || return
}

peBakCommand()
{	
	checkCloudDir || return
	CopyFileProgress "$winPeDir/media/sources/boot.wim" "$cloudDir" || return
}

peCopyCommand()
{
	CopyFileProgress "$winPeDir/WinPE_amd64.iso" "$peDir" || return
	7z x "$peDir/WinPE_amd64.iso" -o"$peDir/WinPE_amd64" -y || return
}

peNbcopyCommand()
{
	getNetBootPeDir || return

	local dest="$nbDir/appdata/netbootxyz/windows/WinPE/x64"

	# copy the Windows PE network boot files
	local nbPeDir="$nbDir/appdata/netbootxyz/windows/WinPE/x64"
	${G}mkdir --parents "$nbPeDir" || return
	CopyDir --recursive "$peDir/WinPE_amd64/" "$nbPeDir" || return

	# copy the Windows PE ISO image
	local nbIsoDir="$nbDir/appconfig/netbootxyz/menus/ipxe"
	${G}mkdir --parents "$nbIsoDir" || return
	CopyFileProgress "$peDir/WinPE_amd64.iso" "$nbIsoDir" || return
}

#
# helper
#

checkCloudDir() 
{ 
	[[ -d "$cloudDir" ]] && return 0
	EchoErr "adk: cloud backup directory ($cloudDir) does not exist"
	return 1
}

getNetBootPeDir() { nbDir="$(unc mount //$(GetServer "file")/root/usr/local/data)"; }

pe()
{
	local prefix; ! IsElevated && prefix="RunScript --elevate"
	$prefix cmd.exe /c WinPe.cmd "$1"
}

ScriptRun "$@"

