#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|close|profile|program|IsInstalled|IsRunning|version](start)
Alfred commands."
}

init()
{
	defaultCommand="start"
	profileName="Alfred" profileDir="$UDATA/app/Alfred" profileMask="*"
	program="$P/Alfred 5.app"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose --force "$program"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "Alfred"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); return 0; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { isRunningCommand && return; startCommand; }

versionCommand()
{
	AppInstallCheck || return

	local v; v="$(defaults read "$program/Contents/Info.plist" CFBundleShortVersionString)" || return
	local buid; build="$(defaults read "$program/Contents/Info.plist" CFBundleVersion)" || return
	printf "${v}_${build}"
}

ScriptRun "$@"
