#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|close|profile|program|IsInstalled|IsRunning](start)
AltTab commands."
}

init()
{
	defaultCommand="start"
	profileName="AltTab" profileDir="$HOME/Library/Preferences" profileMask="com.lwouis.alt-tab-macos.plist"
	program="$P/AltTab.app"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); return 0; }
startCommand() { AppInstallCheck && open -a "$(GetFileNameWithoutExtension "$program")"; }
startupCommand() { startCommand; }

#
# Profile Command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }

profileCommand()
{
	[[ "$command" == "restore" ]] && { closeCommand || return; }
	profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}" || return
	[[ "$command" == "restore" ]] && { startCommand || return; }
	return 0
}

ScriptRun "$@"
