#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

program="$CODE/Antidote/source/Antidote/bin/Debug/Antidote.exe"
([[ ! -f "$program" ]] || echo "$@" | grep -i  'App=Antidote' >& /dev/null) && program="$P/Antidote/Antidote.exe"
[[ ! -f "$program" ]] && { echo "antidote: could not locate Antidote"; exit 1; }
export -n PLATFORM # msbuild uses PLATFORM variable

"$program" "$@"
result=$?
export PLATFORM
exit $result