#!/usr/bin/env bash
. function.sh || exit

program="$CODE/Antidote/Antidote/bin/Debug/Antidote.exe"
[[ ! -f "$program" ]] && program="$P/Antidote/Antidote.exe"
[[ ! -f "$program" ]] && { echo "antidote: could not locate Antidote"; exit 1; }
export -n PLATFORM # msbuild uses PLATFORM variable
"$program" "$@"
result=$?
export PLATFORM
return $result