#!/bin/bash
. function.sh || exit

program="$CODE/Antidote/Antidote/bin/Debug/Antidote.exe" 
[[ ! -f "$program" ]] && program="$P/Antidote/Antidote.exe"
[[ ! -f "$program" ]] && { echo "antidote: could not locate Antidote"; exit 1; }
"$program" "$@"
