#!/usr/bin/env bash
. script.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [COMMAND]... [OPTION]...
Additional Apache web server functionality.
	
	log			show the log file
	dir			return directories"
}

init()
{
	# Ubuntu package defaults
	confDir="/etc/apache2"
	logDir="/var/log/apache2"
	webDir="/var/www/html"

	# container defaults
	if [[ -d "$SRV/apache-web" ]]; then
		confDir="$SRV/apache-web/conf"
		logDir="$SRV/apache-web/log"
		webDir="$SRV/apache-web/htdocs"
	fi
}

argStart() { unset -v host; }

opt()
{
	case "$1" in
		-H|--host|-H=*|--host=*) ScriptOptGet "host" "$@";;
		*) return 1;;
	esac
}

argEnd()
{
	[[ ! $host && ! -f "/etc/apache2/apache2.conf" ]] && host="$(GetServer "web")"
	return 0
}

#
# commands
#

logCommand() { LogShow "$logDir/access.log"; } 
restartCommand() { service restart apache2; }

#
# dir command
#

dirUsage()
{
	echot "Usage: $(ScriptName) dir [conf|log|web](web)
Return the path to an Apache directory."
}

dirCommand() { dirWebCommand; }
dirConfCommand() { echo "$confDir"; }
dirLogCommand() { echo "$logDir"; }
dirWebCommand() { echo "$webDir"; }

ScriptRun "$@"
