#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init()
{
	program="$P32/AquaSnap/AquaSnap.Daemon.exe"
 	profileName="AquaSnap"
	profileKey="HKEY_CURRENT_USER\SOFTWARE\Nurgo-Software\AquaSnap"
}

usage() {	echot "usage: AquaSnap [start|close|program|IsInstalled|IsRunning](start)
	profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset -v brief

	while (( $# != 0 )); do
		case "$1" in
			--brief|-b) brief="--brief";;
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$(GetFileName "$program")"; }
profileCommand() { profile --app "$profileName" --method "$profileKey" "$@" || usage 1; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startCommand() { ! IsInstalledCommand && return 1; start $wait "$program" "$@"; }
startupCommand() { startCommand "$@"; }

run "$@"
