#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: ask [OPTION]... <message>
Prompt the user with messageAsk the user for a response from a list of valid options.
Exit status is the zero based index into the valid responses.
	-vr, --valid [<valid responses>](yn)	valid response keys
	-dr, --default [<default response>](y)	default response, single character or none
	-d, --delay [delay](infinite)						seconds to wait for a response"
	exit $1
}

init() 
{
	unset message delay
	valid='yn'
	default='y'
}

args()
{
	while [ "$1" != "" ]; do
		case "$1" in
			-d|--delay) shift; delay="-t $1";;
			-vr|--valid) shift; valid="$1";;
			-dr|--default) shift; default="$1";;
			-h|--help) usage 0;;
			*) 
				if [[ ! $message ]]; then message="$1"
				else { echoerr "Unknown argument $1"; usage 1; }
				fi;;
		esac
		shift
	done

	args=( "$@" )

	[[ "$default" == "none" ]] && default=""
	[[ ${#default} != 1 ]] && { echoerr "Default response must be a single character"; usage 1; }
}

run() 
{
	init
	args "$@"

	if [[ $default ]]; then
		printf "$message ($default)? "
	else
		printf "$message"
	fi

	while true; do
		read -n 1 $delay -s response
		[[ ! $response ]] && response="$default"
		[[ $response && "$valid" == *$response* ]] && break
	done
	echo "$response"	

	(( index=$(expr index "${valid,,}" "${response,,}") - 1 ))
	exit $index
}

run "$@"
