#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: ask [OPTION]... <message>
Prompt the user with messageAsk the user for a response from a list of valid
options.  Exit status is a zero based index into the valid responses.

	-vr, --valid-responses [<valid>](yn)			allowed responses
	-dr, --default-response [<default>](y)		default response or empty string
	-d, --delay [delay](infinite)							seconds to wait for a response"
	exit $1
}

init() 
{
	unset message delay
	valid='yn'
	default='y'
}

args()
{
	while [ "$1" != "" ]; do
		case "$1" in
			-d|--delay) shift; delay="-t $1";;
			-vr|--valid-responses) shift; valid="$1";;
			-dr|--default-response) shift; default="$1";;
			-h|--help) usage 0;;
			*) 
				! IsOption "$1" && [[ ! $message ]] && { message="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $message ]] && MissingOperand "message"
	[[ $default && ${#default} != 1 ]] && { EchoErr "Default response must be a single character"; return 1; }
	args=("$@")
}

run() 
{
	init || return
	args "$@" || return

	if [[ $default ]]; then
		printf "$message ($default)? "
	else
		printf "$message? "
	fi

	while true; do
		read -n 1 $delay -s response
		[[ ! $response ]] && response="$default"
		[[ $response && "$valid" == *$response* ]] && break
	done
	echo "$response"	

	(( index=$(${G}expr index "${valid,,}" "${response,,}") - 1 ))
	exit $index
}

run "$@"
