#!/usr/bin/env bash
. app.sh

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup](startup)
$(ScriptName) commands."
}

init()
{
	defaultCommand="startup"
	program="$P/AutoHotkey/AutoHotkey64.exe"
	keys="$UDATA/bin/keys.ahk"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { isInstalledCommand && IsTaskRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startupCommand; }
startCommand() { isInstalledCommand && echo start $wait "$program" "${startArgs[@]}"; }
versionCommand() { ! isInstalledCommand && return; FileVersion "$program"; }

startupCommand()
{
	! isInstalledCommand && return 0
	[[ ! -f "$keys" ]] && return 0
	isRunningCommand && return 0
	
	pushd "$DATA/platform/win" > /dev/null || return
	start "$program" "$keys" || return
}

ScriptRun "$@"
