#!/bin/bash
. app.sh

usage() { echot "usage: AutoHotKey [start|startup|close|restart](start)"; exit $1; }
run() {	init; args "$@"; ${command}Command; return "$?"; }

init()
{
	command='startup'
	program="$P/AutoHotkey/AutoHotkey.exe"
	keys="$DOC/data/bin/keys.ahk"
}

args()
{
	while [[ "$1" != "" ]]; do
		case ${1,,} in
			-h|--help) usage 0;;
			*) IsFunction ${1}Command && command=${1} || { echoerr "Unknown argument $1"; usage 1; };;
		esac
		shift
	done
}

startCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	start "$program"
}

startupCommand()
{
	{ ! IsInstalledCommand || [[ ! -f "$keys" ]] || IsRunningCommand; } && return 1
	pushd "$(BatchDir)/win32" > /dev/nul
	start "$keys"
	popd > /dev/nul
}

IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { IsRunningCommand && ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"