#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|program|IsInstalled|IsRunning|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
		
	# find program
	case "$PLATFORM_OS" in
		mac) program="$P/balenaEtcher.app";;
		win) program="$UADATA/balena_etcher/balenaEtcher.exe";;
	esac

	return 0

}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); return 0; }
startCommand() { AppInstallCheck && start "$program" "${startArgs[@]}" "${otherArgs[@]}"; }
startupCommand() { isRunningCommand && return; startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program" | sed 's/\.0$//'; }

ScriptRun "$@"
