#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|close|profile|program|IsInstalled|IsRunning](start)
Bartender commands."
}

init()
{
	defaultCommand="start"
	profileName="bartender"
	program="$P/Bartender 4.app"
	profileDir="$HOME/Library/Preferences"
	profileMask="com.surteesstudios.Bartender.plist"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); }
startCommand() { IsInstalledCommand && open -a "$(GetFileNameWithoutExtension "$program")"; }
startupCommand() { startCommand; }

ScriptRun "$@"
