#!/usr/bin/env bash

# run a bash command interactively (to allow input) and with functions loaded

command="$1"	# command_string
arg0="$1"			# assigned to arg0, the name of the shell
options=("${@:2}")
bashOpt=(-c)

# use a login shell only if stdout is connected, otherwise stderr is not visible and CurrentColumn hangs
[[ -t 1 ]] && bashOpt+=(-l) 

# run the command 
# - requires correct Bash in the configured path.  If command loads Bash it will find it from the configured path, not the PATH variable in this process.  
#   This can be an issue on macOS if Homebrew is not in the user or system path.
bash "${bashOpt[@]}" 'quietPlatformConf="true" . function.sh ""; '"$command"' "$@"' "$arg0" "${options[@]}"
