#!/usr/bin/env bash

# run a bash command interactively with functions

command="$1"	# command_string
arg0="$1"			# assigned to arg0, the name of the shell
options=("${@:2}")
bashOpt=(-c)

# use a login shell only if stdout is connected, otherwise stderr is not visible and CurrentColumn hangs
[[ -t 1 ]] && bashOpt+=(-l) 

# run the command
bash "${bashOpt[@]}" 'quiet="--quiet" . function.sh ""; '"$command"' "$@"' "$arg0" "${options[@]}"
