#!/usr/bin/env bash

# run a bash command interactively with functions

command="$1"	# command_string
arg0="$1"			# assigned to arg0, the name of the shell
options=("${@:2}")

bash -i -c ". function.sh; $command"' "$@"' "$arg0" "${options[@]}"