#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="BetterDisplay" profileDir="$HOME/Library/Preferences" profileMask="me.waydabber.BetterDummy.plist"
	program="$P/BetterDisplay.app"
}

closeCommand() { ! isRunningCommand && return; ProcessClose --force "BetterDisplay"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "BetterDummy"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}" || return; }
programCommand() { echo "$program"; }
startCommand() { isRunningCommand && return; AppInstallCheck && start "$program"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion --allow-alpha "$program"; }

ScriptRun "$@"
