#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="BeyondCompare"
	unset program

	# bcomp - waits for comparison to complete 
	if IsPlatform win && [[ -d "$P/Beyond Compare 4/BCompare.exe" ]]; then program="$P/Beyond Compare 4/BCompare.exe" bcomp="$program" version="$program"
	elif IsPlatform win; then program="$P/Beyond Compare 5/BCompare.exe" bcomp="$program" version="$program"
	elif IsPlatform mac; then program="$P/Beyond Compare.app/Contents/MacOS/BCompare" bcomp="$P/Beyond Compare.app/Contents/MacOS/bcomp" version="Beyond Compare"
	elif IsPlatform debian; then program="/usr/bin/bcompare" bcomp="$program" version="$program"
	fi
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { AppInstallCheck && echo "$program"; }
restartCommand() { closeCommand && startCommand; }

#
# profile command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
									 
profileCommand() 
{	
	[[ $noPrompt ]] && return
	AppInstallCheck || return
	
	local command="${profileArgs[0]}"
	[[ "$command" == "backup" ]] && echo "- Tools, Export settings...,"
	[[ "$command" == "restore" ]] && echo "- Tools, Import settings...,"
  
  profile $noPrompt --app "$profileName" --method "$program" --save-extension "bcpkg" "${profileArgs[@]}" || return;
}

#
# start command	
#

startUsage() 
{
	ScriptUsageEcho "$1" "\
Usage: $(ScriptName) start
Start BeyondCompare.   If waiting, return codes are:

0=Success
1=Binary same
2=Rules-based same
11=Binary differences
12=Similar
13=Rules-based differences
14=Conflicts detected
100=Unknown error
101=Conflicts detected, merge output not written
102=BComp.exe unable to wait until BCompare.exe finishes
103=BComp.exe cannot find BCompare.exe
104=Trial period expired
105=Error loading script file
106=Script syntax error
107=Script failed to load folders or files"
}

startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$bcomp" "${startArgs[@]}"; }
startupCommand() { startCommand; }

#
# version command
#

versionCommand()
{
	AppInstallCheck || return
	IsPlatform linux && return
	AppVersion --allow-alpha "$version" | cut -d" " -f1
}

ScriptRun "$@"
