#!/usr/bin/env bash
. app.sh

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="BeyondCompare"
	unset program

	# bcomp - waits for comparison to complete 
	if IsPlatform win; then program="$P/Beyond Compare 4/BCompare.exe" bcomp="$program" version="$program"
	elif IsPlatform mac; then program="$P/Beyond Compare.app/Contents/MacOS/BCompare" bcomp="$P/Beyond Compare.app/Contents/MacOS/bcomp" version="Beyond Compare"
	elif IsPlatform debian; then program="/usr/bin/bcompare" bcomp="$program" version="$program"
	fi
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { AppInstallCheck && echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$bcomp" "${startArgs[@]}"; }
startupCommand() { startCommand; }

versionCommand()
{
	AppInstallCheck || return
	IsPlatform linux && return
	AppVersion --allow-alpha "$version" | cut -d" " -f1
}

#
# Profile Command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
									 
profileCommand() 
{	
	[[ $noPrompt ]] && return
	AppInstallCheck || return
	
	local command="${profileArgs[0]}"
	[[ "$command" == "backup" ]] && echo "- Tools, Export settings...,"
	[[ "$command" == "restore" ]] && echo "- Tools, Import settings...,"
  
  profile $noPrompt --app "$profileName" --method "$program" --save-extension "bcpkg" "${profileArgs[@]}" || return;
}
	
ScriptRun "$@"
