#!/bin/bash
. function.sh

bashTest()
{
	echot "\
BASH_DEBUG=$BASH_DEBUG
BASH_STATUS_LOGIN_SHELL=$BASH_STATUS_LOGIN_SHELL
BASH_STATUS_LOGIN_SHELL_CHILD=$BASH_STATUS_LOGIN_SHELL_CHILD
BASH_STATUS_INTERACTIVE_SHELL=$BASH_STATUS_INTERACTIVE_SHELL"
	ShowInteractive
	ShowSsh
	declare -p | egrep BASH_STATUS
	[[ "$(export -f)" != "" ]] && ( echo -n "first export function: "; export -f | head -1 ) || echo "No export functions"
	# return 1 so script pauses if run from mintty
	return 1
}

openTest()
{
	echo 'Open a document...'
	cygstart "$HOME\Dropbox\Current.docx"
}

# Determine if run interactively (source) or as a shell (./)
interactiveTest()
{
	IsInteractive && echo 'interactive (sourced, source bkm.sh)' || echo 'not interactive (run as shell, ./bkm.sh)'
}

returnTest()
{
	ReturnTestHelper "fail"; echot "ReturnTest fail=$?";
	ReturnTestHelper "success"; echot "ReturnTest success=$?";
}

ReturnTestHelper()
{
	[[ "$1" != "fail" ]]; result="$?"
	return $result
	echo 'not reached'
}

ArgTest()
{
	i=0
	for arg in ${1:+"$@"}
	do
		((i++))
		echo "arg$i=$arg"
	done
}

echoTest()
{
	echo "\
Double quotes: allow expansion
- variables can be referenced: BIN=$BIN
- \"double quotes\" and other special characters must be escaped
- special character can be escaped with \\
- newlines can be escaped to align first line of text in column 0
"

	echo 'Single quotes: prevent expansion
- variables cannot be referenced: BIN=$BIN
- "double quotes" and other special characters do not need to be quoted
' 

	local s="Space and Tab Test
0 spaces
 1 space
  2 spaces
	1 tab
		2 tabs
12345678"	

	echo "echo/cat/less: tabs use default number of spaces for terminal (usually 8)"
	echo "$s
"
	echo "echot/catt/lesst: tabs use specified number of spaces (tabs=$TABS)"
	echot "$s"
}

Usage()
{
	echot 'usage: bkm bash|echo|interactive|return|arg'
	exit
}

{ [[ $# == 0 ]] || ! IsFunction ${1}Test; } && Usage
echot "--- $1 Test ---"
${1}Test ${@:2}
result="$?"
exit $result