#!/usr/bin/env bash

# bootstrap a Windows system for Windows Subsystem for Linux (WSL) running a debian distribution
# This script uses only what is available on a newly installed system.

init()
{
	user="${1:-jjbutare}"
	host="${2:-nas3}"
}

run()
{
	init || return
	configureProxyServer || return
	installCorePrograms || return
	mountPublic || return

	echo "Bootstrapping from $host..."
	export PATH=$HOME/Volumes/public/documents/data/bin:$HOME/Volumes/public/documents/data/platform/win:$PATH
	bootstrap $host
}

mountPublic()
{
	[[ ! $host || -d "$HOME/Volumes/public/documents/data/bin" ]] && return
	mkdir -p "$HOME/Volumes/public" || return
	sudo mount -t drvfs "//$host/public" "$HOME/Volumes/public" 
}

configureProxyServer()
{
	[[ -f "/etc/apt/apt.conf.d/proxy" ]] && return
	echo 'Acquire::http::Proxy "http://nas3.hagerman.butare.net:3128";
Acquire::http::Proxy "https://nas3.hagerman.butare.net:3128";' | sudo tee "/etc/apt/apt.conf.d/proxy"
}

installCorePrograms()
{
	which xclip >& /dev/null && return
	sudo apt-get update --fix-missing || return
	sudo apt-get install -y net-tools openssh-server || return
	sudo apt-get install -y dbus-x11 dialog expect gcp xclip || return
}

run "$@"
