#!/usr/bin/env bash
. bootstrap-config.sh || exit

# update configuration variables then copy and paste and run this in a Docker terminal

cat <<-EOF
hi
	# first paste
	apt-get update && apt install -y sudo apt-utils curl dialog openssh-client openssh-server; adduser $user --gecos "" && sudo usermod -aG sudo $user && login $user

	# second paste
	mkdir ~/.ssh; scp -P $fsProtocol $fs:~/.ssh/"*" ~/.ssh; chown $user ~/.ssh/*; chmod 700 ~/.ssh/*; [[ -f /assets/sshd_config ]] && sudo sed -i 's/^AllowUsers .*/AllowUsers git '"$user"'/' /assets/sshd_config; sudo /etc/init.d/ssh restart
EOF
