#!/usr/bin/env bash

# bootstrap a Debian system (Ubuntu, Raspberry Pi)
# This script uses only what is available on a newly installed system.
# - (VMware Workstation VM) drag and drop to a terminal
# - (Hyper-V) enable shared drive

init()
{
	reboot=""
	user="${1:-jjbutare}"
	host="${2:-nas3}"
	dnsServers="192.168.100.2 192.168.100.1"
	dnsSuffix="hagerman.butare.net"
	eval $(cat /etc/os-release) # ID=ubuntu|raspbian
}

run()
{
	init || return
	configureProxyServer || return
	checkDomain || return
	installCorePrograms || return
	createUser || return

	[[ "$USER" != "$user" ]] && { echo "Login as $user and run /tmp/bootstrap-debian"; exit; }

	mountPublic || return

	echo "Bootstrapping from $host..."
	export PATH=$HOME/Volumes/public/documents/data/bin:$PATH
	bootstrap $host
}

checkDomain()
{
	ping -c 1 $host >& /dev/null && return

	echo "Configuring DNS..."
	sudo systemd-resolve --set-domain=hagerman.butare.net --interface=eth0 || return
	sleep 5
	ping -c 1 $host
}

configureProxyServer()
{
	[[ ! -f "/etc/apt/apt.conf.d/proxy" ]] && echo 'Acquire::http::Proxy "http://nas3.hagerman.butare.net:3128";
Acquire::https::Proxy "http://nas3.hagerman.butare.net:3128";' | sudo tee "/etc/apt/apt.conf.d/proxy"
}

createUser()
{
	grep "$user" /etc/passwd >& /dev/null && return

	echo "Creating $user..."
	sudo adduser "$user" || return
	sudo usermod -aG sudo $user || return
	sudo chmod ugo+rwx /tmp/bootstrap-debian || return
}

installCorePrograms()
{
	which xclip >& /dev/null && return

	echo "Installing core programs..."
	sudo apt-get update --fix-missing
	sudo apt-get install -y cifs-utils net-tools openssh-server resolvconf || return
	sudo apt-get install -y dialog expect gcp xclip || return

	# credential management - except for Raspberry Pi which is typically headless
	if [[ "$ID" != "raspbian" ]]; then
		sudo apt-get install -y gnome-keyring libsecret-tools || return
	fi
}

mountPublic() # mount //$host/public
{
	[[ ! $host || -d "$HOME/Volumes/public/documents/data/bin" ]] && return

	echo "Mounting //$host/public..."
	mkdir -p "$HOME/Volumes/public" || return
	line="//$host/public /home/$user/Volumes/public cifs username=$user,noauto,rw,users 0 0"
	! grep "$line" /etc/fstab >& /dev/null && { echo "$line" | sudo tee -a //etc/fstab || return; }
	mount.cifs "//$host/public" "$HOME/Volumes/public" -o user=$user sec=ntlmsspi || return
}

run "$@"
