#!/usr/bin/env bash

# bootstrap macOS
# This script uses only what is available on a newly installed system.  Run this from
# - mkdir /tmp/p && mount_smbfs -s "smb://nas3/public" "//tmp/p" && /tmp/p/documents/data/bin/bootstrap-mac 
# - USB drive
# - Finder, Go, Connect to Server..., smb://nas3, Public, right click, New Terminal at Folder, cd documents/data/bin/
 
init()
{
	reboot=""
	user="${1:-jjbutare}"
	host="${2:-nas3}"
	mount="/tmp/public"
	bin="$mount/documents/data/bin"
}

run()
{
	init || return
	installHomebrew || return
	installCorePrograms || return
	installBash || return
	mountPublic || return

	echo "Bootstrapping from $host..."
	export PATH=$bin:$bin/../platform/mac:$PATH
	/usr/local/bin/bash bootstrap $hostp
}

mountPublic()
{
	[[ -d "$bin" ]] && return
	mkdir "$mount" || return
	mount_smbfs -s "smb://$user@$host/public" "$mount" || return
}

installHomebrew()
{
	which brew >& /dev/null && return
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

installBash()
{
	grep '/usr/local/bin/bash' /etc/shells >& /dev/null && return
	echo -n "/usr/local/bin/bash" | pbcopy || return
	sudo nano /etc/shells || return
	chpass -s "/usr/local/bin/bash" || return 
}

installCorePrograms()
{
	which wget >& /dev/null && return
	brew install bash coreutils findutils gawk mas wget || return
}

run "$@"
