#!/usr/bin/env bash

run()
{
	brewInstall || return
	! brew list bash >& /dev/null && { brew install bash || return; }
	! InPath gmkdir && { brew install coreutils || return; }
	"$(ScriptDir)/bootstrap-init" "$@"
}

brewInit()
{
	local brew="/usr/local/bin/brew"
	[[ ! -f "$brew" ]] && brew="/opt/homebrew/bin/brew"
	[[ -f "$brew" ]] && eval "$($brew shellenv)" || return 1
}

brewInstall()
{
	brewInit && return
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || return
	brewInit
}

#
# helper
#

GetFilePath() { local p="${1%/*}"; [[ "$p" == "$1" ]] && echo "" || echo "$p"; }
InPath () { which "$1" &> /dev/null; }
pause() { local response; read -n 1 -s -p "${*-Press any key when ready...}"; echo; }
ScriptDir() { GetFilePath "${BASH_SOURCE[0]}"; }

run "$@"
