#!/usr/bin/env bash

run()
{
	$(uname -m) || return
	! brew list bash >& /dev/null && { brew install bash || return; }
	! InPath gmkdir && { brew install coreutils || return; }
	"$(ScriptDir)/bootstrap-init" "$@"
}

x86_64()
{
	! InPath brew && { bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" || return; }
	return 0
}

arm64()
{
	! InPath "git" && { xcode-select --install || return; pause; }

	if [[ ! -f "/opt/homebrew/bin/brew" ]]; then
		pushd "/opt" >& /dev/null || return
		sudo mkdir "homebrew" || return
		curl -L "https://github.com/Homebrew/brew/tarball/master" | sudo tar xz --strip 1 -C "homebrew" || return
		popd
	fi

	! InPath brew && export PATH="/opt/homebrew/bin:$PATH"

	return 0
}

GetFilePath() { local p="${1%/*}"; [[ "$p" == "$1" ]] && echo "" || echo "$p"; }
InPath () { which "$1" &> /dev/null; }
pause() { local response; read -n 1 -s -p "${*-Press any key when ready...}"; echo; }
ScriptDir() { GetFilePath "${BASH_SOURCE[0]}"; }

run "$@"
