#!/usr/bin/env bash

# bootstrap a Windows system for Windows Subsystem for Linux (WSL) running a debian distribution
# This script uses only what is available on a newly installed system.

init()
{
	user="${1:-jjbutare}"
	host="${2:-nas1}"
}

run()
{
	init || return
	installCorePrograms || return
	mountPublic || return

	echo "Bootstrapping from $host..."
	export PATH=$HOME/Volumes/public/documents/data/bin:$HOME/Volumes/public/documents/data/platform/win:$PATH
	bootstrap $host
}

mountPublic()
{
	[[ ! $host || -d "$HOME/Volumes/public/documents/data/bin" ]] && return
	mkdir -p "$HOME/Volumes/public" || return
	sudo mount -t drvfs "//$host/public" "$HOME/Volumes/public" 
}

installCorePrograms()
{
	which xclip >& /dev/null && return
	sudo apt-get update --fix-missing || return
	sudo apt-get install -y fping net-tools nmap openssh-server || return # resolvconf
	sudo apt-get install -y dbus-x11 dialog expect gcp xclip || return
}

run "$@"
