#!/usr/bin/env bash
. function.sh

init()
{
	armHosts=( router GarageSwitch LivingRoomAp StudyClosetSwitch StudyDeskSwitch )   
	mipsHosts=( BackShedSwitch BackYardAp FrontYardAp StudyAp )
}

run()
{
	init "$@" || return
	microInstall || return
}

microInstall()
{
	cd "/tmp" || return
	export GETMICRO_PLATFORM=linux-arm
	curl https://getmic.ro | bash

	for host in ${armHosts[@]}; do echo "$host..."; scp "/tmp/micro" "$host:/usr/bin"; done
}

run "$@"
