#!/usr/bin/env bash
. function.sh

# bootstrap a system which has bash installed and ssh enabled (allows us to perform platform specific bootstraping)

run()
{
	init "$@" || return
	configureSsh || return
	bootstrap || return
}

bootstrap()
{
	local file="bootstrap-$platform"
	local destFile="/tmp/$file"

	echo "Copying $file to $host:$destFile..."
	scp "$BIN/$file" "$host:$destFile" || return
	echo

	echo "Execute the contents of the clipboard on $host..."
	clipw "$destFile $user $fileHost" || return
	ssh -t $host || return
}

configureSsh()
{
	! ask 'Configure ssh' && return
	ssh $host '[[ -d ~/.ssh ]] || mkdir ~/.ssh' || return
	scp ~/.ssh/* ''$host':~/.ssh' || return
}


init()
{
	host="${1:-pi@pi1}"
	platform="${2:-debian}"
	user="${3:-jjbutare}"
	fileHost="${4:-nas1}"
}

run "$@"
