#!/usr/bin/env bash
. bootstrap-config.sh || exit

# update configuration variables then copy and paste and run this in a Docker terminal

# first paste
user=jjbutare; apt-get update && apt install -y sudo; adduser $user --gecos "" && sudo usermod -aG sudo $user && login $user

# second paste
user=jjbutare host=$fileServer port=608; mkdir ~/.ssh; scp -P $port $host:~/.ssh/"*" ~/.ssh; chown $USER ~/.ssh/*; chmod 700 ~/.ssh/*; [[ -f /assets/sshd_config ]] && sudo sed -i 's/^AllowUsers .*/AllowUsers git '"$user"'/' /assets/sshd_config; sudo /etc/init.d/ssh restart
