#!/usr/bin/env bash

# bootstrap a QNAP QNS NAS

init()
{
	reboot=""
	user="${1:-jjbutare}"
	data="/share/Public/documents/data" 			# assume data directory is already present
}

run()
{
	init || return

	sudo chmod u+s /bin/ping || return # allow ping without sudo
	sudo chmod u+s /usr/bin/mount.cifs || return

	sudo ln -s "$data" "/usr/local/data"

	echo "bootstrapping..."
	export PATH=/usr/local/data/bin:$PATH
	inst --hint "/usr/local/data/install" bootstrap || return
}

run "$@"
