#!/usr/bin/env bash
# bootstrap-init [USER](jjbutare) [HOST] - bootstrap a local system

run()
{
	init "$@" || return
	configureProxyServer || return
	setupPackageManager || return
	setTimezone || return
	installPackages || return
	createUser || return
	runAsUser || return
	mountPublic || return
	runBootstrap || return
}

runBootstrap()
{
	echo "Bootstraping from $host..."
	export PATH=/usr/local/data/bin:$bin:$PATH # add the final and mounted bin to the path
	$bash bootstrap "$host" "$install"
}

configureProxyServer()
{
	[[ ! $proxy || ! -d /etc/apt/apt.conf.d || -f "/etc/apt/apt.conf.d/proxy" ]] && return

	echo "Setting proxy server to $proxy..."
	printf 'Acquire::http::Proxy "%s";\nAcquire::https::Proxy "%s";\n' "$proxy" "$proxy" | $sudo tee "/etc/apt/apt.conf.d/proxy"
}

createUser()
{
	IsMac || grep "$user" /etc/passwd >& /dev/null && return

	echo "Creating user $user..."
	sudo adduser "$user" --gecos "" || return
	sudo usermod -aG sudo $user || return
}

runAsUser()
{
	[[ "$USER" == "$user" ]] && return
	
	local script="${BASH_SOURCE[0]}"

	echo "Running $script as $user..."
	cd /tmp || return
	sudo chmod ugo+rwx "$script" || return
	sudo --preserve-env=PATH --user=$user --set-home "$script"
	exit
}

setTimezone()
{
	( IsMac || cat "/etc/timezone" |& grep "$timezone" > /dev/null ) && return

	sudo DEBIAN_FRONTEND=noninteractive apt install -y tzdata || return
	[[ ! -f "/usr/share/zoneinfo/$timezone" ]] && return
	sudo ln -snf "/usr/share/zoneinfo/$timezone" "/etc/localtime" || return
	echo "$timezone" | sudo tee "/etc/timezone" || return
	dpkg-reconfigure -f noninteractive tzdata || return
}

#
# Helper Functions
#

IsMac() { [[ "$PLATFORM" == "mac" ]]; }
InPath () { which "$1" &> /dev/null; }
pause() { local response; read -n 1 -s -p "${*-Press any key when ready...}"; echo; }

#
# Mount
#

mountPublic() 
{ 
	[[ -d "$bin" ]] && return

	echo "Mounting //$host/public..."
	mkdir -p "$mount" || return
	mountPublic$p || return
}

mountPublicDebian()
{
	local line="//$host/public /home/$user/Volumes/public cifs username=$user,noauto,rw,users 0 0"
	! grep "$line" /etc/fstab >& /dev/null && { echo "$line" | sudo tee -a //etc/fstab || return; }
	mount.cifs "//$host/public" "$HOME/Volumes/public" -o user=$user sec=ntlmsspi || return
}

mountPublicMac() { mount_smbfs -s "smb://$user@$host/public" "$mount" || return; }
mountPublicWin() { sudo mount -t drvfs "//$host/public" "$HOME/Volumes/public"; }

#
# Packages
#

installPackages()
{
	which xclip >& /dev/null && return

	installPackages$p || return
	installPackagesCommon || return

	InPath apt && { apt update || return; } # fix "Could not find command-not-found database"
}

installPackagesCommon() { package dialog expect findutils gawk rsync xclip; }

installPackagesDebian()
{	
	package ubuntu-standard cifs-utils iputils-ping net-tools openssh-server resolvconf

	# credential management - except for Raspberry Pi which is typically headless
	if [[ "$ID" != "raspbian" ]]; then
		sudo apt-get install -y gnome-keyring libsecret-tools || return
	fi

	return 0
}

installPackagesMac() 
{
	grep '/usr/local/bin/bash' /etc/shells >& /dev/null && return
	echo -n "/usr/local/bin/bash" | pbcopy || return
	sudo nano /etc/shells || return
	chpass -s "/usr/local/bin/bash" || return 
}

installPackagesWin() { package ubuntu-standard iputils-ping ubuntu-wsl || return; }

package()
{
	case $PLATFORM in
		debian|win) sudo apt install -y "$@";;
		mac) brew install "$@";;
	esac
}

setupPackageManager()
{
	case $PLATFORM in
		debian|win) setupPackageManagerDebian;;
		mac) ! which brew >& /dev/null && { /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; };;
	esac
}

setupPackageManagerDebian()
{
	local motd="/etc/update-motd.d/60-unminimize"

	[[ ! -f "$motd" ]] && return

	unminimizeDebianDoc || return

	if  [ "$(dpkg-divert --truename /usr/bin/man)" = "/usr/bin/man.REAL" ]; then
		rm -f "/usr/bin/man" || return
		dpkg-divert --quiet --remove --rename "/usr/bin/man" || return
	fi

	apt update && apt dist-upgrade -y && apt install sudo && rm -f "$motd"
}

unminimizeDebianDoc() # from /usr/local/sbin/unminimize
{
	local config="/etc/dpkg/dpkg.cfg.d/excludes" configTmp="/etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp"

	[[ ! -f "$config" && ! -f "$configTmp" ]] && return
	[[ -f "$config" ]] && { mv "$config" "$configTmp" || return; }

  apt-get update || return
  apt-get upgrade -y || return
  dpkg -S /usr/share/man/ |sed 's|, |\n|g;s|: [^:]*$||' | DEBIAN_FRONTEND=noninteractive xargs apt-get install --reinstall -y || return
  dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {print $2}' | sed 's|/[^/]*$||' | sort |uniq | xargs dpkg -S | sed 's|, |\n|g;s|: [^:]*$||' | uniq | DEBIAN_FRONTEND=noninteractive xargs apt-get install --reinstall -y || return
  dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/locale/ {print $2}' | sed 's|/[^/]*$||' | sort |uniq | xargs dpkg -S | sed 's|, |\n|g;s|: [^:]*$||' | uniq | DEBIAN_FRONTEND=noninteractive xargs apt-get install --reinstall -y || return

  dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {exit 1}' && { rm "$configTmp" || return; }
  return 0
}

#
# other
#

init()
{
	. "${BASH_SOURCE[0]%/*}/bootstrap-config.sh" || return

	# variables
	bash=""
	mount="$HOME/Volumes/public"
	bin="$mount/Documents/data/bin"
	install="$mount/Documents/data/install"
	sudo="sudo"; ! InPath sudo && sudo=""

	# PLATFORM=debian|mac|win
	PLATFORM=debian
	[[ "$(uname)" == "Darwin" ]] && PLATFORM=mac bash="/usr/local/bin/bash"
	[[ $(uname -r)  =~ [Mm]icrosoft ]] && PLATFORM=win
	p=${PLATFORM^}

	# ID=ubuntu|raspian
	[[ -f /etc/os-release ]] && eval $(cat /etc/os-release)
}

run "$@"
