#!/usr/bin/env bash
. script.sh || exit

usage() { ScriptUsage "$1" "Usage: $(ScriptName) [prepare|run](run)"; }
init() { defaultCommand="run" config="$BIN/bootstrap-config.sh"; }

#
# Prepare Command
#

prepareUsage() { echot "Usage: $(ScriptName) prepare\nShow steps to prepare a host."; }

prepareCommand()
{
	local user="$USER"
	local host="$HOST"
	local port="$(SshHelper config get "$HOST" port)"

	cat <<-EOF
		Preparation:
		- Docker
			apt-get update && apt install -y sudo apt-utils curl dialog openssh-client openssh-server
			adduser $user --gecos "" && sudo usermod -aG sudo $user && login $user
			mkdir ~/.ssh && scp -P $port $host:~/.ssh/"*" ~/.ssh && chown $user ~/.ssh/*; chmod 700 ~/.ssh/*
			[[ -f /assets/sshd_config ]] && sudo sed -i 's/^AllowUsers .*/AllowUsers git '"$user"'/' /assets/sshd_config && sudo /etc/init.d/ssh restart
		- SSH
			sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' && systemctl restart sshd
		- Raspberry Pi OS: pi/raspberry, Ubuntu=
		- Ubuntu: ubuntu/ubuntu
	EOF
}

#
# Run Command
#

runUsage()
{
	echot "Usage: $(ScriptName) run TARGET
Bootstrap a remote system.  Target is a remote host ([USER]@HOST[:PORT]), a chroot, or a WSL distribution.
	
flow: bootstrap-remote -> bootstrap-init -> bootstrap -> inst
	
example:
	cls; bootstrap-remote ubuntu@pi9 --bin=//ender.hagerman.butare.net/system/usr/local/data/bin
	cls; bootstrap-remote rosie-lvm1 --bin=//rosie.hagerman.butare.net/root/usr/local/data/bin:22

	-b,	--bin=UNC				bin directory UNC, defaults to bootstrapBin in the configuration file
	-f, --config=FILE		the configuration file to use, defaults to bootstrap-config.sh
	-i, --install=DIR		application installation directory, defaults to search with FindInstallFile"
}

runArgStart() { unset -v bin installDir; }

runOpt() 
{
	case "$1" in
		-b|--bin|-b=*|--bin=*) ScriptOptGet "bin" "$@" || return;;
		-c|--config|-c=*|--config-file=*) ScriptOptGet "config" "$@" && ScriptCheckFile "$config";;
		-i|-i=*|--install|--install=*) ScriptOptGet "install" "$@";;
		*) return 1
	esac
}

runArgs() { ScriptArgGet "target" -- "$@"; shift; }

runArgEnd()
{
	bash="bash"
	bootstrapUser="$(ConfigGet "user" "$config")"; bootstrapUser="${bootstrapUser:-$USER}"
	coreFiles=( "$BIN/bootstrap-init" "$config" )
}

runCommand()
{
	header "bootstrap-remote"
	
	if ChrootHelper installed && ChrootHelper exists "$target"; then
		type="chroot"
	elif wsl dist exists "$target"; then
		type="wsl"
	else
		type="ssh"
	fi

	RunFunction bootstrap "${type^}"
}

#
# chroot - bootstrap a chroot
#

bootstrapChroot()
{
	local dist="$target"
	local dir="$(ChrootHelper dir "$dist")"

	log1 "chroot dir=$dir"
	[[ ! -d "$dir" ]] && { EchoErr "$dist root directory "$dir" does not exist"; return 1; }

	# copy core files
	copyCoreFiles "$dir/tmp/bootstrap/" || return
	copyCoreFiles "/tmp/bootstrap/" || return # some chroots mount our tmp directory

	# run bootstrap-init
	runBootstrap || return
}

#
# SSH - bootstrap a remote host using SSH
#

bootstrapSsh()
{
	local host="$(GetSshHost "$target")"
	local port="$(GetSshPort "$target")"; port="${port:-$(SshHelper config get "$host" port)}"
	local sshUser="$(GetSshUser "$target")"; user="${sshUser:-$bootstrapUser}"

	local isHostLocal; GetIpAddress --quiet "$host" | IsIpLocal && isHostLocal="true"
	local sshCommonArgs=( -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ) # trust new hosts, don't modify known_hosts
	local sshArgs=( -p "$port" "${sshCommonArgs[@]}" )
	local scpArgs=( -P "$port" "${sshCommonArgs[@]}" )
	local rsyncSshArgs="ssh ${sshCommonArgs[@]}"
	local rsyncArgs=( --rsh "$rsyncSshArgs" )

	sshBootHost || return	
	sshCheckUserPassword || return
	sshGetHostInfo || return
	sshConfigure || return
	runInit || return
	IsPlatform openwrt,ubiquiti --host && return
	
	while true; do 
		sshCheckBootstrapUser || return
		sshCopyCoreFiles || return
		runBootstrap && return
		sshReconnect || return		
	done
}

sshBootHost() # wait for the host to become available (after initial boot or reboot)
{
	# power on local hosts
	[[ $isHostLocal ]] && ! IsAvailablePort "$host" "$port" && { power on "$host" || return; }

	# resolve .local address - mDNS resolution does not work using SSH in Windows
	IsMdnsName "$host" && { host=$(MdnsResolve "$host") || return; }

	sshWait || return
}

# sshCheckUser - if the bootstrap user exists use it
sshCheckBootstrapUser() 
{ 
	# bootstrap user already being used
	[[ "$bootstrapUser" == "$user" ]] && return

	# check if the bootstrap user exists
	hilight "Checking for bootstrap user $bootstrapUser..."
	! run getent passwd "$bootstrapUser" >& /dev/null && { echo "Bootstrap user $bootstrapUser does not exist"; return; }

	# the bootstrap user exists
	user="$bootstrapUser"
	echo "Bootstrap user $bootstrapUser exists and will be used for further configuration"
	sshConfigure || return
}

# sshCheckUserPassword - check if user password is expired
sshCheckUserPassword()
{
	# ubuntu user password is initially expired 
	[[ "$user" != "ubuntu" ]] && return

	local tries=10
	for (( i = 1; i <= $tries; i++ )); do

		# if SSH failed, sleep before retry
		(( i != 1 )) && sleep 4; 

		hilight "Checking user '$user' password (try $i of $tries)..."

		# run a simple SSH command
		local result; result="$(run ls 2>&1)" && return

		# if the password has expired login interactivelt to change it
		if echo "$result" | grep -q "password has expired"; then
			echo "Changing user '$user' password..."
			runSsh
			return
		fi

	done
}

sshConfigure()
{
	IsPlatform openwrt,ubiquiti --host && return

	local other;

	# Ubuntu SSH connection performance fix
	IsPlatformAll piKernel,ubuntu --host && other+="$(cat <<-EOF
		sudo sed -i "s/^session\soptional\spam_motd.so\s*motd=\/run\/motd.dynamic$/#session optional pam_motd.so motd=\/run\/motd.dynamic/" "/etc/pam.d/sshd" || exit
		EOF
	)"

	hilight "Checking SSH configuration..."
	run 'bash -s' <<-EOF && { echo "SSH is configured for $user"; return; }
		[[ -f "\$HOME/.ssh/authorized_keys" && -f "\$HOME/.ssh/known_hosts" ]] && exit 0
		[[ ! -d "\$HOME/.ssh" ]] && { mkdir "\$HOME/.ssh" || exit; }
		$other
		exit 1
	EOF

	echo "Configuring ssh for $user..."
	scp "${scpArgs[@]}" "$HOME/.ssh/"* ''"$user@$host"':~/.ssh' || return
}

# sshCopyCoreFiles - copy core files into /tmp/bootstrap
sshCopyCoreFiles()
{
	hilight "Copying core files..."

	run 'bash -s' <<-EOF || return
		[[ -d "/tmp/bootstrap" ]] && exit
		mkdir "/tmp/bootstrap" || exit
		chmod o+w "/tmp/bootstrap" || exit
	EOF

	# copy core files - allow updates by other users
	rsync "${rsyncArgs[@]}" --port=$port --perms --chmod=ugo+w --recursive "${coreFiles[@]}" "$user@$host:/tmp/bootstrap/" || return
}

sshGetHostInfo() { ScriptEval HostGetInfo --trust $verbose "$target"; }

sshReconnect()
{
	hilight "Reconnecting to $host..."
	sleep 4
	sshWait || return 
}

sshWait()
{
	IsAvailablePort "$host" "$port" && return
	WaitForPort "$host" "$port" || return
}

#
# WSL - bootstrap a WSL distribution
#

bootstrapWsl()
{
	local dist="$target" dir="/tmp"

	if [[ "$(wsl get name)" != "$dist" ]]; then
		hilight "Mounting share..."
		dir="$(unc mount "//$(wsl get share)/$dist/tmp")" || return
	fi

	# copy core files
	copyCoreFiles "$dir" || return

	# run bootstrap-init
	runBootstrap || return
}

#
# helper
#

copyCoreFiles()
{
	local dir="$1"

	hilight "Copying core files..."

	# create destination directory
	[[ ! -d "$dir" ]] && { mkdir "$dir" || return; }

	# copy core files - allow updates by other users
	local umask="$(umask)"; umask 0
	cp "${coreFiles[@]}" "$dir" || return 
	umask "$umask" || return
}

installMicro()
{
	IsPlatform mips --host && return
	MicroHelper install "$host" || return
}

runInit()
{
	RunPlatform runInit --host || return
}

runInitOpenwrt() { installMicro; }
runInitUbiquiti() { installMicro; }

runInitMac()
{
	local brew="/usr/local/bin/brew"; IsPlatform arm --host && brew="/opt/homebrew/bin/brew"

	run 'bash -s' <<-EOF
		[[ ! -f "$brew" ]] && /bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || exit
		eval "\$($brew shellenv)"
		! brew list bash >& /dev/null && { brew install bash || exit; }
		! InPath gmkdir && { brew install coreutils || exit; }
		exit 0
	EOF
}

runInitQnap()
{
	bash="/opt/bin/bash"

	run 'bash -s' <<-EOF
		export PATH=/opt/bin:\$PATH
		[[ ! -d "/opt/bin" ]] && { wget -O - "http://bin.entware.net/x64-k3.2/installer/generic.sh" | sudo /bin/sh || exit; }
		[[ ! -f "/opt/bin/stat" ]] && { sudo opkg install bash coreutils-stat iputils-ping || exit; }
		grep -q "$user" /etc/passwd | grep "/opt/bin/bash" && { sudo usermod --shell "/opt/bin/bash" "$user" || exit; }
		exit 0
	EOF
}

runBootstrap()
{
	local restart; [[ "$type" == "ssh" ]] && restart="--restart"

	hilight "Running bootstrap on $host..."
	runi "/tmp/bootstrap/bootstrap-init" "/tmp/bootstrap/$(GetFileName "$config")" "$bin" "${globalArgs[@]}" $restart
}

# run command on host
run() { RunFunction run "${type^}" -- "$@"; }
runChroot() { ChrootHelper run "$dist" -s "/bin/bash" -d /tmp "$@"; }
runSsh() { SshAgentConf "${globalArgs[@]}" && ssh "$user@$host" "${sshArgs[@]}" -- "$@"; }
runWsl() { wsl.exe -d "$dist" "$@"; }

# run command on host interactively
runi() { RunFunction runi "${type^}" -- "$@"; }
runiChroot() { ChrootHelper run "$dist" -s /bin/bash -d /tmp "$bash" -l "$@"; }
runiSsh() { ssh -Yt "$user@$host" "${sshArgs[@]}" -- "$bash" -l "$@"; }
runiWsl() { wsl.exe -d "$dist" "$bash" -l "$@"; }

ScriptRun "$@"
