#!/usr/bin/env bash
. script.sh || exit
. color.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [COMMAND]... [OPTION]...
Additional BorgBackup functionality.
	
	backup			backup files
	environment	return environment variables
	extract			extract files
	init				initialize the repository
	ls					list backups
	mount				mount a backup
	repo				repository commands
	run					run borg
	status			show status
	unmount			unmount a backup
	vorta				run vorta

	-d, --dir=DIR						backup directory, defaults to '$backupDirDefault'
	-H,	--backup-host=HOST		backup host
	-P,	--passphrase=HOST		backup passphrase
	-r, --repository=NAME		backup repository name, defaults to '$backupRepoDefault'
	-u,	--user=USER					backup user, defaults to '$backupUserDefault'"
}

init()
{
	backupDirDefault="$ADATA/borg"
	backupUserDefault="root"
	backupRepoDefault="$HOSTNAME"
	borgArgs=( ); [[ $verbose ]] && borgArgs+=( "--verbose" )
	borgPath="/usr/local/bin/borg"
	mountDir="$HOME/Volumes/backup"
	vars=( BORG_PASSPHRASE BORG_REPO )
}

argStart() { unset -v backupDir backupHost backupPassphrase backupRepo backupUser; }

opt()
{
	case "$1" in
		-d|--dir|-d=*|--dir=*) ScriptOptGet "backupDir" "dir" "$@";;
		-H|--backup-host|-H=*|--backup-host=*) ScriptOptGet "backupHost" "host" "$@";;
		-P|--passphrase|-P=*|--passphrase=*) ScriptOptGet "backupPassphrase" "passphrase" "$@";;
		-r|--repository|-r=*|--repository=*) ScriptOptGet "backupRepo" "repo" "$@";;
		-u|--user|-u=*|--user=*) ScriptOptGet "backupUser" "user" "$@";;
		*) return 1;;
	esac
}

#
# other commands
#

environmentCommand() { setBorgEnvironment && ScriptReturn --export $verbose "${vars[@]}"; }
extractUsage() { echot "Usage: $(ScriptName) extract -- [OPTION]...\nExtract files, i.e. BorgHelper extract -- ::ProxyManager-2021-11-03_23:14:58"; }
extractCommand() { runBorg extract; }
initCommand() { hilight "Creating '$BORG_REPO'..."; runBorg init --encryption=repokey-blake2 "${otherArgs}"; }
lsUsage() { echot "Usage: $(ScriptName) list -- [OPTION]...\nList archives, i.e. BorgHelper ls -- --prefix 'web-'"; }
lsCommand() { runBorg list; }

statusCommand()
{
	setBorgEnvironment || return
	echo "borg will use the ${GREEN}$backupRepo${RESET} repository on ${GREEN}$backupHost${RESET}"
	log1 "user=$backupUser dir=$backupDir\nBORG_REPO=$BORG_REPO"
	return 0
}

#
# bBackup command
#

backupUsage()
{
		echot "\
Usage: $(ScriptName) backup [PATH [PATH ...]]
Backup files

	-a,	 --archive=NAME				name of the archive, defaults to archive (see 'borg help placeholders')
	-bh, --backup-hosts=HOSTS	comma separated list of hosts to backup to
	-nc, --no-check						do not check if the repository is initialized
	-p,	 --prune=N						prune backups leaving the last N backups"
}

backupArgStart() { archive="archive"; unset -v backupHostsArg noCheck prune; }

backupOpt()
{
	case "$1" in
		-a|--archive|-a=*|--archive=*) ScriptOptGet "archive" "$@";;
		-bh|--backup-hosts|-bh=*|--backup-hosts=*) ScriptOptGet "backupHostsArg" "$@";;
		-nc|--no-check) noCheck="--no-check";;
		-p|--prune|-p=*|--prune=*) ScriptOptGet --integer "prune" "$@";;
		*) return 1;;
	esac
}

backupArgs() { backupArgs=( "$@" ); shift="$#"; }

backupCommand()
{
	[[ ! $backupHostsArg ]] && { doBackup; return; }

	[[ "${backupHostsArg,,}" == "all" ]] && backupHostsArg="$(network current servers backup)"
	local backupHost backupHosts=(); StringToArray "$backupHostsArg" "," backupHosts
	for backupHost in "${backupHosts[@]}"; do doBackup || return; done
}

doBackup()
{
	setBorgEnvironment || return
	
	# backup
	hilight "Backing up the $backupRepo $archive archive to $(GetHostname "$backupHost")..."
	repoCheck || return
	runBorg create ::$archive'-{now:%Y-%m-%d_%H:%M:%S}' "${backupArgs[@]}" --stats --progress || return
	echo
	
	# prune
	if [[ $prune ]]; then
		echo "Pruning to $prune backups..."
		borg prune --keep-last $prune --prefix "$archive-" || return
	fi

	# status
	[[ ! $prune ]] && echo "Backups..."
	borg list --prefix "$archive-" || return
	echo
}

#
# mount/unmount command
#

mountUsage()
{
		echot "\
Usage: $(ScriptName) mount [ARCHIVE]
Mount backup repository or archive to $mountDir."
}

mountArgStart() { unset -v archive; }
mountArgs() { [[ $# == 0 ]] && return; ScriptArgGet "archive" -- "$@"; shift; }

mountCommand()
{
	# create the mount directory
	[[ ! -d "$mountDir" ]] && { mkdir --parents "$mountDir" || return; }

	# unmount existing borg backup
	isMounted && [[ $force ]] && { unmountCommand || return; }

	# mount the borg backup
	! isMounted && { borg mount "$archive" "$mountDir" || return; }

	# return the mounted directory
	echo "$mountDir"
}

unmountCommand()
{
	{ [[ ! -d "$mountDir" ]] || ! isMounted; } && return
	borg umount "$mountDir" || return
}

isMounted() { findmnt --list --source=borgfs --target="$mountDir" >& /dev/null; }

#
# repo command

repoUsage() { echot "Usage: $(ScriptName) repo ls\nBorg repository commands."; }

repoCommand() { usage; }
repoLsCommand() { setBorgRepo && ssh "$backupHost" ls -1 "$backupDir"; }

#
# run command
#

runUsage()
{
		echot "\
Usage: $(ScriptName) [COMMAND]... [OPTION]...
Run borg as root."
}

runArgs() { runArgs=( "$@" ); shift="$#"; }
runCommand() { runBorg "${runArgs[@]}"; }

#
# vorta command
#

vortaCommand()
{
	log1 "borg $@ ${borgArgs[@]} ${otherArgs[@]}"
	sudoc BORG_PASSPHRASE="$BORG_PASSPHRASE" BORG_REPO="$BORG_REPO" \
		SSH_AUTH_SOCK="$SSH_AUTH_SOCK" SSH_AGENT_PID="$SSH_AGENT_PID" \
		vorta "${otherArgs[@]}" &
}

#
# helper
#

isBorgBaseHost() { [[ "$backupHost" =~ borgbase\.com$ ]]; }
repoCheck() { [[ $noCheck ]] || repoExists || initCommand; }

repoExists()
{
	[[ ! "$backupDir" || $test ]] && return 0
	ssh "$backupHost" "[[ -d \"$backupDir$backupRepo\" ]]"
}

runBorg()
{
	setBorgEnvironment || return

	IsRoot && { RunLog borg "$@" "${borgArgs[@]}" "${otherArgs[@]}"; return; }

	RunLog sudoc BORG_PASSPHRASE="$BORG_PASSPHRASE" BORG_REPO="$BORG_REPO" BORG_REMOTE_PATH="$borgPath" BORG_RELOCATED_REPO_ACCESS_IS_OK="$BORG_RELOCATED_REPO_ACCESS_IS_OK" \
		SSH_AUTH_SOCK="$SSH_AUTH_SOCK" SSH_AGENT_PID="$SSH_AGENT_PID" \
		borg "$@" "${borgArgs[@]}" "${otherArgs[@]}"
}

setBorgEnvironment()
{
	export BORG_RELOCATED_REPO_ACCESS_IS_OK="yes"
	setBorgPassphrase && setBorgRepo
}

setBorgPassphrase()
{
	local passphrase="${backupPassphrase:-$BORG_PASSPHRASE}"
	[[ $force || ! $passphrase ]] && { passphrase="$(credential get borg passphrase --fallback)" || return; }
	export BORG_PASSPHRASE="$passphrase"
}

setBorgRepo()
{
	# do not use BORG_REPO for configuration if forcing or if configuration has been supplied from options
	[[ $force ]] && unset BORG_REPO
	[[ $backupDir || $backupHost || $backupUser || $backupRepo ]] && unset BORG_REPO

	# backup host alias
	case "${backupHost,,}" in
		bb|borgbase) backupRepo="${backupRepo:-$backupRepoDefault}"
			case "${backupRepo,,}" in
				oversoul) backupHost="mk099950.repo.borgbase.com";;
				pi1) backupHost="h7gnr153.repo.borgbase.com";;
				pi2) backupHost="q3d82g14.repo.borgbase.com";;
				pi3) backupHost="gw3jk69x.repo.borgbase.com";;
				rosie) backupHost="kx172994.repo.borgbase.com";;
				*) ScriptErr "No backup host specified for repository '$backupRepo'"; return 1;;
			esac;;
		db|dropbox) backupHost="ender.hagerman.butare.net" backupDir="${backupDir:-/Users/jjbutare/Juntos Holdings Dropbox/John Butare/apps/BorgBackup}" backupUser="jjbutare"
	esac

	# get the backup host from BORG_REPO if needed
	[[ ! $backupHost && $BORG_REPO ]] && backupHost="$(GetSshHost "$BORG_REPO")"

	# discover the backup host if needed
	[[ ! $backupHost ]] && { backupHost="$(network current server backup)" || return; }

	# ensure the backupHost is a fully qualified domain name (prevents extra borg prompting)
	! HasDnsSuffix "$backupHost" && { backupHost="$(DnsResolve "$backupHost")" || return; }

	# get the backup dir from BORG_REPO if needed or use the default
	[[ ! $backupDir && $BORG_REPO ]] && backupDir="$(GetSshPort "$BORG_REPO" | RemoveTrailingSlash | GetFilePath)"	
	backupDir="$(EnsureDir "${backupDir:-$backupDirDefault}")"

	# get the backup repo from BORG_REPO if needed or use the default
	[[ ! $backupRepo && $BORG_REPO ]] && backupRepo="$(GetSshPort "$BORG_REPO" | RemoveTrailingSlash | GetFileName)"	
	backupRepo="${backupRepo:-$backupRepoDefault}"

	# get the backup user from BORG_REPO if needed or use the default
	[[ ! $backupUser && $BORG_REPO ]] && backupUser="$(GetSshUser "$BORG_REPO")"	
	backupUser="${backupUser:-$backupUserDefault}"
		
	# BorgBase special handling: u578g3w0@u578g3w0.repo.borgbase.com:repo
	if isBorgBaseHost; then
		backupUser="$(RemoveDnsSuffix "$backupHost")"
		backupDir="" backupRepo="repo"
	fi

	# set the BORG_REPO environment variable
	export BORG_REPO="$backupUser@$backupHost:$backupDir$backupRepo"
}

ScriptRun "$@"
