#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [IsInstalled|IsRunning|profile|program|start|startup](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="/usr/local/bin/broot"
	profileName="broot"
	profileDir="$HOME/.config/broot"
	profileMask="*"
	return 0
}

isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsTaskRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
									 
ScriptRun "$@"
