#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: templateApp [start|startup|close|restart|opds|OpdsGui](start)
  profile save|restore|dir|SaveDir [<profile name>|default](latest) [--global]
  -b, --brief		brief status messages"; exit $1; }

args()
{
	unset -v brief help
	command="start"
	while (( $# != 0 )); do
		case "$1" in
			--brief|-b) brief="--brief";;	
			--help) help="--help";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";; OpdsGui) command="OpdsGui";;
			*)
				! IsOption "$1" && { CheckCommand "$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init()
{ 
	program="$P/Calibre2/calibre.exe"
	opdsProgram="$P/calibre2opds/run.cmd"
	opdsGuiProgram="$P/calibre2opds/rungui.cmd"
}

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } # task close|CloseKill [--wait] [--title "$title"] "$program"; ProcessKill "$program"; SendKeys "$title" "!FX"; 
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

opdsCommand()
{
	[[ -f "$opdsProgram" ]] || return
	pushd "$(GetFilePath "$opdsProgram")" || return
	cmd /c "$(GetFileName "$opdsProgram")" || return
	popd || return
}

OpdsGuiCommand()
{
	[[ -f "opdsProgram" ]] || return
	pushd "$(GetFilePath "$opdsGuiProgram")" || return
	cmd /c "$(GetFileName "$opdsGuiProgram")" || return
	popd || return
}

run "$@"