#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$P/Calibre2/calibre.exe"
	opdsProgram="$P/calibre2opds/run.cmd"
	opdsGuiProgram="$P/calibre2opds/rungui.cmd"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }

opdsCommand()
{
	[[ -f "$opdsProgram" ]] || return
	pushd "$(GetFilePath "$opdsProgram")" || return
	cmd /c "$(GetFileName "$opdsProgram")" || return
	popd || return
}

opdsGuiCommand()
{
	[[ -f "opdsProgram" ]] || return
	pushd "$(GetFilePath "$opdsGuiProgram")" || return
	cmd /c "$(GetFileName "$opdsGuiProgram")" || return
	popd || return
}
									 
ScriptRun "$@"
