#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$WIN_ROOT/Chocolatey/chocolateyinstall/chocolatey.cmd"
}

argEnd()
{
	AppInstallCheck || return
	[[ ! -d "$profileDir" ]] && { ${G}mkdir --parents "$profileDir" || return; }
}

closeCommand() { return; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { return; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

startArgs() { startArgs=( "$@" ); shift="$#"; }

startCommand()
{
	! AppInstallCheck && return
	unset APPDATA LOCALAPPDATA TMP TEMP PROGRAMDATA ProgramData WINDIR
	cmd /c "$(utw "$WIN_ROOT/Chocolatey/chocolateyinstall/chocolatey.cmd")" "${startArgs[@]}"
}

ScriptRun "$@"
