#!/usr/bin/env bash
#-x (debug) -v (verbose)
. function.sh || exit
unset APPDATA LOCALAPPDATA TMP TEMP PROGRAMDATA ProgramData WINDIR
cmd /c "$(utw "$ROOT/Chocolatey/chocolateyinstall/chocolatey.cmd")" "$@"
