#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

	case "$PLATFORM_OS" in
		mac) program="";;
		win) program="$UADATA/AnthropicClaude/claude.exe";;
	esac

}

closeCommand() { ! isRunningCommand && return; ProcessClose "$programRunning"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$programRunning"; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }
									 
ScriptRun "$@"
