#!/usr/bin/env bash
#-x (debug) -v (verbose)
. function.sh || exit

usage()
{
	echot "\
usage: CleanupFiles
	Cleanup common operating system files"
	exit $1
}

args()
{
	unset -v file
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			*)
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && usage 0
	args=("$@")
}

run() {	args "$@" || return; CleanupFilesCommand "${args[@]}"; }

CleanupFilesCommand()
{
	local sudo=
	[[ "$PLATFORM" == "mac" ]] && sudo="sudo"

	echo -n "cleaning files..."

	[[ -d "$TMP" ]] && { $sudo rm -fr "$TMP/"*; echo -n "."; }

	if [[ "$PLATFORM" == "win" ]]; then
		[[ -d "$ROOT/temp" ]] && { rm -fr "$ROOT/temp/"* >& /dev/null; echo -n "."; }
		[[ -d "$tmp" ]] && { rm -fr "$tmp/"* >& /dev/null; echo -n "."; }
		[[ -d "$WINDIR/Temp" ]] && { rm -fr "$WINDIR/Temp/"* >& /dev/null; echo -n "."; }
	fi

	echo "done"

	which gem >& /dev/null && ask "Cleanup gem" && { sudo gem cleanup || return; }
	which brew >& /dev/null && ask "Cleanup brew" && { brew cleanup || return; }
  	which autoruns >& /dev/null && ask 'Cleanup startup programs' && { autoruns || return; }

	if [[ "$PLATFORM" == "win" ]] && ask "Cleanup path"; then
		os path editor || return
		echo "- Remove unused entries from the system path"
	fi
}

run "$@"
