#!/usr/bin/env bash
#-x (debug) -v (verbose)
. function.sh || exit

usage()
{
	echot "\
usage: CleanupFiles
	Cleanup common operating system files"
	exit $1
}

args()
{
	unset -v file
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			*)
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && usage 0
	args=("$@")
}

run() {	args "$@" || return; CleanupFilesCommand "${args[@]}"; }

CleanupFilesCommand()
{
	[[ "$PLATFORM" == "win" ]] && return 0 # needs testing

	echo -n "cleaning files..."
	[[ -d "$TMP" ]] && sudo rm -fr "$TMP/"*

	if [[ "$PLATFORM" == "win" ]]; then
		[[ -d "~/Local Settings/Temp" ]] && rm -fr "$~/Local Settings/Temp"
		[[ -d "$WINDIR/Temp" ]] && rm -fr "$WINDIR/Temp"
	fi

	echo "done"

	which gem && { sudo gem cleanup || return; }
	which brew && { brew cleanup || return; }
}

run "$@"
