#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|close|profile|program|IsInstalled|IsRunning|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="CleanMyMac" profileDir="$HOME/Library/Preferences" profileMask="com.macpaw.CleanMyMac4.*"
	program="$P/CleanMyMac X.app"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); return 0; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { isRunningCommand && return; startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
