#!/usr/bin/env bash
. script.sh || exit

usage() { ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... check|diff|start|terminal
$(ScriptName) commands."; }

checkCommand()
{
  local service="chrony"; IsPlatform mac && service="org.tuxfamily.chronyc"
  if InPath chronyc && service running "$service"; then
    header "Chrony Sources"; chronyc sources || return
    header "Chrony Client"; chronyc tracking || return
  fi

  local timeServer="$(ConfigGet "timeServer")"
  if [[ $timeServer ]] && diffInstalled && IsAvailable "$timeServer"; then
    header "Time Server Comparison ($timeServer)"
    diff "$timeServer" || return;
  fi

  if [[ -f "/etc/chrony/chrony.conf" ]] && grep "^allow" "/etc/chrony/chrony.conf" >& /dev/null; then
    header "Chrony Server"
    sudoc chronyc serverstats || return
  fi
}

startCommand()
{
  if [[ $DISPLAY ]] && InPath xclock; then coproc xclock -title $HOSTNAME -digital -update 1
  else terminalCommand
  fi
}

terminalCommand()
{
  if InPath tty-clock; then tty-clock -s -c; 
  else date;
  fi
}

#
# diff command
#

diffUsage() { EchoWrap "$1" "Usage: $(ScriptName) diff [HOST](time.apple.com)\nCompare system time against another host."; }
diffArgStart() { host="time.apple.com"; }
diffArgs() { (( $# == 0 )) && return; ScriptArgGet "host" -- "$@"; }
diffCommand() { diff "$host"; }

diff()
{
  local host="$1"
  if IsPlatform mac; then sudoc sntp -sS "$host"
  elif InPath ntpdate; then ntpdate -q "$host"
  fi
}

diffInstalled() { IsPlatform mac || InPath ntpdate; }

ScriptRun "$@"
