#!/usr/bin/env bash
. script.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... dns|test|resolve|update|zone
Manage CloudFlare DNS."
}						 

init() { nameServer="1.1.1.1"; }

#
# Commands
#

testCommand() { api "user/tokens/verify" | jq; }

#
# DNS Commands
#

dnsUsage()
{
	echot "Usage: $(ScriptName) dns id|list
Zone commands.

	id ZONE HOST	return the specified host's DNS ID
	list ZONE			list all DNS records in the specified zone"
}

dnsCommand() { dnsListCommand; }
dnsListArgs() { getZoneArg "$@"; }
dnsListCommand() { getDnsRecords "$zone"; }
dnsIdArgs() { getZoneArg "$@" && shift && getHostArg "$@"; }
dnsIdCommand() { getDnsRecordId "$zone" "$host"; }

#
# Resolve Commands
#

resolveUsage() { echot "Usage: $(ScriptName) resolve NAME\nResolve a name using CloudFlare."; }
resolveArgs() { ScriptArgGet "name" -- "$@"; }
resolveArgEnd() { [[ $(GetDnsSuffix "$name") ]] && return; name+=".$(NetworkDnsBaseDomain)"; }
resolveCommand() { dig "$name" @$nameServer +short; }

#
# Update Command
#

updateUsage()
{
	echot "Usage: $(ScriptName) update ZONE HOST IP
Update a DNS HOST record to IP."
}

updateArgs()
{
	getZoneArg "$@"; shift
	getHostArg "$@"; shift
	ScriptArgGet "ip" -- "$@"; shift
}

updateCommand()
{
	local name="$host.$zone"
	local currentIp; currentIp="$(dig "$name" @$nameServer +short)" || return

	# only update if it changed
	[[ ! $force && "$currentIp" == "$ip" ]] && return

	# https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record
	local id; id="$(getDnsRecordId "$zone" "$host")" || return
	apiPut "$id" '{"type":"A","name":"'$name'","content":"'$ip'","ttl":1,"proxied":false}'
}

#
# Zones Command
#

zonesUsage()
{
	echot "Usage: $(ScriptName) zone list
Zone commands.

	id ZONE		return the zone ID
	list			list all zones"
}

zoneCommand() { usage; }
zoneListCommand() { api "zones"; }

zoneIdArgs() { getZoneArg "$@"; }
zoneIdCommand() { getZoneId "$zone"; }

#
# API Helper
#

api()
{
	local command="$1"
	local key; key="$(credential get CloudFlare key --fallback --quiet)" || return
	local url="https://api.cloudflare.com/client/v4/$command"

	[[ $test ]] && return

	curl --silent -X GET "$url" \
		-H "Authorization: Bearer $key" \
		-H "X-Auth-Email:johns@butare.net" \
	  -H "Content-Type:application/json"
}

apiPut()
{
	local command="$1" data="$2"
	local key; key="$(credential get CloudFlare key)" || return
	local url="https://api.cloudflare.com/client/v4/$command"

	[[ $test ]] && return

	curl -X PUT "$url" \
		-H "Authorization: Bearer $key" \
		-H "X-Auth-Email:johns@butare.net" \
		-H "Content-Type:application/json" \
		--data "$data"
}

getHostArg() { ScriptArgGet "host" -- "$@"; }
getZoneArg() { ScriptArgGet "zone" -- "$@"; }

getZoneId()
{
	local zone="$1"
	local id; id="$(api "zones" | jq ".result[] | select(.name == \"$zone\").id" | RemoveQuotes)" || return
	[[ ! $quiet && ! $id ]] && EchoErr "zone '$zone' not found"
	[[ $id ]] && echo "$id"
}

getDnsRecords() { local zone="$1" id; id="$(getZoneId "$zone")" && api "zones/$id/dns_records"; }

getDnsRecordId()
{
	local zone="$1" name="$2"
	local dnsRecords; dnsRecords="$(getDnsRecords "$zone")" || return
	local zoneId="$(echo "$dnsRecords" | jq ".result[] | select(.name == \"$name.$zone\").zone_id" | RemoveQuotes)" || return
	local dnsId="$(echo "$dnsRecords" | jq ".result[] | select(.name == \"$name.$zone\").id" | RemoveQuotes)" || return
	[[ ! $dnsId ]] && { [[ ! $quiet ]] && EchoErr "DNS record '$name' in zone '$zone' not found"; return 1; }	
	echo "zones/$zoneId/dns_records/$dnsId"
}

ScriptRun "$@"
