#!/usr/bin/env bash
. app.sh || exit

usage() 
{	
	echot "
usage: code changes|checkout|clone|commit|log|status|update PROJECTS
	changes         exit status is 0 if there are changes
  switch PROJECTS [-v|--version VERSION](master)
  -g, --gui		use the GUI command"
	exit $1
}

args()
{
	unset -v command gui projects 
	version="master"

	while (( $# != 0 )); do
		case "$1" in
			-g|--gui) gui="true";;
			-v|--version) version="$2"; shift;;
			-h|--help) usage 0;;
			IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && { ! IsFunction "${1,,}Command" && usage 1; command="${1,,}"; shift; continue; }

				if [[ "$command" == @(log) ]]; then
					file="$1"; shift
					[[ ! -f "$file" ]] && { EchoErr "code: cannot access `$file`: No such file"; return 1; }
				else
					local project="$1" projectDir="$CODE/$1"; projects+=( "$project" )					
					[[ "$command" == @(clone)  && ! -d "$projectDir" ]] && { mkdir --parents "$projectDir" || return; }
					[[ ! -d "$projectDir" ]] && { EchoErr "code: cannot access \`$project\`: Project does not exist"; return 1; }
				fi;;
		esac
		shift
	done
	[[ ! $command ]] && MissingOperand "COMMAND"
	[[ $command == @(log) && ! $file ]] && MissingOperand "FILE"

	args=( "$@" )
}

init()
{ 
	gitRepository="github.intel.com/csis"
}

run() 
{	
	args "$@" || return; init || return; 
	
	if [[ "$command" == @(log) ]]; then
		${command}Command "${args[@]}"; return
	fi

	[[ ! $projects ]] && MissingOperand "PROJECTS"; shift
	for project in "${projects[@]}"; do
		projectDir="$CODE/$project"
		${command}Command "${args[@]}" || return
	done
}

gitc() { builtin cd "$projectDir" || return; git "$@"; }
gitg() { builtin cd "$projectDir" || return; GitHelper gui "$@"; }

checkoutCommand() { gitc checkout "$version"; }

statusCommand() 
{ 
	echo "************ $project Status ************"
	gitc status
}

revertCommand()
{ 
	echo "************ Reverting $project ************"
	[[ $gui ]] && { gitg commit; return; } 
	gitc reset --hard;
}

changesCommand() {  [[ "$(gitc status --porcelain)" != "" ]]; }

commitCommand() 
{ 
	echo "************ Committing $project ************"
	! code changes "$project" && { echo "no changes"; return 0; }
	echo "changes present..."
	gitg
}

cloneCommand()
{ 
	echo "************ Cloning $project ************"

	[[ ! -d "$projectDir/.git" ]] && { gitc clone "https://$gitRepository/$project" "$projectDir" || return; }
	cd "$projectDir" && { GitHelper hide || return; }
}

updateCommand()
{ 
	echo "************ Updating $project ************"
	integrationResetAll || return
	gitc up || return
}

branchExist() { gitc rev-parse --verify $1 >& /dev/null; }

integrationResetAll()
{
	local branch
	for branch in Continuous Test Pre-Production; do
		integrationReset $branch || return;
	done
	return 0
}

integrationReset() 
{ 
	local branch=$1

	branchExist $branch || return 0

	local localSha="$(gitc show-ref --verify refs/heads/$branch | cut -f1 -d" ")"
	local remoteSha="$(gitc show-ref --verify refs/remotes/origin/$branch | cut -f1 -d" ")"
	[[ "$localSha" == "$remoteSha" ]] && return 0

	local currentBranch="$(gitc symbolic-ref -q HEAD | cut -d"/" -f 3)"

	echo "Reseting $branch..."
	[[ "$currentBranch" != "$branch" ]] && { gitc checkout $branch || return; }
	gitc reset --hard origin/$branch || return
	[[ "$currentBranch" != "$branch" ]] && { gitc checkout $currentBranch || return; }
}

run "$@"