#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init()
{
	program="$P/Adobe/Adobe Creative Cloud/ACC/Creative Cloud.exe"
	IsPlatform mac && program="$P/Utilities/Adobe Creative Cloud/ACC/Creative Cloud.app"

	return 0
}

usage() {	echot "usage: CreativeCloud"; exit $1; }

args()
{
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
startCommand() { IsInstalledCommand && start $wait "$program" $waitArg "$@"; }

run "$@"
