#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: credential [ -q ]
	check 													check if we can use credential management
	exists attribute value					see if a credential exists
	get attribute value 						get the password specified by attribute and value
	set attribute value password 		set the password specified by attribute and value to password
"
	exit 1
}

args()
{
	unset command attribute value password quiet

	[[ "$1" == "-q" ]] && { quiet="true"; shift; }

	{ [[ $# == 0 ]] || ! IsFunction ${1}Command; } && usage

	case "$command" in
		exists|get) [[ $# != 3 ]] && usage;;
		set) [[ $# != 4 ]] && usage;;
	esac

	command="$1" attribute="$2" value="$3" password="$4"
}

run() {	args "$@"; checkCommand || return; "${command}Command"; }

noCredentialManager()
{
	[[ ! "$quiet" ]] && EchoErr "A credential manager is not available"
	exit 1
}

checkCommand()
{
	local remoteServer

	_platform="$PLATFORM"
	_platformLike="$PLATFORM_LIKE"
	_platformId="$PLATFORM_ID"

	case "$_platform" in
		linux) [[ "$DISPLAY" ]] && which secret-tool >& /dev/null && return;;
		win) which wincred.exe >& /dev/null && return;;
	esac

	noCredentialManager
}

existsCommand()
{
	case "$_platform" in
		linux) secret-tool search ssh default |& grep label >& /dev/null;;
		win) cmd.exe /c wincred.exe get "$attribute-$value" |& egrep -v "does not exist" >& /dev/null;;
	esac
}

getCommand()
{	
	local pass

	case "$_platform" in
		linux) pass="$(secret-tool lookup "$attribute" "$value")";;
		win) pass="$(RunInDir wincred.exe get "$attribute-$value" 2> /dev/null)";;
	esac

	if [[ ! $pass && $DISPLAY && -f /usr/bin/ssh-askpass ]]; then
		pass="$(SUDO_ASKPASS=/usr/bin/ssh-askpass ssh-askpass "Enter the $attribute $value password" )"
	fi

	[[ ! $pass ]]	&& return 1
	echo "$pass"
}

setCommand()
{
	case "$_platform" in
		linux) echo "$password" | secret-tool store --label "credential for $attribute $value" "$attribute" "$value";;
		win) RunInDir wincred.exe set "$attribute-$value" "$USER" "$password" 2> /dev/null;;
	esac
}

run "$@"

