#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() 
{ 
	:
}

usage() {	echot "usage: CrontHelper backup"; exit $1; }

args()
{
	unset -v noPrompt 

	while (( $# != 0 )); do
		case "$1" in
			--help|-h) usage 0;;
			--no-prompt|-np) noPrompt="--no-prompt";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	
	[[ ! $command ]] && { MissingOperand "command"; }
	args=( "$@" )
}

#
# commands
#

backupCommand() { AppBackup "$HOSTNAME.cron" /etc/cron* || return; }

run "$@"
