#!/bin/bash
. app.sh

init()
{ 
	command="start"
	program="$P32/CCTray/cctray.exe"
	title="CCTray "

	ProfileApp="CruiseControlTray"
	ProfileMethod="$APPDATA"
	ProfileFiles="cctray-settings.xml"
}

usage() {	echot "usage: templateApp [start|startup|close|restart|cd](start)
  profile dir|SaveDir|backup|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	task start --wait --title "$title" "$program" "$@"
	WinClose "$title"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"