#!/bin/bash
. app.sh

# setup examples:
#   cygwin download 			# view and download the latest updates, or download new packages
#   cygwin install 				# install latest updates
# 	cygwin download -q 		# get latest updates with no prompting
# 	cygwin install -q 		# install latest updates with no prompting
#   cygwin download -q -P attr,cron	# download the attr and cron packages silently
#   cygwin install -q -P attr,cron	# download the attr and cron packages silently
#		cygwin close || return; cygwin install || return # install packages which require Cygwin programs closed
# 	cygwin setup -q --download --root /cygdrive/c/Temp # re-download core packages that are installed on the local system

usage() {	
echot "\
usage: cygwin [command] (install)
	cleanup - cleanup directories
  close - close Cygwin programs
  setup|(re)download|install|help [-P|--packages <package,...>] [-C|--categories <categories,...>] 
  	download (to local store), install (from local store), or start setup
	-q|--quiet  		run in quiet mode without prompting"
	exit $1
}

init()
{ 
	installDir="$P/Cygwin"
	bin="$InstallDir/bin"
	downloadSite="http://mirrors.kernel.org/sourceware/cygwin/"
	defaultPackages="dialog,git,git-gui,gitk,git-completion,openssh,util-linux,vim"
	setupArgs=( --no-shortcuts --site "$downloadSite" --root "$installDir" )
}

args()
{
	unset setup packageDir 
	quiet="--package-manager"
	while [[ "$1" != "" ]]; do
		case "$1" in
			-q|--quiet) quiet="--quiet-mode";;
			-h|--help) usage 0;;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(download|install|setup) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='install'
	args=( "$@" )
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
RunSetup() {	FindSetup || return; start -d="$tmp" "$setup" "${setupArgs[@]}" "$@"; }
setupCommand() { RunSetup "$@"; }
helpCommand() { FindSetup || return; "$setup" --help; }
installCommand() { RunSetup $quiet --local-install "$@"; }
downloadCommand() { RunSetup $quiet --download "$@"; }

redownloadCommand()
{
	FindSetup || return
	DelDir --content --ask "$packageDir"
	RunSetup -q --download --root /cygdrive/c/Temp -P "$defaultPackages"
}

closeCommand()
{
	pskill ssh-agent >& /dev/null
	service stop sshd

	while true; do
		bashCount=$(( $(pslist bash |& egrep "^bash" | wc -l) - 4 ))
		(( bashCount == 0 )) && break
		pause "Manually close $bashCount bash shells then process any key..."
	done
	echo "Once setup has started, close this terminal"
}

FindSetup()
{
	[[ $setup ]] && return
	local base
	base="$(FindPublicDoc data/install/Cygwin)" || return
	setup="$base/setup/setup-x64.exe"
	packageDir="$base/package-x64"
	setupArgs+=( --local-package-dir "$packageDir" )
}

cleanupCommand()
{
	# cleanup files in /
	local files=( "/Cygwin.bat" "/Cygwin-Terminal.ico" "/Cygwin.ico" )
	for file in "${files[@]}"; do 
		rm -f "$file" || return
	done
}

run "$@"
