#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: DasKeyboard [start|close|program|IsInstalled](start)
  -b, --brief		brief status messages"; exit $1; }

init()
{	
	title="Das Keyboard Q"
	
	case "$PLATFORM" in
		win) program="$ADATA/das-keyboard-q/das-keyboard-q.exe";;
	esac
}

args()
{
	unset var wait
	while (( $# != 0 )); do
		case "$1" in
			--brief|-b) brief="--brief";;	
			--help|-h) usage 0;;
			--wait|-w) wait="--wait";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1
	task start --minimize "$program" --title "$title" --wait || return
	/usr/bin/sleep 2 || return
	WinSetState "Das Keyboard Q" minimize || return	
}

closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startupCommand() { startCommand; }
run() {	init; args "$@"; ${command}Command "${args[@]}"; }

run "$@"
