#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: DelDir <dirs>
	Safely delete directories
	-a, --ask			ask to delete the directory
	-v, --verbose verbose output"
	exit $1
}

init() { :; }

args()
{
	unset ask dir verbose
	while [ "$1" != "" ]; do
		case "$1" in
			--ask|-a) ask="true";;
			--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			--verbose|-v) verbose="true";;
			*)
				! IsOption "$1" && [[ ! $dir ]] && { dir="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $dir ]] && MissingOperand "dir"
	args=("$@")
}

run()
{	
	init; args "$@"; 
	delete "$dir"
}

delete()
{
	[[ ! -d "$dir" ]] && return
	
	if [[ $ask ]]; then
		ask "Are you sure you want to delete directory \"$dir\"" -dr n || return 1
	fi

	[[ $verbose ]] && printf "Deleting directory \"$dir\"..."
	rm -fr "$dir" || return
	[[ $verbose ]] && echo "done"
}

run "$@"
