#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [DIR]... [OPTION]...
Safely delete a directory
	-a, --ask				ask before deleting 
	-c, --contents	delete the contents"
}

init() { defaultCommand="delete"; }
argStart() { unset -v ask contents; }

opt()
{
	case "$1" in
		--ask|-a) ask="true";;
		--contents|-c) contents="true";;
		*) return 1;;
	esac
}

args() { ScriptArgGet "dir" -- "$@"; shift; }

deleteCommand()
{
	[[ ! -d "$dir" ]] && return
	
	if [[ $ask ]]; then
		local desc; [[ $contents ]] && desc=" the contents of"
		ask "Are you sure you want to delete$desc directory \`$(FileToDesc "$dir")\`" -dr n || return 1
	fi

	[[ $verbose ]] && printf "Deleting directory \"$dir\"..."
	[[ $contents ]]	&& { rm -fr "$dir/"* || return; } || { rm -fr "$dir" || return; }
	log1 "done"
	return 0
}

ScriptRun "$@"
