#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	echot "\
Usage: $(ScriptName) FILES
	Safely delete files
	-a, --ask			ask to delete the file
	-t, --test		do not delete the file"
	exit $1
}

init() { :; }

args()
{
	unset ask file test
	while [ "$1" != "" ]; do
		case "$1" in
			-a|--ask) ask="true";;
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			-t|--test) test="true";;
			*)
				! IsOption "$1" && [[ ! $file ]] && { file="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $file ]] && MissingOperand "file"
	args=("$@")
}

run()
{	
	init; args "$@"; 
	delete "$file"
}

delete()
{
	[[ ! -f "$file" ]] && return
	
	if [[ $ask ]]; then
		ask "Are you sure you want to delete file \"$file\"" -dr n || return 1
	fi
	
	[[ $test ]] && echo "DelFile: would have deleted \`$file\`" || rm -f "$file"
}

run "$@"
