#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) FILES
Safely delete files.
	-a, --ask			ask to delete the file
	-t, --test		do not delete the file"
}

init() { defaultCommand="delete"; }
argStart() { unset -v ask; }

opt()
{
	case "$1" in
		-a|--ask) ask="true";;
		*) return 1;;
	esac
}

args() { files=( "$@" ); (( shift+=$# )); return 0; }

deleteCommand()
{
	local file; for file in "${files[@]}"; do deleteDo "$file" || return; done
}

# deleteDo FILE
deleteDo()
{
	[[ ! -f "$file" ]] && return
	
	if [[ $ask ]]; then
		ask "Are you sure you want to delete file \"$file\"" -dr n || return 1
	fi
	
	[[ $test ]] && { echo "DelFile: would have deleted \`$file\`"; return; }

	rm -f "$file"
}

ScriptRun "$@"
