#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup|switch](start)
$(ScriptName) commands."
}

init()
{
	ddm="/mnt/c/Program Files (x86)/Dell/Dell Display Manager/ddm.exe"
	ddmHost="oversoul"
	ddmHostInput="DP"
	ddmAlternateInput="Thunderbolt (90W)"

	defaultCommand="start"
	program="$ddm" 
 	profileName="DellDisplayManager"
	profileKey="HKEY_CURRENT_USER/Software/EnTech/DDM"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsTaskRunning "$(GetFileName "$program")"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { ddmCheck && profile $noPrompt --app "$profileName" --method "$profileKey" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { ddmCheck && closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { ddmCheck && isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { ddmCheck && startCommand "$@"; }

switchCommand()
{
	ddm /SetActiveInput "$(onDdmHost && echo "$ddmAlternateInput" || echo "$ddmHostInput")"
}

#
# helper
#

ddmCheck() { [[ -f "$ddm" ]] && return; ScriptErr "Dell Display Manager is not installed"; return 1; }
onDdmHost() { [[ "$HOSTNAME" == "$ddmHost" ]]; }

# runDdm [COMMAND]... - run a DDM command on the ddmHost
ddm()
{
	if [[ -f "$ddm" ]]; then
		"$ddm" "$@"
	else
		local cmd="'$ddm' $@"
		ssh "$ddmHost" "$cmd"
	fi
}

ScriptRun "$@"
