#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: DiskSpaceUsage DIR"; exit $1; }

init() 
{ 
	program=() start="start"
	
	case "$PLATFORM" in
		mac) program="$P/Disk Inventory X.app";;
		win) program="$DATA/platform/win/windirstat.exe";;
	esac
	[[ -f "$program" ]] && return

	if [[ ! $DISPLAY ]]; then
		InPath ncdu && { program="ncdu"; start=""; return; }
		InPath gt5 && { program="gt5"; start=""; return; }
		InPath duc && { program=( duc ui ); start=""; return; }
	fi

	InPath qdirstat && { program="qdirstat"; return; }
	InPath baobab && { program="baobab"; return; }

	return 0
}

run() {	init || return; startCommand "$@"; }

startCommand()
{
	local args=( "$@" ); [[ "${#args[@]}" == "0"  || "$1" == "." ]] && args="$PWD"

	$start "${program[@]}" "${args[@]}"
}

run "$@"