#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: DiskSpaceUsage DIR"; exit $1; }

init() 
{ 
	case "$PLATFORM" in
		mac) program="$P/Disk Inventory X.app";;
		win) program="$DATA/platform/win/windirstat.exe";;
	esac
}

run() {	init || return; startCommand "$@"; }
cdCommand() { echo "$cd"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } # task close|CloseKill [--wait] [--title "$title"] "$program"; ProcessKill "$program"; SendKeys "$title" "!FX"; 
IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	local args=( "$@" ); (( ${#args[@]} == 0 )) && args="."
	start "$program" "${args[@]}"
}

run "$@"