#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) IsActive|IsInstalled|version
Docker helper commands.
	
	IsActive			return true if the Docker Swarm node is active
	IsInstalled		return true if Docker is installed"
}

init()
{
	defaultCommand="start"

	case "$PLATFORM_OS" in
		mac) program="$P/Docker.app";;
		win) program="$P/Docker";;
	esac
}

#
# commands
#

isActiveCommand() { isActive; }
isInstalledCommand() { isInstalled; }
isRunningCommand() { IsProcessRunning "$program"; }
closeCommand() { :; } 
startCommand() { AppInstallCheck && start "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }

versionCommand()
{
	! AppInstallCheck && return

	case "$PLATFORM_OS" in
		mac) defaults read "$P/Docker.app/Contents/Info.plist" "CFBundleShortVersionString";;
		win) CanElevate && registry get "HKLM/Software/Microsoft/Windows/CurrentVersion/Uninstall/Docker Desktop/DisplayVersion" | RemoveCarriageReturn;;
	esac
}

#
# IsHealthy Command
#

isHealthyUsage() { echot "\
Usage: $(ScriptName) IsHealthy NAME
Check the health status of container NAME.  Returns healthy (return code 0) or unhealthy (return code 1)."; }

isHealthyArgStart() { unset name; }
isHealthyArgs() { ScriptArgGet "name" -- "$@"; shift; }

isHealthyCommand()
{
	local status; status="$(docker inspect --format='{{.State.Health.Status}}' "$name")" || return
	echo "$name is $status"
	[[ "$status" == "healthy" ]] && return 0 || return 2
}

#
# helper
#

isActive() { isInstalled && docker node inspect pi1 |& grep '"Availability": "active"' >& /dev/null; }
isInstalled() { [[ -d "$program" ]]; }

ScriptRun "$@"
