#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) IsActive|IsInstalled|version
Docker helper commands.
	
	IsActive			return true if the Docker Swarm node is active
	IsInstalled		return true if Docker is installed"
}

argEnd()
{
	case "$PLATFORM" in
		mac) program="$P/Docker.app";;
		win) program="$P/Docker";;
	esac
}

#
# commands
#

isActiveCommand() { isActive; }
isInstalledCommand() { isInstalled; }

versionCommand()
{
	! AppInstallCheck && return

	case "$PLATFORM" in
		mac) defaults read "$P/Docker.app/Contents/Info.plist" "CFBundleShortVersionString";;
		win) registry get "HKLM/Software/Microsoft/Windows/CurrentVersion/Uninstall/Docker Desktop/DisplayVersion";;
	esac
}

#
# IsHealthy Command
#

isHealthyUsage() { echot "\
Usage: $(ScriptName) IsHealthy NAME
Check the health status of container NAME.  Returns healthy (return code 0) or unhealthy (return code 1)."; }

isHealthyArgStart() { unset name; }
isHealthyArgs() { ScriptArgGet "name" -- "$@"; shift; }

isHealthyCommand()
{
	local status; status="$(docker inspect --format='{{.State.Health.Status}}' "$name")" || return
	echo "$name is $status"
	[[ "$status" == "healthy" ]] && return 0 || return 2
}

#
# helper
#

isActive() { isInstalled && docker node inspect pi1 |& grep '"Availability": "active"' >& /dev/null; }
isInstalled() { [[ -d "$program" ]]; }

ScriptRun "$@"
