#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [COMMAND]...
Manage the Domotz controller.

	api				perform an API command
	devices		list all devices"
}

init() { defaultCommand="api"; }
argStart() { unset -v apiInitialized; }

#
# API Command
#

apiUsage()
{
	echot "Usage: $(ScriptName) api [URI](/device)
Perform an API command.

Examples:
	/device - all devices"
}

apiArgStart() { uri="device"; }

apiArgs()
{
	(( $# > 0 )) && { ScriptArgGet "uri" -- "$@"; shift; }
	return 0
}

apiCommand() { api "$uri"; } 

#
# Commands
#

devicesCommand() { api "device"; }

backupCommand()
{
	local dest="$1" result; [[ ! $dest ]] && { dest="$(AppGetBackupDir)/domotz.devices.json" || return; }

	hilight "Backing up Domotz configuration..."

	# initialize
	apiInit || return
	[[ -f "$dest" ]] && { bak --move "$dest" || return; }

	# backup
	printf "backup..."
	devicesCommand > "$dest"
  echo "done"

  echo "Domotz backup of agent $agent devices completed to $(FileToDesc "$dest")"
}

#
# API Helper
#

api()
{
	local uri="$(echo "$1" | RemoveFront "/")"
	apiInit || return
	curl -s -X GET "$url/agent/$agent/$uri" -H "Accept: application/json" -H "X-Api-Key: $key"
}

apiInit()
{
	[[ $apiInitialized ]] && return

  key="$(credential get --fallback domotz key)" || return
  agent="$(credential get --fallback domotz agent)" || return
  url="$(credential get --fallback domotz url | RemoveTrailingSlash)" || return

	! [[ $key && $agent && $url ]] &&
		{ EchoErr "$(ScriptName): Domotz configuration is missing from the credential store"; return 1; }

  apiInitialized="true"
}

ScriptRun "$@"
