#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [COMMAND]...
Manage the Domotz controller.

	api				perform an API command
	devices		list all devices
	down			list important devices that are down
	important	list important devices"
}

argStart() { unset -v apiInitialized; }

#
# commands
#

devicesCommand() { api "device"; }
downCommand() { api "device" | jq '.[] | select(.importance == "VITAL" and .status == "DOWN" and .protocol == "IP") | { a: .display_name, b: .hw_address } | join(",")' | RemoveQuotes; }
importantCommand() { api "device" | jq '.[] | select(.importance == "VITAL" and .protocol == "IP") | .hw_address' | RemoveQuotes; }

backupCommand()
{
	hilight "Backing up Domotz configuration..."

	# mount backup directory
	local dest; [[ ! $dest ]] && { dest="$(AppGetBackupDir)/domotz.devices.json" || return; }

	# initialize
	apiInit || return
	[[ -f "$dest" ]] && { bak --move "$dest" || return; }

	# backup
	printf "backup..."
	devicesCommand > "$dest"
  echo "done"

  echo "Domotz backup of agent $agent devices completed to $(FileToDesc "$dest")"
}

#
# API Command
#

apiUsage()
{
	echot "Usage: $(ScriptName) api [available|put] [URI](/device) [JSON]({})
Perform an API command.

Examples:
	/device - all devices"
}

apiArgStart() { uri="device" json="{}"; }

apiArgs()
{
	(( ! $# )) && return; ScriptArgGet "uri" -- "$@" || return
	(( ! $# )) && return; ScriptArgGet "json" -- "$@"
}

apiCommand() { api "$uri"; } 
apiavailableCommand() { apiInit; }
apiPutCommand() { apiPut "$uri" "$json"; }

#
# API Helper
#

api()
{
	local uri="$1"
	apiInit || return
	RunLog curl -s -X GET "$url/agent/$agent/$(echo "$1" | RemoveFront "/")" -H "Accept: application/json" -H "X-Api-Key: $key"
}

apiInit()
{
	[[ $apiInitialized ]] && return

  key="$(credential get --fallback domotz key)" || return
  agent="$(credential get --fallback domotz agent)" || return
  url="$(credential get --fallback domotz url | RemoveTrailingSlash)" || return

	! [[ $key && $agent && $url ]] &&
		{ EchoErr "$(ScriptName): Domotz configuration is missing from the credential store"; return 1; }

  apiInitialized="true"
}

apiPut()
{
	local uri="$1" json="$2"
	apiInit || return
	RunLog curl -X PUT --silent --data "$json" "$url/agent/$agent/$(echo "$1" | RemoveFront "/")" -H "Accept: application/json" -H "X-Api-Key: $key"
}

ScriptRun "$@"
