#!/usr/bin/env bash
. app.sh

init()
{ 
	unset var
	command="start"
	title="DropboxTrayIcon"
	program="$APPDATA/Dropbox/bin/Dropbox.exe"
}

usage() {	echot "usage: templateApp [start|startup|close|restart](start)"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			--brief|-b) ;;
			--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup|profile|service) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program" 2; }
restartCommand() { closeCommand && startCommand; }

MoveConfig()
{
	EchoErr "DropBox MoveConfig is not implemented"
	return 1
# if %# != 2 goto usage

# set src=%@UnQuote[%1]
# set dest=%@UnQuote[%2]

# # Return if the configuration is already linked to DropBox
# if %@IsLink["%src"] == 1 return 0

# call ask `Do you want to move application configuration data to the cloud?` y
# if %? == 0 return 1

# # If there is no configuration data on  DropBox move the local configuration data to DropBox
# iff IsDir "%src" .and. not IsDir "%dest" then
# 	call MergeDir /rename "%src" "%dest"
# endiff

# # If both the local and dropbox configuration data exist prompt to #ove the local data
# iff IsDir "%src" .and. IsDir "%dest" then

# 	call ask `Do you want to #ove the existing local (non-cloud) configuration? ` y
# 	if %? == 0 return 1
	
# 	call DelDir "%src"
# 	if %? != 0 return %?
	
# endiff

# # Create the DropBox configuration directory if needed
# iff not IsDir "%dest" then
# 	MakeDir "%dest"
# 	if %? != 0 return %?
# endiff

# # Link the DropBox configuration directory to the local directory
# call MakeLink junction "%dest" "%src"

}

run "$@"