#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... IsInstalled|IsMounted|mount|program|unmount|validate|version
Mount or unmount an encrypted file system.   Currenltly only CryFS is supported."
}

init()
{
	defaultCommand="start"
	mountDirRoot="$(drive dir user)"
	program="cryfs"
}

#
# Commands
#

isInstalledCommand() { InPath "$program"; }
programCommand() { echo "$program"; }
validateCommand() { validateProgram; }
versionCommand() { validateProgram && AppVersion "$program"; }

#
# IsMounted Command
#

isMountedUsage() { echo "Usage: $(ScriptName) IsMounted DIR\nReturn true if the specified encrypted directory is mounted."; }
isMountedArgStart() { unset dir; }
isMountedArgs() { ScriptArgGet --required "dir" -- "$@" && ScriptCheckDir "$dir"; }
isMountedCommand() { [[ -d "$mountDirRoot/$(GetLastDir "$dir")" ]]; }

# Mount Command
#

mountUsage() { ScriptUsageEcho "\
Usage: $(ScriptName) mount DIR
Mount the specified directory.

	-np, --no-password PASSWORD		do not get the password from the credential store
	-p,  --password PASSWORD			password for the file
	-v,  --validate								validate the cloud files are downloaded"
}

mountArgStart() { unset dir noPassword password validate; }

mountOpt() 
{
	case "$1" in
		-np|--no-password) noPassword="true";;
		-p|--password|-p=*|--password=*) ScriptOptGet password "$@" || return;;
		-v|--validate) validate="--validate";;
		*) return 1
	esac
}

mountArgs() { ScriptArgGet --required "dir" -- "$@" && ScriptCheckDir "$dir"; }

mountCommand() { validateProgram && mount "$dir"; }

mount()
{
	local dir="$1" baseDir="$1" mountDir="$mountDirRoot/$(GetLastDir "$1")"
	local result; mountWorker; result="$?"
	(( $result != 0 )) && { rmdir "$mountDir"; return "$result"; }
	echo "$mountDir"
}

mountWorker()
{
	# check if the directory is already mounted
	[[ -d "$mountDir" ]] && (( $(DirCount "$mountDir") > 0 )) && return
	[[ ! -d "$mountDir" ]] && { ${G}mkdir "$mountDir" || return; }

	# ensure baseDir is available offline
	if IsPlatform win && IsCloudFile "$baseDir"; then
		CloudOffline "$baseDir" || return
	fi

	# ensure all of the encrypted files are downloaded
	if [[ $validate ]]; then
		local check="encrypt-$(GetFileName "$mountDir")"
		if UpdateNeeded "$check"; then
			EchoErr "Downloading encrypted files..."
			RunLog CloudGet "$baseDir" "${globalArgs[@]}" 1>&2 || return
			UpdateDone "$check" || return
		fi
	fi

	# get the password
	[[ ! $password && ! $noPassword ]] && credential exists secure strong --fallback && { password="$(credential get secure strong --fallback)" || return; }
	[[ $noPrompt && ! $password ]] && { ScriptErr "unable to get the password for the encrypted volume"; return; }

	# log mount
	[[ ! $quiet ]] && EchoErr "Mounting encrypted directory '$(FileToDesc "$baseDir")' to '$(FileToDesc "$mountDir")'..."

	# mount without a password
	[[ ! $password ]] && { RunLog cryfs "$baseDir" "$mountDir"; return; }
	
	# mount using supplied password
	local script="$(cat <<-EOF
		spawn cryfs "$baseDir" "$mountDir"
		expect "Password: "
		send "$password\r";
		expect eof
		EOF
	)"

	export CRYFS_FRONTEND="noninteractive" CRYFS_NO_UPDATE_CHECK="true"
	log1 "$script"
	local result="$(expect -c "$script")" || return
	log1 "$result"

	echo "$result" | grep --quiet "Mounting filesystem." || { ScriptErr "unable to mount encrypted directory '$(FileToDesc "$baseDir")'"; return 1; }
	return 0
}

#
# Unmount Command
#

unmountUsage() {
EchoWrap "\
Usage: $(ScriptName) unmount DIR
Unmount the specified directory.  Only the last part of the directory is used and is assumed to be mounted in '$(drive dir root)', which means it can be the mount point or the base directory that was mounted."
}

unmountArgStart() { unset dir; }
unmountArgs() { ScriptArgGet "dir" -- "$@"; }

unmountCommand() { validateProgram && unmount "$dir"; }

unmount()
{
	local dir="$1" mountDir="$mountDirRoot/$(GetLastDir "$1")"
	local args=(); [[ $force ]] && args+=(--immediate)

	# cleanup and return if not mounted
	rmdir "$mountDir" >& "/dev/null"
	[[ ! -d "$mountDir" ]] && return

	# unmount
	[[ ! $quiet ]] && echo "Unmounting encrypted volume '$(FileToDesc "$mountDir")'..."
	RunLog cryfs-unmount "$mountDir" "${args[@]}" && rmdir "$mountDir"
}

#
# helper
#

validateProgram() { isInstalledCommand && return; ScriptErr "'$(GetFileName "$program")' is not installed"; }

ScriptRun "$@"
