#!/bin/bash
. app.sh

init()
{
	command="start";
	title=".* - Evernote"; 
	program="$P32/Evernote/Evernote/Evernote.exe"; 
	TrayProgram="$P32/Evernote/Evernote/EvernoteTray.exe"
	ClipperProgram="$P32/Evernote/Evernote/EvernoteClipper.exe"
}

usage() {	echot "usage: evernote [start|startup|close|restart](start)"; 	exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*) 
				if [[ "$1" == @(start|startup) ]]; then { command="${1,,}"; shift; break; }
				elif IsFunction "${1,,}Command"; then command="${1,,}"
				else { echoerr "Unknown argument $1"; usage 1; }
				fi;;
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

closeCommand() 
{
	IsRunningCommand && { ProcessClose "$program" || return; }
	IsTaskRunning "$TrayProgram" && { ProcessClose "$TrayProgram" || return; }
	IsTaskRunning "$ClipperProgram" && { ProcessClose "$ClipperProgram" || return; }
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
startupCommand() { startCommand; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"