#!/bin/bash
. function.sh || exit

usage()
{
	echot "\
usage: FileInfo FILES
	Display information about the specified file"
	exit $1
}

args()
{
	unset -v file
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			*)
				! IsOption "$1" && { files+=( "$1" ); shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	[[ ! $files ]] && MissingOperand "file"							# missing argument
	args=("$@")
}

init()
{
	mediaExtensions=( avi 3g2 3gp jpg kpg m2ts m4a m4p m4v mp3 mp4 mpe mpg modd moff mov mts ram rm rmvb wma wmv )
	mediaMetadata="-ImportedFileName -ImportedFileSizeBytes -ImportedFileModificationTime -ImportedOnHost -ImportedByUser -ImportedDate -ImportedFromFolder -ImportedToFolder"
}

run() 
{
	args "$@" || return
	init || return
	for file in "${files[@]}"; do FileInfo "$file" || return; done
}

FileInfo()
{
	local ext file="$1"

	[[ ! -f "$file" ]] && { EchoErr "FileInfo: cannot access \`$file\`: No such file"; return 1; }
	ShowHeader "$file"
	file "$file" || return
	GetFileExtension "$file" ext

	IsInArray "$ext" mediaExtensions && { MediaInfo || return; }
	return 0
}

ShowHeader()
{
	printf "**************************************************\n* $1\n**************************************************\n"
}

MediaInfo()
{
	ShowHeader "Media"
	MediaInfo.exe "$file" || return
	
	[[ "$ext" != @(mp3) ]] && { MediaMetadata || return; }
}

MediaMetadata()
{
	exiftool "$(utw "$file")" $mediaMetadata
}

run "$@"
