#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [cli|close|IsInstalled|IsRunning|profile|program|restart|start|startup|stop|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="files-preview.exe"; ! InPath "$program" && program="files-stable.exe"
	programRunning="Files.exe"
	profileName="files"
	profileMask="*"
}

cliArgs() { cliArgs=( "$@" ); shift="$#"; }
cliCommand() { AppInstallCheck && "$program" "${cliArgs[@]}" "${otherArgs[@]}"; }
closeCommand() { ! isRunningCommand && return 0; ProcessClose "$programRunning"; } 
isInstalledCommand() { InPath "$program"; }
isRunningCommand() { IsProcessRunning "$programRunning"; }
profileUsage() { ScriptUsageEcho "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgStart() { AppInstallCheck && profileDir="$(FindDir "$UADATA/Packages" 'Files_*' 1)/LocalState/settings"; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start "$program" "${startArgs[@]}" "${otherArgs[@]}"; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; AppInstallCheck && start "$program"; }
stopCommand() { closeCommand; } 
versionCommand() { AppInstallCheck && AppVersion "$program"; }
									 
ScriptRun "$@"
