#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: FindInstallFile FILE
	Find an installation file or directory
	-e, --eval				return variables to evaluate
  -h, --hint DIR 		first directory to search
  -q, --quiet				do not display status messages
  -s, --suppress		suppress the error messages
  	  --help 				display this help and exit"
	exit $1
}

init() 
{ 
	localDirs=( "$PUB/Documents/data/install" "/cygdrive/e/data/install" )
}

args()
{
	unset eval file hint quiet suppress
	while [ "$1" != "" ]; do
		case "$1" in
			-e|--eval) eval="true";;
			--hint) hint="$2"; shift;;
			--quiet) quiet="true";;
			--suppress) suppress="true";;
			--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				! IsOption "$1" && [[ ! $file ]] && { file="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	args=("$@")
}

run() 
{	
	init; args "$@"; find || return
	
	[[ ! $eval ]] && 
		echo "$file" ||
		ScriptReturn InstallDir file

}

find()
{
	[[ $hint ]] && checkDir --quiet "$hint" && return

	checkDir --quiet "$hint" ${localDirs[@]} && return

	[[ ! $quiet ]] && PrintErr "checking..." 

	case "$USERNAME" in
		jjbutare|ad_jjbutare)
			checkHost oversoul.hagerman.butare.net "//oversoul/public/Documents/data/install" && return
			checkHost nas.hagerman.butare.net "//nas/public/Documents/data/install" && return
			checkHost jjbutare-mobl.amr.corp.intel.com "//jjbutare-mobl/portable/data/install" && return;;
	esac
	
	checkHost CsisBuild.intel.com "//CsisBuild.intel.com/install" && return
	
	[[ ! $quiet ]] && EchoErr "not found"
	[[ ! $suppress ]] && EchoErr "FindInstallFile: Could not locate ${file:-the installation directory}"
	return 1
}

checkHost()
{
	local host="$1" dir="$2"
	[[ ! $quiet ]] && PrintErr "${host%%\.*}..." 
	host available "$host" && checkDir "$dir"
}

checkDir()
{
	local localQuiet; [[ "$1" == "--quiet" ]] && { localQuiet="true"; shift; }

	for dir in "$@"; do
		if [[ $dir && -e "$dir/$file" ]]; then
			[[ ! $quiet && ! $localQuiet ]] && EchoErr "found"
			InstallDir="$dir"
			file="$dir/$file"
			return 0
		fi
	done
	return 1
}

run "$@"
