#!/usr/bin/env bash
. function.sh || return

usage()
{
	echot "\
usage: FindInstallFile FILE
	Find an installation file or directory from known locations.  Searches 
	INSTALL_DIR if defined.  
	-e, --eval				return variables to evaluate (InstallDir and file)
	-h, --hint DIR 		first directory to search
	-q, --quiet				do not display status messages
	-s, --select			select the install location
			--suppress		suppress error messages
			--help 				display this help and exit"
	exit $1
}

args()
{
	unset eval fileSuffix hint quiet select suppress
	while [ "$1" != "" ]; do
		case "$1" in
			--eval|-e) eval="true";;
			--hint|-h) hint="$2"; shift;;
			--quiet|-q) quiet="true";;
			--select|-s) select="true";;
			--suppress) suppress="true";;
			--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				! IsOption "$1" && [[ ! $fileSuffix ]] && { fileSuffix="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	args=("$@")
}

AddDirs()
{
	AddLocalDirs || return

	# Wiggin
	if IsAvailable nas3; then AddDir nas3 "//nas3/public/Documents/data/install"
	elif IsAvailable nas3.hagerman.butare.net; then AddDir nas3 "//nas3.hagerman.butare.net/public/Documents/data/install"
	elif IsAvailable nas1; then AddDir nas1 "//nas1/public/Documents/data/install"
	elif IsAvailable nas1.hagerman.butare.net; then AddDir nas1 "//nas1.hagerman.butare.net/public/Documents/data/install"
	fi

	return 0
}

AddLocalDirs()
{
	local disks; GetDisks disks

	for disk in "${disks[@]}"; do
		[[ -d "$disk/install" ]] && AddDir "local-$(GetFileName "$disk")" "$disk/install"
		[[ -d "$disk/Users/Public/install" ]] && AddDir "local-$(GetFileName "$disk")" "$disk/Users/Public/install"
		[[ -d "$disk/nas1/public/documents/data/install" ]] && AddDir "local-$(GetFileName "$disk")" "$disk/nas1/public/documents/data/install"
	done

	# VMware Host
	[[ -d "/mnt/hgfs/c/Users/Public/Documents/data" ]] && AddDir "vmware-host" "/mnt/hgfs/c/Users/Public/Documents/data"
	IsVmwareVm && [[ -d "//vmware-host/Shared Folders/d/users/public/install/" ]] && AddDir "host-drive-d" "//vmware-host/Shared Folders/d/users/public/install"

	# Parallels Host
	[[ -d "/media/psf/AllFiles" ]] && AddDir "parallels-host" "/media/psf/AllFiles"

	# Synology DSM NAS
	[[ -d "/volume1/public/documents/data/install" ]] && AddDir "dsm-host" "/volume1/public/documents/data/install"

	# QNAP NAS
	[[ -d "/share/Public/documents/data/install" ]] && AddDir "qnap-host" "/share/Public/documents/data/install"

	return 0
}

AddDir() { dirs["$1"]+="$2"; }

CheckDir()
{
	local dir="$1"

	IsUncPath "$dir" && { dir="$(unc mount "$dir")" || return; }

	if [[ -e "$dir/$fileSuffix" ]]; then
		InstallDir="$dir"
		file="$dir/$fileSuffix"
		return 0
	fi
	return 1
}

CheckServerAvailability()
{
	local pingTime

	[[ ! $quiet ]] && PrintErr "checking..." 

	for key in "${!dirs[@]}"; do
		local dir="${dirs["$key"]}" server
		unset dirs["$key"]
		GetUncServer "$dir" server; [[ ! $server || "$server" == "vmware-host" ]] && { AddDir "0-$key" "$dir"; continue; }
		pingResult="$(PingResponse "$server")" && { AddDir "$pingTime-$key" "$dir" || return; }
		[[ ! $quiet ]] && PrintErr "." 
	done
	[[ "${#dirs[@]}" == "0" ]] && return 0

	shopt -s lastpipe
	printf '%s\0' "${!dirs[@]}" | sort --numeric --zero-terminated | xargs -0n1 | readarray -t closestKeys

	return 0
}

FindClosest()
{
	local items

	[[ $hint ]] && { CheckDir "$hint" && return; }	
	[[ $INSTALL_DIR ]] && { CheckDir "$INSTALL_DIR" && return; }

	# check local dirs	
	for key in "${!dirs[@]}"; do
		local dir="${dirs["$key"]}" server
		GetUncServer "$dir" server; [[ $server ]] && continue
		CheckDir "$dir" && return
		unset dirs["$key"]
	done

	CheckServerAvailability || return
	
	for key in "${closestKeys[@]}"; do
		[[ ! $quiet ]] && PrintErr "${key#*-}..." 
		CheckDir "${dirs["$key"]}" && { [[ ! $quiet ]] && EchoErr "found"; return 0; }
	done

	[[ ! $quiet ]] && EchoErr "not found"
	[[ ! $suppress ]] && EchoErr "FindInstallFile: Could not locate ${fileSuffix:-the installation directory}"
	return 1
}

Select()
{
	[[ $hint ]] && AddDir "$hint" "$hint"

	CheckServerAvailability || return

	local items=( )
	for key in "${closestKeys[@]}"; do
		local dir="${dirs["$key"]}" desc="${key#*-}" ms="${key%%-*}ms away"
		items+=( "$desc" "$ms" )
		unset dirs["$key"]; AddDir "$desc" "$dir"
	done

	if (( ${#items[@]} == 0 )); then
		[[ ! $quiet ]] && EchoErr "not found"
		[[ ! $suppress ]] && EchoErr "FindInstallFile: Could not locate any installation servers"
		return 1
	fi

	while true; do
		local result=$(dialog --stdout --backtitle "Select Installation Location" \
	  	--menu "Choose the location to search for:\n$fileSuffix" $(($LINES-5)) 50 $(($LINES)) "${items[@]}")
		[[ "$result" == "" ]] && return 1
		[[ ! $quiet ]] && PrintErr "checking...$result ("${dirs[$result]}")..."
		CheckDir "${dirs[$result]}" && { [[ ! $quiet ]] && EchoErr "found"; return; }
		[[ ! $quiet ]] && EchoErr "not found"
		[[ ! $suppress ]] && EchoErr "FindInstallFile: ${fileSuffix:-the installation directory} is not located on $result"
		pause
	done

}

run() 
{	
	local -A dirs; local closestKeys
	args "$@" || return; 
	AddDirs || return

	[[ $select ]] && { Select || return; } || { FindClosest || return; }
	[[ $eval ]] && { ScriptReturn InstallDir file; true; } || { echo "$file"; true; }
}

run "$@"
