#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: FindPublicDoc FILE
	Find a public documents folder which contains the specified file
  -h,--host <host> 				name of the host to use
	-r,--reset							reset the location of the public documents
  -s,--select							select from a list of available hosts
  -S,--search <attribute>	search for a host with the specified attribute"
	exit $1
}

init() { :; }

args()
{
	unset dest exclude file show arg1 arg2
	while [ "$1" != "" ]; do
		case "$1" in
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				! IsOption "$1" && [[ ! $file ]] && { file="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	args=("$@")
}

run() 
{	
	init; args "$@"; 

	# TODO: convert rest of FindPublicDoc.btm, cache SharedDocuments to /tmp and use if present

	# "//jjbutare-mobl/e$"
	dirs=( "$PUB/Documents" "/cygdrive/e" "//oversoul/public/Documents" )
	
	for dir in "${dirs[@]}"; do
		[[ -e "$dir/$file" ]] && { echo "$dir/$file"; return 0; }
	done

	EchoErr "Could not find $file in any public document locations"
	return 1
}

run "$@"
