#!/usr/bin/env bash
. script.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... FILE
Find an installation file or directory from known locations.  
Searches INSTALL_DIR if defined.  

	-a, --all					return all found directories
	-e, --eval				return variables to evaluate (installDir and file)
	-f, --force				do not use cached installation directory
	-h, --hint DIR 		first directory to search
	-q, --quiet				do not display status messages
	-s, --select			select the install location
			--suppress		suppress error messages
	-v, --verbose			display detailed output"
}

init()
{
	declare -Ag dirs
	defaultCommand="closest"
	preferredServers=( ender rp1 rp2 ) # 10G/2.5G servers
}

argStart() { unset -v eval file hint suppress; }

opt()
{
	case "$1" in "") : ;;
		-a|--all) command="all";;
		-e|--eval) eval="true" quiet="--quiet";;
		-h|--hint) ScriptOptGet "hint" "$@";;
		-s|--select) command="select";;
		   --suppress) suppress="true";;
		*) return 1;;
	esac
}

args() { [[ $1 ]] && ScriptArgGet "file" -- "$@"; shift; true; }

#
# commands
#

allCommand()
{	
	quiet="--quiet"

	addDirs || return
	checkServerAvailability || return

	for key in "${closestKeys[@]}"; do
		echo "${dirs["$key"]}"
	done
}

closestCommand() { findClosest && returnData; }
selectCommand() { findSelect && returnData; }

#
# helper
#

printStatus() { [[ $quiet || $verbose ]] && return; PrintErr "$1"; }
returnData() { [[ $eval ]] && ScriptReturn installDir file || printf "$file"; }
status() { [[ $quiet ]] && return; EchoErrEnd "$1"; }

addDirs()
{
	[[ $hint ]] && { addLocalDir "$hint" "$hint" && return; }

	# add local directories
	addLocalDirs && return

	# domain
	RunFunction addDirs "$(GetDomain)" && return

	# internet
	# addDirHost "ln1.butare.net" "root/usr/local/data/install" "ssh" && return
	addDirHost "ssh.butare.net" "root/usr/local/data/install" "608" && return

	return 0
}

addDirsHagerman()
{
	addDirHost "ender.hagerman.butare.net" "public/install" && return
	addDirHost "rp1.butare.net" "public/install" && return
	addDirHost "rp2.butare.net" "public/install" && return
	return 1
}

addDirsSandia()
{
	addDirHost "s1091967" "install" && return # rack
	addDirHost "s1071466" "install" && return # desktop
}

# addDirHost HOST SUFFIX PROTCOL - if HOST is available using PROTOCOL (nfs|smb|ssh) add directory //HOST/SUFFIX.
# - return 1 to continue searching and 0 to stop searching.
addDirHost()
{
	local host="$1" suffix="$2" protocol="${3:-smb}"

	# return if host is not available using the specified protocol
	log1 "checking '//$host:$protocol/$suffix'..."
	unc IsAvailable "$host" --protocol="$protocol" $verboseLess || return

	# get a host description if needed
	local desc
	if [[ "$protocol" == "22" ]]; then desc=" (ssh)"
	elif IsInteger "$protocol"; then desc=" (ssh $protocol)"
	elif [[ $protocol ]]; then desc=" (${protocol,,})"
	fi
	
	# add the UNC direcory
	addLocalDir "$(RemoveDnsSuffix "$host")$desc" "//$host/$suffix:$protocol" 
}

addLocalDir()
{
	local name="$1" dir="$2"

	# directory does not exist
	[[ ! -d "$dir" ]] && return 1

	# add directory
	log1 "adding '$name' ($dir)..."
	dirs["$name"]="$dir"

	# return 1 (keep checking) if we are selecting from all available locations
	[[ "$command" != "select" ]]
}

addLocalDirs()
{
	local p="public/install"

	# local drive
	addLocalDir "local" "$DATA/install" && return

	# cloud provider
	CloudConf --quiet && addLocalDir "cloud" "$CLOUD/install" && pause return

	# domain
	RunFunction addLocalDirs "$(GetDomain)" && return

	# mounted drives
	if drive mount all $quiet; then
		local desc drive drives; IFS=$'\n' ArrayMake drives "$(drive mounts)"
		for drive in "${drives[@]}"; do
			if [[ -d "$drive/$p" ]]; then
				drive IsDrive "$drive" && desc="drive-$(drive label "$drive")" || desc="drive-$(GetFileName "$drive")"
				addLocalDir "$desc" "$drive/$p" && return
			fi
		done
	fi

	# VMware Host
	IsVmwareVm && addLocalDir "host-drive-d" "//vmware-host/Shared Folders/d/users/public/install" && return

	return 1
}

addLocalDirsSandia()
{
	# use OneDrive if it is not configured properly
	local dir="$WIN_HOME/OneDrive - Sandia National Laboratories/install"
	[[ -d ~/OneDrive || ! -d "$dir" ]] && return 1
	addLocalDir "cloud-temp" "$dir"
}

checkDir()
{
	local dir="$1"

	log1 "checking $(FileToDesc "$dir")..."
	IsUncPath "$dir" && { dir="$(unc mount "$dir" --no-host-check $verbose)" || return; }

	log1 "checking $(FileToDesc "$dir")/$file..."
	if [[ -e "$dir/$file" ]]; then
		log1 "found in $(FileToDesc "$dir")..."
		installDir="$dir"
		file="$dir/$file"
		return 0
	fi
	return 1
}

checkServerAvailability()
{
	printStatus "checking..." 

	for key in "${!dirs[@]}"; do
		local dir="${dirs["$key"]}" server protocol
		unset dirs["$key"]

		log1 "Checking $dir...."
		GetUncServer "$dir" server
		[[ ! $server || "$server" == "vmware-host" ]] && { addLocalDir "0-$key" "$dir"; continue; }

		local protocol; GetUncProtocol "$dir" protocol
		local port; port="$(unc get port --protocol="$protocol")" || return
		local responseTime="$(PortResponse "$server" "$port")" && { addLocalDir "$responseTime-$key" "$dir" || return; }
		printStatus "." 
	done

	[[ "${#dirs[@]}" == "0" ]] && return 0

	shopt -s lastpipe

	# sort the array by response time
	printf '%s\0' "${!dirs[@]}" | sort --numeric --zero-terminated | ${G}xargs -0n1 | readarray -t closestKeys

	return 0
}

findClosest()
{
	local dir key server

	[[ $hint ]] && { checkDir "$hint" && return; }	
	[[ ! $force && $INSTALL_DIR ]] && { checkDir "$INSTALL_DIR" && return; }

	addDirs || return

	# check local dirs	
	for key in "${!dirs[@]}"; do
		dir="${dirs["$key"]}"
		GetUncServer "$dir" server; [[ $server ]] && continue		
		checkDir "$dir" && return
		unset dirs["$key"]
	done

	# get available servers
	checkServerAvailability || return
	
	# if no servers are available update the current network and try again
	if [[ ! $closestKeys ]]; then
		log1 "updating current network"
		network current update --quiet || return
		log1 "network set to '$(NetworkCurrent)'"
		addDirs || return
		checkServerAvailability || return
	fi

	# check preferred servers
	for key in "${closestKeys[@]}"; do
		server="${key#*-}"
		if IsInArray "$server" preferredServers; then
			printStatus "$server..." 
			checkDir "${dirs["$key"]}" && { status "found"; return 0; }
		fi
	done

	# check closet servers
	for key in "${closestKeys[@]}"; do
		printStatus "${key#*-}..." 
		checkDir "${dirs["$key"]}" && { status "found"; return 0; }
	done

	status "not found"
	[[ ! $suppress ]] && EchoErr "FindInstallFile: Could not locate ${file:-the installation directory}"
	return 1
}

findSelect()
{
	addDirs || return
	checkServerAvailability || return

	local items=( )
	for key in "${closestKeys[@]}"; do
		local dir="${dirs["$key"]}" desc="${key#*-}" ms="${key%%-*}ms away"
		items+=( "$desc" "$ms" )
		unset dirs["$key"]; addLocalDir "$desc" "$dir"
	done

	if (( ${#items[@]} == 0 )); then
		status "not found"
		[[ ! $suppress ]] && EchoErr "FindInstallFile: could not locate any installation servers"
		return 1
	fi

	while true; do
		local result=$(dialog --stdout --backtitle "Select Installation Location" \
	  	--menu "Choose the location to search for:\n$file" $(($LINES-5)) 50 $(($LINES)) "${items[@]}")
		[[ "$result" == "" ]] && return 1
		[[ ! $quiet ]] && clear
		printStatus "checking...$result ("$(FileToDesc "${dirs[$result]}")")..."; log1
		checkDir "${dirs[$result]}" && { status "found"; return; }

		status "not found"		
		if [[ ! $suppress ]]; then			
			EchoErr "FindInstallFile: ${file:-the installation directory} is not located on $result"
			[[ ! $quiet ]] && pause
		fi
	done
}

ScriptRun "$@"
