#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script mozilla  PlatformVars || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [bookmarks|close|config|extension|IsInstalled|IsRunning|profile|program|restart|start|startup|vars|version](start)
$(ScriptName) commands."
}

init() { defaultCommand="start"; }
argStart() { unset -v dev; }

opt()
{
	case "$1" in
		--dev|-d) dev="--dev";;
		*) return 1;;
	esac
}

argEnd()
{
	defaultCommand="start"
	unset program configDir profileDir

	# platform configuration
	case "$PLATFORM_OS" in
		linux) 
			program="$P/firefox/firefox"			
			if [[ ! -f "$program" ]]; then program="/usr/bin/firefox"
			elif [[ ! -f "$program" ]]; then program="/usr/lib/firefox/firefox"
			elif [[ ! -f "$program" ]]; then program="/usr/lib/firefox-esr/firefox-esr"
			elif [[ ! -f "$program" ]]; then program="/snap/firefox/current/firefox"
			fi
			;;
		mac)
			local suffix; [[ $dev ]] && suffix=" Developer Edition"
			program="$P/Firefox$suffix.app"
			configDir="$HOME/Library/Application Support/Firefox"
			extensionDir="$(GetFullPath "$configDir/../Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}")"
			;;
		win)
			program="$P/Mozilla Firefox/firefox.exe"
			[[ ! -f "$program" ]] && program="$WIN_HOME/PortableApps/FirefoxPortable/App/Firefox64/firefox.exe"
			configDir="$(GetFullPath "$UADATA/../Roaming/Mozilla/Firefox")"
			extensionDir="$(GetFullPath "$configDir/../Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}")"
			;;
	esac

	# other
	profileDirInit || return
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() {  IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
varsUsage() { echot "Usage: $(ScriptName) vars\nReturn Firefox configuration variables: program configDir profileDir"; }
varsCommand() { ScriptReturn "program" "configDir" "profileDir"; }

versionCommand()
{
	AppInstallCheck || return
	if IsPlatform win; then "$program" -v | cut -d" " -f3 | RemoveCarriageReturn | ${G}sed 's/esr//'
	else AppVersion "$program" | ${G}sed 's/esr//'
	fi
}

#
# bookmarks commands
#

bookmarksUsage() { echot "Usage: $(ScriptName) bookmarks [json|markdown](json)"; }
bookmarksArgEnd() { AppInstallCheck; }
bookmarksCommand() { bookmarksJsonCommand; }
bookmarksJsonUsage() { echot "Usage: $(ScriptName) bookmarks json\nReturn the latest bookmark backup as JSON."; }

bookmarksJsonCommand()
{
	local dir="$profileDir/bookmarkbackups"	
	local file; file="$dir/$(command ls -Art "$dir" | ${G}tail --lines=1)"
	lz4jsoncat "$file"
}

bookmarksMarkdownCommand()
{
	bookmarksJsonCommand | jq -r '
  def bookmark($iconuri; $title; $uri):
     if $iconuri != null then "![\($iconuri)]" else "" end +
     "[\($title)](\($uri))";

  def bookmarks:
    (objects | to_entries[]
     | if .value | type == "array" then (.value | bookmarks)
                                   else .value end ) //
    (arrays[] | [bookmarks] | " - \(.[0])", "  \(.[1:][])" );

  (.. | .children? | arrays)
    |= map(if .uri != null then {bookmark: bookmark(.iconuri; .title; .uri)}
                           else {title} end +
           {children})
  | del(..| select(length == 0))     # remove empty children and empty titles
  | del(..| select(length == 0))     # remove objects that got empty because of previous deletion
  | del(..| objects | select(has("title") and (.children | length == 0)))   # remove objects with title but no children
  | .children                        # remove root level
  | bookmarks'
}

#
# config command
#

configUsage() { echot "Usage: $(ScriptName) profile config get|set VAR VALUE\nConfiguration commands, i.e. network.proxy.type"; }
configCommand() { usage; }

configGetArgStart() { unset -v var value; }
configGetArgs() { ScriptArgGet "variable" -- "$@"; }
configGetCommand() { configGet "$variable"; }

# configGet VAR - get VAR's value from Firefox configuration (prefs.js)
# format: user_pref("VAR", VALUE);
configGet()
{	
	local var="$1" file="$profileFile"; profileDirValidate || return

	local prefix='user_pref("'$var'", '
	log2 "Getting '$var' from '$file'"
	! qgrep "^${prefix}" "$file" && return
	${G}grep "^${prefix}" "$file" | ${G}sed 's/^.*,//' | RemoveSpaceFront | ${G}sed 's/).*//'
}

configSetArgStart() { unset -v var value; }
configSetArgs() { ScriptArgGet "variable" -- "$@" && shift && ScriptArgGet "value" -- "$@"; }
configSetCommand() { profileDirValidate && ensureClosed && configSet "$variable" "$value"; }

# configSet VAR VALUE - set VAR to VALUE in Firefox configuration (prefs.js)
# format: user_pref("VAR", VALUE);
configSet()
{	
	local var="$1" value="$2" file="$profileFile"; profileDirValidate || return
	local prefix='user_pref("'$var'", '
	local value="$prefix$value);"

	qgrep "^${value}$" "$file" && return
	
	log2 "Setting '$var' to '$value' in '$file' ($value)"

	if qgrep "^${prefix}" "$file"; then
		${G}sed -i "s/^${prefix}.*$/$value/" "$file"
	else
		echo "$value" >> "$file"
	fi
}

#
# profile command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|edit|restore|save"; }
profileArgStart() { profileAllInit; }
profileArgEnd() { AppInstallCheck; }
profileArgs() { [[ "${commandNames[2]}" != @(bounjourr|config|stg) ]] && return; profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { usage; }

profileDirUsage() { echot "Usage: $(ScriptName) profile dir [create|exists|show](show)\nProfile directory commands"; }
profileDirCommand() { profileDirShowCommand; }
profileDirCreateUsage() { echot "Usage: $(ScriptName) profile dir create\nCreate the profile directory, which might start Firefox"; }
profileDirCreateCommand() { profileDirCreate; }
profileDirExistsCommand() { [[ -d "$profileDir" ]]; }
profileDirShowCommand() { echo "$profileDir"; }

profileEditCommand() { TextEdit "$profileFile"; }

profileRestoreUsageCommand() { echot "Usage: $(ScriptName) profile restore [all|bonjourr|config|extensions|stg](all) [<profile>|default](default)\n$(ScriptName) configuration."; }
profileRestoreCommand() { profileRestoreAllCommand; }
profileRestoreExtensionsCommand() { profileExtensionsDo "firefox" "other/Mozilla/Firefox/extensions"; }

profileRestoreAllCommand() { profileAllDo "restore"; }
profileSaveAllCommand() { profileAllDo "save"; }
profileAllDo() { local what; for what in "${all[@]}"; do RunFunction "profile${1^}${what^}Command"; done; }
profileAllInit() { all=( "config" ); IsDomainRestricted && all+=( "extensions" "bonjourr" ); return 0; } # Firefox Sync is used for non-restricted domains

profileSaveUsageCommand() { echot "Usage: $(ScriptName) profile save [all|bonjourr|stg](all) [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileSaveCommand() { profileSaveAllCommand; }

profileRestoreBounjourrCommand() { hilight "Bounjourr..."; echo "- New tab, gear, Settings Management, Import, Import as file, click Drop file to import settings"; profileBounjourrDo; }
profileSaveBounjourrCommand() { hilight "Bounjourr..."; echo "- New tab, gear, Settings Management, Export, Export as file"; profileBounjourrDo; }
profileBounjourrDo() { profile $noPrompt --app "Firefox Bounjourr" --method "firefox" --save-extension "json" --editor "${profileArgs[@]}" "${globalArgs[@]}"; }

profileRestoreStgCommand() { hilight "Simple Tab Groups..."; echo "- Simple Tab Groups, gear, Backup, Restore backup"; profileStgDo; }
profileSaveStgCommand() { hilight "Simple Tab Groups..."; echo "- Simple Tab Groups, gear, Backup, check Include tab fav-icons in backup, Create backup"; profileStgDo; }

profileStgDo()
{
	profile --app "Firefox SimpleTabGroups" --method firefox --save-extension json restore; return
	echo profile $noPrompt --app "Firefox SimpleTabGroups" --method "firefox" --save-extension "json" "${commandNames[1]}" "${profileArgs[@]}" "${globalArgs[@]}"
}

profileRestoreConfigCommand()
{
	hilight "Configuration..."

	# create profile directory if needed
	profileDirCreate || return

	# close Firefox so profile changes are not overwritten
	ensureClosed || return

	# configure
	configSet "browser.tabs.closeWindowWithLastTab" "false" || return
	configSet "signon.rememberSignons" "false" || return
	configSet "network.proxy.type" "4" || return # 0=none, 4=Auto-detect proxy settings for this network, 5=Use system proxy settings
}

profileDirInit()
{
	profileDir="$(profileDirGet)"
	profileFile="$profileDir/prefs.js"
	extensionDirProfile="$profileDir/extensions"
}

ScriptRun "$@"
