#!/usr/bin/env bash
. function.sh || exit

usage()
{
	echot "\
usage: firewall [console|disable|enable|enabled|log|panel|rule|status](console)
 Manipulate the Windows firewall
 	-h, --host HOST			the host to use
 	-s, --suppress			suppress errors if the firewall service is not running"
 	exit $1
}

ruleUsage() 
{ 
	echot "\
usage: firewall COMMAND NAME
	add NAME RULES 	add a rule
	enable|disable|delete|exist|status manipulate a rule"
	exit $1
}

args()
{
	unset command host suppress
	while (( $# != 0 )); do
		case "$1" in
			-h|--host) host="$2"; shift;;
			-s|--suppress) suppress="--suppress";;
			--help) help="--help";;
			*)
				[[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "$command" == @(rule) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="console"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage || usage 0; }
	args=("$@")
}

init() { :; }
run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
panelCommand() { start firewall.cpl; }
consoleCommand() { start wf.msc; }
enableCommand() { netsh.exe advfirewall set currentprofile state on; }
disableCommand() { netsh.exe advfirewall set currentprofile state off; }
statusCommand() { netsh.exe advfirewall show currentprofile; }
enabledCommand() { netsh.exe firewall show state | grep -i "Operational Mode" | grep Enable > /dev/null; }

logCommand()
{
	local p; [[ $host ]] && p="//$host/admin\$" || p="$WINDIR"
	local file="$p/system32/LogFiles/Firewall/pfirewall.log"
	[[ ! -f "$p" ]] && { EchoErr "firewall: cannot access \`$file\`: No such file"; return 1; }
	TextEdit "$file"
}

ServiceRunning() { [[ "$(service state MpsSvc)" == "RUNNING" ]]; }

ruleCommand()
{
	if ! ServiceRunning; then
		[[ $suppress ]] && return 0
		echo "firewall: service is not running"
		return 1
	fi

	local command; CheckSubCommand rule "$1"; shift
	local name="$1"; shift; [[ ! $name ]] && MissingOperand "name"; 
	[[ "$command" != "add" && $# != 0 ]] && UnknownOption "$1"
	Rule${command}Command "$@"
}

RuleAddCommand()  
{ 
	local command="add" new; RuleExistCommand && { command="set"; new="new"; }
	! IsElevated && { EchoErr "adding firewall rules requires elevation"; return 1; }
	printf "firewall: adding rule $name..."	
	netsh.exe advfirewall firewall $command rule name="$name" $new "$@"
}

RuleDeleteCommand() { ! RuleExistCommand && return; netsh advfirewall firewall delete rule name="$name"; }
RuleEnableCommand() { ! RuleExistCommand && return; netsh advfirewall firewall set rule name="$name" new enable=yes; }
RuleDisableCommand() { ! RuleExistCommand && return; netsh advfirewall firewall set rule name="$name" new enable=no; }
RuleExistCommand() { RuleStatusCommand > /dev/null;}
RuleStatusCommand() { netsh.exe advfirewall firewall show rule name="$name"; }

run "$@"
