#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|close|profile|program|IsInstalled](start)
Fork commands."
}

init()
{
	profileName="Fork$(ProperCase "$PLATFORM")"

	case "$PLATFORM" in
		mac) program="/usr/local/bin/fork" profileDir="$ADATA/Fork" profileMask="*";;
		win) program="$ADATA/Fork/Fork.exe" profileDir="$ADATA/Fork" profileMask="settings.json";;
	esac
		
	[[ ! -d "$profileDir" ]] && { mkdir --parents "$profileDir" || return; }

	return 0
}

closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }

#
# Profile Command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgStart() { profileArgs=(); }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }

#
# Start Command
#

startArgStart() { startArgs=(); }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); }
startCommand() { IsInstalledCommand && start "$program" "${startArgs[@]}"; }

ScriptRun "$@"
