#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init()
{
	profileName="Fork$(ProperCase "$PLATFORM")"

	if IsPlatform win; then
		program="$ADATA/Fork/Fork.exe"
		profileDir="$ADATA/Fork"
		profileMask="settings.json"

	elif IsPlatform mac; then
		program="/usr/local/bin/fork"
		profileDir="$ADATA/../Roaming/Fork"
		profileMask="*"

	else
		EchoErr "Fork is not supported on $(PlatformSummary)"
		return 1
	fi

	return 0
}

usage() {	echot "usage: fork
  profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset -v noPrompt 

	while (( $# != 0 )); do
		case "$1" in
			--help|-h) usage 0;;
			--no-prompt|-np) noPrompt="--no-prompt";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "$@" || usage 1; }
startCommand() { IsInstalledCommand && start "$program" "$@"; }

run "$@"
