#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() 
{
	dir="$HOME/.config/geany"
	[[ ! -d "$dir" ]] && { ${G}mkdir "$dir" || return; }
	return 0
}

usage() {	echot "usage: GeanyHelper
	profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset -v brief

	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

profileCommand() { profile --app "geany" --method "$dir" --files "*" "$@" || usage 1; }

run "$@"
