#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... [close|IsInstalled|program|start|startup|version](start)
Logitech G HUB commands."
}

init()
{
	defaultCommand="start"
	agent="$P/LGHUB/lghub_agent.exe"
	service="LGHUBUpdaterService"
	program="$P/LGHUB/lghub.exe"
}

isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && { "$program" "$@" >& /dev/null & } }
startupCommand() { startCommand "--background"; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

closeCommand()
{ 
	AppInstallCheck || return
	{
		ProcessKill "$(GetFileName "$agent")" >& /dev/null
		ProcessKill "$(GetFileName "$program")" >& /dev/null
		service running "$service" && service stop "$service" --quiet 
	} >& /dev/null
	return 0
}

ScriptRun "$@"
