#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... [close|IsInstalled|program|start|startup|version](start)
Logitech G HUB commands."
}

init()
{
	defaultCommand="start"
	agent="$P/LGHUB/lghub_agent.exe"
	program="$P/LGHUB/lghub.exe" programInstalled="$program" programVersion="$program"
	IsPlatform mac && program="lghub.app"	programInstalled="$P/lghub.app" programVersion="lghub"
	service="LGHUBUpdaterService"	
}

isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
startupCommand() { startCommand "--background"; }
versionCommand() { AppInstallCheck && AppVersion "$programVersion"; }

closeCommand()
{ 
	AppInstallCheck || return
	{
		ProcessKill "$(GetFileName "$agent")" >& /dev/null
		ProcessKill "$(GetFileName "$program")" >& /dev/null
		service running "$service" && service stop "$service" --quiet 
	} >& /dev/null
	return 0
}

startCommand()
{
	AppInstallCheck || return
	IsPlatform mac && { start "$programInstalled"; return; }
	"$program" "$@" >& /dev/null &
}

ScriptRun "$@"
