#!/usr/bin/env bash
. app.sh || exit

usage()
{
	ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... [close|IsInstalled|program|start|startup|version](start)
Logitech G HUB commands."
}

init()
{
	defaultCommand="start"
	program="$P/LGHUB/lghub.exe"
	agent="$P/LGHUB/lghub_agent.exe"
	service="LGHUBUpdaterService"
}

isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
startupCommand() { startCommand "--background"; }
versionCommand() { FileVersion "$program"; }

closeCommand()
{ 
	! isInstalledCommand && return
	{
		ProcessKill "$(GetFileName "$agent")" >& /dev/null
		ProcessKill "$(GetFileName "$program")" >& /dev/null
		service running "$service" && service stop "$service" --quiet 
	} >& /dev/null
	return 0
}

startCommand()
{
	isInstalledCommand && "$program" "$@" >& /dev/null &
}

ScriptRun "$@"
