#!/usr/bin/env bash

run()
{
	[[ $# != 3 ]] && { echo "usage: git revert-to <revert to> <new tag> <version info> 

Revert to the <revert to> commit.   The new branch is named <new version>.   The <version info> commit contains
the version information changes (SQL and Assembly Info) that need to be updated to the new version.  For example:

git revert v4.3.3.0 v4.3.4.2 22a74c954"; exit 1; }

	local revertTo=${1}
	local newTag=${2}
	local versionInfo=${3}

	git branch Release-$newTag $revertTo || exit 1
	git checkout Release-$newTag || exit 1
	git cherry-pick $versionInfo --no-commit --strategy=recursive --strategy-option=theirs || exit 1
	git status --porcelain=2 | cut -f9 -d" " | xargs edit
	pause "When done updating the versions TO $newTag, press any key to continue..."

	git commit --all -m "Reversion to $revertTo from $versionInfo" || exit 1
	git tag $newTag || exit 1
	git push origin $newTag || exit 1

	exit 0
}

pause() { local response; read -n 1 -s -p "${*-Press any key when ready...}"; echo; }

run "$@"