#!/usr/bin/env bash

[[ $# != 1 ]] && { echo "usage: git integrate <branch>"; exit 1; }

integrationBranch=$(git branch --list -r | egrep -i "origin/$1" | cut -d/ -f2 | sed 's/ //g')
[[ ! $integrationBranch ]] && { echo "Integration branch $1 does not exist on origin"; exit 1; }

currentBranch="$(git symbolic-ref -q HEAD | cut -d"/" -f 3)"
[[ ! $currentBranch ]] && { echo "Not on a branch"; exit 1; }

git fetch --all
git checkout "$integrationBranch" || exit 1
git reset "origin/$integrationBranch" || exit 1

echo -e "\nIntegrating $currentBranch to $integrationBranch..."
git merge --no-ff "$currentBranch" || exit 1

echo -e "\nUpdating origin..."
git push || exit 1

git checkout "$currentBranch" || exit 1