#!/usr/bin/env bash
#. app.sh || exit

[[ $# != 1 ]] && { echo "usage: git integrate <branch>"; exit 1; }

integrationBranch=$(git branch --list -r | grep -E "^[ ]*origin/I-$1$" | cut -d/ -f2 | sed 's/ //g')
[[ ! $integrationBranch ]] && { echo "Integration branch I-$1 does not exist on origin"; exit 1; }

currentBranch="$(git symbolic-ref -q HEAD | cut -d"/" -f 3)"
[[ ! $currentBranch ]] && { echo "Not on a branch"; exit 1; }

if [[ "$(git status --porcelain)" ]]; then
	echo "Current branch $currentBranch has changes that must be committed before integration"
	exit 1
fi

git fetch --all
git checkout "$integrationBranch" || exit 1
git reset --hard "origin/$integrationBranch" || exit 1

echo -e "\nIntegrating $currentBranch to $integrationBranch..."
git merge "$currentBranch" --no-edit || exit 1

echo -e "\nPushing $integrationBranch to origin..."
git push origin "$integrationBranch" || exit 1

echo
git checkout "$currentBranch" || exit 1