#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [build|close|create|kill|install|IsInstalled|IsRunning|profile|program|restart|start|startup|stop|web](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="gui"
	profileName="git-annex" profileDir="$HOME/.config/git-annex" profileMask="*"
	program="git-annex"
	programShell="git-annex-shell"
	programRunning="^${program}$"; IsPlatform mac && programRunning="git-annex"
	src="$CODE/git-annex"
}

stopCommand() { closeCommand; } 
closeCommand() { [[ $force ]] && ! isRunningCommand && return 0; git annex assistant --autostop > "$quietOutput"; } 
guiCommand() { start git annex webapp; }
isInstalledCommand() { InPath "$program" && [[ -f "$HOME/.config/git-annex/autostart" ]]; }
isRunningCommand() { [[ $verbose ]] && pgrep -l "$program" > "/dev/stderr"; IsProcessRunning "$programRunning"; }
killCommand() { pkill "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && git annex assistant --autostart "${startArgs[@]}" > "$quietOutput"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && "$program" version | head -1 | cut -d":" -f 2 | RemoveSpace; }

#
# build command
#

buildCommand()
{
	GitHelper clone "git://git-annex.branchable.com/" "$(GetFileName "$src")" || return
	inst AptSrc || returng
	sudoc apt-get build-dep git-annex || return
	cd "$src" || return
	cabal update || return
	make || return
}

#
# create command
#

createUsage()
{
	ScriptUsageEcho "\
Usage: $(ScriptName) create DIR [REMOTES]
Create a git-annex repository with the list of command separated remotes.

	-n , --new 					create a new repository, if not specified the first remote is cloned"
}

createArgStart() { unset -v dir remotes; }

createArgs()
{
	ScriptArgGet "dir" -- "$@"; shift;
	[[ $1 ]] && { ScriptArgGet "remotes" -- "$@"; shift; }
	return 0
}

createArgStart() { unset -v new; }

createOpt() 
{
	case "$1" in
		--new|-n) new="true";;
		*) return 1
	esac
}

createCommand()
{
	# directory - create and change to the directory
	local fullDir; fullDir="$(GetFullPath "$dir")" || return
	ScriptCheckDir "$(echo "$fullDir" | RemoveTrailingSlash | GetFilePath)" || return # ensure base directory exists
	[[ ! -d "$dir" ]] && { mkdir "$dir" || return; }
	command cd "$dir" || return # remote needs to be $PWD, full path to the given dir, not the dereferenced fullDir
	
	# initilaize
	local clone="true"; [[ $new ]] && unset clone
	! IsGitDir "." && { hilight "Initialize repository..."; RunLog git init || return; }
	
	if ! git annex status >& /dev/null; then
		hilight "Initializing git annex..."
		RunLog git annex init "$HOSTNAME-$(GetFileName "$fullDir")" || return
	fi

	# setup a new repository
	if [[ $new ]]; then
		local file="README.md"
		echo "New annex." > "$file" || return
		git annex add "$file" || return
		git commit --all --message "initial commit" || return
	fi

	# add remotes
	[[ ! $remotes ]] && return
	local remote; StringToArray "$remotes" "," remotes

	for remote in "${remotes[@]}"; do
		local fqdn; fqdn="$(DnsResolve "$remote")" || return
		remote="$(RemoveDnsSuffix "$fqdn")" || return
		git remote | grep --quiet "^${remote}$" && continue
		
		hilight "Adding remote '$remote'..."
		RunLog git remote add "$remote" "ssh://$USER@$fqdn$PWD" || return

		# clone the remote
		if [[ $clone ]]; then
			hilight "Cloning '$remote'..."
			RunLog git fetch "$remote" || return
			RunLog git pull "$remote" master || return
			unset clone
		fi

	done

	# configure
	echot "\
- Dashboard, click syncing disbaled (where present)
- Configuration
	- Repositories, actions, Edit, Repository group=client (full backup for server), Save Changes
	- Preferences, Auto restart on upgrade=enabled, Save Preferences
	- Consistency Checks, Add, Save
	- Unused files, Enable expiry, Save Changes"
}

#
# install command
#

installCommand()
{
	PrintErr "installing..."	
	command cd "$src" || return

	# find the install dir
	PrintErr "dir..."
	local dir; dir="$(FindInstallFile --quiet "shareware/git-annex/image")" || return

	# bin
	PrintErr "bin..."
	local id; id="$(os executable id "git-annex")" || return
	cp "git-annex" "$dir/git-annex-$id" || return

	# doc
	PrintErr "doc..."
	rsync -a --delete "html/" "$dir/html/" || return

	# man
	PrintErr "man..."
	rsync -a --delete "man/" "$dir/man/" || return

	# completion
	PrintErr "completion..."
	cp "bash-completion.bash" "$dir" || return

	EchoErrEnd "done"
}

ScriptRun "$@"
