#!/usr/bin/env bash
. script.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... build|install
$(ScriptName) commands."
}

init()
{
	src="$CODE/git-annex"
}

buildCommand()
{
	GitHelper clone "git://git-annex.branchable.com/" "$(GetFileName "$src")" || return
	inst AptSrc || return
	sudoc apt-get build-dep git-annex || return
	cd "$src" || return
	cabal update || return
	make || return
}

installCommand()
{
	PrintErr "installing..."	
	command cd "$src" || return

	# find the install dir
	PrintErr "dir..."
	local dir; dir="$(FindInstallFile --quiet "shareware/git-annex/image")" || return

	# bin
	PrintErr "bin..."
	local id; id="$(os executable id "git-annex")" || return
	cp "git-annex" "$dir/git-annex-$id" || return

	# doc
	PrintErr "doc..."
	rsync -a --delete "html/" "$dir/html/" || return

	# man
	PrintErr "man..."
	rsync -a --delete "man/" "$dir/man/" || return

	# completion
	PrintErr "completion..."
	cp "bash-completion.bash" "$dir" || return

	EchoErrEnd "done"
}

ScriptRun "$@"
