#!/bin/bash
. function.sh || exit

usage()
{
	echot "\
usage: GitHelper git|gui|tgui|changes|up|down|commit
	Addition Git functionality"
	exit $1
}

guiUsage() { "$gui" --help; exit $1; }

args()
{
	unset command help dest exclude file show arg1 arg2
	versions=( 2013 2012 )
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			IsInstalled) command="IsInstalled";;
			*)
				! IsOption "$1" && IsInArray "$1" versions && { version="$1"; shift; continue; }
				[[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "$command" == @(git|gui|tgui|up|down) ]] && break																						# defer argument processing
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && { IsFunction "${command}Usage" 0 && ${command}Usage || usage 0; }
	[[ ! $command ]] && { MissingOperand "command"; }
	args=("$@")
}

init()
{ 
	git="$P32/Git/bin/git.exe"
	gui="$P32/GitExtensions/GitExtensions.exe"
	tgui="$P/TortoiseGit/bin/TortoiseGitProc.exe" # http://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-automation.html
}

run() {	init || return; args "$@" || return; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$git" ]]; }

gitCommand()
{
	[[ ! -f "$git" ]] && { EchoErr "Could not find git command: is Git Extensions installed?"; return 1; }
	start --direct "$git" "$@"
}

guiCommand()
{
	[[ ! -f "$gui" ]] && { EchoErr "Could not find GitExtensions command: is Git Extensions installed?"; return 1; }

	# convert /path:"$dir" paths
	#local args; for arg in "$@"; do
	#	[[ "$arg" == @(/path:*) ]] && args+=( "/path:$(utw "${arg#/path:}")" ) || args+=( "$arg" )
	#done

	[[ $# == 0 ]] && start "$gui" || start --direct "$gui" "${args[@]}"
}

tguiCommand()
{
	[[ ! -f "$tgui" ]] && { EchoErr "Could not find TortoiseGitProc command: is TortoiseGit installed?"; return 1; }

	# convert /path:"$dir" paths
	#local args; for arg in "$@"; do
	#	[[ "$arg" == @(/path:*) ]] && args+=( "/path:$(utw "${arg#/path:}")" ) || args+=( "$arg" )
	#done

	start --direct "$tgui" "${args[@]}"
}

changesCommand()
{
	[[ "$(git status --porcelain)" != "" ]]
}

upCommand()
{
	(( $# == 2 )) && { pushd "$1" > /dev/null || return; echo "Uploading $1..."; shift; }
	changesCommand || return 0
	git status
	git add --all || return
	git commit -m "$1" || return
	git push || return
}

downCommand()
{
	(( $# == 1 )) && { pushd "$1" > /dev/null || return; echo "Downloading $1..."; shift; };
	git pull
}

commitCommand() { guiCommand commit; }

run "$@"
