#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

# validate directory exists
dir="$1"
ScriptCheckDir "$dir"

# validate Windows directory exists
dir="$(utw "$1")"
[[ ! $dir ]] && { ScriptErr "unable to get the Windows directory for '$1"; exit 1; }

# take ownership and set permissions
takeown.exe /f "$dir" /r /d y
icacls.exe "$dir" /setowner $WIN_USER /c /t
icacls.exe "$dir" /c /grant "$WIN_USER:(OI)(CI)F" /t /inheritance:d

exit 0 # ignore errors