#!/usr/bin/env bash
. function.sh || exit
takeown.exe /f "$(utw "$*")" /r /d y
icacls.exe "$(utw "$*")" /setowner $WIN_USER /c /t
icacls.exe "$(utw "$*")" /c /grant "$WIN_USER:(OI)(CI)F" /t /inheritance:d
exit 0 # ignore errors