#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [cli|close|IsInstalled|monitor|profile|program|start|service](start)
$(ScriptName) commands."
}

init() { defaultCommand="start"; }
argEnd() { program="$P/Hammerspoon.app"; }

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
monitorCommand() { hs -C; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start "$program" "${startArgs[@]}"; } # h
startupCommand() { start "$program" "${startupArgs[@]}"; }
versionCommand() { AppVersion "Hammerspoon"; }

cliArgs() { cliArgs=( "$@" ); shift="$#"; }

cliCommand()
{
	AppInstallCheck || return

	local cli prefix
	hs "${cliArgs[@]}" "${otherArgs[@]}"
}

#
# Profile Command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }

profileCommand()
{
	profile $noPrompt --app "hammerspoon-settings" --method "$HOME/Library/Preferences" --files "org.hammerspoon.Hammerspoon.plist" "${profileArgs[@]}" || return
	profile $noPrompt --app "hammerspoon-config" --method "$HOME/.hammerspoon" "${profileArgs[@]}" --files "*" || return
}

ScriptRun "$@"
