#!/usr/bin/env bash
. function.sh || exit
. bootstrap-config.sh || exit

run() {	init && args "$@" && ${command}Command "${args[@]}"; }

init() { :; }

usage()
{
	echot "\
usage: $(ScriptName)
	install consul|nomad 				if no hosts are specified use hosts from bootstrap-config.sh
		-c, --clients	HOSTS				comma separated list of clients to install
		-dc, --datacenter					name of the data center
		-j, --join HOSTS					comma separated list of hosts to join to, defaults to specified servers
		-s, --server HOSTS				comma separated list of servers to install
	remove consul|nomad"
	exit ${1:-1}
}

args()
{
	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-h|--help) usage 0;;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; command="${1,,}"; shift; continue; }
				! IsOption "$1" && [[ "$command" == @(install|remove) ]] && break
				UnknownOption "$1"
		esac
		shift
	done

	[[ ! $command ]] && { usage; }

	args=("$@")
}

#
# Install Command
#

installCommand()
{
	local clients=() command datacenter="$workgroup" servers=() join=()

	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-c|--client) [[ ! $2 ]] && usage 0; shift; StringToArray "$1" "," clients;;
			-dc|--datacenter) datacenter="$1";;
			-j|--join) [[ ! $2 ]] && usage 0; shift; StringToArray "$1" "," join;;
			-s|--servers) [[ ! $2 ]] && usage 0; shift; StringToArray "$1" "," servers;;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckSubCommand "install" "$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	[[ ! $command ]] && { usage; }

	# defaults
	[[ ! $clients && ! $servers ]] && { clients=( "${hashiClients[@]}" ) servers=( "${hashiServers[@]}" ); }
	[[ ! $join ]] && join=( "${servers[@]}" )
	[[ ! $join ]] && join=( "${hashiServers[@]}" )

	initInstall || return
	$command || return
}

initInstall()
{
	user="$systemUser" # requires passwordless sudo permission
	common=( --user "$user" ) # --show

	consul=( --datacenter "$datacenter" --client "0.0.0.0" --bind "{{ GetInterfaceIP \"eth0\" }}" )
	consulServer=( --server --bootstrap-expect="${#servers[@]}" --advertise "{{ GetInterfaceIP \"eth0\" }}" )
	for host in "${join[@]}"; do consul+=( --retry-join="$host" ); done

	nomad=( --datacenter "$datacenter" --client "0.0.0.0" )
	nomadServer=( --server --bootstrap-expect="${#servers[@]}" --advertise "{{ GetInterfaceIP \"eth0\" }}" )
}

installConsulCommand()
{ 
	for host in "${servers[@]}"; do
		hilight "Installing consul server on $host..."
		hashi-up consul install --ip "$(GetIpAddress "$host")" "${common[@]}" "${consul[@]}" "${consulServer[@]}" || return
	done

	for host in "${clients[@]}"; do
		hilight "Installing consul client on $host..."
		hashi-up consul install --ip "$(GetIpAddress "$host")" "${common[@]}" "${consul[@]}" || return
	done
}

installNomadCommand()
{
	for host in "${servers[@]}"; do
		hilight "Installing nomad server on $host..."
		hashi-up nomad install --ip "$(GetIpAddress "$host")" "${common[@]}" "${nomad[@]}" "${nomadServer[@]}" || return
	done

	for host in "${clients[@]}"; do
		hilight "Installing nomad client on $host..."
		hashi-up nomad install --ip "$(GetIpAddress "$host")" "${common[@]}" "${nomad[@]} --client" || return
	done
}

#
# Remove Command
#

removeCommand()
{
	local command; CheckSubCommand remove "$1"; shift
	[[ $# != 0 ]] && UnknownOption "$1"
	$command "$@"
}

removeConsulCommand()
{
	service exists consul && { service delete consul || return; }
	sudo rm -fr "/etc/consul.d" || return
	sudo rm -fr "/opt/consul" || return
	sudo rm -f "/usr/local/bin/consul" || return
}

removeNomadCommand()
{
	service exists nomad && { service delete nomad || return; }
	sudo rm -fr "/etc/nomad.d" || return
	sudo rm -fr "/opt/nomad" || return
	sudo rm -f "/usr/local/bin/nomad" || return
}


#
# helper
#

run "$@"
