#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... backup|restore
$(ScriptName) commands."
}

init() 
{ 
	homebridgeDir="$HOME/.homebridge"
	[[ ! -d ~/.homebridge || -L ~/.homebridge ]] && homebridgeDir="/var/lib/homebridge"
	return 0
}

#
# commands
#

versionCommand() { echo "0"; }

#
# Backup Command
#

backupUsage() { echot "Usage: $(ScriptName) backup [HOST]...
Backup Homebridge configuration."; }

backupArgStart() { unset -v hosts; }
backupArgs() { hosts=( "$@" ); shift="$#"; }

backupCommand()
{
	# backup hosts
	if [[ $hosts ]]; then
		backupHosts "${hosts[@]}"

	# backup local Homebridge directory
	elif [[ -d "$homebridgeDir" ]]; then
		AppBackup "$HOSTNAME.homebridge" "$homebridgeDir"

	# nothing found
	else
		ScriptErr "no hosts specified and no Homebridge directory found"; return 1

	fi
}

backupHosts() { local host; for host in "$@"; do backupHost "$host" || return; done; }

# backupHost HOST - backup /var/lib/honebridge directory on host to AppGetBackupDir (i.e. //rp1.hagerman.butare.net/public/backup)
backupHost()
{
	local host="$1" file="$host.homebridge.zip"

	hilight "Backing up $host Homebridge configuration..."
	
	# mount backup directory
	local dest; dest="$(AppGetBackupDir)/$file" || return

	# initialize
	[[ -f "$dest" ]] && { bak --move "$dest" "${globalArgs[@]}" || return; }

	# backup
	echo  "Creating backup from $host..."
	SshHelper connect "$host" "${globalArgs[@]}" "rm -f $file; zip -r $file /var/lib/homebridge" || return

	echo "Copying backup file to $dest..."
	RunLog scp -4 $verbose $host:~/$file "$dest" || return

	echo "Removing backup file from $host..."
	RunLog SshHelper connect "$host" "${globalArgs[@]}" "rm -f $file"

	echo "Homebridge backup of $host completed to $(FileToDesc "$dest")"
}

#
# Restore Command
#

restoreUsage() { echot "Usage: $(ScriptName) HOST FILE\nRestore Homebridge configuration."; }
restoreArgs() { ScriptArgGet "host" -- "$@" && shift && ScriptArgGet --required "file" -- "$@" && file="$file.homebridge.zip" && ScriptCheckFile "$file"; }

restoreCommand()
{
	ask -dr n "Are you sure you want to restore "$f" to $h" || return

	hilight "Restoring $host Homebridge configuration..."
	scp "$f" $h:~ || return
	ssh -t $h "sudo hb-service stop && sudo find ~/.homebridge -mindepth 1 -maxdepth 1 -exec rm -fr {} + && sudo unzip -o $f -d ~" || return
}

ScriptRun "$@"
