#!/usr/bin/env bash
. function.sh || return
. color.sh || return

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() { :; }

usage()
{
	echot "\
usage: HostCleanup [gui]
	Cleanup extraneous files and configuration on the host
		-np, --no-prompt		do not prompt for what to cleanup"
	exit $1
}

args()
{
	unset command

	while [ "$1" != "" ]; do
		case "$1" in
			-h|--help) IsFunction "${command}Usage" && ${command}Usage 0 || usage 0;;		
			-np|--no-prompt) function ask { :; };;		
			*) 
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	command="${command:-cleanup}"
}

guiCommand()
{
	IsPlatform mac && { start "CleanMyMac X.app"; return; }
	IsPlatform win && { start "$P/CleanMyPC/CleanMyPC.exe"; return; }
	return 0
}

cleanupCommand() { cleanupFiles && cleanupPrograms && RunPlatform cleanup; }

cleanupWin()
{
	ask 'Cleanup old windows versions' && { elevate CleanMgr.exe /AUTOCLEAN || return; }
	ask 'Cleanup path' && { os path; }
	ask 'Cleanup startup programs' && { start --elevate autoruns || return; }
	ask 'Cleanup scheduled tasks' && { start --elevate task scheduler || return; }
	ask 'Cleanup remaining files' && { elevate CleanMgr.exe /VERYLOWDISK || return; }
	return 0
}

cleanupFiles()
{
	echo -n "${GREEN}cleaning files...${RESET}"
	cleanupTmp && cleanupVolumes && RunPlatform cleanupFiles
	echo "done"
}

cleanupFilesWin()
{
	[[ -d "$UADATA/temp" ]] && { rm -fr "$UADATA/temp/"* >& /dev/null; echo -n "."; }
	[[ -d "$WIN_ROOT/temp" ]] && { rm -fr "$WIN_ROOT/temp/"* >& /dev/null; echo -n "."; }
	[[ -d "$WINDIR/Temp" ]] && { rm -fr "$WINDIR/Temp/"* >& /dev/null; echo -n "."; }
	return 0
}

cleanupTmp() { ! IsPlatform mac && [[ -d "$TMP" ]] && rm -fr "$TMP/"*; echo -n "."; }
cleanupVolumes() { [[ -d "$HOME/Volumes" ]] && rmdir "$HOME/Volumes/"* >& /dev/null; echo -n "."; }

cleanupPrograms() { cleanupApt && cleanupBrew && cleanupRuby && cleanupJournal; }
cleanupBrew() { IsPlatform brew && hilight "cleaning Homebrew..." && brew cleanup; return 0; }
cleanupRuby() { which gem >& /dev/null && hilight "cleaning Ruby..." && sudo gem cleanup; return 0; }

cleanupApt()
{
	! IsPlatform apt && return
	hilight "Cleanup apt..."
	sudoc apt-get clean -y || return 	# cleanup downloaded package files in /var/cache/apt/archives
	sudoc apt autoremove -y || return
	InPath wajig && { wajig purgeremoved || return; }
	return 0
}

cleanupJournal()
{
	! IsPlatform systemd && return
	hilight "cleaning systemd journal..."
	sudo journalctl --rotate
	sudo journalctl --vacuum-time=2d
}

run "$@"