#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: HostCleanup
	Cleanup extraneous files and configuration on the host"
	exit $1
}

args()
{
	unset command

	while [ "$1" != "" ]; do
		case "$1" in
			-h|--help) IsFunction "${command}Usage" && ${command}Usage 0 || usage 0;;		
			*) 
				IsFunction "${1,,}Update" && { command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	command="${command:-cleanup}"
}

init() { sudo="sudo"; IsPlatform win && sudo=""; return 0; }
run() {	args "$@" || return; init || return; cleanup; }

cleanup()
{
	IsFunction "${PLATFORM}Cleanup" && { ${PLATFORM}Update || return; }
	IsFunction "${PLATFORM_LIKE}Cleanup" && { ${PLATFORM_LIKE}Cleanup || return; }
	IsFunction "${PLATFORM_ID}Cleanup" && { ${PLATFORM_ID}Cleanup || return; }
	return 0;
}

debianCleanup()
{
	$sudo apt-get clean || return 	# cleanup downloaded package files in /var/cache/apt/archives
	$sudo apt autoremove || return
	return 0
}

winCleanup()
{
	echot "\
- remove path entries  are not used or interfere with system"
	os path editor || return
	pause
 
	echot "\
- Options, uncheck Hide Windows Entries
- disable login programs that are not used or interfere with system"
	autoruns || return
 
	echot "\
- disable login programs that are not used or interfere with system: NVidia, DropBox, etc.
	- NVidia: https://www.ghacks.net/2016/11/07/nvidia-telemetry-tracking/"
	task scheduler || return
	pause
}

run "$@"