#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: HostCleanup
	Cleanup extraneous files and configuration on the host
		-p, --prompt		prompt for what to cleanup"
	exit $1
}

args()
{
	unset command prompt

	while [ "$1" != "" ]; do
		case "$1" in
			-p|--prompt) prompt="--prompt";;		
			-h|--help) IsFunction "${command}Usage" && ${command}Usage 0 || usage 0;;		
			*) 
				IsFunction "${1,,}Update" && { command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	command="${command:-cleanup}"
}

init()
{
	[[ ! $prompt ]] && function ask { :; }
	return 0; 
}

run() {	args "$@" || return; init || return; cleanup; }

cleanup()
{
	IsFunction "${PLATFORM}Cleanup" && { ${PLATFORM}Cleanup || return; }
	IsFunction "${PLATFORM_LIKE}Cleanup" && { ${PLATFORM_LIKE}Cleanup || return; }
	IsFunction "${PLATFORM_ID}Cleanup" && { ${PLATFORM_ID}Cleanup || return; }
	return 0;
}

debianCleanup()
{
	sudoc apt-get clean -y || return 	# cleanup downloaded package files in /var/cache/apt/archives
	sudoc apt autoremove -y || return
	return 0
}

winCleanup()
{
	ask 'cleanup path' && { start --elevate os path editor || return; }
	ask 'cleanup startup programs' && { start --elevate autoruns || return; }
	ask 'cleanup scheduled tasks' && { start --elevate task scheduler || return; }
	return 0
}

run "$@"