#!/usr/bin/env bash
. script.sh || return

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [TARGET|host](localhost)
Return host information in variables.  Target can be a host, directory, or UNC.
If the target is \"host\", find a mounted host such as a virtual machine host of 
a guest virtual machine.

	-d,	--detail			include more detailed information
	-p, --protocol		$(ScriptOptNetworkProtocolUsage)
	-T, --trust				trust host identification ignoring possible security issues
	-u,	--user USER		the user to find directories for"
}

init() { defaultCommand="vars"; }
argStart() { unset -v protocol; }

#
# Vars Command
#

varsArgStart() { unset -v detail protocol target trust user verbose; }

varsOpt() 
{
	case "$1" in
		-d|--detail) detail="true";;
		-p|--protocol|-p*|--protocol=*) ScriptOptNetworkProtocol "$@";;
		-T|--trust) trust="--trust";;
		-u|--user) user="$1";;
		*) return 1
	esac
}

varsArgs() {	[[ ! $1 ]] && return; ScriptArgGet "target" -- "$@"; }

varsCommand()
{
	local basicVars=() detailVars=() local protocolArg="$protocol"

	protocol="${protocol:-smb}"

	varsBasic || return
	[[ $detail ]] && { varsDetail || return; }

 	ScriptReturn "${basicVars[@]}" "${detailVars[@]}"
}

varsBasic()
{	
	# define GetPlatform function
	. bash.bashrc || return 

	# variables
	local var	
	basicVars=(_platformTarget _platformLocal	_platformOs _platformLike _platformId _platformKernel _machine _data)
	basicVars+=(_root _media _public _users _user _home)	# directory
	basicVars+=(_protocol)																# file sharting protocol
	basicVars+=(_busybox _chroot _wsl)										# other

	for var in "${basicVars[@]}"; do unset $var; done

	# find target for a mounted host
	if [[ "$target" == "host" ]]; then

			local drive drives; IFS=$'\n' ArrayMake drives "$(drive mounts)"; unset target
			for drive in "${drives[@]}"; do
				[[ -d "$drive/usr/local" || -d "$drive/Users/Public" ]] && { target="$drive"; break; }
			done

			[[ ! $target ]] && { ScriptErr "unable to find information for host"; return 1; }
	fi
	_platformTarget="$target"

	# local
	if IsLocalHost "$target" || [[ "$target" == "/" ]]; then
		_platformTarget="localhost"
		_platformLocal="true"
		_platformOs="$PLATFORM_OS" _platformLike="$PLATFORM_LIKE" _platformId="$PLATFORM_ID" _platformKernel="$PLATFORM_KERNEL" _machine="$MACHINE"
		_root="/" _users="$USERS" _public="$PUB"	_data="$DATA"; [[ ! $_user ]] && _home="$HOME"
		_busybox="$(IsBusyBox && echo "$true")" _chroot="$(IsChroot && echo "true")" _wsl="$WSL"

	# directory
	elif [[ -d "$target" ]]; then
		varsBasicDir || return

	# host
	else
		varsBasicHost || return

	fi

	# Synology does not support SMB connections
	[[ "$protocol" == "smb" ]] && IsPlatform synology && protocol="ssh";

	# assume QNAP and Synology use port 608 for SSH
	[[ "$protocol" == "ssh" ]] && { IsPlatform qnap,synology --host && _protocol="608"; }

	# override standard shares
	if [[ $target && "$protocol" == "smb" ]] && IsPlatform qnap,synology --host; then
		_root="//$target" _users="$_root/homes" _public="$_root/public" _data="$_public/documents/data" _home="$_root/home" _media="$_root/data/media"
	fi

	# _users
	if [[ ! $_users && $_root ]]; then		
		if isProtocolSsh && IsPlatform win --host; then _users="$_root/home"
		elif IsPlatform mac,win --host; then _users="$_root/Users"
		elif IsPlatform qnap --host; then _users="$_root/share/homes"
		elif IsPlatform linux --host; then _users="$_root/home"
		fi
	fi

	# _public
	[[ ! $_public && $_users ]] && _public="$_users/Shared"

	# _data
	[[ ! $_data && $_root ]] && _data="$_root/usr/local/data"

	# _user
	_user="${user:-$(SshUser "$target")}" || return
	
	# _home
	[[ ! $_home && $_users ]] && _home="$_users/$_user"

	# file sharing
	_protocol="$protocol"

	return 0
}

varsBasicDir()
{
	# dir - USB drive with a public and option home directory
	if [[ -d "$target/public" ]]; then
		_public="$target/public" _data="$_public/documents/data"
		[[ -d "$target/home" ]] && _home="$target/home"

	# dir -  public directory
	elif [[ -d "$target/documents/data/platform" ]]; then
		_public="$target" _data="$_public/documents/data"

	# dir - home directory
	elif [[ -d "$target/data/bin" ]]; then
		_home="$target"

	# dir - host root directory
	else

		if [[ -d "$target/mnt/c" ]]; then
			_platform="win"
		elif [[ -d "$target/usr/local" ]]; then
			_platform="linux"
		elif [[ -d "$target/Applications" ]]; then
			_platform="mac"; 
		else
			ScriptErr "unable to find host information in \`$target\` directory"
			return 1
		fi
		_root="$target"

	fi
}

varsBasicHost()
{
	local host="$(RemoveDnsSuffix "$target")"
	local network="$(network current name)"

	# Wiggin hosts - Synology 
	if [[ "$network" == "hagerman" && "$host" == @(nas1) ]]; then
		_platform="linux" _platformLike="synology" _platformId="dsm" _platformKernel="linux" _machine="x86_64" _root="//$target/root"
	
	# Wiggin hosts - QNAP
	elif [[ "$network" == "hagerman" && "$host" == @(nas3|nas3.hagerman.butare.net|nas3.butare.net) ]]; then
		_platform="linux" _platformLike="qnap" _platformId="qts"  _platformKernel="linux" _machine="x86_64" _root="//$target/root"
	
	# other host - determine platform using SSH
	elif SshAgentConf --quiet "${globalArgs[@]}" && GetPlatform "$target" --quiet $trust $verbose; then
		_platformOs="$platformOs" _platformLike="$platformLike"	_platformId="$platformId" _platformKernel="$platformKernel" _machine="$machine"
		_busybox="$busybox" _chroot="$chroot" _wsl="$wsl"

		# _root
		_root="//$target/root"
		if IsPlatformAll mac,arm --host; then _root="//$target/system"
		elif IsPlatformAll mac,x86 --host; then _root="//$target/system/volumes/data"
		fi

		# for Windows assume SSH (for the WSL file ssytem) unless the protocol was set explicitly
		[[ ! $protocolArg ]] && IsPlatform win --host && protocol="$(SshHelper config get "$target" port)" # access WSL drives by default
	
		# if SMB is not available fall back to SSH 
		[[ "$protocol" == "smb" ]] && ! unc IsAvailable "$target" --protocol="$protocol" && protocol="$(SshHelper config get "$target" port)"

	else
		[[ ! $quiet ]] && ScriptErr "unable to determine '$target' platform"
		return 1

	fi

	return 0
}

varsDetail()
{
	# variables
	local var; detailVars=( pd ud udoc uhome udata)
	for var in "${detailVars[@]}"; do unset $var; done

	# additional directory information
	pd="$_public/Desktop"
	ud="$_home/Desktop"
	udoc="$_home/Documents"
	uhome="$_home"
	udata="$uhome/data"

	#
	# platform information
	#
	case "$_platformOs" in

		win)
			detailVars+=( psm pp ao usm up )
			psm="$_root/mnt/c/ProgramData/Microsoft/Windows/Start Menu"
			pp="$psm/Programs"
			ao="$pp/Applications/Other"
			usm="$UADATA/../Roaming/Microsoft/Windows/Start Menu"	
			up="$usm/Programs"
			;;

		mac)
			detailVars+=( si la ula )
			si="/Library/StartupItems"
			la="/Library/LaunchAgents"
			ula="$HOME/Library/LaunchAgents"
			;;

	esac

	#
	# host specific information
	#
	local vars=( _minimalInstall )
	unset "${vars[@]}"
	detailVars+=( "${vars[@]}" )
		
	# limit what is installed on embedded systems such as Raspberry Pi, nas, and docker systems
	IsPlatform pi,pikernel --host && _minimalInstall="true" 
	[[ ! $target ]] && IsPlatform docker && _minimalInstall="true"

	return 0
}

#
# helper
#

isProtocolSsh() { [[ "$protocol" == "ssh" ]] || IsInteger "$protocol"; }

ScriptRun "$@"
