#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|control|IsInstalled|IsRunning|profile|program|restart|start|startup](control)
$(ScriptName) commands."
}

init()
{
	defaultCommand="control"
	dir="$P32/Common Files/Apple/Internet Services"
	iCloudServicesProgram="$dir/iCloudServices.exe"
	ApplePhotoStreamsProgram="$dir/ApplePhotoStreams.exe"
	program="$dir/iCloud.exe"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
controlCommand() { startCommand; }
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$iCloudServicesProgram" && IsProcessRunning "$ApplePhotoStreamsProgram"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }
									 
startupCommand()
{
	AppInstallCheck || return; IsRunningCommand && return
	start "$iCloudServicesProgram"
	start "$ApplePhotoStreamsProgram"
}

ScriptRun "$@"
