#!/bin/bash
. app.sh

init()
{ 
	command="control"
	dir="$P32/Common Files/Apple/Internet Services"
	program="$dir/iCloud.exe"
	iCloudServicesProgram="$dir/iCloudServices.exe"
	ApplePhotoStreamsProgram="$dir/ApplePhotoStreams.exe"
}

usage() {	echot "usage: templateApp [start|startup|close|restart|close](start)"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				if [[ "$1" == @(start|startup|profile|service) ]]; then { command="${1,,}"; shift; break; }
				elif IsFunction "${1,,}Command"; then command="${1,,}"
				else { echoerr "Unknown argument $1"; usage 1; }
				fi;;
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$iCloudServicesProgram"
	start "$ApplePhotoStreamsProgram"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
controlCommand() { startCommand; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$iCloudServicesProgram" && IsTaskRunning "$ApplePhotoStreamsProgram"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"