#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	echot "\
usage: ImageEdit FILE
	Open the specified file or directory in an installed image editor"
	exit $1
}

[[ "$1" == @(-h|--help) ]] && usage 0

if IsInstalled fsview; then
	fsview start "$@"

elif IsInstalled irfan; then
	irfan start "$@"

else
	start "$@"

fi
