#!/usr/bin/env bash
. function.sh || exit

run()
{
	local desc dirs src srcDesc

	src="//nas3.hagerman.butare.net/public/Documents/data/install"
	srcDesc="$(GetUncServer "$src" | RemoveDnsSuffix)"
	src="$(unc mount "//nas3.hagerman.butare.net/public/Documents/data/install")" || return

	IFS=$'\n' dirs=( $(FindInstallFile --all) )

	for dir in "${dirs[@]}"; do
		
		if IsUncPath "$dir"; then
			desc="$(GetUncServer "$dir" | RemoveDnsSuffix)"
			[[ "$desc" == "$srcDesc" ]] && continue
			dir="$(unc mount "$dir")" || return

		elif drive IsDrive "$dir"; then
			desc="$(drive label "$dir")"; desc="${desc:-$dir}"

		else
			EchoErr "InstBak: unable to backup to \"$dir\""
			return 1
		fi
		
		header "$desc"
		CopyDir --recursive --delete "$src" "$dir" || return
		echo
	
	done
}

run "$@"
