#!/bin/bash
. function.sh || exit

templateInstall()
{
	printf "**************************************************\n* name\n**************************************************\n"
	
	run "" || return # download location

	echo "Updating icons..."
	$mergeDir "$pp/(dir)" "$ao" || return
	$mergeDir "$pp/(dir)" "$pp/Development/Other" || return
	$mv "$pp/Sublime Text 2.lnk" "$pp/Applications" || return
	$rm "$pd/(prog).lnk" || return
}

TemplateAlias() { TemplateFullInstall; };
TemplateFullInstall()
{
	printf "**************************************************\n* name\n**************************************************\n"
	echot "- application infromation"

	# download: 
	# installs:
	run "" || return

	FindFile "Intel/Profile Manager/ProfileManager.xml" || return
	$cp	"$file" "$WINDIR/system32" || return
	$rc --mirror --quiet "$src" "$dest" || return

	echo "Updating icons..."
	$mergeDir "$pp/(dir)" "$pp/Development/Other" || return
	$mergeDir "$pp/(dir)" "$ao" || return
	$rm "$pd/(prog).lnk" || return
	$mergeDir --rename "$pp/(dir)" "$ao/(new name)" || return
	$makeDir "$pp/Operating System/bash" || return
	$makeShortcut "$installDir/bin/mintty.exe" "$pp/Operating System/bash" -a="-" || return

	echo "Moving data folders..."
	$makeLink --merge --hide "$udoc/code/web/sites" "$udoc/My Web Sites" || return

	echo "Updating registry..."	
	$registry import "$install/AutoHotKey/setup/other/AutoHotkey-${architecture}.reg" || return
	$registry set "HKCU/SOFTWARE/Foo/File" REG_EXPAND_SZ "$(utw "$file")" || return
	$registry delete "run/ErmTray" # C:/Program Files/McAfee/Host Intrusion Prevention/FireTray.exe 

	echo "Updating services..."
	service manual "Stereo Service"
	service manual "nvUpdatusService"

	echo "Updating firewall..."
	$firewall rule add "SSH" dir=in action=allow protocol=TCP localport=22 profile=private program="$(utw "$P/Cygwin/usr/sbin/sshd.exe")" || return

	echo "Creating directories..."
	$makeDir "$_userDocuments/code/test"

	sublime profile restore default || return

	echot "\
	- configure
	"
	app start
	pause
}

usage()
{
	echot "\
usage: install cd|install APP*
	Install programs
	-h, --hint DIR			first directory to search for installation files
      --no-run-prompt	do not ask to run the executable
  -s, --select				select the install location"
	exit $1
}

args()
{
	unset command apps host noRunPrompt select
	originalArgs=( "$@" ) 
	while [ "$1" != "" ]; do
		case "$1" in
			--no-run-prompt) noRunPrompt="true";;
			--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			--hint|-h) hint=( --hint "$2" ); shift;;
			--select|-s) select="--select";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; } # command
				! IsOption "$1" && { apps+=( "$1" ); shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='install'
	[[ "$command" == "cd" && ${#apps[@]} != 0 ]] && UnknownOption "${apps[0]}"
	[[ "$command" == "apps" && ${#apps[@]} == 0 ]] && MissingOperand "APPS"
	args=("$@")
}

cdCommand()
{
	FindFile || return
	echo "$file"
}

installCommand()
{
	! IsElevated && { sudo mintty -h error bash -l inst "${originalArgs[@]}"; return; }
	InstallInit || return
	InstallApps "${apps[@]}" || return
}

i() {	InstallApps "$@"; }
InstallApps()
{
	local prompt; { (( $# > 1 )) || [[ $noRunPrompt ]]; } && prompt="true"
	while (($# != 0 )); do
		app="$1"; shift
		if [[ ! $prompt ]] || ask "\nInstall $app"; then
			installFunction="$(GetInstallFunction)" || { EchoErr "inst: $app installation does not exist"; return 1; }
			$installFunction || return
		fi
	done
	return 0
}

GetInstallFunction()
{
	declare -f | egrep -i "^${app} \(\) $|^${app}Install \(\) $" | sed "s/ () //" # Similar to GetFunction
	return ${PIPESTATUS[1]}
}

InstallInit() 
{
	ScriptEval os FindInfo || return
	serverPrograms="$pp/Development"; [[ $server ]] && serverPrograms="$pp/Server";

	local test #="echo "
	cp="${test}FileCommand cp"
	firewall="${test}firewall --suppress"
	hide="${test}FileCommand hide"
	hideAndSystem="${test}FileCommand HideAndSystem"
	makeDir="${test}mkdir --parents"
	makeLink="${test}MakeLink --suppress"
	makeShortcut="${test}MakeShortcut"
	mergeDir="${test}MergeDir --suppress --parents"
	mv="${test}FileCommand mv"
	rc="${test}CopyDir"
	registry="${test}registry"
	ren="${test}FileCommand ren"
	rm="${test}rm -f"
	rmd="${test}rm -fr"
	
	netShareOptions=/grant:Everyone,full
	setupFiles="$(ScriptDir)/../setup"
}

run() # run EXE [OPTIONS...]
{
	local exe="$1"

	[[ ! $exe ]] && { EchoErr "inst: executable was not specified"; return 1; }
	FindFile "$exe" || { ask "Continue the installation"; return; }
	RunExe "$file" "${@:2}" || return
}

FindEditorProgram()
{
	if [[ -f "$P/Sublime Text 3/sublime_text.exe" ]]; then
		program="$P/Sublime Text 3/sublime_text.exe"
	elif [[ -f "$P32/Notepad++/notepad++.exe" ]]; then
		program="$P32/Notepad++/notepad++.exe"
	else
		program="$(FindInPath "notepad")"
	fi
}

FindCompareProgram()
{
	if [[ -f "$P32/Beyond Compare 3/BComp.exe" ]]; then
		program="$P32/Beyond Compare 3/BComp.exe"
	elif [[ -f "$P32/KDiff3/kdiff3.exe" ]]; then
		program="$P32/KDiff3/kdiff3.exe"
	else
		program=""
	fi
}

FindFile()
{
	local pattern; file="$1"

	if IsWild "$file"; then
		GetFileName "$file" pattern || return
		GetFilePath "$file" file || return
	fi

	if ! ScriptEval FindInstallFile $select --suppress --eval "${hint[@]}" "$file"; then
		EchoErr "inst: could not locate ${1:-the installation directory}"
		return 1
	fi

	hint=( --hint "$InstallDir" )
	[[ $pattern ]] && { SelectFile "$file" "$pattern" || return; }
	return 0
}

SelectFile() # DIR PATTERN
{
	local dir="$1" pattern="$2" result items

	pushd "$dir" > /dev/null || return
	
	for f in $pattern; do items+=( "$f" "" ); done

	result=$(dialog --stdout --backtitle "Select File" \
  	--menu "Choose file to install:" $(($LINES-5)) 50 $(($LINES)) "${items[@]}")
	clear

	[[ ! $result ]] && { EchoErr "inst: a file was not selected"; return 1; }

	file="$dir/$result"
	popd > /dev/null
}

RunExe()
{
	local exe="$1"; shift
	local exeParts; StringToArray "$exe" "/" exeParts
	local exeDesc="$(IFS=/; echo "${exeParts[*]: -3}")"
	local standard; [[ "$1" == @(-s|--standard) ]] && { standard="--standard"; shift; }
	local pause; [[ "$1" == @(-p|--pause) ]] && { pause="--pause"; shift; }

	[[ $noRunPrompt ]] && echo "Runing $exeDesc..." ||
		{ ask "Do you want to run $exeDesc" || return 0; }	

	local exeExt; GetFileExtension "$exe" exeExt

 	[[ "$exeExt" == @(air|iso|msu|vsix|xpi) ]] && pause="--pause"

	case "$exeExt" in
		bat|cmd) cmd /c "$exe" "$@";;
		msi) start --wait msiexec /i "$exe" "$@";;
		iso) iso mount 1 "$exe"; echo "If needed run the setup program manually...";;
		zip|7z|gz|tar|xpi|ear|jar|war) RunZip "$exe" "$@" || return;;
		*) [[ $standard ]] && sudo --standard "$exe" "$@" || start --wait "$exe" "$@";;
	esac

	[[ $pause || $standard ]] && pause "When the installation has finished press any key..."
	
	case "$exeExt" in
		iso) iso UnmountAll || return
	esac	
}

RunZip()
{
	local exe="$1"; shift
	local installDir; PrepareInstallDir "$@" || return	

	7z.exe x -o"$(utw "$installDir")" "$(utw "$exe")" || return

	# If the archive contains a single directory move the contents of that directory up
	if [[ "$(DirCount "$installDir")" == 1 ]]; then
		for dir in "$installDir"/*; do
			if [[ -d "$dir" ]]; then
				MoveAll "$dir" "$installDir" || return
				break
			fi
		done
	fi
}

PrepareInstallDir()
{
	installDir="$1"; shift;
	[[ ! $installDir ]] && { EchoErr "inst: installation directory was not specified"; return 1; }

	if [[ -d "$installDir" ]]; then
		ask "Do you want to delete the existing installation in \"$(GetFileNameWithoutExtension "$installDir")\"" -dr n || return
		$rmd "$installDir" || return
	fi

	$makeDir "$installDir" || return
}

#
# Installations
#

testInstall()
{
	FindFile "Shareware" || return
	echo "Found Shareware in $file"
}

bootstrap()
{
	printf "**************************************************\n* Bootstrap\n**************************************************\n"

	ScriptEval SetVar SEE_MASK_NOZONECHECKS 1 || return # disable Open File Secirity Warning
	coreDirectories || return

	i cygwin bash console VirtualCloneDrive || return

	case "${USERNAME#ad_}" in
		jjbutare) i sublime AutoHotKey BeyondCompare WinSplit || return;;
		*) i notepadpp || return;;
	esac

	i BashFinal
}

coreDirectories()
{
	$makeDir "$pp/Applications/Other" || return
	$makeDir "$pp/Development/Other" || return
	$makeDir "$pp/Media/Other" || return
	$makeDir "$pp/Operating System/Other" || return
	[[ $client ]] && { $makeDir "$pp/Games/Other" || return; }

	$makeDir "$_sys/temp" || return
	$makeDir "$pdata/doc" || return
	$makeDir "$pdata/log" || return
	$makeDir "$pdoc/drop" || return
}

core()
{
	printf "**************************************************\n* Core\n**************************************************\n"
	i SysInternals WindowsSetup || return

	local common="DropBox EverNote Sonos Chrome BrowserHomePage"
	case "$COMPUTERNAME" in
		oversoul) i $common pGina ssh office365 nVidia LastPass DevCore iCloud iExplorer || return;;
		minime) i $common pGina ssh MiniMe TrueImage office365 LastPass iCloud || return;;
		jjbutare-mobl|jjbutare-mobl7|jjbutare-mobl9) 
			i $common OfficeFinal IntelCore CsisDeveloperCore || return
			[[ "$COMPUTERNAME" == @(jjbutare-mobl7) ]] && i iCloud || return;;
	esac
}

CygwinInstall()
{
	printf "**************************************************\n* Cygwin - POSIX environment for Windows\n**************************************************\n"
	local installDir="$P/Cygwin"

	echo "Update environment variables..."
	ScriptEval SetVar --system --path PATH "$installDir/bin" || return
	ScriptEval SetVar --system --path PATH "$_PublicBin" || return
	ScriptEval SetVar --system --path PATH "$_PublicBin/win" || return
	ScriptEval SetVar --path PATH "$_UserBin" || return
	ScriptEval SetVar --system CYGWIN "" || return # nodosfilewarning

	# cleanup
	cygwin cleanup || return

	# icons and registry
	if FindFile "Cygwin/setup"; then

		echo "Copying files..."
		cp "$file/Command Prompt.ico" "$installDir/etc" || return

		echo "Updating registry..."
		$registry import "$file/setup $architecture.reg" || return

	fi

	echo "Updating icons..."
	$makeShortcut "$installDir/bin/mintty.exe" "$pp/Operating System/bash" -a="-" || return
	$makeShortcut "$_PublicBin/run.sh" "$psm/Programs/Startup/startup" -a "startup" -d "Start applications" || return

	echo "Adding user..." # first user added when Cygwin installed, other users are not
	local user="$(mkpasswd -c)"
	! grep "^$(id -un)" /etc/passwd > /dev/null && { echo "$user" >> /etc/passwd || return; }
	
	# set home directory in /etc/passwd
	if grep ":/home" /etc/passwd > /dev/null; then
		echo "Updateing home directory locations..."
		local escapedUsers="${_data//\//\/}\/users"
		cp /etc/passwd /etc/passwd.bak || return
		sed 's/:\/home/:'"$escapedUsers"'/g' < /etc/passwd.bak > /etc/passwd || return
		HOME="$_data/users/$USERNAME"
	fi

	# Add group - domain user's group not in /etc/group by default
	echo "Adding user's group to /etc/group..."
	local group="$(mkgroup -c)"
	! grep "$group" /etc/group > /dev/null && echo "$group" >> /etc/group

	# Completion
	cygwin FixCompletion || return

	if [[ -d ~/.ssh ]]; then	
		echo "Configuring ssh..."
		# if issues: chgrp root ~/.ssh/*
		$hide ~/.ssh || return
		[[ -f ~/.ssh/id_dsa ]] && { chmod 700 ~/.ssh/id_dsa || return; }
		SshAgent startup || return
	fi

	echo "Cleaning up..."
	$rmd "/home"
}

BashInstall()
{
	printf "**************************************************\n* Bash - Bourne Again Shell\n**************************************************\n"

	printf "Configuring bash..."

	# home directory links
	local files=( .bashrc .bash_profile .bash_logout .dialogrc .kdiff3rc .lessfilter .inputrc .minttyrc )
	for file in "${files[@]}"; do
		$makeLink --symbolic --hide "$_UserBin/$file" "$_UserHome/$file" || return
	done

	# windows sytem home directory links (for Windows program that require Windows links, not a POSIX .lnk link)
	files=( .ExifTool_config  .gitconfig )
	for file in "${files[@]}"; do
		$makeLink --symbolic --hide --windows --absolute "$_UserBin/$file" "$_UserSysHome/$file" || return
		$makeLink --symbolic --hide --windows --absolute "$_UserBin/$file" "$_UserHome/$file" || return
	done
	
	files=( .bash_history .lesshst )
	for file in "${files[@]}"; do
		touch "$_UserHome/$file" || return
		$hide "$_UserHome/$file" || return
	done

	echo done
}

BashFinal()
{
	printf "**************************************************\n* Bash - Final Configuration\n**************************************************\n"

	if ask "Edit /etc/bash.bashrc"; then
		echo '- paste the text in the clipboard before "# If not running interactively, don'\''t do anything"'
		clipw $'# Global
[[ -d "/cygdrive/d/users" ]] && export USERS="/cygdrive/d/users" || export USERS="/cygdrive/c/users"
[[ -f "$USERS/Public/Documents/data/bin/bash.bashrc" ]] && . "$USERS/Public/Documents/data/bin/bash.bashrc"\n\n'
		TextEdit --wait "/etc/bash.bashrc" 
	fi
}

SshInstall()
{
	printf "**************************************************\n* SSH - Secure Shell\n**************************************************\n"
	
	sshHome="$uhome/.ssh"
	sshCloudHome="$_CloudDocuments/data/.ssh"

	echo Creating data directory...
	$makeDir "$sshHome" && $hide +h "$sshHome" || return

	echo "Updating firewall..."
	$firewall rule add "SSH" dir=in action=allow protocol=TCP localport=22 profile=private program="$(utw "$P/Cygwin/usr/sbin/sshd.exe")" || return

	echot "\
Configuring SSH...
- privilege separation=yes, new local account=yes, install sshd as a service=yes, 
  value of CYGWIN for the daemon=ntsec, use a diferent account name=no, 
  create privileged account=yes, password=<administrator>
- possible issue: service delete sshd; chmod -R 777 /var"
	ssh-host-config && service start sshd || return
	pause
}

IntelCore()
{
	printf "**************************************************\n* Intel Core\n**************************************************\n"
 
	echo "Installing Applications..."	
	i IntelApps IntelCleanup VisionApp || return
}

IntelApps()
{
	if ask 'Install VPN (AnyConnect)'; then
		start "$P32/Intel/Orion/AnyConnect.exe" /enroll || return
		pause
	fi

	if ask 'Install Backup (CNB)'; then
		cmd /c 'C:\APPS\CNB\InstallCNB.bat' || return
		echo '- Andvanced Options, check New CNB Account Installation'
		pause
	fi

	if ask 'Install Conference Room Scheduler (CRS)'; then
		cmd /c 'C:\Apps\CRS\Install_CRS.bat' || return
		echo '- Andvanced Options, check New CNB Account Installation'
		pause
	fi

	if ask 'Install Intel Software Market'; then
		ShellRun 'http://iss.intel.com/ProductInfo/TabProductInfo.asp?Product=12747&CanInstall=0'
		pause
	fi

	if ask 'Install Windows 8 Tips'; then
		ShellRun 'http://iss.intel.com/issasp/passthru/tabpassthrustart.asp?ProductNumber=12797 '
		pause
	fi

	if ask 'Install Virtual IT Service Center'; then
		echot '- Win, Virtual IT Service Center, Pin to Start'
		pause
	fi
}

IntelCleanup()
{
	ask 'Cleanup icons' && { IntelIcons || return; }

	if ask 'Cleanup programs (close Outlook if hangs)'; then
		printf "Uninstalling..."
	 	printf "WinZip 15.5..."; product uninstall {CD95F661-A5C4-44F5-A6AA-ECDD91C240C3} > /dev/null
	 	printf "WinZip 17.5..."; product uninstall {CD95F661-A5C4-44F5-A6AA-ECDD91C240DB} > /dev/null
	 	printf "Adobe Reader 9.5.4..."; product uninstall {AC76BA86-7AD7-1033-7B44-A95000000001} > /dev/null
	 	echo done
	fi

	if ask 'Cleanup file system'; then
		$rmd "$_sys/Drivers" "$_sys/Flash11" \
			"$_sys/PreDelivery_Automation" "$uhome/Roaming" "$udoc/Add-in Express" || return
		$rm "$_sys/build.ini" "$_sys/Regionalization.xml"
		$hide "$_sys/APPS" "$_sys/Quarantine" "$_sys/Intel" "$_sys/OpalStatus.efi"				
	fi

	if ask 'Cleanup startup programs'; then
		$registry 32 delete "run/AgentUiRunKey" # "C:\Program Files (x86)\Autonomy\Connected BackupPC\Agent.exe" -ni -sss -e http://localhost:16386/
		$registry 32 delete "run/McAfeeUpdaterUI"
		$registry 32 delete "run/ShStatEXE"
		$registry 32 delete "run/SunJavaUpdateSched"
		$registry 32 delete "run/Cisco AnyConnect Secure Mobility Agent for Windows" # "C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpnui.exe" -autolaunched
		$registry delete "run/ErmTray" # "C:/Program Files/Intel/Security/ERM/Win64/ErmTray.exe"
		$registry delete "run/McAfee Host Intrusion Prevention Tray" # C:/Program Files/McAfee/Host Intrusion Prevention/FireTray.exe
		$registry delete "urun/test"
		$rm "$up/Startup/Send to OneNote.lnk" || return
	fi
}

IntelIcons()
{
	printf "Updating Intel icons..."
	! intel IsIntelHost && return 0

	local d="$pp/Operating System/Other/Intel"; $makeDir "$d/Other" || return
	$mergeDir --rename "$pp/Intel" "$d" || return
	$mergeDir --rename "$up/Intel" "$d" || return

	$rm "$pd/AddaPrinter.lnk" || return
	$rm "$pp/Adobe Reader 9.lnk" || return
	$rm "$pd/Adobe Reader 9.lnk" || return
	$rm "$pd/AnyConnect"*.lnk || return
	$rm "$pd/Connected BackupPC.lnk" || return
	$rm "$pd/Intel Security Checker.lnk" || return
	$rm "$pd/Intel Software Market.lnk" || return
	$rm "$pp/Intel Software Market.lnk" || return
	$rm "$ud/WiFi Health Advisor.lnk" || return

	$mergeDir "$pp/Autonomy" "$pp/Operating System/Other" || return
	$mergeDir "$up/Cisco" "$pp/Operating System/Other" || return
	$mergeDir "$pp/Cisco" "$pp/Operating System/Other" || return
	$mergeDir "$pp/Dolby" "$pp/Operating System/Other" || return
	$mergeDir "$pp/Intel PROSet Wireless" "$pp/Operating System/Other" || return
	$mergeDir "$pp/Intel Software Market" "$pp/Operating System/Other" || return
	$mergeDir "$pp/McAfee" "$pp/Operating System/Other" || return
	$mergeDir "$pp/ThinkVantage" "$pp/Operating System/Other" || return

	$mv "$pd/AnyConnect User Guide 3_1.lnk" "$pp/Operating System/Other/Cisco/Cisco AnyConnect Secure Mobility Client" || return
	$mv "$pd/AnyConnect_Health_Check_Tool.lnk" "$pp/Operating System/Other/Cisco/Cisco AnyConnect Secure Mobility Client" || return
	$mv "$pd/Install CNB - Client Network Backup.lnk" "$pp/Operating System/Other/Intel" || return
	$mv "$pd/Install Conference Room Scheduler.lnk" "$pp/Operating System/Other/Intel" || return
	$mv "$pd/Intel SSD Encryption.lnk" "$pp/Operating System/Other/Intel"
	$mv "$up/McAfee HIP Messages.lnk" "$pp/Operating System/Other/McAfee" || return
	$mv "$up/McAfee VirusScan Scan Messages.lnk" "$pp/Operating System/Other/McAfee" || return
	$mv "$pd/Pre Delivery Automation.lnk" "$pp/Operating System/Other/Intel" || return
	$mv "$pp/SRS Premium Sound.lnk" "$pp/Operating System" || return
	$mv "$pd/Windows 8 Training.lnk" "$pp/Operating System/Other/Intel" || return
	$mv "$psm/Intel Security Checker.lnk" "$pp/Operating System/Other/Intel" || return

	echo "done"
	return
}

DevCore()
{
	printf "**************************************************\n* Development Core\n**************************************************\n"
	
	echo "Creating directories..."
	$makeDir "$_userDocuments/code/test" || return
	$makeDir "$_Code/test" || return
	
	echo "Updating icons..."
	$makeShortcut "$_Code" "$pp/Development/Code" || return

	echo "Moving data folders..."
	$makeLink --merge --hide "$udoc/code/web/sites" "$udoc/My Web Sites" || return
	$makeLink --merge --hide "$udata/LINQPad" "$udoc/LINQPad Queries" || return

	ask "\nInstall GIT core" && { i GitExtensions TortoiseGit || return; }
	ask "\nInstall SQL Development core" && { i iis SqlServer SqlPrompt || return; }
	ask "\nInstall .NET Development core" && { DotNetDevCore || return; }
	ask "\nInstall JAVA Development core" && { JavaDevCore || return; }
	return 0
}

DotNetDevCore() 
{
	printf "**************************************************\n* .NET Development Core\n**************************************************\n"

	echo "Creating directories..."
	$makeDir "$pp/Development/.NET/Other"

	echo "Installing Applications..."	
	i VisualStudio NUnit ReSharper || return
}

CsisDeveloperInstall()
{
	printf "**************************************************\n* Intel Development Core\n**************************************************\n"

	i DevCore || return

	$makeDir "$pp/Development/CSIS" || return

	if ask "Install Intel Profile Manager"; then
		run "Intel/Profile Manager/ITBAS.zip" "$P/ITBAS" || return

		FindFile "Intel/Profile Manager/ProfileManager.xml" || return
		$cp	"$file" "$WINDIR/system32" || return
		chmod 744 "$WINDIR/system32/ProfileManager.xml" || return
		$makeDir "$_sys/winnt/system32" || return 
		$hide "/cygdrive/c/winnt" || return
		$cp "$file" "$_sys/winnt/system32" || return
		chmod 744 "$_sys/winnt/system32/ProfileManager.xml" || return
		MakeShortcut "/cygdrive/c/Program Files/ITBAS/ProfileManager/ProfileManager.exe" \
			"$pp/Development/CSIS/Profile Manager" || return
	fi

	if ask "Install Antidote"; then
		run "Intel/Antidote/setup/Antidote.zip" "$P/Antidote" || return
		MakeShortcut "mintty" "$pp/Development/CSIS/Antidote" \
			-a="/c \"$(utw "$P/Antidote/antidote.exe")\" & pause" || return
	fi

	if ask "Update machine.config"; then
		clipw '<appSettings><add key="Environment" value="Development" /></appSettings>'
		echo "- After </configSections> paste the text in the clipboard"
		DotNet 4 MachineConfig || return
		pause
	fi

	i TortoiseSvn CruiseControlTray SilverlightSdk || return

	if ask "Configure SVN source server certificate and credentails"; then
		echo "- Accept the certificate permanently"
		echo "- Authentication, Username=USERNAME, Password=PASSWORD, check Save authentication"
		code --svn --gui clone CSIS || return
	fi
	
	if ask "Setup shared projects"; then
		code clone IntelNuGet || return
		code --svn clone Antidote Errgo Magellan || return

		echo "Configuring Antidote..."
		MakeShortcut "mintty" "$pp/Development/CSIS/Antidote Local Build" \
			-a="--hold=error antidote verbose App=Antidote BuildType=LocalBuild" || return
 		chgrp root "$CODE/Antidote/unversioned/SqlData" || return; chmod 777 "$CODE/Antidote/unversioned/SqlData"
		antidote verbose App=Antidote BuildType=LocalBuild || return

		echo "Configuring Magellan..."
		MakeShortcut "mintty" "$pp/Development/CSIS/Magellan Local Build" 
			-a="--hold=error run.sh sudo antidote verbose App=Magellan BuildType=LocalBuild CacheBrokerAddress=@DatabaseServer@" || return
		chgrp root "$CODE/Magellan/unversioned/SqlData" || return; chmod 777 "$CODE/Magellan/unversioned/SqlData"
		antidote verbose App=Magellan BuildType=LocalBuild CacheBrokerAddress=@DatabaseServer@ || return

	fi

	if ask "Setup applications"; then
		applications=( RPIAD ScadaPortal )
		for app in "${applications[@]}"; do 
			if ask "Setup $app"; then
				case $app in
					RPIAD) chmod 777 "$CODE/RPIAD/SQLData" || return;;
				esac
				code --svn clone "$app" || return
				MakeShortcut "mintty" "$pp/Development/CSIS/$app Local Build" \
					-a="--hold=error run.sh sudo antidote verbose App=$app BuildType=LocalBuild" || return
				antidote verbose App=$app BuildType=LocalBuild || return
			fi
		done
	fi

}

JavaDevCore()
{
	printf "**************************************************\n* JAVA Development Core\n**************************************************\n"
}

WinampInstall()
{
	printf "**************************************************\n* Winamp\n**************************************************\n"
	
	run "Nullsoft/WinAmp/setup/winamp565_pro_all.exe" || return

	echo "Updating icons..."
	$mergeDir "$pp/Winamp" "$ao" || return
	$mergeDir --rename "$up/Winamp Detector Plug-in" "$ao/Winamp" || return
	$rm "$pd/Winamp.lnk" || return

	echot "Note
- WiFi Sync - disable addition network interfaces (i.e. VMware networks), run WinAmp as Administrator"
}

ahk() { AutoHotKeyInstall; }
AutoHotKeyInstall()
{
	printf "**************************************************\n* AutoHotKey\n**************************************************\n"
	echo "- Express installation"

	AutoHotKey close

	# http://l.autohotkey.net/ http://www.autohotkey.com/download/ http://l.autohotkey.net/docs/AHKL_ChangeLog.htm
	run "AutoHotKey/setup/AutoHotkey v1.1.13.00.exe" || return

	echo "Updating icons..."
	$mergeDir "$pp/AutoHotKey" "$pp/Operating System/Other" || return
	
	echo "Updating registry..."
	FindFile "AutoHotKey" || return
	$registry import "$file/setup/other/AutoHotkey-$architecture.reg" || return

	sudo --standard AutoHotKey startup
}

WinSplitInstall()
{
	printf "**************************************************\n* WinSplit\n**************************************************\n"
	run "Shareware/WinSplit Revolution/image.zip" "$P32/WinSplit Revolution" || return
	WinSplit startup
}

SublimeInstall()
{
	# packages: PackageControl (https://sublime.wbond.net/installation)
	printf "**************************************************\n* Sublime Text Editor\n**************************************************\n"
	echo "- Check add to explorer context menu"

	run "Sublime/setup/Sublime Text Build 3047 x64 Setup.exe" || return # http://www.sublimetext.com/3dev
	
	echo "Updating registry..."	
	registry delete "HKEY_CLASSES_ROOT/Applications/sublime_text.exe/" # Fix Windows Open With

	echo "Updating icons..."
	$mv "$pp/Sublime Text 2.lnk" "$pp/Applications" || return
	$mv "$pp/Sublime Text 3.lnk" "$pp/Applications" || return

	$makeDir "$udata/Sublime Text" || return
	$makeDir "$_ApplicationData/Sublime Text 3" || return
	sublime profile restore default || return
}

ReSharperInstall()
{
	printf "**************************************************\n* ReSharper\n**************************************************\n"
	
	# download: http://www.jetbrains.com/resharper/download/index.html http://www.jetbrains.com/resharper/download/index.html, http://confluence.jetbrains.net/display/ReSharper/ReSharper+8.0+Nightly+Builds
	# what's new: http://www.jetbrains.com/resharper/whatsnew/
	# cleanup: $LocalAppData$/JetBrains/ReSharper/v7.1/SolutionCaches
	run "JetBrains/ReSharper/setup/ReSharperSetup.8.0.2000.2660.msi" || return

	ReSharper profile restore default || return

	echot "\
	- Select ReSharper Shortcuts Scheme, ReSharper 2.x and IntelliJ IDEA
	- ReSharper, Options
		- Keyboards & Menus, ReSharper keyboard scheme=ReSharper 2.x or IntelliJ IDEA, Apply Scheme
		- Environment, Editor, Editor Behavior, uncheck Use CamelHumps
		- Environment, IntelliSense
			- Autopopup, C#, Where value is expected, Do not display
			- Completion Appearance, check Show Member Signatures and Show Summary
		- Code Editing, Code Cleanup, Add, default
			- Check all
			- C#, Use 'var' in declaration, Can Change/Always use/Always use
		- Tools, Unit Testing
			- Uncheck Save and restore Unit Test Sessions
			- Uncheck Wrap long lines in Unit Test Session output
			- Run up to 4 assemblies in parallel"
	sudo --standard VisualStudio start
	pause
}

ConsoleInstall()
{
	printf "**************************************************\n* Console \n**************************************************\n"

	key="HKCU/Console"

	echo "Setting console defaults..."

	registry set "$key/QuickEditMode" REG_DWORD 1 || return
	registry set "$key/QuickEdit" REG_DWORD 1 || return

	# foreground text: bright white=31 (255, 255, 255), white=23 (192,192,192)
	registry set "$key/ScreenColors" REG_DWORD 7 || return

	# Screen Background: black=0 (0,0,0), blue=8388608 (or 0, 0, 128)
	# Black does not flicker when large amounts of text are displayed (for example when do dir bin:)
	registry set "$key/ColorTable01" REG_DWORD 0 || return

	registry set "$key/ColorTable11" REG_DWORD 16776960 || return
	registry set "$key/ColorTable15" REG_DWORD 16777215 || return

	# Font
	registry set "$key/FaceName" REG_SZ "Lucida Console" || return
	registry set "$key/FontFamily" REG_DWORD 54 || return
	registry set "$key/FontSize" REG_DWORD 1048586 || return
	registry set "$key/FontWeight" REG_DWORD 400 || return

	# Screen 165x29 (1680x1050)
	registry set "$key/ScreenBufferSize" REG_DWORD 19660964 || return
	registry set "$key/WindowSize" REG_DWORD 1835172 || return
}

WindowsSetup()
{
	printf "**************************************************\n* Windows Setup\n**************************************************\n"

	WindowsIcons || return

	echo "Cleaning file system..."
	$rmd "$_sys/PerfLogs" || return

	echo "Moving data folders..."
	$makeLink --merge "$udata/download" "$uhome/Downloads" || return
	[[ -d "$udoc/Fax" ]] && $makeLink --merge --hide "$udata/fax" "$udoc/Fax"
	[[ -d "$udoc/My Data Sources" ]] && $makeLink --merge --hide "$udata/Data Sources" "$udoc/My Data Sources"
	[[ -d "$udoc/Scanned Documents" ]] && $makeLink --merge --hide "$udata/scans" "$udoc/Scanned Documents"
}

WindowsIcons()
{
	echo "Updating icons..."

	$mv "$pp/Desktop.lnk" "$pp/Applications" || return
	$mv "$up/Internet Explorer.lnk" "$pp/Applications" || return
	$mergeDir "$up/Accessories" "$pp/Applications" || return
	$mergeDir "$pp/Accessories" "$pp/Applications" || return
	$mergeDir "$up/Accessibility" "$pp/Applications/Accessories" || return
	$mergeDir "$pp/Accessibility" "$pp/Applications/Accessories" || return
	$mv "$pp/Camera.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/Immersive Control Panel.lnk" "$pp/Applications/Accessories" || return
	$mv "$up/Immersive Control Panel.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/Bing Desktop/Bing Desktop.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/PhotosApp.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/Search.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/FileManager.lnk" "$pp/Applications/Accessories" || return
	$mv "$up/SkyDrive.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/Windows Store.lnk" "$pp/Applications/Accessories" || return
	$mv "$pp/Windows Media Player.lnk" "$pp/Applications/Accessories" || return
	
	$mergeDir --rename "$pp/Microsoft Mouse and Keyboard Center" "$pp/Operating System/Mouse and Keyboard Center"|| return
	$mergeDir "$up/Maintenance" "$pp/Operating System"|| return
	$mergeDir "$pp/Maintenance" "$pp/Operating System"|| return
	$mergeDir "$up/System Tools" "$pp/Operating System" || return
	$mergeDir "$pp/System Tools" "$pp/Operating System" || return
	$mergeDir "$pp/Microsoft Silverlight" "$pp/Operating System/Other" || return
	$mergeDir "$pp/Applications/Accessories/System Tools" "$pp/Operating System" || return
	$mergeDir "$pp/Administrative Tools" "$pp/Operating System" || return

	$mergeDir "$pp/IIS" "$pp/Development/Other/IIS" || return

	local dest="$pp/Games/Other/Microsoft"; $makeDir "$dest" || return
	$mv "$pp/Games/Chess.lnk" "$dest" || return
	$mv "$pp/Games/FreeCell.lnk" "$dest" || return
	$mv "$pp/Games/Hearts.lnk" "$dest" || return
	$mv "$pp/Games/InkBall.lnk" "$dest" || return
	$mv "$pp/Games/Minesweeper.lnk" "$dest" || return
	$mv "$pp/Games/PurblePlace.lnk" "$dest" || return
	$mv "$pp/Games/Spider Solitaire.lnk" "$dest" || return
	$mv "$pp/Games/Hold 'Em.lnk" "$dest" || return
	$mv "$pp/Games/Mahjong.lnk" "$dest" || return
	$mv "$pp/Games/Solitaire.lnk" "$dest" || return

	$hideAndSystem "$pp/Applications/Accessories/Desktop.ini" || return
	$hideAndSystem "$pp/Applications/Accessories/Accessibility/Desktop.ini" || return
	$hideAndSystem "$pp/Applications/Accessories/Tablet PC/Desktop.ini" || return
}

MiniMe()
{
	if ask 'Cleanup programs'; then
		printf "Uninstalling..."
		printf "Absolute Reminder..."; product uninstall {40F4FF7A-B214-4453-B973-080B09CED019} > /dev/null
		printf "Dolby Home Theater..."; product uninstall {B26438B4-BF51-49C3-9567-7F14A5E40CB9} > /dev/null
	 	printf "Nitro Pro..."; product uninstall {34BE77EE-B563-49D7-A8A0-FFD76D29BBD3} > /dev/null
	 	printf "UserGuide..."; product uninstall {{F07C2CF8-4C53-4EC3-8162-A6221E36EB88} > /dev/null
	 	echo done
	fi

	if ask 'Cleanup file system'; then
		$rmd "$_sys/Intel" "$_sys/UserGuidePDF" "$_sys/Windows.old" "$_sys/\$Windows.~BT" "$P32/Nuance" || return
	fi

	if ask 'Cleanup icons'; then
		$mergeDir "$pp/Intel" "$pp/Operating System/Other" || return
		$ren "$pp/Intel AppUp(SM) center/Intel AppUp(SM) center.lnk" "$pp/Operating System/Other/Intel/AppUp Center.lnk" || return
		$rmd "$pp/Intel AppUp(SM) center"
		$mergeDir "$pp/Lenovo" "$pp/Applications/Other" || return
		$mergeDir "$pp/OneKey Recovery" "$pp/Operating System/Other" || return
		$rm "$pd/OneKey Recovery.lnk" || return
	fi

	if ask 'Cleanup registry'; then
		$registry 32 delete "run/Intel AppUp(SM) center" # ""C:\Program Files (x86)\Intel\IntelAppStore\bin\ismagent.exe" --domain-id F0399437-FD0C-4A48-B101-F0314A6172E4"
		$registry 32 delete "run/mcui_exe" # "C:\Program Files\McAfee.com\Agent\mcagent.exe" /runkey
		$registry 32 delete "run/YouCam Tray" # "C:\Program Files (x86)\Lenovo\YouCam\YouCamTray.exe" /s
	fi
}

pGinaInstall()
{
	printf "**************************************************\n* pGina\n**************************************************\n"
	
	IsInDomain && return 0
	
	# http://pgina.org/download.html
	run "Microsoft/Visual Studio/redistributable/vcredist_x86.exe" || return # /silent
	run "Microsoft/Visual Studio/redistributable/vcredist_x64.exe" || return # /silent
	run "Shareware/pGina/setup/pGinaSetup-3.1.8.0.exe" /silent || return

	echo "Updating icons..."
	$mergeDir "$pp/pGina" "$pp/Operating System/Other" || return

	pGina profile restore default || return
}

DropBoxInstall()
# https://www.dropbox.com/install
{
	printf "**************************************************\n* DropBox\n**************************************************\n"
	echo "- (new install) Ensure $(utw "$_CloudDocuments") directory is empty"
	echo "- I already have a Dropbox account"
	echo "- Advanced, I want to choose where to put my Dropbox=$(utw "$_UserHome")"
	
	run "Dropbox/setup/Dropbox 2.4.6.exe" --standard || return

	echo "Updating icons..."
	# Keep icons in user programs or else may run incorrect version that another user has installed
	$makeDir "$up/Operating System/Other" || return
	$mergeDir "$up/Dropbox" "$up/Operating System/Other" || return
	$rm "$up/Startup/Dropbox.lnk" || return
	$rm "$ud/Dropbox.lnk" || return

	if [[ "$_data" != "/cygdrive/c" ]]; then
		$makeShortcut "$_UserHome/Dropbox" "$_UserSysHome/Dropbox.lnk" || return
	fi;

	if ask "Do you want to update index locations"; then
		DropBox close

		dir="$_CloudDocuments/.dropbox.cache"
		$makeDir  "$dir" || return
		attrib -s -h "$(utw "$dir")" || return

		echo "- Modify, $(utw "$_CloudDocuments"), check Dropbox, uncheck .dropbox.cache"
		os index options || return
		pause

		attrib +s +h "$(utw "$dir")"

		sudo --standard DropBox startup
	fi

	utw "$_CloudDocuments" > /dev/clipboard
	echot "\
- Preferences...
  - General
    - Uncheck Show desktop notifications
    - Uncheck Start Dropbox on system startup
  - (Intel) Proxies
    - Select Manual
    - Server=proxy.fm.intel.com
    - Port=911
- Explorer
  - Libraries, Documents, locations, 
    - Add..., <paste>
    - (not Intel) Move Up (to top), Set as default save location
  - View, List"
	start explorer "$udoc"
	pause

}

vs() { vs13; }; VisualStudioInstall() { vs13; }; 
vs13() 
{ 
	printf "**************************************************\n* Visual Studio 2012\n**************************************************\n"
	echo "- (optional) Uncheck Microsoft Foundation Classes for C++ (1.4 GB)"
	echo "- uncheck Tools for Maintaining Store apps for Windows 8 and Windows Phone 8.0 SDK"

	vs="Microsoft/Visual Studio"

	if [[ "$USERNAME" == @(jjbutare|ad_jjbutare) ]] || ask -dr n 'Install Ultimate (requires MSDN license)'; then
		run "$vs/setup/vs/en_visual_studio_ultimate_2013_x86_dvd_3009107.iso" || return
	else
		run "$vs/setup/vs/en_visual_studio_professional_2013_x86_dvd_3009197.iso" || return
	fi
	
	run "$vs/setup/other/en_visual_studio_2013_sdk_x86_3009047.exe" || return

	# extensions
	#run "$vs/extension/NuGet.Tools.2013.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca
	run "$vs/extension/NUnitVisualStudioTestAdapter-1.0.vsix" || return # requires ReSharper disabled, https://launchpad.net/nunit-vs-adapter/+download, http://visualstudiogallery.msdn.microsoft.com/6ab922d0-21c0-4f06-ab5f-4ecd1fe7175d?SRC=VSIDE
	run "$vs/extension/WebEssentials2013.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361

	VsFinal || return
}

vs12()
{
	local vs="Microsoft/Visual Studio"
	printf "**************************************************\n* Visual Studio 2012\n**************************************************\n"
	echo "- (optional) Uncheck Microsoft Foundation Classes for C++ (1.4 GB)"

	run "$vs/setup/vs/en_visual_studio_ultimate_2012_x86_dvd_920947.iso" || return # path: $P32/Windows Kits/8.1/Windows Performance Toolkit;
	run "$vs/update/VS2012.3.exe" || return
	run "$vs/setup/other/en_visual_studio_2012_sdk_x86_920808.exe" || return
	run "$vs/setup/ssdt/image/SSDTSetup.exe" || return # http://www.microsoft.com/en-us/download/details.aspx?id=29062
	run "$vs/setup/other/Microsoft.TeamFoundation.Git.Provider.msi" || return # http://visualstudiogallery.msdn.microsoft.com/abafc7d6-dcaa-40f4-8a5e-d6724bdb980c

	run "$vs/extension/ProPowerTools.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/3a96a4dc-ba9c-4589-92c5-640e07332afd
	run "$vs/extension/NuGet.Tools.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/27077b70-9dad-4c64-adcf-c7cf6bc9970c
	run "$vs/extension/WebEssentials.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/07d54d12-7133-4e15-becb-6f451ea3bea6
	run "$vs/extension/WinLibJS_VSE.exe" || return

	VsFinal || return
}

VsFinal()
{
	IisExpressFinal || return
	ScriptEval VisualStudio init || return

	echo "Creating directories..."
	$makeDir "$_Code/test/vs$vsName"
	
	if ask "Initialize Visual Studio"; then
		echo "- (optional) Sign In, <Microsoft Live account>"
		echo "- Choose your default environment settings=Visual C# Development Settings"
		echo "- Development Settings=Visual C#"
		echo "- Close Visual Studio"
		VisualStudio start; pause
	fi

	echo "Moving data folders..."
	$makeLink --merge --hide "$vsData" "$udoc/Visual Studio $vsName" || return
	$makeLink --merge --hide "$udata/Web Essentials" "$uhome/Web Essentials" || return

	ask "Update registry" && { VsRegistry || return; }
	ask "Update icons" && { VsIcons || return; }
	ask "Restore profile" && { VisualStudio profile restore default; return; }

	echot "\
Tools, Options...
- Environment
	- Documents
	  - check Auto-load changes, if saved
	  - uncheck Check for consistent line endings on load
	  - Tabs and Windows
	  	- check Insert new tabs to the right of existing tabs
	  	- check Show pinned tabs in a separate row
- Environment, Keyboard 
  - ctrl-shift-c = View.SynchronizeClassView
- Text Editor, C#
  - General: check Line numbers
  - Tabs: Tab size=3, Indent size=3, Keep tabs"
	VisualStudio start; pause

}

VsRegistry()
{
	echo "Updating Visual Studio registry..."
	ScriptEval VisualStudio init || return
	local r="$vsRegistryKey" c="$(utw "$code")"
	
	$registry 32 set "$r/DefaultFileOpenLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/DefaultNewProjectLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/DefaultNewProjItemLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/DefaultOpenProjectLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/DefaultOpenProjItemLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/DefaultOpenSolutionLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/VisualStudioProjectsLocation" REG_EXPAND_SZ "$c" || return
	$registry 32 set "$r/UserProjectTemplatesLocation" REG_EXPAND_SZ "$(utw "$vsData/Templates/ProjectTemplates")" || return
	$registry 32 set "$r/UserItemTemplatesLocation" REG_EXPAND_SZ "$(utw "$vsData/Templates/ItemTemplates")" || return
	$registry 32 set "$r/VisualStudioLocation" REG_EXPAND_SZ "$(utw "$vsData")" || return
}

VsIcons()
{
	echo "Updating Visual Studio icons..."
	ScriptEval VisualStudio init || return
	local base="$pp/Development/.NET"; local other="$base/Other"; local vs="$other/Visual Studio $vsName"

	$makeDir "$other" || return
	$makeShortcut "$_windows/assembly" "$base/GAC.lnk" || return

	# 2013
	$mergeDir --rename "$pp/Visual Studio $vsName" "$other/Visual Studio $vsName" || return
	$mergeDir "$pp/Hyper-V Management Tools" "$pp/Development/other" || return
	$mergeDir "$pp/Windows Phone SDK 8.0" "$vs" || return
	$mergeDir "$pp/Windows Kits" "$pp/Development/other" || return
	 
	# 2012
	$mergeDir --rename "$pp/Microsoft Visual Studio 2012" "$other/Visual Studio 2012" || return
	$mergeDir --rename "$pp/Microsoft Visual Studio $vsName" "$other/Visual Studio $vsName" || return
	$mergeDir --rename "$pp/Microsoft Windows SDK Tools" "$vs/Windows SDK Tools" || return
	$mergeDir --rename "$pp/Microsoft Visual Studio $vsName SDK" "$vs/sdk" || return

	# other
	for f in "$vs/Microsoft"*.lnk; do $ren "$f" "${f/\/Microsoft //}" || return; done
	$cp "$vs/Visual Studio $vsName.lnk" "$base" || return
	$mergeDir "$pp/Windows Kits" "$vs" || return
	$ren "$pp/Microsoft Web Platform Installer.lnk" "$pp/Development/.NET/Web Platform Installer.lnk" || return
	$ren "$pp/SQL Server Data Tools 2012.lnk" "$base/SQL Server Data Tools.lnk" || return

	SilverlightIcons || return
	ExpressionIcons || return
}

ExpressionIcons()
{
	local base="$pp/Development/Other/Expression"; $makeDir "$base"
	$mergeDir --rename "$pp/Microsoft Expression" "$base"
	$mergeDir --rename "$ud/Expression" "$ud/code/web"
	$mergeDir --rename "$base/Microsoft Expression Blend SDK" "$base/Expression Blend SDK"
	$ren "$ud/Expression/Expression Design/Samples 2.lnk" "$base/Design Samples.lnk"
	$ren "$base/Microsoft Expression Encoder 4 Screen Capture.lnk" "$base/Expression Encoder Screen Capture.lnk"
	$ren "$base/Microsoft Expression Encoder 4 SDK.lnk" "$base/Expression Encoder SDK.lnk"
	$ren "$base/Microsoft Expression Web 4 SuperPreview.lnk" "$base/Expression Web SuperPreview.lnk"
	for file in "$base/Microsoft Expression"*4.lnk; do $ren "$f" "${f/\/Microsoft //}"; done
}

IisExpressFinal()
{
	echo "Moving IIS Express data folders..."
	$makeLink --merge --hide "$udata/IISExpress" "$udoc/IISExpress"
	$mergeDir "$udoc/My Web Sites" "$udoc/code/web"
}

VirtualCloneDriveInstall()
{
	printf "**************************************************\n* Virtual Clone Drive\n**************************************************\n"

	# download: http://www.slysoft.com/en/download.html
	# installs:
	# - ElbyDelay drive LowerFilter
	# - VirtualCloneDrive vcddaemon in Startup
	# - VirtualCloneDrive CloseTray shell extension (elbyvcdshell.dll)
	# - Drivers: ElbyCDIO, ElbyDelay, VClone
	run "SlySoft/CloneDrive/SetupVirtualCloneDrive5460.exe" || return

	echo "Updating icons..."
	$mergeDir "$pp/Elaborate Bytes" "$pp/Operating System/Other" || return
	$rm "$pd/Virtual CloneDrive.lnk" || return

	echot "\
- Settings
  - Number of Drives=2
  - Check Virtual Sheep
  - Uncheck Show Tray Icon"
	iso gui || return
	pause 
}

BcInstall() { BeyondCompareInstall; }
BeyondCompareInstall()
{
	printf "**************************************************\n* BeyondCompare\n**************************************************\n"
	echo "- Uncheck Launch Beyond Compare 3"

	# download: http://www.scootersoftware.com/download.php
	# plugins: http://www.scootersoftware.com/download.php?zz=kb_moreformats&cartid=482293831
	# license: http://www.scootersoftware.com/support.php?zz=kb_netsetup
	run "Scooter Software/Beyond Compare/setup/BCompare-3.3.8.16340.exe" || return
	run "Scooter Software/Beyond Compare/plugins/AllPlugins.exe" || return

	echo "Updating icons..."
	$mergeDir "$up/Beyond Compare" "$pp/Applications/Other" || return
	$mergeDir "$pp/Beyond Compare" "$pp/Applications/Other" || return
	$rm "$ud/Beyond Compare 3.lnk" || return
	$rm "$pd/Beyond Compare 3.lnk" || return

	echo "- Enter Key..., check Register for all users"
	BeyondCompare start
	pause

	BeyondCompare profile restore default || return
}

EverNoteInstall()
{
	printf "**************************************************\n* EverNote\n**************************************************\n"
	
	# http://www.evernote.com/about/download/windows.php?file=Win&btn=grey
	run "EverNote/setup/Evernote_5.0.3.1614.exe" || return

	echot "\
- View, Left Panel, uncheck Show Left Panel
- Tools, Options
  - General 
    - Uncheck Autoamtically check for updates
    - Uncheck Show advertisements
  - Sync
    - Uncheck Enable sync notifications
    - Check Synronize automatically Every 15 minutes
  - Note, Note editor font=Arial 10"
  pause

	EverNote close || return
	sudo --standard EverNote startup || return

	echo "Updating icons..."
	$mergeDir "$pp/Evernote" "$ao" || return
	$rm "$pd/Evernote.lnk" || return
	$rm "$ud/Evernote.lnk" || return
	$rm "$pp/Startup/EvernoteClipper.lnk" || return
	$rm "$up/Startup/EvernoteClipper.lnk" || return
}

SonosInstall()
{
	printf "**************************************************\n* Sonos Music System\n**************************************************\n"
	
	run "Sonos/setup/SonosDesktopController42.exe" || return # http://sonos.com/support/

	echo "Updating icons..."
	$rm "$pd/Sonos.lnk" || return
	$mergeDir "$pp/Sonos" "$pp/Media/Other" || return

	if intel IsIntelHost; then
		echo "- McAfee Host Intrusion Prevention, Add, Name=Sonos, Application=C:\Program Files(x86)\Sonos\Sonos.exe"
		pause
	fi
}

nUnitInstall()
{
	local version="2.6.2"
	printf "**************************************************\n* NUnit\n**************************************************\n"
	echo "Choose Setup Type=Complete"

	# download: http://www.nunit.org/?p=download
	run "Shareware/.NET/NUnit/setup/NUnit-$version.msi" || return

	echo "Updating icons..."
	$mergeDir "$up/NUnit $version" "$pp/Development/.NET/Other"
}

SilverlightSdk()
{
	printf "**************************************************\n* Silverlight SDK\n**************************************************\n"

	# downloads  http://www.silverlight.net/downloads
	# 	Developer Runtime (debugging): http://go.microsoft.com/fwlink/?LinkID=229323
	#   toolkit (additonal controls): http://silverlight.codeplex.com/ http://silverlight.codeplex.com/releases/view/78435
	#   SDK: http://www.microsoft.com/en-us/download/details.aspx?id=28359
	#   tools (developer runtime, SDK, Visual Studio 2010 support): http://www.microsoft.com/en-us/download/details.aspx?id=28358
	# version: http://www.microsoft.com/getsilverlight/Get-Started/Install/Default.aspx
	#run "Microsoft/.NET/Silverlight/development/silverlight_sdk.exe"
	run "Microsoft/.NET/Silverlight/development/Silverlight_Developer_${architecture}.exe"
	run "Microsoft/.NET/Silverlight/development/Silverlight_5_Toolkit_December_2011.msi"

	SilverlightIcons || return
}

SilverlightIcons()
{
	local base="$pp/Development/.NET/Silverlight"; $makeDir "$base"
	$ren "$pp/Microsoft Silverlight/Microsoft Silverlight.lnk" "$pp/Applications/Accessories/Silverlight.lnk"
	$ren "$pp/Microsoft Silverlight 4 SDK/Welcome.lnk" "$base/Silverlight 4 SDK Welcome.lnk"
	$ren "$pp/Microsoft Silverlight 5 SDK/Welcome.lnk" "$base/Silverlight 5 SDK Welcome.lnk"
	$mergeDir --rename "$pp/Microsoft Silverlight 5 Toolkit December 2011" "$base/Silverlight 5 Toolkit"
	$rmd "$pp/Microsoft Silverlight 4 SDK"
	$rmd "$pp/Microsoft Silverlight 5 SDK"
	$rmd "$pp/Microsoft Silverlight"
}

cctray() { CruiseControlTrayInstall; }
CruiseControlTrayInstall()
{
	local version="1.8.3.0"
	printf "**************************************************\n* CruiseControl Tray\n**************************************************\n"
	echo '- Uncheck Run CruiseControl.NET CCTray 1.8.3.0'	

	# download: http://vmspwbld001/ccnetpreprod/ViewFarmReport.aspx http://www.cruisecontrolnet.org/projects/cctray http://cruisecontrol.sourceforge.net http://ccnet.sourceforge.net/CCNET/CCTray.html
	run "Shareware/CruiseControl/tray/CruiseControl.NET-CCTray-$version-Setup.exe" || return

	echo "Updating icons..."
	$mergeDir "$pp/CCTray" "$pp/Development/Other" || return
	$mergeDir "$up/CCTray" "$pp/Development/Other" || return
	$rm "$ud/CCTray.lnk" || return
	$rm "$up/Startup/CCTray.lnk" || return

	CruiseControlTray profile restore default || return
	CruiseControlTray startup || return
}

ChromeInstall()
{
	printf "**************************************************\n* Google Chrome Browser\n**************************************************\n"
	echo '- Keep using Internet Explorer (to use Chrome on the desktop)'
	echo '- Sign in Email=NNN, Password=NNN'
	echo '- New Tab, Apps, Learn more, Get the launcher'

	# download: http://www.google.com/chrome/eula.html?system=true&standalone=1
	run "Google/Chrome/setup/ChromeStandaloneSetup.exe" || return

	echo "Updating icons..."
	$rm "$ud/Google Chrome.lnk"
	$rm "$pd/Google Chrome.lnk"
	$rm "$ud/Chrome App Launcher.lnk"
	$rm "$ud/Google Chrome Canary Build.lnk"
	$mergeDir --rename "$pp/Google Chrome" "$ao/Chrome"
	$mergeDir --rename "$up/Google Chrome" "$ao/Chrome"
	$mergeDir --rename "$up/Google Chrome Canary Build" "$ao/Chrome Beta"

	echot "\
- (for texting) Apps, Gmail Offline, select Allow offline mail
- Defer, Options, Default Service=Instapaper, Usrname=NNN, Password=NNN
- LastPass
	- (private computer) General, Security, uncheck Automatically Logoff
	- Notifications, uncheck Show Matching Sites Count in toolbar
- MightyText
- (optional) chrome://flags, enable features"
	ShellRun chrome || return
	pause
}

iisInstall()
{
	# - Add/Remove Windows Components requires inf files
	# - Remote Desktop Web Connection reference http://www.microsoft.com/windowsxp/using/networking/expert/northrup_03may16.mspx
	printf "**************************************************\n* IIS\n**************************************************\n"
  echo "- Internet Information Services, check all"
  echo "- (optional) Internet Information Services Hostable Web Core"
	
	product optional --wait || return

	if [[ $client ]] && ! intel IsIntelHost; then
	  echo "Updating firewall..."
	  $firewall rule enable "World Wide Web Services HTTP Traffic In"
	fi

	echo "Updating services..."
	service exist FTPSVC && { service manual FTPSVC || return; }

	if [[ $client ]] && ask "Set IIS services to run manually"; then
	  service exist IISADMIN && { service manual IISADMIN || return; }
	  service exist w3svc && { service manual w3svc || return; }
	  service exist AppHostSvc && { service manual AppHostSvc || return; }
	fi

	echo "Updating icons..."
	$makeDir "$pp/Development/Other/IIS" || return
	$mergeDir "$pp/IIS" "$pp/Development/Other" || return
	$makeShortcut "$WINDIR/system32/inetsrv/iis.msc" "$pp/Development/Other/IIS/IIS Client Manager" || return

	# [[ $client ]] && ask "Install remote manager" && { IisRemoteManager || return; }
	# ask "Configure WebDAV" --default n && { IisWebDav || return; }
	# ask "Configure FTP" --default n && { IisFtp || return; }
	# ask "Configure debugging" --default n && { IisDebugging || return; }
	# ask "Configure compression" --default n && { IisCompression || return; }
	# ask "Configure SSL" --default n && { IisSsl || return; }

	echo "Restarting IIS..."
	iisreset
}

IisCheck()
{ 
	if ! IsInstalled iis && ask "Do you want to install IIS"; then
		iisInstall; return
	fi
	return 0
}

ss() { SqlServerInstall; }; ss12() { SqlServerInstall; }
SqlServerInstall()
{
	local base="Microsoft/SQL Server"
	printf "**************************************************\n* SQL Server 2012\n**************************************************\n"
	
	echo; echo "Checking for IIS (required for reporting services)..."; IisCheck || return

	echot "\
Note: Logs are in \"$P/Microsoft SQL Server/110/Setup Bootstrap/Log\"
- Installation, New SQL installation or add features to an existing installation
- Setup Roles, All Features with Defaults
- Feature Selection
  - (light development+SQL Server Express, 6gb) Uncheck all Instance Features
  - (minimal development) Check only Database Engine Services, Client Tools Connectivity,
    Documentation Components, and Management Tools - Complete
  - (full development, 8gb) No changes
  - (server, 2gb) Uncheck all Shared Features
 - Instance Configuration
  - (optional) Named instance=MSSQLSERVER<version>
	- (optional) Instance root directory=d:\Program Files\Microsoft SQL Server\
- Database Engine Configuration
  - Authentication Mode=Mixed Mode, Enter password=XXX, Confirm password=XXX
  - Add..., Add Current User, (optional) Add..., Administrators
- Analysis Services Configuration
  - Add..., Add Current User, (optional) Add..., Administrators
- Distributed Replay Controller
  - Add..., Add Current User"

  # download: http://www.microsoft.com/en-us/sqlserver/editions/2012-editions/express.aspx
	# updates: http://support.microsoft.com/kb/2755533
	# installs:
	# - Path:
	#   c:/Program Files (x86)/Microsoft SQL Server/110/Tools/Binn/
	#   c:/Program Files/Microsoft SQL Server/110/Tools/Binn
	#   c:/Program Files/Microsoft SQL Server/110/DTS/Binn
	#   c:/Program Files (x86)/Microsoft SQL Server/110/Tools/Binn/VSShell/Common7/IDE
	#   c:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/PrivateAssemblies
	#   c:/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn/
  if [[ $client ]]; then
  	run "$base/setup/en_sql_server_2012_developer_edition_x86_x64_dvd_813280.iso" || return
	else
		run "$base/setup/en_sql_server_2012_enterprise_edition_x86_x64_dvd_813294.iso" || return
	fi

	# updates
	run "$base/update/SQLServer2012SP1-KB2674319-${architecture}-ENU.exe"

	# determine components were installed
	local clientTools; [[ -f "$P32/Microsoft SQL Server/110/Tools/Binn/ManagementStudio/Ssms.exe" ]] && clientTools="true"
	local database; [[ -f "$P/Microsoft SQL Server/MSSQL11.MSSQLSERVER/MSSQL/Binn/sqlservr.exe" ||
		-f "d:/Program Files/Microsoft SQL Server/MSSQL11.MSSQLSERVER/MSSQL/Binn/sqlservr.exe" ]] && database="true"

	if [[ $clientTools ]]; then
		run "$base/plugins/SSMSBoostInstaller2012_2.10.4957.30631.msi" || return # http://www.ssmsboost.com
	fi

	ask "Cleanup log" && { SsLogCleanup || return; }
	ask "Update services" && { SsUpdateServices || return; }

	if [[ $database ]]; then 
		ask "Update server configuration" && { SsServerConfig || return; }
		#ask "Update mail configuration" && { SsMailConfig || return; }
		#ask "Update reporting server configuration" && { SsReportServerConfig || return; }
	fi

	if [[ $clientTools ]]; then
		ask "Configure SQL Server Management Studio" && { SsManagementStudioConfig || return; }
	fi

	SsFinal || return
}

SsLogCleanup()
{
	echo "Removing log files..."
	$rmd "$P/Microsoft SQL Server/110/Setup Bootstrap/Log" || return
}

SsServerConfig()
{
	echo "- Object Explorer, Server, Properties, Memory, Maximum server memory=256"
	SqlServer studio || return
	pause

	echo "Updating firewall..."
	$firewall rule add "SQL Server" dir=in action=allow protocol=TCP localport=1433 profile=private \
		program="$(utw "$P/Microsoft SQL Server/MSSQL10.MSSQLSERVER/MSSQL/Binn/sqlservr.exe")" || return

	echot "\
- SQL Server Network Configuration, Protocols for MSSQLSERVER
- Named Pipes and TCP/IP=Enabled (click drop down, down arrow, enter)
- TCP/IP, IP Addresses, (IP for primary NIC) IPn, Enabled=Yes, (optional) TCP Port=3180"
	SqlServer config
	pause
}

SsUpdateServices()
{
	[[ ! $client ]] && return 0

 	echo "Updating services..."
	SqlServer service demand --all || return
	SqlServer service stop --all || return

	if ask 'Automatically start SQL Server'; then
		SqlServer service auto || return
		SqlServer service start || return
	fi
}

SsManagementStudioConfig()
{
	ask 'Restore profile' && { SqlServer profile restore default || return; }

	echot "\
	- View: Registered Servers at top left, Solution Explorer at bottom right
	- Tools, Options
	  - Environment
	    - General, 20 items shown
	    - Startup, At startup Open empty environment
	  - Text Editor
	    - All Languages, check Line numbers
	    - (if using SQL Prompt) Transact-SQL, uncheck Auto list members
	    - Editor Tab and Status Bar, Tab Text, all but Include File Name to False
	- Help, Yes"
	SqlServer studio || return; pause
}

SsFinal()
{
	echo "Creating sql directory..."
	local dir="$udata/sql"; $makeDir "$dir"
	[[ -d "$_CloudData/sql" ]] && { $makeShortcut "$_CloudData/sql" "$dir/cloud.lnk" || return; }

	echo "Moving data folders..."
	local dir="$udata/SQL Server Management Studio"
	$makeLink --merge --hide "$udata/SQL Server Management Studio" "$udoc/SQL Server Management Studio" || return
	$makeLink --merge --hide "$udata/Visual Studio 2010" "$udoc/Visual Studio 2010" || return

	$makeDir "$dir/Projects" || return
	$makeShortcut "$udata/sql" "$dir/Projects/sql.lnk" || return

	ask "Update registry" && { SsRegistry || return; }
	SsIcons || return;

	if ask "Cleanup path"; then
		os path editor || return
		echo "- Remove SQL entries from the system path"
		pause
	fi
}

SsRegistry()
{
	local dir="$(utw "$udata/sql")" r="HKCU/Software/Microsoft/SQL Server Management Studio/11.0"

	echo "Updating SQL Server registry..."
	$registry set "$r/DefaultBrowseComponentLocation" REG_EXPAND_SZ "$dir" || return
	$registry set "$r/DefaultFileOpenLocation" REG_EXPAND_SZ "$dir" || return
	$registry set "$r/DefaultNewProjectLocation" REG_EXPAND_SZ "$dir" || return
	$registry set "$r/DefaultNewProjItemLocation" REG_EXPAND_SZ "$dir" || return
	$registry set "$r/DefaultOpenProjectLocation" REG_EXPAND_SZ "$dir" || return
	$registry set "$r/DefaultOpenProjItemLocation" REG_EXPAND_SZ "$dir" || return
	$registry set "$r/DefaultOpenSolutionLocation" REG_EXPAND_SZ "$dir" || return
}

SsIcons()
{
	echo "Updating icons..."
	$mergeDir --rename "$pp/Microsoft SQL Server 2012" "$serverPrograms/Other/SQL Server 2012"
	$mergeDir --rename "$pp/Microsoft Visual Studio 2010" "$pp/Development/.NET/Other/Visual Studio 2010"
	$mergeDir --rename "$pp/Microsoft SQL Server 2008" "$serverPrograms/Other/SQL Server 2008"
}

SqlPromptInstall()
{
	printf "**************************************************\n* SQL Prompt\n**************************************************\n"
	
	# download: http://www.red-gate.com/products/sql-development/sql-prompt
	run "RedGate/SQLPromptDownload.exe" || return

	echo "Updating icons..."
	$mergeDir "$pp/Red Gate" "$pp/Development/Other"

	echot "\
	- SQL Prompt 5
		- Serial Number, Enter Serial Number...
		- Options...
		  - Format, Tabs & wraping, Characters per line=120
		  - Experimental Features, check Enable Tabs Instead of Spaces"
	 SqlServer studio || return
	 pause
}

VisionAppInstall()
{
	printf "**************************************************\n* VisioApp Remote Desktop\n**************************************************\n"

	# home: http://www.visionapp.com/germany/software/visionapp-remote-desktop
	# download: //vmsdaklx001/software$/Visionapp_remotedesktop
	run "VisionApp/Remote Desktop/setup/vRD2011inclPatch2.exe" || return

	echo "Updating icons..."
	$rm "$pd/visionapp remote Desktop 2011.lnk" || return
	$mergeDir "$pp/visionapp remote Desktop 2011" "$pp/Operating System/Other" || return
	$mergeDir "$pp/ASG-Remote Desktop 2012" "$pp/Operating System/Other" || return
	$rm "ASG-Remote Desktop 2012.lnk" || return

	echo "Configure..."

	local cloudDir="$_CloudData/VisionApp" localDir="$udata/VisionApp"
	$makeDir "$cloudDir" "$localDir"

	FindFile "VisionApp/Remote Desktop/license/Intel Corporation_Global.xml" || return
	clipw "$file" || return
	echot "\
- ?, Info..., Import new license file, <paste>
- (Wiggin) Add..., File..., Name=Wiggin, path=$(utw $cloudDir/settings.xml), Yes
- (Intel) File, Environment Wizard, Add…, Database…, Connect to an Existing Database
	- Name of the environment=Intel
  - Database server=azscsissql950,3180
  - Database name=VisionApp
  - User name=vRDDbUser
  - Password=VisionUser!1
- View, Icon Size, 24x24
- Tools, Options, Application, check Pass-through authentication
- Pin this program to the taskbar"
	VisionApp start || return
	pause
}

Office365Install()
{
	printf "**************************************************\n* Office 365\n**************************************************\n"
	echo "- How would you like your office to look=Clouds"
	run "Microsoft/Office/setup/office/en_office_365_${architecture}.exe"
	OfficeFinal || return
}

OfficeFinal()
{
	. office.sh || { EchoErr "inst: Office is not installed"; return 1; }

	echo "Updating directories..."
	$makeDir "$udata/Templates" "$pdata/Templates" || return

	echo "Moving data folders..."
	$makeLink --merge --hide "$udata/OneNote" "$udoc/OneNote Notebooks" || return

	ask "Restore normal templates" && { word RestoreNormal || return; }
	ask "Update registry" && { registry import "$setupFiles/ShellNew.reg" || return; }
	ask "Update icons" && { OfficeIcons || return; }
	ask "Configure" && { for o in "$setupFiles/Set Options".*; do start "$o" || return; pause; done; }
}

OfficeIcons()
{
	p="$ao/Office"

	$mergeDir --rename "$pp/Microsoft Office 2013" "$p" || return
	$mergeDir --rename "$p/Office 2013 Tools" "$p/tools" || return
	$rm "$up/Startup/Send to OneNote.lnk" || return
	for f in "$p/"*2013.lnk; do $ren "$f" "${f/ 2013/}" || return; done
	for f in "$p/tools/"*2013*.lnk; do $ren "$f" "${f/ 2013/}" || return; done
}

nVidiaInstall()
{
	printf "**************************************************\n* nVidia Video Drivers\n**************************************************\n"

	# Driver: http://www.nvidia.com/Download/Find.aspx?lang=en-us for GTX 550 Tx
	# Scan: http://www.nvidia.com/Download/Scan.aspx?lang=en-us
	# System tools: http://www.nvidia.com/object/nvidia_system_tools_6.03.html
	# NTune: http://www.nvidia.com/object/sysutility.html
	# Installs:
	# Path: c:/Program Files (x86)/NVIDIA Corporation/Physx/Common
	# Service: 
	# - nvUpdatusService - NVIDIA Settings Update Manager, check for new updates
	# - Stereo Service - NVIDIA Stereoscopic 3D Driver Service (3D glasses)
	# - nvsvc - Provides system and desktop level support to the NVIDIA display driver
	#     Note: In 2010 on Oversoul the nVidia service changed the display settings to undesired settings, 2011 trying again
	# - nTuneService - display the Performance and System Stability sections of the NVIDIA control panel (clock and fan adjustment, etc).
	run "nVidia/driver/331.65-desktop-win8-win7-winvista-${bits}bit-english-whql/setup.exe" || return

	echo "Updating services..."
	service manual "Stereo Service" || return
	service manual "nvUpdatusService" || return

	echo "Updating icons..."
	$mergeDir --rename "$pp/NVIDIA Corporation" "$pp/Operating System/Other/NVIDIA" || return
	$rm "$pd/GeForce Experience.lnk" || return
	$rm "$pd/3D Vision Photo Viewer.lnk" || return
}

GitExtensionsInstall()
{
	printf "**************************************************\n* Git Extensions\n**************************************************\n"
	
	echot "\
- check Msysgit, optional KDiff
- Custom Setup
	- check Extra application icons
	- uncheck Visual Studio NNNN integration
	- (optional) uncheck Assign with...
- Git Setup, uncheck Associate .sh files to be run with Bash
- Checkout as-is, commit as-is"

	# http://msysgit.github.com/, http://superuser.com/questions/393218/adding-git-bash-here-right-click-option-with-silent-install
	run "Shareware/GitExtensions/setup/GitExtensions24703SetupComplete.msi" || return # https://code.google.com/p/gitextensions/ 

	echo "Configuring git..."
	git config --system http.sslcainfo "$P32/git/bin/curl-ca-bundle.crt"
	git config --system core.filemode false
	git config --system core.autocrlf false

	echo "Updating icons..."
	$mergeDir "$pp/Git" "$pp/Development/Other"
	$mergeDir "$pp/KDiff3" "$pp/Operating System/Other"
	$mv "$pp/Git Extensions.lnk" "$pp/Development/Other/Git"
	$rm "$pd/Git Bash.lnk"
	$rm "$pd/Git Extensions.lnk"

	FindEditorProgram || return; clipw "\"$(utw "$program")\"" || return
	echot "\
- Git Extensions, 
	- Git Extensions
		- Check Use FileSystemWatcher to check if index has changed
		- Check Check for uncommitted changes in checkout branch dialog
		- Check Close Process dialog when process succeeds
		- Default clone destination=c:\Projects
	- Global settings
		- User name=NNN, User email=NNN
		- Editor=<paste>
		- (optional) Mergetool=BeyondCompare3, Diftool=beyondcompare3
	- SSH, select PuTTY
	- Scripts, Fetch changes, check Enanbled, uncheck Ask for confirmation
	- Shell Extensions, check Clone, Commit, Create new repository"
	GitHelper gui || return
	pause
}

TortoiseGitInstall()
{
	printf "**************************************************\n* TortoiseGit\n**************************************************\n"
	
	# https://code.google.com/p/tortoisegit/ https://code.google.com/p/tortoisegit/wiki/Download?tm=2
	echot "- (optional) Check Registrer link handlers"
	run "Shareware/TortoiseGit/setup/TortoiseGit-1.8.6.0-${bits}bit.msi" || return

	echo "Updating icons..."
	$mergeDir "$pp/TortoiseGit" "$pp/Development/Other"

	FindCompareProgram || return; clipw "$(utw "$program")" || return
	echot "\
- General
	- Contect Menu, uncheck all but Clone
	-Dialogs 1, check Enable Gravatar
- Git, Credential, Credential helper=wincred - all Windows users
	- note: when clone with HTTPS cancel first credential prompt
- (optional) Diff Viewer (1 place) and Merge Tool (1 place), External=<paste>
- Icon Overlays
	- check Unversioned files mark parent folder as modified
	- Icon Set, Icon Set=Straight
"
	GitHelper tgui /command:settings || return
}

VisualSvnInstall() { TortoiseSvnInstall; }
TortoiseSvnInstall()
{
	printf "**************************************************\n* TortoiseSVN Source Control\n**************************************************\n"
	echo "- Select all features"
	
	run "Shareware/TortoiseSVN/TortoiseSVN-1.8.3.24901-${architecture}-svn-1.8.4.msi" || return # http://tortoisesvn.net/downloads.html, path C:/Program Files/TortoiseSVN/bin
	run "VisualSVN/VisualSVN-4.0.0.msi" || return # http://www.visualsvn.com/visualsvn/download/

	echo "Updating icons..."
	$mergeDir "$pp/TortoiseSVN" "$pp/Development/Other" || return
	$mergeDir "$up/VisualSVN" "$pp/Development/Other" || return
	$mergeDir "$pp/VisualSVN" "$pp/Development/Other" || return

	FindCompareProgram || return; clipw "$(utw "$program")" || return
	echot "- (optional) Diff Viewer (2 places) and Merge Tool (1 place), External=<paste>"
  TortoiseSVN gui /command:settings || return
}	

BrowserHomePage()
{
	local file="$udata/replicate/default.htm"
	local url="file:///$(utw "$file")"

	[[ ! -f "$file" ]] && { EchoErr "inst: cannot access browser home page file \`$file\`: No such file"; return 1; }

 	# Chrome
	$makeLink "$udata/replicate" "$APPDATA/replicate" || return

	# Internet Explorer
	echo "- Tools, Internet Options, Use Current"
	InternetExplorer start "$url" || return
	pause

	# Firefox
	if IsInstalled firefox; then
		echo "Setting Firefox home page..."
		echo "- Close other tabs"
		echo "- Tools, Options, Main, Use Current Page"
		firefox "$url"
		pause
	fi
}

sysInternalsInstall()
{
	printf "**************************************************\n* SysInternals Tools\n**************************************************\n"
	registry import "$pdata/setup/SysInternalsEula.reg"
}

iTunesInstall()
{
	printf "**************************************************\n* iTunes\n**************************************************\n"
	echo "- Uncheck Use iTunes as the default player for audio files"
	echo "- Uncheck Automatically update iTunes and other Apple software"
	
	# Download: http://itunes.com
	# Setup: VBScript is not installed error: http://coderjournal.com/2007/03/apple-wants-vista-to-run-un-secured-to-install-itunes/
	# AirPrint: http://discussions.apple.com/thread.jspa?threadID=2659544 or http://ipadhelp.com/ipad-help/how-to-enable-airprint-for-windows-and-use-any-printer/
	# Installs:
	#   - iTunesHelper - optional, for quick launch
	#   - Shell Extension: iTunes
	#   - Task Scheduler: AppleSoftwareUpdateApple
	# -   Services: Apple Mobile Device (required), iPod Service (recognize iPods), Bonjour Service (sharing), AirPrint
	run "Apple/iTunes/setup/iTunes v11.1.3.0 ${architecture}.exe" || return

	echo "Updating icons..."
	$rm "$pd/iTunes.lnk" || return
	$mergeDir "$pp/iTunes" "$ao" || return

	echo "Updating registry..."	
	$registry 32 delete "run/iTunesHelper" || return 	# "C:/Program Files/iTunes/iTunesHelper.exe"
	$registry 32 delete "run/APSDaemon" || return 		# "C:/Program Files (x86)/Common Files/Apple/Apple Application Support/APSDaemon.exe"

	echo "Updating services..."
	service auto "iPod Service"

	iTunes profile restore default || return
	QuickTimePost || return
	AppleCore || return

	echot "\
	Use alt to open menu items
	- iTunes Store, Sign In
	- Store, Authorize Computer...
	- Edit, Preferences
		- General
	    - Library Name=<first name>'s Library
	    - Sources, check all
	    - Import Settings
	      - Import Using=MP3 Encoder
	      - Setting=Higer Quality
		- Store, uncheck Automatic Downloads, Music, Apps, Books
		- Advanced
	    - iTunes Music folder location=Music/My Music or (Music ROO) Music/Public Music
	    - uncheck Keep iTunes Music folder organized
	    - uncheck Copy files to iTunes Music folder when adding to library
	    - check Enable full keyboard navigation
	- File, Add folder to library..., Music/My Music or (Music ROO) Music/Public Music
	- Connect iOS device
	  - (optional) Music, check Selected playlists, artists, and genres, check Best or 5 Star
	  - (optional) Info
	    - Check Sync Contacts with Outlook
	    - (one time) check Sync Mail Accounts from Outlook
	    - Check Sync notes with Outlook
	- Notes: Ctrl-t visualizer, ctrl-f full screen"
	sudo --standard iTunes start || return
	pause
}

QuickTimePost()
{
	$registry 32 delete "run/QuickTime Task" # "C:/Program Files/QuickTime/qttask.exe" -atboottime

	echo "Updating icons..."
	$makeDir "$ao/Apple" || return
	$mergeDir "$pp/QuickTime" "$ao" || return
	$rm "$pd/QuickTime Player.lnk" || return
	$mv "$pp/Apple Software Update.lnk" "$ao/Apple" || return
}

TeamViewerInstall()
{
	printf "**************************************************\n* TeamViewer\n**************************************************\n"
	echo "- How do you want to use TeamViewer=personal / non-commercial use"

	run "TeamViewer/setup/TeamViewer_Setup_en.exe" || return # http://www.teamviewer.com/en/download/windows.aspx

	echo "Updating icons..."
	$mv "$pp/TeamViewer "?".lnk" "$pp/Operating System" || return
	$rm "$pd/TeamViewer "?".lnk" || return

	echot "\
- Computers & Contacts, Sign In, ...
- Add this computer, Comptuer name=<camel case>, Password/Confirm Password=<secure numeric>
	"
	pause
}

TrueImageInstall()
{
	printf "**************************************************\n* True Image\n**************************************************\n"
	
	run "Acronis/setup/ATIH2014_5560_en-US" || return # http://www.acronis.com/support/updates/

	echo "Updating icons..."
	$mergeDir "$pp/Acronis" "$pp/Operating System/Other" || return
	$rm "$pd/Acronis True Image 2014.lnk" || return

	echo "Updating registry..."	
	$registry delete "run/Acronis Scheduler2 Service" # "C:\Program Files (x86)\Common Files\Acronis\Schedule2\schedhlp.exe"
	$registry 32 delete "run/AcronisTibMounterMonitor" # C:\Program Files (x86)\Common Files\Acronis\TibMounter\TibMounterMonitor.exe
	$registry 32 delete "run/TrueImageMonitor.exe" # "C:\Program Files (x86)\Acronis\TrueImageHome\TrueImageMonitor.exe"
}

npp() { NotepadPpInstall; }
NotepadPpInstall()
{
	printf "**************************************************\n* Notepad++\n**************************************************\n"
	echo "- Uncheck Run Notepad++"

	run "Shareware/Notepad++/setup/npp.6.5.1.Installer.exe" || return # http://notepad-plus-plus.org/download/

	FindFile "Shareware/Notepad++" || return

	if ask "Deleting existing plugins and install the defaults"; then
		$rc --mirror --quiet "$file/plugins/default" "$P32/Notepad++/plugins" || return
	fi

	echo "Updating registry..."
	registry import "$file/setup/NotepadPP.reg" || return

	echo "Updating icons..."
	$rm "$ud/Notepad++.lnk" || return
	$rm "$pd/Notepad++.lnk" || return
	$mergeDir "$up/Notepad++" "$ao" || return
	$mergeDir "$pp/Notepad++" "$ao" || return

	notepadpp profile restore default || return

	echot "\
- Settings, Preferences, MISC, uncheck Minimize to system tray
- Settings, Shortcut Mapper...,  Reload from Disk=Ctrl+R
- Explorer, Search=*.txt, Open with, Choose Default program...
  - Notepad++, check Always use the selected program to open this kind of file
- keyboard shortcuts 
  ctrl-n/w=new/close,  ctrl+/-=zoom
  [shift]ctrl-tab=switch, ctrl-shift-o=file switcher
  [alt]click drag=[block] select, ctrl-space=auto complete
	"
	notepadpp
	pause
}

jreInstall()
{
	printf "**************************************************\n* Java Runtime Environment \n**************************************************\n"
	
	# Download 7: http://www.oracle.com/technetwork/java/javase/downloads/index-jsp-138363.html#javasejdk
	# Download: http://www.java.com/en/download/manual.jsp
	# Download: http://www.oracle.com/technetwork/java/javase/downloads/index.html
	# Eary access: http://www.oracle.com/technetwork/java/javase/downloads/ea-jsp-142245.html
	# Test: http://www.java.com/en/download/installed.jsp http://java.com/en/download/help/testvm.xml
	# Services: JavaQuickStarterService
	run "Sun/Java/jre/*-x86.exe" || return
	[[ "$architecture" == "x64" ]] && { run "Sun/Java/jre/*-x64.exe" || return; }

	JavaFinal
}

JavaFinal()
{
	echo "Updating registry..."
	$registry 32 delete "run/SunJavaUpdateSched"
	$registry 64 delete "run/SunJavaUpdateSched"

	echo "Updating icons..."
	$mergeDir "$pp/Java" "$pp/Operating System/Other" || return

	ask "Test the Java browser plugin?" && JavaUtil test
}

VmwareWorkstationInstall()
{
	printf "**************************************************\n* VMware Workstation\n**************************************************\n"
	echot "\
- Custom
  - Uncheck development environment plug-ins 
  - Workstation Server Component COnfiguration
    - Store shared VMs to=Public/Documents/data/VMware
    - HTTPS Port=444
- Uncheck Check for product updates on startup"
	
	# download - http://vmware.com/download/ws/
	# services - VMAuthdService: run virtual machines as non-admin or in the background
	run "VMware/workstation/setup/VMware-workstation-full-10.0.1-1379776.exe" || return 

	echo "Updating firewall..."
	# When the guest uses NAT echo replies (ICMP type and code 0) must be allowed for ping to function on the guest
	$firewall rule add "VMware NAT Echo Reply" dir=in action=allow enable=yes profile=private,domain localip=any remoteip=any protocol=icmpv4:0,0 interfacetype=any edge=yes || return

	echo "Creating VMware directory..."
	$makeDir "$udata/VMware"

	echo "Updating icons..."
	$mergeDir "$pp/VMware" "$pp/Operating System/Other" || return
	$rm "$pd/VMware Workstation.lnk" || return

	echo "Virtual Network Editor..."
	echo "(optional) - VMnet1 (host-only), VMnet8 (NAT): uncheck Connect a host virtual adapter to this network, Apply"
	#VMware network
	pause

	if [[ "$(service StartType SysMain)" != "DISABLED" ]] && ask "Disable SuperFetch (causes excessive disk utilization with virtual machines)"; then
		 service disable SysMain || return
	fi

	echot "\
- Edit, Preferences...
  - Workspace
    - Default location for virtual machines=Documents/data/VMware or <drive>:\data\VMware\win81
    - Check Keep VMs running after workstation closes
  - Hotkeys, select Ctrl and Win only
  - Display
    - Uncheck Autofit Window
    - Check Autofit guest
    - Uncheck Show toolbar edge when unpinned in full screen
  - Memory, How much host RAM=12000 (Oversoul)
  - Priority
    - Input grabbed=High
    - Input ungrabbed=Low
    - (optional) Uncheck Take and restore snapshots in the background when possible
  - (optional) Devices, Uncheck Disable Autorun on the host when a VM is running"
	# Start manually default location folder is not yet configured
	start --wait "$P32/VMware/VMware Workstation/vmware.exe"
}

LastPassInstall()
{
	printf "**************************************************\n* LastPass\n**************************************************\n"

	# https://lastpass.com/misc_download2.php	
	#run "LastPass/setup/LastPass Setup ${architecture} v3.0.0.exe" || return
	run "LastPass/setup/LastPass for Applications Setup ${architecture} v2.5.0.exe" || return

	echo "Updating icons..."
	$mergeDir "$up/LastPass" "$pp/Operating System/Other" || return
	$rm "$pp/Operating System/Other/LastPass/Uninstall LastPass For Applications.lnk" || return

	echo "Updating registry..."	
	$registry 32 delete "run/LastApp" # C:\Program Files (x86)\LastPass\lastapp.exe
}

FoxitReaderInstall()
{
	echot "**************************************************\n* Foxit Reader - PDF Reader\n**************************************************\n
- Uncheck Shell Extensions, Install Foxit Reader Creator, Add-on for ...
- Uncheck Enable Safe Reading Mode"
	
	run "Foxit/reader/setup/FoxitReader611.1031_enu_Setup.exe" || return # http://www.foxitsoftware.com/downloads/index.php
	run "Foxit/reader/setup/FoxitPdfPreviewHandlerSetup_1_1.msi" || return # http://timheuer.com/blog/archive/2008/05/09/foxit-pdf-preview-handler.aspx

	echo "Updating icons..."
	$mergeDir "$pp/Foxit Reader" "$ao" || return
	$rm "$pd/Foxit Reader.lnk" || return
	$rm "$ud/Foxit Reader.lnk" || return

	echot "\
- Edit, Preferences
  - General, uncheck Show Start Page
  - History, Maximum number of documents in recently used list=10
  - Updater, Do not download"
	start "$P32/Foxit Software/Foxit Reader/Foxit Reader.exe" || return
	pause
}

iCloudInstall()
{
	printf "**************************************************\n* iCloud\n**************************************************\n"
	
	run "Apple/iCloud/iCloudSetup v3.0.2.exe" || return # http://support.apple.com/kb/DL1455

	# iCloudServices - C:\Program Files (x86)\Common Files\Apple\Internet Services\iCloudServices.exe
	# registry delete "urun/iCloudServices" || return

	# ApplePhotoStreams - C:\Program Files (x86)\Common Files\Apple\Internet Services\ApplePhotoStreams.exe
	# registry delete "urun/ApplePhotoStreams" || return

	echo "Updating icons..."
	$mergeDir "$pp/iCloud" "$pp/Operating System/Other" || return

	AppleCore || return

	echot "\
iCloud Control Panel
- uncheck Mail, Contacts, Calendars, & Tasks and Bookmarks
- check Photo Stream"
	pause
}

AppleCore()
{
	echo "Updating Apple icons..."
	$makeDir "$ao/Apple" || return
	$mv "$pp/Apple Software Update.lnk" "$ao/Apple" || return
}

iExplorerInstall()
{
	printf "**************************************************\n* iExplorer\n**************************************************\n"
	
	run "Macroplant/iExplorer/setup/iExplorer_3_Setup_3252.exe" || return # http://www.macroplant.com/iexplorer/download-ie3-pc.php

	echo "Updating icons..."
	$mergeDir "$pp/iExplorer" "$pp/Operating System/Other" || return
	$rm "$pp/Operating System/Other/iExplorer/Uninstall iExplorer.lnk" || return
		$rm "$pp/Operating System/Other/iExplorer/iExplorer on the Web.url" || return
	QuickTimePost || return
}

args "$@"; ${command}Command "${args[@]}";