#!/usr/bin/env bash
. function.sh
. color.sh || return

run() {	init && args "$@" && install; }

init() { :; }

usage()
{
	echot "\
usage: InstallAppFromZip ZIP [DESTINATION]($P) -- ZIP_OPTIONS
	Install an application from a ZIP file.

	-e, --elevate				in Windows install the application with an elevated (Administrator) token
	-np, --no-prompt		do not prompt for input
	-v, --verbose				display detailed output"
	exit $1
}

args()
{
	unset -v dest elevate noPrompt verbose zip
	
	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-e|--elevate) elevate="--elevate";;
			-h|--help) usage 0;;
			-np|--no-prompt) noPrompt="--no-prompt";;
			-v|--verbose) verbose="--verbose";;
			*)
				! IsOption "$1" && [[ ! $zip ]] && { zip="$1"; shift; continue; }
				! IsOption "$1" && [[ ! $dest ]] && { dest="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	[[ ! $zip ]] && MissingOperand "zip"
	[[ ! $dest ]] && MissingOperand "dest"
	[[ ! "$dest" =~ ^/ ]] && dest="$P/$dest"
	return 0
}

#
# install
#

install() { RunPlatform install; }

installLinux() { checkExists "$dest" && runCommon; }

installMac()
{
	local dir="$(zipinfo -1 "$zip" | head -1)"
	if [[ "$dir" =~ ^.*app/$ ]]; then
		checkExists "$dest/$dir" || return
		unzip "$zip" -d "$P" || return
		return
	fi

	checkExists "$dest" || return
	runCommon
}

installWin()
{
	checkExists "$dest" || return
	
	if [[ "$elevate" ]] && ! IsElevated; then
		RunScript --elevate $verbose -- InstallAppFromZip $verbose --no-prompt "$zip" "$dest" || return
	else
		runCommon || return
	fi
}

#
# helper
#

checkExists()
{
	local dir="$1"

	[[ ! -d "$dir" ]] && return
		
	[[ ! $noPrompt ]] && { ask "Do you want to delete the existing installation in \"$dir\"" -dr n || return; }

	if IsPlatform win && ! IsElevated; then
		printf "cleaning..."
		RunScript --elevate -- rm -fr "\"$dir\"" || return
		echo "done"
	else
		sudo ${G}rm -fr "$dir"
	fi
}

runCommon()
{
	local ext="$(GetFileExtension "$zip")"

	sudoc ${G}mkdir --parents "$dest" || return

	[[ $verbose ]] && hilight "Unzipping \"$(GetFileName "$zip")\" to \"$dest\"..." || hilight "Inflating..."

	# use 7z.exe to unzip on Windows drives
	drive IsWin "$dest" && { UnzipPlatform "$zip" "$dest" --sudo || return; }

	# determine if the archive contains a single driectory assume it is the destination directory
	local dir dirCount;
	[[ "$ext" == "zip" ]] && dirCount="$(zipinfo -1 "$zip" | cut -d"/" -f1 | sort | uniq | wc -l)"

	if [[ "$dirCount" == "1" ]]; then
		dir="$(zipinfo -1 "$zip" | head -1 | GetFilePath)"
	fi

	# unzip the archive
	if [[ "$ext" == @(bz2|gz|tar) ]]; then
		sudo tar --extract --verbose --auto-compress --file="$zip" -C "$dest"; return
	else
		sudo unzip -o "$zip" -d "$dest" || return
	fi

	if [[ $dir ]]; then
		sudo mv "$dest/$dir/"* "$dest" || return
		sudo rmdir "$dest/$dir" || return
	fi

	return 0
}

run "$@"
