#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

# InstBak - backup all installation locations
run()
{
	local src srcDesc
	src="$(unc mount public)/install" || return
	srcDesc="$(unc get unc "$src" | GetUncServer | RemoveDnsSuffix)"

	local src dir dirs; IFS=$'\n' ArrayMake dirs "$(FindInstallFile --all)"

	for dir in "${dirs[@]}"; do
		
		if IsUncPath "$dir"; then
			desc="$(GetUncServer "$dir" | RemoveDnsSuffix)"
			[[ "$desc" == "$srcDesc" ]] && continue
			dir="$(unc mount "$dir")" || return

		elif drive IsDrive "$dir"; then
			desc="$(drive label "$dir")"; desc="${desc:-$dir}"

		else
			desc="local"

		fi
		
		header "$desc"
		CopyDir --recursive --delete "$src" "$dir" || return
		echo
	
	done
}

run "$@"
