#!/usr/bin/env bash
. script.sh

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... ZIP [DESTINATION]($P) -- ZIP_OPTIONS
Install an application from a ZIP file.

	-e, --elevate				in Windows install the application with an elevated (Administrator) token
	-np, --no-prompt		do not prompt for input"
}

init() { defaultCommand="install"; }

opt()
{
	case "$1" in
		-e|--elevate) elevate="--elevate";;
		*) return 1;;
	esac
}

args()
{
	ScriptArgGet "zip" -- "$@"; shift
	ScriptArgGet "dest" -- "$@"; shift
}

argEnd()
{
	# if a full path is not specified, use the program directory ($P)
	[[ ! "$dest" =~ ^/ ]] && dest="$P/$dest"

	# use sudoc - except for windows drives to prevent a possible credential prompt in a hidden elevated window
	sudo="sudoc"; IsPlatform win && drive IsWin "$(GetFilePath "$dest")" && unset sudo 

	return 0; 
}

#
# install
#

installCommand() { RunPlatform install; }

installLinux()
{
	# firefox
	if [[ "$dest" =~ /firefox$ ]]; then
		checkExists "$dest" && extract "$zip" "$(EnsureDir "$dest" | GetParentDir)"; return
	fi

	# other
	checkExists "$dest" && runCommon; 
}

installMac()
{
	local dir="$(zipinfo -1 "$zip" | head -1)"

	if [[ ! "$dir" =~ ^.*app/$ ]]; then installMacStandard
	elif [[ "${dir,,}" =~ install ]]; then installMacInstaller
	else installMacApp
	fi
}

installMacApp()
{	
	checkExists "$dest/$dir" || return
	installMacAppRestore || return

	sudo mv "$TEMP/hold/$dir" "$dest" || return
	sudo rmdir "$TEMP/hold" || return

	[[ "$dest" != "$P" ]] && return
	sudo gchown root -R "$dest/$dir" || return
	sudo gchgrp wheel -R "$dest/$dir" || return
}

installMacInstaller()
{
	installMacAppRestore || return
	start "$TEMP/hold/$dir" || return
	pause "When the installation has finished press any key..."
	clean "$TEMP/hold" || return
}

installMacAppRestore() { echo "Restoring $(GetFileName "$zip")..."; RunLog $sudo ditto -kx "$zip" "$TEMP/hold"; } # use ditto to unzip, unzip corrupts some applications (seen with Sublime Merge)

installMacStandard() { checkExists "$dest" && runCommon; }

installWin()
{
	if [[ "$elevate" ]] && ! IsElevated; then
		cleanPrompt "$dest" || return
		RunScript --elevate "${globalArgs[@]}" -- InstallAppFromZip "${globalArgs[@]}" --no-prompt "$zip" "$dest" || return
	else
		checkExists "$dest" && runCommon
	fi
}

#
# helper
#

checkExists() { cleanPrompt "$@" && clean "$@"; }

clean()
{
	local dir="$1"; [[ ! -d "$dir" ]] && return

	# ensure the full path to the program is specified
 	[[ "$(RemoveTrailingSlash "$dir")" == @($P|) ]] && { ScriptErr "cannot install to '$P' directly"; return 1; }

	# clean
	printf "cleaning..."
	$sudo ${G}rm -fr "$dir" || return
	echo "done"
}

cleanPrompt()
{
	local dir="$1"; [[ $noPrompt || ! -d "$dir" ]] && return
	ask "Do you want to delete the existing installation in '$dir'" -dr n
}

runCommon()
{	
	$sudo ${G}mkdir --parents "$dest" || return

	# determine if the archive contains a single driectory assume it is the destination directory
	local dirs=()

	if [[ "$zip" =~ .zip$ ]]; then
		dirs=( $(zipinfo -1 "$zip" | cut -d"/" -f1 | sort | uniq) )
	elif [[ "$zip" =~ [.](tar[.]bz2|tar[.]gz)$ ]]; then
		dirs=( $(tar --list --auto-compress --file="$zip" | cut -d"/" -f1 | sort | uniq) )
	fi	

	extract "$zip" "$dest" || return

	if (( ${#dirs[@]} == 1 )); then
		local dir="${dirs[0]}"
		$sudo mv "$dest/$dir/"* "$dest" || return
		$sudo rmdir "$dest/$dir" || return
	fi

	return 0
}

# extract ZIP DEST
extract()
{
	local zip="$1" dest="$2"

	[[ $verbose ]] && hilight "Installing '$(GetFileName "$zip")'' to '$dest'..." || hilight "Installing..."

	# Windows drive - use 7z.exe
	if drive IsWin "$dest"; then
		UnzipPlatform "$zip" "$dest"

	# tar extract
	elif [[ "$zip" =~ [.](bz2|gz|tar)$ ]]; then
		$sudo tar --extract --verbose --auto-compress --file="$zip" -C "$dest"

	# zip extract
	else
		$sudo unzip -o "$zip" -d "$dest"
	fi
}

ScriptRun "$@"
