#!/usr/bin/env bash
. function.sh || exit

run()
{
	local desc dirs src srcDesc

	src="//nas3.hagerman.butare.net/public/Documents/data/install"
	srcDesc="$(RemoveDnsSuffix "$(GetUncServer "$src")")"
	src="$(unc mount "//nas3.hagerman.butare.net/public/Documents/data/install")" || return

	IFS=$'\n' dirs=( $(FindInstallFile --all) )

	for dir in "${dirs[@]}"; do

		if IsUncPath "$dir"; then
			desc="$(RemoveDnsSuffix "$(GetUncServer "$dir")")"
			[[ "$desc" == "$srcDesc" ]] && return
			dir="$(unc mount "$dir")" || return

		elif IsDrive "$dir"; then
			desc="$(GetDriveLabel "$(GetDrive "$dir")")"; desc="${desc:-$dir}"

		else
			EchoErr "InstBak: unable to backup to \"$dir\""
			return 1
		fi
		
		header "$desc"
		# --delete
		CopyDir --archive --verbose "$src" "$dir" || return
		echo
	done
}

run "$@"
