#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: irfan [start|close|restart](start)
  Irfan View
 	-t, --thumbs		display the thumbnail view"; exit $1; }

args()
{
	unset -v help thumbs
	command="start"
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			--thumbs|-t) thumbs="/thumbs";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init()
{ 
	program="$P32/IrfanView/i_view32.exe"
}

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" $thumbs "$@"
}

run "$@"