#!/bin/bash
. function.sh || exit

usage()
{
	echot "/
usage: iso [mount|unmount|UnmountAll](mount) [NUM](1) FILE...
	Mountor unmount the specified ISO image"
	exit $1
}

args()
{
	unset num files
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			UnmountAll) command="UnmountAll";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				{ [[ ! $num ]] && IsInteger "$1"; } && { num="$1"; shift; continue; }
				[[ -f "$1" ]] && { files+=( "$1" ); shift; continue; }
				EchoErr "iso: cannot access /`$1/`: No such file"; return 1;;
		esac
		shift
	done
	command="${command:-mount}"
	num="${num:-1}"
	args=("$@")
}

init()
{
	# http://www.slysoft.com/en/virtual-clonedrive.html
	program="$P32/Elaborate Bytes/VirtualCloneDrive/VCDMount.exe"
	gui="$P32/Elaborate Bytes/VirtualCloneDrive/VCDPrefs.exe"

	[[ ! -f "$program" ]] && { EchoErr "There is no ISO mounting program installed"; return 1; }
	return 0
}
run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
guiCommand() { start "$gui"; }
unmountCommand() { "$program" /d=$(( num-1 )) /u; }
UnmountAllCommand() { "$program" /d=0 /u; "$program" /d=1 /u; }

mountCommand()
{
	for file in "${files[@]}"; do
  	echo "Mounting $(GetFilename "$file")..."
  	start --direct "$program" /d=$(( num-1 )) "$file" || return
  	(( num+=1 ))
	done	
}

run "$@"
