#!/usr/bin/env bash
. function.sh || exit

usage()
{
	echot "/
usage: iso [mount|dismount](mount) FILE...
	Mount or dismount the specified ISO image"
	exit $1
}

args()
{
	unset files
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ -f "$1" ]] && { files+=( "$1" ); shift; continue; }
				EchoErr "iso: cannot access /`$1/`: No such file"; return 1;;
		esac
		shift
	done
	command="${command:-mount}"
	args=("$@")
}

init()
{
	# http://www.slysoft.com/en/virtual-clonedrive.html
	#program="$P32/Elaborate Bytes/VirtualCloneDrive/VCDMount.exe"
	#gui="$P32/Elaborate Bytes/VirtualCloneDrive/VCDPrefs.exe"
	#unmountCommand() { "$program" /d=$(( num-1 )) /u; }
	#UnmountAllCommand() { "$program" /d=0 /u; "$program" /d=1 /u; }
	#start --direct "$program" /d=$(( num-1 )) "$file" || return

	[[ "$PLATFORM" != "win" ]] && { EchoErr "There is no ISO mounting program installed"; return 1; }
	return 0
}
run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
dismountCommand() 
{ 
	for file in "${files[@]}"; do
  	echo "Dismounting $(GetFileName "$file")..."
  	dismount$PLATFORM "$file" || return
	done	
}

mountCommand()
{
	for file in "${files[@]}"; do
  	echo "Mounting $(GetFileName "$file")..."
  	mount$PLATFORM "$file" || return
	done	
}

mountwin() { powershell Mount-Diskimage -ImagePath "\"$(utw "$file")\""; }
dismountwin() { powershell DisMount-Diskimage -ImagePath "\"$(utw "$file")\""; }

run "$@"
