#!/bin/bash

#!/bin/bash
. function.sh

run()
{
	init
	args "$@"
	${command}Command "$@"
	exit $?
}

init() 
{
	var='value'
}

usage()
{
	# psstat (SysInternals), tasklist (Windows, /v window title - slow), ps -W (CygWin, full path)
	echot "\
usage: IsTaskRunning <executable>
Determine if the specified executable is running using the given method
	executable - can contain wildcard characters * or ?"
	exit $1
}

args()
{
	unset file server interactive verbose test
	command='pstat'
	[[ $# != 1 ]] && usage 1
	executable="$1"
}

pstatCommand()
{
	pstat -sW | cut -c 27- | egrep "$executable"
}

run "$@"
