#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: templateApp [start|startup|close|restart|cd](start)
  profile save|restore|dir|SaveDir [<profile name>|default](latest) [--global]
  -b, --brief		brief status messages"; exit $1; }

args()
{
	unset -v brief command help
	while (( $# != 0 )); do
		case "$1" in
			--brief|-b) brief="--brief";;	
			--help) help="--help";;
			NextTrack) command="NextTrack";; PreviousTrack) command="PreviousTrack";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start|startup|profile|service) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command="start"
	[[ ! $command ]] && MissingOperand "command"
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init()
{ 
	title=".* - Sublime Text 2"
	program="$P/Sublime Text 2/sublime_text.exe"
	cd="$DOC/data/templates"
}

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }
cdCommand() { echo "$cd"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } # task close|CloseKill [--wait] [--title "$title"] "$program"; ProcessKill "$program"; SendKeys "$title" "!FX"; 
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";
profileCommand() {	profile --app "BeyondCompare" --method "<dir|exe|registry key|$program>" --files "*.ini *.xml" --save-extension "bcpkg" "$@"; }
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
	#task start --duplicate --title "$title" "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
	#task start $brief --fast --wait --title "$FastStartTitle" "$program" "\"$(utw "$FastStart")\""
	#task start $brief --wait --minimize "$program" --title "$title" "$program" "$@"
	#WinSetState "$title" minimize
}

send() { osascript -e 'tell application "iTunes"' -e "$1" -e "end tell"; }
NextTrackCommand() { send "next track"; }
pauseCommand() { send "pause"; }
playCommand() { send "play"; }
PreviousTrackCommand() { send "previous track"; }


run "$@"