#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [consumer|IsInstalled|producer|service|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	bin="/opt/kafka/bin"
	program="$bin/kafka-server-start.sh"
}

isInstalledCommand() { [[ -e "$program" ]]; }
versionCommand() { AppInstallCheck && "$program" --version | ${G}tail -1; }

consumerCommand() { bin/kafka-console-consumer.sh --topic test1 --from-beginning --bootstrap-server localhost:9092; }
producerCommand() { "$bin/kafka-console-producer.sh" --topic test1 --bootstrap-server localhost:9092; }

closeCommand() { ! serviceIsRunningCommand && return 0; "$program" machine stop; } 
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { [[ ! $force ]] && isRunningCommand && return; AppInstallCheck && podman machine start; }

#
# service Commands
#

serviceUsage()
{
		echot "\
Usage: $(ScriptName) service IsRunning|restart|start|status|stop
Service commands."
}

serviceCommand() { usage; }
serviceIsRunningCommand() { ps -a | ${G}grep -v grep | qgrep "kafka.Kafka"; }
serviceRestartCommand() { serviceStopCommand && serviceStartCommand; }
serviceStartCommand() { serviceIsRunningCommand && return; "$bin/kafka-server-start.sh" config/server.properties; }
serviceStatusCommand() { service status "$service"; }
serviceStopCommand() { ! serviceIsRunningCommand && return; "$bin/kafka-server-stop.sh"; }

#
# helper
#

podman() { RunWin "$program" "$@"; }

ScriptRun "$@"
