#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [cli|config|close|dir|IsInstalled|IsRunning|profile|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="karabiner" profileDir="$HOME/.config/karabiner" profileMask="*"
	program="$P/Karabiner-Elements.app"
}

configCommand() { echo "Loading Karabiner-Elements configuration folder in the text editor..."; TextEdit "$profileDir"; }
closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
dirCommand() { echo "$profileDir"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

#
# CLI Commands
#

cliUsage() { echot "Usage: $(ScriptName) cli [ARGS]"; }
cliArgStart() { unset -v cliArgs; }
cliArgs() { cliArgs=("$@" "${otherArgs[@]}"); shift="$#"; }
cliCommand() { "/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli" "${cliArgs[@]}"; }

ScriptRun "$@"
