#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [launcher](launcher)
$(ScriptName) commands."
}

init() { defaultCommand="launcher"; }
launcherCommand() { chrome start "https://launcher.keychron.com"; }

ScriptRun "$@"
