#!/bin/bash
. app.sh || exit

usage() {	echot "usage: LastPass [start|startup|close|restart](start)"; exit $1; }

args()
{
	unset -v command help
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";; # case-insensitive aliases
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start|startup|profile|service) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && IsFunction "${command}Usage" && { ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init() { program="$P32/LastPass/lastapp_x64.exe"; }
run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } # task close|CloseKill [--wait] [--title "$title"] "$program"; ProcessKill "$program"; SendKeys "$title" "!FX"; 
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";
profileCommand() {	profile --app "BeyondCompare" --method "<dir|exe|registry key|$program>" --files "*.ini *.xml" --save-extension "bcpkg" "$@"; }
restartCommand() { closeCommand && startCommand; }
startupCommand() { startCommand; }
startCommand() { ! IsInstalledCommand && return 1; IsRunningCommand && return 0; start "$program" "$@"; }

run "$@"