#!/usr/bin/env bash
. app.sh || exit


run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init()
{
	program="$WIN_ROOT/ProgramData/Logishrd/LogiOptions/Software/Current/LogiOptionsUI.exe"
	IsPlatform mac && program="$P/Logi Options.app"

	profileName="LogitechOptions$(ProperCase "$PLATFORM")"

	profileDir="$APPDATA/Logishrd/LogiOptions"
	IsPlatform mac && profileDir="$ADATA/Logitech/Logitech Options"

	return 0
}

usage() {	echot "usage: LogitechOptions
  profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1
	
	start $wait "$program" $waitArg "$@"
}

IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }

#ProcessKill LogiOptionsMgr.exe >& /dev/null; ProcessKill LogiOverlay.exe >& /dev/null
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 

restartCommand() { closeCommand && startCommand; }

profileCommand() { profile --app "$profileName" --method "$profileDir" --files "*" "$@" || usage 1; }

run "$@"
