#!/bin/bash
. app.sh
. office.sh init || exit 1

init()
{ 
	unset var
	title="Lync"
	program="$OfficeDir/lync.exe";

	BridgeNumber="87942663"
	PersonalBridge="2"
	PersonalPasscode="9056309"
	# # 87942663 +15057942663
}

usage() {	echot "usage: templateApp start|startup|close|restart|login|call|bridge|PersonalBridge
	bridge [bridge] [passcode]			call the Intel bridge"; exit $1; }

args()
{
	unset -v brief
	while [[ "$1" != "" ]]; do
		case "$1" in
			--brief|-b) brief="--brief";;
			--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";; PersonalBridge) command="PersonalBridge";; # case insensitive commands
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup|profile|service|call) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
}

callCommand() 
{ 
	[[ $# != 1 ]] && usage 1
	phone="$1"
	start /pgm "$program" Tel:$phone
	#SendKeys "$title" "+{TAB}+{TAB} "; sleep 3; # Lync 2010
	SendKeys "$title" "{TAB}{TAB}{ENTER}" # Lync 2013
}

bridgeCommand()
{
	[[ $# > 2 ]] && usage 1

	printf "Calling bridge..."
	lync call $BridgeNumber
	[[ $# == 0 ]] && { echo "done"; return; }

	bridge="$1"
	passcode="$2"

	[[ ! $bridge ]] && return
	printf bridge $bridge...
	SendKeys "$bridge"
	sleep 3s

	[[ ! $passcode ]] && return
	printf "passcode $passcode..."
	SendKeys "$passcode$#{ESC}"
	sleep 3s
	echo "done"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
PersonalBridge() { lync bridge $PersonalBridge $PersonalPasscode; }
loginCommand() { start lync.js login; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; task close $brief --title "$title" "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"