#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [cli|close|IsInstalled|IsRunning|profile|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	cli="$UADATA/MaxTo/app-2.2.1/MaxTo.exe"
	program="$UADATA/MaxTo/MaxTo.Core.exe"
}

cliArgs() { cliArgs="$@"; shift="$#"; }
cliCommand() { "$cli" "${cliArgs[@]}" "${otherArgs[@]}"; }
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$(GetFileName "$program")"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "MaxTo" --method "$UADATA/../Roaming/MaxTo" --files "Monitor config.json" --platform "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startupCommand() { startCommand "$@"; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

closeCommand()
{
	[[ ! $force ]] && ! isRunningCommand && return
	local quiet="/dev/null"; [[ "$quiet" == "status" ]] && quiet="/dev/stdout"
	"$cli" service stop >& $quiet
}


startCommand()
{
	AppInstallCheck || return
	[[ ! $force ]] && isRunningCommand && return
	local prefix=(); CanElevate && prefix=(elevate --window-style hidden)
	"${prefix[@]}" "$cli" service start
}


ScriptRun "$@"
