#!/bin/bash
#-x (debug) -v (verbose)
. function.sh || exit

usage()
{
	echot "\
usage: media collect|get|sync
  local [NUM](100)		copy NUM random picutres to the local computer
  frame  							copy media to a picture frame 
  nas									synchronize media with nas"
	exit $1
}

getUsage() { echot "\
usage: media get 
	-c, --copy				copy media 
	-d, --dest DEST 	destination directory
	-m, --move				move media
	    --no-metadata do not add import metadata
	-p, --person NAME person's name used in the destination folder
	-s, --source DIR	media source directory
	-t, --test 				test the operation without making any changes
	-v, --verbose			verbose output"; exit $1; }

args()
{
	unset -v command help
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			TestMetadata) command="TestMetadata";;
			*)
				! IsOption "$1" && IsInArray "$1" versions && { version="$1"; shift; continue; }
				[[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "$command" == @(get) ]] && break																						# defer argument processing
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	[[ ! $command ]] && { MissingOperand "command"; }
	args=("$@")
}

GetArgs()
{
	unset noMetadata person test verbose
	dest="$PUB" operationArg="default" ;
	while (( $# != 0 )); do
		case "$1" in
			--copy|-c) operation="copy";;
			--dest) dest="$2"; shift;;
			--move|-m) operation="move";;
			--no-metadata) noMetadata="true";;
			--person|-p) person="$2"; shift;;
			--source|-s) source="$2"; shift;;
			--test|-t) test="--test";;
			--verbose|-v) verbose="--verbose";;
			*) getUsage 1;;
		esac
		shift
	done
	[[ "$dest" && ! -d "$dest" ]] && { EchoErr "media get: directory  \`$dest\` does not exit"; return 1; }
	[[ ! $person ]] && person="$(FullName)"
	return 0
}

init() 
{
	mediaRoo=oversoul
	mediaUnc="//$mediaRoo/Public"
	nas="//nas"
	#videoSources=`"$mediaUnc/Videos" "$mediaDriveDir"`

	# Music: exclude WPL (Windows Playlists) - Sonos shows WPL but doesn't support auto playlists, so save auto playlists as M3U before copying
	musicFilters=-*.wpl
}

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }

getCommand()
{
	local importLocation processedDirs srcDirs metadataProcessed

	GetArgs "${args[@]}" || return
	GetInit || return
	
	if [[ "$source" ]]; then
		ProcessDir || return
	else
		for dir in "${localDirs[@]}"; do ProcessDir "$dir" || return; done
		for drive in "/cygdrive/"*; do ProcessDrive "$drive" || return; done
	fi

	if [[ $processedDirs ]]; then

		for dir in "${processedDirs[@]}"; do start explorer "$dir"; done
		pause "Review media then press any key to continue..."

		if [[ $metadataProcessed ]] && ask "Remove original images"; then
			printf "Removing original images..."
			for dir in "${srcDirs[@]}"; do 
				if ls "$dir/"*_original &> /dev/null; then
					[[ $verbose ]] && printf "\n(removing \`$dir/*_original\`)"
					[[ ! $test ]] && { rm "$dir/"*_original || return; }
					[[ ! $verbose ]] && printf "."
				fi
			done
			[[ ! $verbose ]] && echo "done"
		fi

	fi
}

ProcessDrive()
{
	local drive="$1" dir operation options importLocation
	
	[[ "$drive" == "c" ]] && return 0

	for dir in "${externalDirs[@]}"; do
		operation="$operationArg"
		IFS=":" read -a options <<<"$dir"; importLocation="${options[0]}"
		if [[ "$operation" == "default" ]]; then
			if IsInArray copy options; then operation="copy"
			elif IsInArray move options; then operation="move"
			else operation="move"; fi
		fi
		ProcessDir "${drive}${importLocation}" || return
	done
}

ProcessDir()
{ 
	local dir="$1" lastGetSeconds

	[[ ! -d "$dir" ]] && return

	case "$dir" in
		"$dropbox") importLocation="Dropbox";;
		"$iCloud") importLocation="iCloud";;
		*) [[ ! $importLocation ]] && importLocation="${dir///cygdrive/}";;
	esac
	printf "**************************************************\n* $importLocation\n**************************************************\n"	

	[[ -f "$dir/$lastGetDateFile" ]] && lastGetSeconds="$(cat "$dir/$lastGetDateFile")"

	shopt -s  nullglob
	for file in "$dir/"*; do ProcessFile "$file" || return; done
}

ProcessFile()
{
	local file="$1" fileName ext fileDesc mediaType destPrefix
	local fileSize="$(GetFileSize "$file" B)"
	GetFileName "$file" fileName || return
	GetFileExtension "$file" ext || return
	GetFileNameWithoutExtension "$file" fileDesc || return

	[[ "$operation" == "default" ]] && operation="move"

	if IsInArray "$ext" pictureExtensions; then
		mediaType="picture"; destPrefix="$destPicturePrefix"
	elif IsInArray "$ext" videoExtensions; then
	 mediaType="video"; destPrefix="$destVideoPrefix"
	else
		return 0
	fi 

	if [[ ! -d "$destPrefix" ]]; then
		ask "Create the destination directory $destPrefix" || return 1
		mkdir --parents "$destPrefix" || return
	fi

	printf "$fileName..."

	local -A fileMetadata destMetadata; GetMetadate file fileMetadata "${metadata[@]}" || return
	local dateTaken; GetDateTaken "$file" || return
	local dateTakenSeconds=$(GetSeconds "$dateTaken")
	local prefix="$(date "+%Y_%m_%d %H_%M_%S" -d "$dateTaken")"

	[[ $lastGetSeconds ]] && CompareTime $lastGetSeconds ">=" $dateTakenSeconds && 
		{ RemoveProcessedFile "$file" "$prefix"; return; }

	local destDir="$destPrefix/$(date +%Y -d "$dateTaken")/$(date +%Ym -d "$dateTaken")" 
	[[ ! -d "$destDir" ]] && { mkdir --parents "$destDir" || return; }

	local suffix dest="$destDir/$prefix.$ext"
	while [[ -f "$dest" ]]; do
		[[ "$mediaType" == "video" || "$fileSize" == "$(exiftool -s3 -ImportedFileSizeBytes "$dest")" ]] &&
			{ RemoveProcessedFile "$file" "$prefix-$suffix"; return; } 
		(( ++suffix )); dest="destDir/$prefix-$suffix.$ext" # use a suffix for rapid picture taking (same name, different size)
	done
	
	IsInArray "$destDir" processedDirs || processedDirs+=( "$destDir" )	
	IsInArray "$dir" srcDirs || srcDirs+=( "$dir" )	

	local operationDesc="moving"; [[ "$operation" == "copy" ]] && operationDesc="copying"
	printf "$prefix-$suffix..."

	[[ ! $noMetadata && "$ext" != @(mts) ]] && { AddMetadata || return; }

	local bigFile;	(( fileSize >= $bigFileSizeBytes )) && bigFile="true"
	GetCopyFile "$file" "$dest" || return

	[[ ! $test ]] && { echo "$dateTakenSeconds" > "$dir/$lastGetDateFile" || return; }

	if [[ "$operation" == "move" ]]; then
		[[ $verbose ]] && printf "\n(rm \`$file\`)"
		[[ ! $test ]] && { rm "$file" || return; }
	fi

	[[ ! $bigFile || $test ]] && echo "done"
	[[ $verbose ]] && pause
	return 0
}

AddMetadata()
{
	metadataProcessed="true"
	printf "metadata..."
	[[ $verbose ]] && printf "\n(exiftool \"$file\")"
	[[ $test ]] && return
	exiftool "$(utw "$file")" \
		-ImportedDate="$(date '+%Y:%m:%d %H:%M:%S')" \
		-ImportedFileModificationTime="$(date '+%Y:%m:%d %H:%M:%S' -d @$(stat -c%Y "$file"))" \
		-ImportedFileSizeBytes="$fileSize" \
		-ImportedOnHost="$COMPUTERNAME" \
		-ImportedByUser="$USERNAME" \
		-ImportedFromFolder="$importLocation" \
		-ImportedFileName="$fileName" \
		-ImportedToFolder="${destDir///cygdrive/}" > /dev/null
}

RemoveProcessedFile()
{
	local file="$1" desc="$2"
	[[ "$operation" == "copy" ]] && { echo "$desc already processed...skipping"; return 0; }
	printf "$desc already processed...removing..."
	[[ $verbose ]] && printf "(removing \`$file\`)"
	[[ ! $test ]] && { rm "$file" || return; }
	echo "done"
	return 0
}

GetCopyFile() # SRC DEST
{
	local src="$1" dest="$2" srcDir destDir srcFileName destFileName
	GetFilePath "$src" srcDir || return
	GetFilePath "$dest" destDir || return
	GetFileName "$src" srcFileName || return
	GetFileName "$dest" destFileName || return

	printf "$operationDesc..."
	[[ $verbose ]] && { printf "\n(cp \"$src\" \"$dest\")"; }
	[[ $test ]] && return 0
	[[ ! $bigFile ]] && { cp "$src" "$dest"; return; }

	[[ "$srcFileName" != "$destFileName" ]] && { mv "$src" "$srcDir/$destFileName" || return; }
	CopyDir --quiet "$srcDir" "$destDir" "$destFileName" || return
	[[ "$srcFileName" != "$destFileName" ]] && { mv "$srcDir/$destFileName" "$src" || return; }
}

GetDateTaken() # dateTaken format: YYYY-MM-DD HH:MM:SS
{
	# -fast2, -s2 -d "%Y:%m:%d %H:%M:%S"
	if IsInArray "$importLocation" dateTimeOriginalDirs; then
		dateTaken=( $(exiftool -s3 -d "%Y-%m-%d %H:%M:%S" "$(utw "$file")" -DateTimeOriginal | sed 's/\r\n//') )
		dateTaken="${dateTaken[@]:0:2}"
		[[ ! $dateTaken ]] && { EchoErr "media get: unable to find a date for \`$file\`"; return 1; }
	else
		dateTaken="$(stat -c%y "$file")" || return # y (modification) w (creation)
		dateTaken="${dateTaken%%.*}"
	fi
}

testCommand() { TestMetadataCommand; }

TestMetadataCommand()
{
	declare -A srcMetadata
	GetMetadata "/cygdrive/d/users/jjbutare/Desktop/DSC01581.JPG" srcMetadata -Make -Model -FileModifyDate 
	echo ${srcMetadata[Make]}

	for var in "${!srcMetadata[@]}"; do
		echo "$var=${srcMetadata[$var]}"
	done
	echo "${srcMetadata[FileModifyDate]}=$(date -d "${srcMetadata[FileModifyDate]}")"
}

GetMetadata() # 
{
	local file="$1" array="$2"
	eval "$array=( $(exiftool -s2 "$(utw "$file")" "${@:3}" | sed -e 's/: /]="/' -e 's/^/[/' -e 's/$/"/'  -e 's/:/-/' -e 's/:/-/' ) )"
}

GetInit()
{
	bigFileSizeBytes=5000000 # 5 MiB
	pictureExtensions=( jpg )
	videoExtensions=( 3gp mpg mp4 mts m2ts moff modd mov 3gp )
	metadata=( -Make -Model -DateTimeOriginal -ImportedFileSizeBytes )

	dropbox="$HOME/Dropbox/Camera Uploads"
	iCloud="$userPictures/iCloud Photos/My Photo Stream"
	localDirs=( "$DOC/data/download/pictures" "$iCloud" "$dropbox" )

	# options: GMT, copy, move
	unset externalDirs
	#externalDirs=( /DCIM/100OLYMP /mssony/moml0001 /dcim/100PHOTO )
	#externalDirs+=( /private/avchd/bdmv/stream:move )
	externalDirs+=( /dcim/100msdcf /dcim/101msdcf /mp_root/101pnv01:copy /avchd/bdmv/stream:copy )

	# determine media recording date: see Media Notes, Information, Media Recorded Date
	dateTimeOriginalDirs=( /dcim/100msdcf /dcim/101msdcf /mp_root/101pnv01 /avchd/bdmv/stream )

	lastGetDateFile=".media_last_get_date"
	fileFormat="^[0-9][0-9][0-9][0-9]_[0-9][0-9]_[0-9][0-9] [0-9][0-9]_[0-9][0-9]_[0-9][0-9]" # YYYY_MM_DD HH_MM_SS

	local nas="nas.hagerman.butare.net" suffix="Camera/$person"
	if network cache "$nas"; then
		destPicturePrefix="//$nas/photo/$suffix"
		destVideoPrefix="//$nas/video/$suffix"
	else
		destPicturePrefix="$(PublicPictures)/$suffix"
		destVideoPrefix="$(PublicVideos)/$suffix"
	fi

	processedDirs=()
}

syncCommand()
{
	merge "$PUB/Music" "//nas/music" || return
	merge "$PUB/Pictures" "//nas/photo" || return
	merge "$PUB/Videos" "//nas/video" || return
}

run "$@"
