#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: merge <src> <dest>
	Merge contents of source and destination files using an installed merge program"
	exit $1
}

[[ "$1" == @(-h|--help) ]] && usage 0

webDAV=; egrep -i "@ssl@5006" > /dev/null <<< "$@" && webDav="true"

if IsInstalled BeyondCompare && [[ ! $WebDAV ]]; then
	BeyondCompare start "$@"

elif IsInstalled WinMerge; then
	WinMerge start "$@"

elif IsInstalled emacs; then
	emacs start "$@"

else
	TextEdit "$@"

fi
