#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: merge SRC DEST
	Merge contents of source and destination files using an installed merge program"
	exit $1
}

[[ "$1" == @(-h|--help) ]] && usage 0

if HasWindowManager; then
	IsInstalled BeyondCompare && { BeyondCompare start "$@"; exit; }
	InPath ksdiff && { ksdiff "$@"; return; }
	InPath meld && { [[ "$1" == "--wait" ]] && { shift; meld "$@"; } || start meld "$@"; exit; }
	InPath kompare && { kompare "$@"; exit; }
fi

InPath delta && { delta --side-by-side "$@"; exit; }
TextEdit "$@"
