#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	echot "\
usage: template SRC DEST
	Move SRC directory to DEST directory
	-c, --copy						copy the directory instead of moving it
	-p, --parents					create destination parent directories
	-r, --rename					rename SRC, assume DEST ends with a new name for SRC
	-s, --suppress				suppress error message if SRC does not exist"
	exit $1
}

init() { :; }

args()
{
	unset copy src dest parents rename suppress
	while [ "$1" != "" ]; do
		case "$1" in
			--copy|-c) copy="--copy";;
			--parents|-p) parents="--parents";;
			--rename|-r) rename="--rename";;
			--suppress|-s) suppress="--suppress";;
			--help|-h) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				! IsOption "$1" && [[ ! $src ]] && { src="$1"; shift; continue; }
				! IsOption "$1" && [[ ! $dest ]] && { dest="${1%*/}"; shift; continue; }
				UnknownOption "$1"; return
		esac
		shift
	done
	[[ ! $src ]] && { MissingOperand "SRC"; return; }
	[[ ! $dest ]] && { MissingOperand "DEST"; return; }
	args=("$@")
}

run() 
{	
	init
	args "$@"

	# validate src
	if [[ ! -d "$src" ]]; then
		[[ $suppress ]] && return 0
		EchoErr "MergeDir: source directory \`$src\`: No such directory"
		return 1
	fi

	# rename
	[[ ! $rename ]] && dest="$dest/$(GetFileName "$src")"

	# make destination
	[[ ! -d "$dest" ]] && { ${G}mkdir $parents "$dest" || return; }

	# copy files
	if [[ "$(DirCount "$src")" != "0" ]]; then
		CopyDir --recursive "$src/" "$dest" || return
		#cp -r $ "$src/"* "$dest" || return
	fi

	# delete src
	[[ ! $copy ]] && rm -fr "$src" || return

	return 0
}

run "$@"
