#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: template SRC DEST
	Move SRC directory to DEST directory
	-p, --parents					create destination parent directories
	-s, --suppress				suppress errors if source or destination directories do not exist"
	exit $1
}

init() { :; }

args()
{
	unset src dest parents rename suppress
	while [ "$1" != "" ]; do
		case "$1" in
			-p|--parents) parents="--parents";;
			-r|--rename) rename="--rename";;
			-q|--suppress) suppress="--suppress";;
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				! IsOption "$1" && [[ ! $src ]] && { src="$1"; shift; continue; }
				! IsOption "$1" && [[ ! $dest ]] && { dest="${1%*/}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $src ]] && MissingOperand "SRC"
	[[ ! $dest ]] && MissingOperand "DEST"
	args=("$@")
}

run() {	
	init
	args "$@"

	if [[ ! -d "$src" ]]; then
		[[ $suppress ]] && return 0
		EchoErr "Source directory \"%src\" does not exist";
		return 1
	fi

	[[ ! $rename ]] && dest="$dest/$(GetFilename "$src")"

	if [[ ! -d "$dest" ]]; then
		if [[ $parents ]]; then 
			mkdir --parents "$dest" || return;
		else
			[[ $suppress ]] && return 0
			EchoErr "Destination directory \"$dest\" does not exist"
			return 1
		fi
	fi;		

	cp -rp "$src/"* "$dest" || return
	rm -fr "$src" || return
	return 0
}

run "$@"
