#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: template SRC DEST
	Move SRC directory to DEST directory
	-p, --parents					create destination parent directories
	-r, --rename					rename SRC, DEST ends with a new name for SRC
	-s, --suppress				suppress error message if SRC does not exist"
	exit $1
}

init() { :; }

args()
{
	unset src dest parents rename suppress
	while [ "$1" != "" ]; do
		case "$1" in
			-p|--parents) parents="--parents";;
			-r|--rename) rename="--rename";;
			-s|--suppress) suppress="--suppress";;
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			*)
				! IsOption "$1" && [[ ! $src ]] && { src="$1"; shift; continue; }
				! IsOption "$1" && [[ ! $dest ]] && { dest="${1%*/}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $src ]] && MissingOperand "SRC"
	[[ ! $dest ]] && MissingOperand "DEST"
	args=("$@")
}

run() {	
	init
	args "$@"

	if [[ ! -d "$src" ]]; then
		[[ $suppress ]] && return 0
		EchoErr "MergeDir: source directory \`$src\`: No such directory"
		return 1
	fi

	[[ ! $rename ]] && dest="$dest/$(GetFilename "$src")"

	[[ ! -d "$dest" ]] && { mkdir $parents "$dest" || return; }

	cp -rp "$src/"* "$dest" || return
	rm -fr "$src" || return
	return 0
}

run "$@"
