#!/usr/bin/env bash
. function.sh

usage()
{
	echot "\
usage: merge SRC DEST
	Merge contents of source and destination files using an installed merge program"
	exit $1
}

[[ "$1" == @(-h|--help) ]] && usage 0

if HasWindowManager; then
	IsInstalled BeyondCompare && { BeyondCompare start "$@"; return; }
	InPath meld && { [[ "$1" == "--wait" ]] && { shift; meld "$@"; } || start meld "$@"; return; }
	InPath kompare && { kompare "$@"; return; }
fi

TextEdit "$@"
