#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() 
{
	program="micro"
	dir="$HOME/.config/micro"
	[[ ! -d "$dir" ]] && { mkdir "$dir" || return; }
	return 0
}

usage() {	echot "usage: MicroHelper profile|update
	profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset -v brief noPrompt

	while (( $# != 0 )); do
		case "$1" in
			--brief|-b) brief="--brief";;
			--help|-h) usage 0;;
			--no-prompt|-np) noPrompt="--no-prompt";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

updateCommand() { RunInDir "/usr/local/bin" "curl https://getmic.ro | sudoc bash" || return; }
profileCommand() { profile $noPrompt --app "micro" --method "$dir" --files "*" "$@" || usage 1; }

run "$@"
