#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) IsInstalled|service
MongoDB datbase server functionality."
}

#
# commands
#

isInstalledCommand() { InPath mongod; }
versionCommand() { mongod --version | head -1 | cut -d" " -f3 | RemoveFront "v"; }

ScriptRun "$@"
