#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... add|ls|remove
$(ScriptName) commands."
}

#
# add command
#

addUsage() { ScriptUsageEcho "Usage: $(ScriptName) add FILE\nAdd (install) an MSIX package."; }
addArgStart() { unset -v file; }
addArgs() { ScriptArgGet --required "file" -- "$@" && ScriptCheckFile "$file"; }
addCommand() { ps 'Add-AppxPackage -Path '$(utw "$file")' -ErrorAction Stop'; }

#
# ls command
#

lsUsage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... ls
List installed MSIX packages.

	-d, --detail		$(ScriptOptDetailUsage)"
}

lsArgStart() { ScriptOptDetailArgStart; }

lsOpt()
{
	case "$1" in
		--detail|-d|-dd|-ddd|-dddd|-ddddd) ScriptOptDetail "$1";;
		*) return 1;;
	esac
}

lsCommand()
{
	# name only
	if [[ ! $detail ]]; then
		ps 'Get-AppxPackage | Select-Object -ExpandProperty Name | Sort-Object'

	# several columns
	elif (( detailLevel == 1 )); then
		ps 'Get-AppxPackage | Select-Object Name, Version, PackageFullName | Format-Table -AutoSize'	

	# all columns
	else
		ps 'Get-AppxPackage'

	fi
}

#
# remove command
#

removeUsage() { ScriptUsageEcho "Usage: $(ScriptName) add PACKAGE\nRemove (uninstall) an MSIX package.  The name can include wildcards (*)."; }
removeArgStart() { unset -v name; }
removeArgs() { ScriptArgGet "name" -- "$@"; }
removeCommand() { RunLog powershell 'Get-AppxPackage -Name "'$name'" | Remove-AppxPackage'; }

#
# helper
#

ps() { local args=(); [[ $verbose ]] && args=(-Verbose); RunScript --elevate "${globalArgs[@]}" -- powershell.exe "$@" "${args[@]}"; }
psRaw() { RunScript --elevate -- powershell.exe "$@"; }

ScriptRun "$@"
