#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... domains|hosts|update
Manage namecheap DNS."
}						 

#
# Domains Command
#

domainsUsage()
{
	echot "Usage: $(ScriptName) domains
List all domains."
}

domainsCommand() { api "namecheap.domains.getList"; }

#
# Hosts Command
#

hostsUsage()
{
	echot "Usage: $(ScriptName) hosts [domain]
Get host record for the domain."
}

hostsArgs() 
{ 
	[[ $# == 0 ]] && { domain="$(GetDnsBaseDomain)"; return; }
	ScriptArgGet "domain" -- "$@"; shift
}

hostsCommand()
{
	local sld="$(GetWord "$domain" 1 .)"
	local tld="$(GetWord "$domain" 2 .)"
	api "namecheap.domains.dns.getHosts&SLD=$sld&TLD=$tld" || return
}

#
# Update Command
#

updateUsage()
{
	echot "Usage: $(ScriptName) update HOST IP
Update a DNS HOST record to IP."
}

updateArgs()
{
	ScriptArgGet "host" -- "$@"; shift
	ScriptArgGet "ip" -- "$@"; shift
}

updateCommand()
{
	local currentIp; currentIp="$(UpdateGet "ip_$host")" && [[ "$currentIp" == "$ip" ]] && return
	local domain; domain="$(GetDnsBaseDomain)" || return
	local password; password="$(credential get namecheap ddns_password)" || return
	curl "https://dynamicdns.park-your-domain.com/update?host=$host&domain=$domain&password=$password&ip=$ip" || return
	UpdateSet "ip_$host" "$ip" || return
}

	# domains				list all domains
	# hosts	DOMAIN	list hosts for specified domain

#
# API Helper
#

api()
{
	local user; user="$(credential get namecheap user)" || return
	local key; key="$(credential get namecheap key)" || return
	local ip; ip="$(network internet address)" || return
	local url="https://api.namecheap.com/xml.response?ApiUser=$user&ApiKey=$key&UserName=$user&ClientIp=$ip&Command=$1"
	[[ $verbose ]] && printf 'curl "%s"' "$url"
	curl "$url"
}

ScriptRun "$@"
