#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() { ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... check\n$(ScriptName) commands."; }
checkArgs() { ScriptArgGet "host" -- "$@"; }

checkCommand()
{
	local ok; ok="$(curl --silent "http://$host:81/api/" | jq --raw-output '.status')"
	echo "$ok"; [[ "$ok" == "OK" ]]
}
									 
ScriptRun "$@"
