#!/usr/bin/env bash
. app.sh || exit

usage() { ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... check
$(ScriptName) commands."; }

checkArgs() { ScriptArgGet "host" -- "$@"; shift; }

checkCommand()
{
	local ok; ok="$(curl --silent "http://$host:81/api/" | jq --raw-output '.status')"
	echo "$ok"; [[ "$ok" == "OK" ]]
}
									 
ScriptRun "$@"
