#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [IsInstalled|IsRunning|profile|program|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="nix" profileDir="$HOME"	profileMask="default.nix"
	program="nix"
}

closeCommand() { :; }
isInstalledCommand() { InPath "$program"; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { ScriptUsageEcho "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
programCommand() { echo "$program"; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { :; }
versionCommand() { AppInstallCheck && AppVersion "$(FindInPath "$program")"; }

ScriptRun "$@"
