#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [IsInstalled|IsRunning|profile|startversion](start)
$(ScriptName) commands."
}

init() { defaultCommand="start" program="nom"; }
isInstalledCommand() { InPath "$program"; }
profileUsage() { ScriptUsageEcho "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgStart() { AppInstallCheck; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { AppInstallCheck && profile $noPrompt --app "$profileName" --method "$(GetFilePath "$(profileFile)")" --files="$(GetFileName "$(profileFile)")" "${profileArgs[@]}"; }
profileFile() { InPath nom && nom config | grep "^configpath:" | cut -d":" -f2 | RemoveSpaceTrim; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && "$program" "${startArgs[@]}" "${otherArgs[@]}"; }
versionCommand() { AppInstallCheck && "$program" version; }
									 
ScriptRun "$@"
