#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	title=".*Notepad++"
	program="$P/Notepad++/notepad++.exe"
	profileName="NotepadPP"
	profileDir="$UADATA/../Roaming/Notepad++"
	profileMask="config.xml contextMenu.xml shortcuts.xml stylers.xml userDefineLang.xml *.ini plugins\config\*.ini"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsTaskRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startupCommand() { startCommand; }

#
# Start Command
#

startUsage()
{
	echot "Usage: $(ScriptName) start [FILES]
Start Notepad++.

	-d, --duplicate			open a new instance"
}

startOpt()
{
	unset -v duplicate
	case "$1" in
		-d|--duplicate) duplicate="-multiInst";;
		*) return 1;;
	esac
}

startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait $duplicate "$program" "${startArgs[@]}"; }
		
ScriptRun "$@"
