#!/usr/bin/env bash
#-x (debug) -v (verbose)
. function.sh || exit

usage()
{
	echot "\
usage: numlock [set on|off]|[boot on|off|status](set)
	Show or set the boot status of numlock key"
	exit $1
}

args()
{
	unset -v file
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			*)
				[[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "$command" == @(boot|set) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=("$@")
}

init() 
{ 
	userKey="HKEY_CURRENT_USER/Control Panel/Keyboard/InitialKeyboardIndicators"
	defaultKey="HKEY_USERS/.DEFAULT/Control Panel/Keyboard/InitialKeyboardIndicators"
}

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }

bootCommand()
{
	local command; CheckSubCommand boot "$1"; shift
	[[ $# != 0 ]] && UnknownOption "$1"
	$command "$@"
}

bootOnCommand() { SetBoot 2 || return; SetOnCommand || return; BootStatusCommand; }
bootOffCommand() { SetBoot 0 || return; SetOffCommand || return; BootStatusCommand;}

bootStatusCommand() 
{
	local state="unspecified" status="$(registry get "$userKey")"

	case "${status:0:1}" in # ignore trailing null
		0) state="off";;
		2) state="on";;
	esac
	echo "NumLock will be $state when the system starts."
	return 0
}

SetBoot()
{
	registry set "$userKey" REG_SZ "$1" || return
	registry set "$defaultKey" REG_SZ "$1" || return
	return 0
}

setCommand()
{
	local command; CheckSubCommand set "$1"; shift
	[[ $# != 0 ]] && UnknownOption "$1"
	$command "$@"
}

setOnCommand() { start SetKeyState.exe NumLock on; }
setOffCommand() { start SetKeyState.exe NumLock off; }

run "$@"
