#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
usage: numlock boot|set
Numlock key commands."
}

init()
{
	ScriptOnlyWin || return
	userKey="HKEY_CURRENT_USER/Control Panel/Keyboard/InitialKeyboardIndicators"
	defaultKey="HKEY_USERS/.DEFAULT/Control Panel/Keyboard/InitialKeyboardIndicators"
}

#
# Boot Command
#

bootUsage()
{
	echot "Usage: $(ScriptName) boot [on|off|status](status)
numlock state for computer boot."
}

bootCommand() { bootStatusCommand; }
bootOnCommand() { setBoot 2 && setOnCommand && bootStatusCommand; }
bootOffCommand() { setBoot 0 && setOffCommand && bootStatusCommand;}

bootStatusCommand() 
{
	local state="unspecified" status="$(registry get "$userKey")"

	case "${status:0:1}" in # ignore trailing null
		0) state="off";;
		2) state="on";;
	esac

	echo "NumLock will be $state when the system starts."
}

setBoot()
{
	registry set "$userKey" REG_SZ "$1" || return
	registry set "$defaultKey" REG_SZ "$1" || return
	return 0
}

#
# Set Command
#

setUsage()
{
	echot "Usage: $(ScriptName) set on|off
Set numlock state."
}

setCommand() { usage; }
setOnCommand() { ! InPath SetKeyState.exe && return; start SetKeyState.exe NumLock on; }
setOffCommand() { ! InPath SetKeyState.exe && return; start SetKeyState.exe NumLock off; }

ScriptRun "$@"
