#!/usr/bin/env bash
. script.sh || exit
. office.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... profile"
}

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { pause profile $noPrompt --app "Office Templates" --method "$OfficeTemplates" --files "*" "${profileArgs[@]}" || usage 1; }

ScriptRun "$@"
