#!/usr/bin/env bash
. function.sh || exit
. office.sh || exit

run() {	init && args "$@" && ${command}Command "${args[@]}"; }

init() { :; }

usage()
{
	echot "
usage: $(ScriptName)
	profile dir|SaveDir|save|restore [<profile name>|default](latest)"
	exit ${1:-1}
}

args()
{
	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-h|--help) usage 0;;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; command="${1,,}"; shift; continue; }
				[[ "$command" == @(profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done

	[[ ! $command ]] && { usage; }

	args=("$@")
}

#
# commands
#

profileCommand() { profile $noPrompt --app "Office Templates" --method "$OfficeTemplates" --files "*" "$@" || usage 1; }

run "$@"
