#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script office || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... profile"
}

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "Office Templates" --method "$OfficeTemplates" --files "*" "${profileArgs[@]}"; }

ScriptRun "$@"
