#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]...  [COMMAND]...
$(ScriptName) commands.

	program commands: close|IsInstalled|IsRunning|program|restart|start|startup|vars|version"
}

init()
{
	unset -v apiInitialized program baseDir rootDir userDir rootDirPattern
	defaultCommand="start"

	# platform configuration
	case "$PLATFORM_OS" in
		mac)
			program="$P/OneDrive.app"
			baseDir="$HOME/Library/CloudStorage"
			rootDirPattern="OneDrive-*"
			rootDir="$(FindDir "$baseDir" "$rootDirPattern" | sort -r | head -1)" # put root directory with - first
			;;
		win)
			program="$P/Microsoft OneDrive/OneDrive.exe"
			baseDir="$WIN_HOME"
			rootDirPattern="OneDrive*"
			rootDir="$(FindDir "$baseDir" "$rootDirPattern" | sort -r | head -1)" # put root directory with - first
			;;
	esac

	# other configuration
	homeDir="$HOME/OneDrive"
	userDir="$rootDir"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
varsUsage() { echot "Usage: $(ScriptName) vars\nReturn Dropbox configuration variables: program baseDir homeDir rootDir rootDirPattern userDir"; }
varsCommand() { AppInstallCheck && ScriptReturn "program" "baseDir" "homeDir" "rootDir" "rootDirPattern" "userDir"; }
versionCommand() { AppInstallCheck && AppVersion "$program" | cut -d"." -f1-3; }

#
# helper
#

ScriptRun "$@"
