#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|dir|IsInstalled|IsRunning|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$P/OpenSpeedTest-Server.app"
	programRunning="$P/OpenSpeedTest-Server.app/Contents/MacOS/OpenSpeedTest-Server"
}

configCommand() { echo "Loading Karabiner-Elements configuration folder in the text editor..."; TextEdit "$profileDir"; }
closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
dirCommand() { echo "$profileDir"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$programRunning"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
