#!/usr/bin/env bash
. app.sh

# Test homebridge-script2
#
#         {
#            "accessory": "Script2",
#            "name": "Oversoul VR",
#            "on": "OversoulVrState on",
#            "off": "OversoulVrState off",
#            "state": "OversoulVrState state",
#            "on_value": "on"
#        }

if [[ "$1" == "on" ]]; then
	! HostUtil available oversoul && { HostUtil boot oversoul --wait || exit 1; sleep 10s; }
	ssh oversoul bash -i -c 'monden' >& /dev/null || exit 1
	
elif [[ "$1" == "off" ]]; then
	ssh oversoul bash -i -c 'monstudy' >& /dev/null || exit 1
	
elif [[ "$1" == "state" ]]; then
	! HostUtil available oversoul && { echo off; exit 0; }
	ssh oversoul bash -i -c 'moninfo | egrep "LG TV" --after-context=2 | grep "Enabled=true"' >& /dev/null && echo on || echo off
	
else
	EchoErr "ERROR: invalid state"
	exit 1
fi

exit 0

