#!/usr/bin/env bash
. app.sh || exit

run() {	init || return; startCommand "$@"; }

init() 
{ 
	partitionAssistant="$P32/AOMEI Partition Assistant/PartAssist.exe"
}

usage() {	echot "usage: PartitionManager"; exit $1; }

startCommand() 
{ 
	program=() start="start"
	
	! HasWindowManager && { EchoErr "No partition manager is available"; return 1; }

	case "$PLATFORM" in

		mac) start "Disk Utility.app";;

		win) 
			if [[ -f "$partitionAssistant" ]]; then elevate "$partitionAssistant"
			else elevate diskmgmt.msc
			fi
			;;

	esac

	if InPath partitionmanager; then ( sudox partitionmanager & ) >& /dev/null
	elif InPath gparted; then ( sudox gparted & ) >& /dev/null
	elif InPath gnome-disks; then ( sudox gnome-disks & ) >& /dev/null
	fi

}

run "$@"