#!/usr/bin/env bash
. app.sh || exit

run() {	init && args "$@" && startCommand "$@"; }

init() 
{ 
	partitionAssistant="$P32/AOMEI Partition Assistant/PartAssist.exe"
}

usage()
{
	echot "usage: PartitionManager
	-l, --linux		only start the Linux partition manager
	-w, --win			only start the Windows partition manager"
	exit ${1:-1}
}

args()
{
	unset linux win

	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-h|--help) usage 0;;
			-l|--linux) linux="true";;
			-w|--win) win="true";;
			*) UnknownOption "$1";;
		esac
		shift
	done
}

startCommand() 
{ 
	! HasWindowManager && { EchoErr "No partition manager is available"; return 1; }
	RunPlatform start || return
}

startLinux()
{
	if InPath partitionmanager; then ( sudox partitionmanager & ) >& /dev/null
	elif InPath gparted; then ( sudox gparted & ) >& /dev/null
	elif InPath gnome-disks; then ( sudox gnome-disks & ) >& /dev/null
	fi
}

startMac() { start "Disk Utility.app"; }

startWin()
{
	if [[ ! $linux ]]; then
		if [[ -f "$partitionAssistant" ]]; then elevate "$partitionAssistant"
		else elevate diskmgmt.msc
		fi
	fi

	[[ ! $win ]] && { startLinux || return; }

	return 0
}

run "$@"