#!/usr/bin/env bash
#-x (debug) -v (verbose)
. function.sh || exit

usage()
{
	echot "\
usage: password
	User password management
	change [ChangeNas] [USER](current) [PASSWORD]"
	exit $1
}

args()
{
	unset command help dest exclude file show arg1 arg2
	versions=( 2013 2012 )
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			ChangeNas) command="ChangeNas";;
			*)
				[[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "$command" == @(change|ChangeNas) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage || usage 0; }
	[[ ! $command ]] && { MissingOperand "command"; }
	args=("$@")
}

init() { :; }
run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }

changeCommand()
{
	IsInDomain && { echo "ctrl-alt-del / ctrl-win-del (VMware) / ctrl-alt-end (Remote Desktop), Change Password"; return 0; }	

	local passowrd
	case $# in
		0) user="$USER";;
		1) password=$1;;
		2) user="$1"; password="$2";;
		*) usage 1
	esac
	
	[[ "$PLATFORM" == "win" ]] && { sudo --wait run.sh --multiple 'pspasswd "'$user'" "'$password'"; pause'; return; }
	passwd "$user"
}

ChangeNasCommand()
{
	[[ $# != 2 ]]	&& usage 1
	local user="$1" password="$2"

	HostUtil available nas || return

	read -s -p "Enter $user current butare.net LDAP password: " ldapPassword; echo
	ssh nas ldappasswd -x -D "uid=$user,cn=users,dc=butare,dc=net" -w "$ldapPassword" -s "$password" "uid=$user,cn=users,dc=butare,dc=net" || return
	echo "$user@butare.net password successfully changed"
	echo 

	ssh root@nas /usr/syno/sbin/synouser -setpw "$user" "$password" || return
	echo "NAS\\$user password successfully changed"
	echo
}
run "$@"
