#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$P/Pearcleaner.app"
}

closeCommand() { ! isRunningCommand && return; ProcessClose "$(GetFileNameWithoutExtension "$program")"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "pearcleaner" --method "$HOME/Library/Preferences" --files "com.alienator88.Pearcleaner.plist" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && open "$program"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && defaults read "$program/Contents/Info.plist" CFBundleVersion; }

ScriptRun "$@"
