#!/bin/bash
. app.sh || exit

usage() {	echot "usage: pGina [start](start)
  profile dir|SaveDir|backup|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";; # case-insensitive aliases
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "${command:-start}" == @(profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'
	args=( "$@" )
}

run() {	args "$@"; init; ${command}Command "${args[@]}"; }
init() { set program="$P/pGina/pGina.Configuration.exe"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

profileCommand() 
{
	echot "\
On save, remove:
- SearchPW - prevent pGina crash on LDAP configuration
- Password - prevent pGina crash on MySQL Logger configuration"
	profile --app "pGina" --method "HKEY_LOCAL_MACHINE\SOFTWARE\pGina3" "$@" || return; 
}

run "$@"