#!/bin/bash
. app.sh || exit

usage() {	echot "usage: picasa [start [DB]|close|restart](start)"; exit $1; }

args()
{
	unset -v help
	command="start"
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init()
{ 
	program="$P32/Google/Picasa3/Picasa3.exe"
	starter="$P32/PicasaStarter/PicasaStarter.exe"
}

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	local db="$1" args
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	if [[ $# == 1 ]]; then
		[[ "$db" == @(butare|butare.net|nas|wiggin) ]] && db="photo.butare.net"
		[[ "$db" != @(starter|select) ]] && args=( /autorun "$db" )
		start -d="$P32/PicasaStarter" "$starter" "${args[@]}"
	else
		start "$program" "$@"
	fi
}

run "$@"