#!/usr/bin/env bash
. script.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... template
$(ScriptName) commands."
}

init()
{
	baseDir="$CODE/pitstop"
	schemaDir="$baseDir/cx.model.pitstop.schema"
}

#
# template commands
#

templateUsage() { ScriptUsageEcho "Usage: $(ScriptName) template repo\nPitstop template commands."; }
templateCommand() { usage; }

templateRepoUsage() { ScriptUsageEcho "Usage: $(ScriptName) template repo\nCreate template repositories."; }

templateRepoCommand()
{
	local templateFile="$schemaDir/template/all-templates.yaml"
	local repo repos; IFS=$'\n' ArrayMake repos "$(yq '.spec.targets[]' "$templateFile")"

	# setup local directory for template repos
	local repoDir="$baseDir/template"
	${G}mkdir --parents "$repoDir" || return
	cd "$repoDir" || return
	
	# clone template repos if needed
	for repo in "${repos[@]}"; do
		repo="$(echo "$repo" | sed 's/\/blob.*//')"
		repoName="$(GetFileName "$repo")"
		[[ -d "$repoName" ]] && continue
		hilight "Cloning $repoName..."
		git clone "$repo" || return
	done
}


#
# helper
#


ScriptRun "$@"
