#!/usr/bin/env bash
. script.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... template
$(ScriptName) commands."
}

init()
{
	baseDir="$CODE/pitstop"
	schemaDir="$baseDir/cx.model.pitstop.schema"
	templateDir="$baseDir/templates"
	uiDir="$baseDir/cx.ui.pitstop.web"
}

#
# template commands
#

templateUsage() { ScriptUsageEcho "Usage: $(ScriptName) template repo\nPitstop template commands."; }
templateCommand() { usage; }

templateRepoUsage() { ScriptUsageEcho "Usage: $(ScriptName) template repo\nCreate template repositories."; }

templateRepoCommand()
{
	local templateFile="$schemaDir/template/all-templates.yaml"
	local repo repos; IFS=$'\n' ArrayMake repos "$(yq '.spec.targets[]' "$templateFile")"

	# setup local directory for template repos
	${G}mkdir --parents "$templateDir" || return
	[[ ! -L "$uiDir/templates" ]] && { ln -s "../templates" "$uiDir" || return; }
	
	# clone template repos if needed
	cd "$templateDir" || return
	for repo in "${repos[@]}"; do
		repo="$(echo "$repo" | sed 's/\/blob.*//')"
		repoName="$(GetFileName "$repo")"
		[[ -d "$repoName" ]] && continue
		hilight "Cloning $repoName..."
		git clone "$repo" || return
	done
}


#
# helper
#


ScriptRun "$@"
