#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|stop|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

	# find program
	case "$PLATFORM_OS" in
		mac) program="$P/Podman Desktop.app";;
		win) program="$P/Podman Desktop/Podman Desktop.exe"; [[ ! -f "$program" ]] && program="$UADATA/Programs/Podman Desktop/Podman Desktop.exe";;
		*) unset program;;
	esac

	return 0
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start "$program" "${startArgs[@]}" "${otherArgs[@]}"; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; AppInstallCheck && start "$program" --minimized; }
stopCommand() { closeCommand; } 
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
