#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [cli|close|IsInstalled|IsRunning|program|restart|start|startup|stop|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="podman"

	# find program
	case "$PLATFORM_OS" in
		win) program="$P/RedHat/Podman/podman.exe";;
		*) unset program;;
	esac
}

cliUsage() { ScriptUsageEcho "Usage: $(ScriptName) cli [ARGS]..."; }
cliArgs() { cliArgs=( "$@" ); shift="$#"; }
cliCommand() { AppInstallCheck && podman "${cliArgs[@]}" "${otherArgs[@]}"; }
closeCommand() { ! isRunningCommand && return 0; "$program" machine stop; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { isInstalledCommand && podman machine list | ${G}grep "podman-machine-default" | qgrep "running"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { [[ ! $force ]] && isRunningCommand && return; AppInstallCheck && podman machine start; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; AppInstallCheck && podman machine start --quiet; }
stopCommand() { closeCommand; } 
versionCommand() { AppInstallCheck && "$program" --version | ${G}cut -d' ' -f3; }

#
# helper
#

podman() { RunWin "$program" "$@"; }

ScriptRun "$@"
