#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) dir|info|IsInstalled|IsRunning|patroni|run|service|vars
PostgreSQL datbase server functionality.

	-i,	 --instance=INSTANCE		the instance to use
	-v,	 --version=VERSION			the version to use

	-H,  --host=HOST						the database to use, defaults to localhost
	-db, --database=DATABASE		the database to use, defaults to postgres

	-u,	 --user=USER						the user to use, defaults to postgres
	-p,	 --password=VERSION			the password to use"
}

init()
{
	defaultCommand="run"
	confDirBase="/etc/postgresql"
	dataDirBase="/var/lib/postgresql"
	patroniConf="/etc/patroni/config.yml"
	patroniPortDefault="8008"
	patroniScopeDefault="postgres-db"
	patroniService="patroni"
	postgresPort="5432"
}

argStart()
{
	unset -v binDir confDir dataDir instance version password service;
	unset -v patroniPort patroniScope;
	user="postgres" host="localhost" database="postgres"
}

opt()
{
	case "$1" in

		--instance|--instance=*|-i|-i=*) ScriptOptGet "instance" "$@";;
		--version|--version=*|-n|-n=*) ScriptOptGet "version" "$@";;

		--user|--user=*|-u|-u=*) ScriptOptGet "user" "$@";;
		--password|--password=*|-p|-p=*) ScriptOptGet "password" "$@";;

		--host|--host=*|-H|-H=*) ScriptOptGet "host" "$@";;
		--database|--database=*|-db|-db=*) ScriptOptGet "database" "$@";;

		*) return 1;;
	esac
}

argEnd()
{	
	export PGHOST="$host"
	export PGDATABASE="$database"
	export PGUSER="$user"
	export PGPASSWORD="$password"
}

#
# commands
#

dirCommand() { findPostgres && echo "$confDir"; }
isInstalledCommand() { [[ -d "$confDirBase" ]]; }
isRunningCommand() { isInstalledCommand && IsAvailablePort localhost "$postgresPort"; }
varsCommand() { findPostgres && ScriptReturn version instance binDir confDir confDirBase dataDir dataDirBase service; }

#
# info command
#

infoUsage() { ScriptUsageEcho "Usage: $(ScriptName) info postgres|patroni"; }
infoCommand() {	infoPostgresCommand && patroniInfoCommand; }

infoPostgresCommand()
{
	local desc; isRunningCommand && desc=" (running)"
	findPostgres || desc=" (not installed)"
	header "PostgreSQL$desc"
	! isInstalledCommand  && return
	varsCommand || return
	serviceExistsCommand && echo "service=$(serviceStatusCommand)"
	return 0
}

infoPatroniCommand()
{
	local desc; patroniIsRunningCommand && desc=" (running)"
	! patroniIsInstalled && desc=" (not installed)"
	header "Patroni$desc"


	InPath consul && echo "leader="$(patroniLeaderCommand)""


	! patroniIsInstalled && return
	echo "patroniConf=$patroniConf"
	echo "port=$(getPatroniPort)"
	patroniServiceExistsCommand && echo "service=$(patroniServiceStatusCommand)"
	[[ $desc ]] && patroniCtrl "topology"
	return 0
}

#
# run command
#

runArgs() { commandArg="$@"; shift+=$#; }

runCommand()
{
	local args=(); [[ $commandArg ]] && args=(--command "$commandArg")
	getPassword && psql "${args[@]}"
}

#
# patroni commands
#

patroniUsage() { ScriptUsageEcho "Usage: $(ScriptName) patroni ctl|info|leader|start|stop|tag|IsInstalled|IsRunning|service"; }
patroniCommand() { usage; }

patroniInfoCommand() { infoPatroniCommand; }
patroniLeaderCommand() { patroniLeader; }
patroniIsInstalled() { InPath patroni; }
patroniIsRunningCommand() { patroniIsInstalled && patroniIsRunning; }
patroniIsRunning() { IsAvailablePort localhost "$(getPatroniPort)"; }

patroniStartCommand()
{
	patroniValidateInstall || return
	patroniIsRunning && { echo "Patroni is already running"; return; }
	( cd "/tmp"; sudoc -u postgres patroni "$patroniConf" )
}

patroniStopCommand()
{
	patroniValidateInstall || return
	! patroniIsRunning && { echo "Patroni is not running"; return; }
	echo "Stopping Patroni..."
	sudoc pkill "patroni"
}

#
# patroni ctl commands
#

patroniCtlArgStart() { patroniCtlArgs=(topology); }
patroniCtlArgEnd() { patroniValidateInstall; }
patroniCtlArgs() { [[ $@ ]] && patroniCtlArgs=( "$@" ); (( shift+=$# )); return 0; }
patroniCtlCommand() { patroniCtrl "${patroniCtlArgs[@]}" "${otherArgs[@]}"; }
patroniCtrl() { CONSUL_HTTP_ADDR= patronictl --config-file "$patroniConf" "$@"; }

#
# patroni service commands
#

patroniServiceUsage() { ScriptUsageEcho "Usage: $(ScriptName) service detail|exists|install|log|restart|running|start|status|stop"; }
patroniServiceCommand() { serviceStatusCommand; }
patroniServiceArgEnd() { patroniValidateInstall; }
patroniServiceDetailCommand() { service detail $patroniService; }
patroniServiceExistsCommand() { service exists $patroniService; }
patroniServiceLogCommand() {	service log $patroniService; }
patroniServiceRestartCommand() { service restart "$patroniService"; }
patroniServiceRunningCommand() { service running "$patroniService"; }
patroniServiceStartCommand() { service start "$patroniService"; }
patroniServiceStatusCommand() { service status "$patroniService"; }
patroniServiceStopCommand() { service stop "$patroniService"; }

#
# patroni tag commands
#

patroniTagUsage() { ScriptUsageEcho "Usage: $(ScriptName) tag [HOST|all](localhost)\nUpdate Nomad service tags for the specified hosts."; }
patroniTagArgStart() { host="localhost"; }
patroniTagArgs() { [[ ! $@ ]] && return; ScriptArgGet "host" -- "$@"; shift; }

patroniTagCommand()
{
	[[ "$host" != "all" ]] && { patroniTag "$host"; return; }
	GetHostsApp "$(getPatroniScope)" active && ForAllHosts patroniTag  --header "Patroni Tag"
	return 0
}

# patroniTag HOST
patroniTag()
{
	# get the host
	local host="$1"; ! HasDnsSuffix "$host" && { host="$(DnsResolve "$host")" || return; }
	local hostShort="$(RemoveDnsSuffix "$host")"

	# get the name of the Nomad service, which is the same as the Patroni scope
	local service="$(getPatroniScope)"

	# get the current leader
	local leader; leader="$(patroniLeaderCommand)" || return

	# get the existing tags for the host
	local existingTags; existingTags="$(consul catalog services -node="$hostShort" -tags | grep "^$service " | tr -s " " | cut -d" " -f2)" || \
		{ ScriptErr "unable to get existing tags for service '$service' from host '$host'"; return 1; }
	existingTags="$(StringSort "$existingTags")"

	# get the new tags for this host
	local newTags="replica"; [[ "$hostShort" == "$leader" ]] && newTags="primary,master"
	newTags="$(StringSort "$newTags")"

	log1 "host=$host hostShort=$hostShort service=$service leader=$leader existingTags=$existingTags newTags=$newTags"
	[[ ! $force && "$newTags" == "$existingTags" ]] && return

	# get and modify existing service
	hilight "Getting existing '$service' service information from '$hostShort'..."
	local tags=(); [[ $newTags ]] && StringToArray "$newTags" "," tags
	local data; data="$(hashi consul api "/catalog/node-services/$hostShort" | jq "$(cat <<-EOF
		.Services[] | select(.Service == "$service") |
		.["Name"] = .Service | del(.Service, .Proxy, .Connect, .PeerName, .CreateIndex, .ModifyIndex) |
		.Tags=[ $(ArrayShow tags ",") ]
		EOF
	)")" || return

	# re-register service - /catalog/register does not work
	hilight "Re-registering '$service' service information for '$hostShort'..."
	hashi consul api put --api="$host" "/agent/service/register" "${globalArgs[@]}" -- "$data" || return
}

#
# patroni helper
#

patroniLeader() { consul kv get "/app/patroni/$(getPatroniScope)/leader"; }
patroniValidateInstall() { isInstalledCommand && return; ScriptErr "Patroni is not installed"; return 1; }

#
# service commands
#

serviceUsage() { ScriptUsageEcho "Usage: $(ScriptName) service detail|exists|log|restart|running|start|status|stop"; }
serviceArgEnd() { findPostgres; }
serviceCommand() { serviceStatusCommand; }
serviceDetailCommand() { service detail $service; }
serviceExistsCommand() { service exists $service; }
serviceLogCommand() {	LogShow "/var/log/postgresql/postgresql-$version-$instance.log"; }
serviceRestartCommand() { service restart "$service"; }
serviceRunningCommand() { service running "$service"; }
serviceStartCommand() { service start "$service"; }
serviceStatusCommand() { service status "$service"; }
serviceStopCommand() { service stop "$service"; }

#
# helper
#

validateInstall() { isInstalledCommand && return; ScriptErr "PostgreSQL is not installed"; return 1; }

getPassword()
{
	[[ $password ]] && return
	password="$(credential get secure system)" || return
	export PGPASSWORD="$password"
}

getPatroniPort()
{
	[[ $patroniPort ]] && { echo "$patroniPort"; return; }
	[[ -f "$patroniConf" ]] && InPath yq && patroniPort="$(yq ".restapi.listen" "$patroniConf" |& GetUriPort)"
	echo "${patroniPort:-$patroniPortDefault}"
}

getPatroniScope()
{
	[[ $patroniScope ]] && { echo "$patroniScope"; return; }
	[[ -f "$patroniConf" ]] && InPath yq && patroniScope="$(yq ".scope" "$patroniConf")"
	echo "${patroniScope:-$patroniScopeDefault}"
}

findPostgres()
{
	validateInstall || return
	[[ ! $force && $service ]] && return

	# version
	[[ ! $version ]] && version="$(command ls -1 "$confDirBase" | sort --reverse --numeric | head -1)"
	! IsNumeric "$version" && { ScriptErr "PostgreSQL version '$version' is not numeric"; return 1; }
	[[ ! -d "$confDirBase/$version" ]] && { ScriptErr "PostgreSQL version '$version' is not installed"; return 1; }

	# instance
	if [[ ! $instance ]]; then
		if [[ -d "$confDirBase/$version/main" ]]; then instance="main"
		else instance="$(command ls -1 "$confDirBase/$version" | sort | head -1)"
		fi
	fi
	confDir="$confDirBase/$version/$instance"
	[[ ! -d "$confDir" ]] && { ScriptErr "PostgreSQL instance '$instance' is not installed"; return; }

	binDir="/usr/lib/postgresql/$version/bin"
	dataDir="$dataDirBase/$version/$instance"
	service="postgresql@$version-$instance.service"
}

ScriptRun "$@"
