#!/usr/bin/env bash
. app.sh

init()
{ 
	command="start"
	program="$P32/Power Mixer/pwmixer.exe"

	ProfileApp="PowerMixer"
	ProfileMethod="$ADATA/../Roaming/Power Mixer"
	ProfileFiles="*.cfg"
}

usage() {	echot "usage: templateApp [start|startup|close|restart|cd](start)
  profile dir|SaveDir|backup|restore [<profile name>|default](latest)
	load <preset> - load a preset"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			--brief|-b) ;;
			--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup|preset|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

presetCommand()
{
	[[ $# > 1 ]] && usage 1
	preset="${1-default}"
	start "$program" /p=$preset
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
startupCommand() { startCommand; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessKill "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"