#!/bin/bash
. app.sh

init()
{ 
	command="start"
	program="$P32/Power Mixer/pwmixer.exe"

	ProfileApp="PowerMixer"
	ProfileMethod="$APPDATA/Power Mixer"
	ProfileFiles="*.cfg"
}

usage() {	echot "usage: templateApp [start|startup|close|restart|cd](start)
  profile dir|SaveDir|backup|restore [<profile name>|default](latest)
	load <preset> - load a preset"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				if [[ "$1" == @(start|startup|preset|profile) ]]; then { command="${1,,}"; shift; break; }
				elif IsFunction "${1,,}Command"; then command="${1,,}"
				else { echoerr "Unknown argument $1"; usage 1; }
				fi;;
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

presetCommand()
{
	[[ $# > 1 ]] && usage 1
	preset="${1-default}"
	start "$program" /p=$preset
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
startupCommand() { startCommand; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessKill "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"