#!/bin/bash
. app.sh

init()
{ 
	command="start"
	program="$P32/CyberPower PowerPanel Personal Edition/pppeuser.exe"
	title="com.cyberpowersystems.powerpanelpe.tray.win32msgqueue.windowname"
}

usage() {	echot "usage: templateApp [start|startup|close|restart](start)"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
startupCommand() { startCommand "$@"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; task CloseKill --title "$title" "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"