#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup](start)
$(ScriptName) commands."
}

init()
{ 
	defaultCommand="start"
	program="$P32/CyberPower PowerPanel Personal Edition/pppeuser.exe"
	title="com.cyberpowersystems.powerpanelpe.tray.win32msgqueue.windowname"
}

closeCommand() { ! isRunningCommand && return 0; task CloseKill --title "$title" "$program"; }
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsTaskRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
									 
ScriptRun "$@"
