#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	echot "\
usage: product [list|uninstall <product code>|optional|gui](gui)"
	exit $1
}

init() 
{
	command='list'
}

args()
{
	while [ "$1" != "" ]; do
		case "$1" in
			-h|--help) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
			ListFile) command="ListFile";;
			*) 
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(optional|uninstall) ]] && break
				UnknownOption "$1"; return
		esac
		shift
	done
	args=( "$@" )
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
listCommand() {  start ProductList.vbs; }
guiCommand() { rundll32.exe shell32.dll,Control_RunDLL appwiz.cpl; }
optionalCommand() { [[ "$1" == @(-w|--wait) ]] && OptionalFeatures || start OptionalFeatures; } 

ListFileCommand() 
{  
	local file="$TMP/products.txt";
	listCommand > "$file" || return
	TextEdit "$file"
}

uninstallCommand() 
{ 
	local result=$(mktemp), success
	start ProductUninstall.vbs $1 |& tee "$result"
	! grep -E "^usage:|API Error" "$result" >& /dev/null; success=$?
	rm "$result"
	return $success
}

run "$@"
