#!/bin/bash
. function.sh

usage()
{
	echot "\
usage: product [list|uninstall <product code>|gui](gui)"
	exit $1
}

init() 
{
	command='list'
}

args()
{
	while [ "$1" != "" ]; do
		case "$1" in
			*) 
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(uninstall) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
listCommand() {  ElevationRequired; start ProductList.vbs; }
guiCommand() { start rundll32.exe shell32.dll,Control_RunDLL appwiz.cpl; }

uninstallCommand() 
{ 
	local result=$(mktemp), success
	start ProductUninstall.vbs $1 |& tee "$result"
	! egrep "^usage:|API Error" "$result" >& /dev/null; success=$?
	rm "$result"
	return $success
}

run "$@"
