#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup](start)
$(ScriptName) commands.  PuTTY tools include: putty plink pscp psftp puttytel pageant PuttyGen"
}

init()
{
	defaultCommand="start"
	certificate="$UDATA/certificate/private/id_rsa.ppk"
	programPassword="$(FindInPath "pageant_twee")"
	program="$(FindInPath "pageant")"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$programPassword" || IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startupCommand() { startCommand; }

#
# Start Command
#

startArgs() { startArgs=( "$@" ); shift="$#"; }

startCommand()
{
	AppInstallCheck || return; isRunningCommand && return

	[[ ! -f "$certificate" ]] && { ScriptErr "SSH2 certificate '$certificate' is not available"; return 1; }

	local password="$(credential get ssh default)"
	if [[ $password ]]; then
		start "$programPassword" -p "$password" "$certificate" "$@"
	else
		start "$program" "$certificate" "$@"
	fi
}

ScriptRun "$@"
