#!/usr/bin/env bash
. function.sh

init() 
{
	command='autorun'
}

usage()
{
	echot "\
usage: autorun"
	exit $1
}

args()
{
	unset command
	while [ "$1" != "" ]; do
		case "$1" in
			-h|--help) usage 0;;
			*) 
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

autorunCommand()
{ 
	local d="/tmp/config"
	local f="$d/autorun.sh"

	[[ ! -d "$d" ]] && { sudo mount $(sudo hal_app --get_boot_pd port_id=0)6 "$d" || return; }
	[[ ! -f "$f" ]] && { sudo touch "$f" || return; sudo chmod +x "$f" || return; }
	sudo nano "$f"
	sudo umount "$d"
	rmdir "$d"
}

run "$@"
