#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... autorun|cli
QNAP helper commands.
	
	autorun		edit the autorun script
	cli				cli commands
	package		package commands"
}

init() { defaultCommand="cli"; }

#
# Autorun Command
#

autorunCommand()
{ 
	local d="/tmp/config"
	local f="$d/autorun.sh"

	[[ -d "$d" ]] && { sudo umount "$d" >& /dev/null; }
	[[ ! -d "$d" ]] && { mkdir "$d"; }
	sudo mount $(sudo hal_app --get_boot_pd port_id=0)6 "$d" || return
	[[ ! -f "$f" ]] && { sudo touch "$f" || return; sudo chmod +x "$f" || return; }
	sudoedit "$f" 
	sudo umount "$d"
	rmdir "$d"
}

#
# CLI Commands
#

cliUsage()
{
	echot "Usage: $(ScriptName) cli login|run [HOST](current)
qcli helper commands.

	login			login to the specified QNAP nas
	run				run a cli command"
}

cliCommand() { usage; }
cliArgStart() { unset -v host; }

cliRunUsage()
{
	echot "Usage: $(ScriptName) cli run -- [COMMAND]
Run a qcli command, setting the sid."
}

cliRunCommand()
{
	local sid; sid="$(getSid)" || return

	if IsPlatform qnap; then
		RunLog qcli_"${otherArgs[@]}" sid="$sid"
	else
		ssh "$(getHost)" qcli_"${otherArgs[@]}" sid="$sid"
	fi
}

getHost()
{
	# host from arguments
	[[ $hostArg ]] && { echo "$hostArg"; return; }

	# get host from configuration
	local configHost="$(ConfigGetCurrent "nas")"
	[[ $configHost ]] && { echo "$configHost"; return; }

	MissingOperand "host" || return
}

#
# CLI Login
#

cliLoginUsage()
{
	echot "Usage: $(ScriptName) cli login [sid|vars](sid)
qcli login commands.  With no command, performs a login to HOST.

	sid				display the login sid
	vars			return cli variables for evaluation"
}

cliLoginArgs() { [[ $# == 0 ]] && return; ScriptArgGet "hostArg" "host" -- "$@"; }
cliLoginCommand() { cliLoginSidCommand; }
cliLoginSidCommand() { getSid; }
cliLoginVarsCommand() { local sid; sid="$(getSid)" || return; export QCLI_SID="$sid"; ScriptReturn --export "QCLI_SID"; }

#
# Package Commands
#

packageUsage()
{
	echot "Usage: $(ScriptName) package [detail|list|install|IsInstalled|uninstall](list)
Package commands.

	detail			list detail for all installed packages
	list				list installed packages
	install			install a package
	IsInstalled	return true if a package is installed
	status			package status
	uninstall		uninstall a package"
}

packageArgStart() { conf="/etc/config/qpkg.conf"; [[ -f "$conf" ]] && return; ScriptErr "package configuration file '$conf' not found"; return 0; }
packageCommand() { packageListCommand; }
packageArgs() { [[ "$command" == @(package|packageDetail|packageList) ]] && return; ScriptArgGet "name" -- "$@"; }
packageDetailCommand() { cat "/etc/config/qpkg.conf"; }
packageListCommand() { cat "/etc/config/qpkg.conf" | grep "^Name =" | cut -d" " -f 3 | sort; }
packageIsInstalledCommand() { packageIsInstalled "$name"; }
packageStatusCommand() { qpkg_cli --status "$name"; }
packageUninstallCommand() { ! packageIsInstalled "$name" && return; sudoc qpkg_cli --remove "$name"; }

packageInstallCommand()
{
	packageIsInstalled "$name" && return
	local result="$(sudoc qpkg_cli --add "$name")"; echo "$result"
	[[ ! "$result" =~ "invalid QPKG" ]]
}

packageIsInstalled() { qpkg_cli --status "$1" | grep -q "is installed$"; }

#
# helper
#

getSid()
{
	# on QNAP devices use QCLI_SID environment variable
	if IsPlatform qnap; then
		[[ $QCLI_SID ]] && { echo "$QCLI_SID"; return; }
		ScriptErr "QCLI_SID is not set"; return 1
	fi

	# get the host
	local host="$(getHost)"

	# get the sid from the credential store if possible
	if [[ ! $force ]] && ! UpdateNeeded qcli && credential exists qnap/sid "$host" "${globalArgs[@]}"; then
		credential get qnap/sid "$host"; return
	fi

	# login to get a new sid
	local sid; sid="$(ssh "$host" -- qcli --login user="$USER" pw="$(credential get secure default)" | grep "sid is" | cut -d" " -f3)" || return
	[[ ! $sid ]] && { ScriptErr "unable to login to $host"; return 1; }

	credential set qnap/sid "$host" "$sid" --quiet "${globalArgs[@]}" || return
	UpdateSet qcli || return # only cache the SID for the current day 
	echo "$sid"
}

ScriptRun "$@"
