#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: quicken [start|close|restart](start)"; exit $1; }

args()
{
	unset -v brief help
	command="start"
	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start|startup|profile|service) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init() { program="$P32/Quicken/qw.exe"; }
run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }
cdCommand() { echo "$cd"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }
startCommand() { ! IsInstalledCommand && return 1; IsRunningCommand && return 0; start "$program" "$@"; }

run "$@"