#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="rectangle" profileDir="$HOME/Library/Preferences" profileMask="com.knollsoft.Hookshot.plist"
	program="$P/Rectangle Pro.app"
	programRunning="$P/Rectangle Pro.app/Contents/MacOS/Rectangle Pro"
}

closeCommand() { ! isRunningCommand && return; ProcessClose "$programRunning"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$programRunning"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}" || return; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }
									 
ScriptRun "$@"
