#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init()
{
	profileName="rectangle"
	program="$P/Rectangle.app"
	profileDir=~/Library/Preferences
	profileMask="com.knollsoft.Rectangle.plist"
}

usage() {	echot "usage: rectangle [start|program|IsInstalled](start)
  profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

IsInstalledCommand() { [[ -d "$program" ]]; }
profileCommand() { profile --app "$profileName" --method "$profileDir" --files "$profileMask" "$@" || usage 1; }
startCommand() { IsInstalledCommand && open -a rectangle "$@"; }

run "$@"
