#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup](start)
Rectangle commands."
}

init()
{
	defaultCommand="start"
	profileName="rectangle"
	program="$P/Rectangle.app"
	profileDir="$HOME/Library/Preferences"
	profileMask="com.knollsoft.Rectangle.plist"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsTaskRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}" || return; }
programCommand() { echo "$program"; }
startCommand() { isInstalledCommand && open -a rectangle; }
startupCommand() { startCommand; }
									 
ScriptRun "$@"
