#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: ReSharper
  profile dir|SaveDir|backup|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset var
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "${command:-profile}" == @(profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	command="${command:-profile}"
	args=( "$@" )
}

init()
{ 
	version="7.1"
	solutionCacheDir="$LOCALAPPDATA/JetBrains/ReSharper/v$version/SolutionCaches"
}

run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }

profileCommand() 
{	
	ScriptEval VisualStudio init || return

	[[ "$1" == @(backup|restore) ]] &&
	 	echo "- RESHARPER, Manage Options..., Import / Export Settings, Import/Export to File"

	profile --app "ReSharper" --method "$vsIde" --save-extension "DotSettings" "$@" || return; 
}

run "$@"