#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [profile](profile)
$(ScriptName) commands."
}


init()
{
	defaultCommand="profile"
	profileName="ReSharper"
	solutionCacheDir="$UADATA/JetBrains/ReSharper/v$version/SolutionCaches"
	version="7.1"
}

#
# Profile Command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }

profileCommand() 
{	
	AppInstallCheck || return
	ScriptEval VisualStudio init || return

	[[ "$1" == @(backup|restore) ]] &&
	 	echo "- RESHARPER, Manage Options..., Import / Export Settings, Import/Export to File"

	profile $noPrompt --app "$profile" --method "$vsIde" --save-extension "DotSettings" "${profileArgs[@]}" || return; 
}
									 
ScriptRun "$@"
