#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [profile](profile)
$(ScriptName) commands."
}

init()
{
	defaultCommand="profile"
	profileName="ReSharper"
	solutionCacheDir="$UADATA/JetBrains/ReSharper/v$version/SolutionCaches"
	version="7.1"
}

isInstalledCommand() { return 0; }
#
# Profile Command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }

profileCommand() 
{	
	AppInstallCheck || return
	ScriptEval VisualStudio init || return
	[[ "${profileArgs[0]}" == @(restore|save) ]] &&
	 	echo "- Extensions, ReSharper, Manage Options..., Import and Export, Export to File..., select all"
	profile $noPrompt --app "$profileName" --method "$vsIde" --save-extension "DotSettings" "${profileArgs[@]}" || return; 
}
									 
ScriptRun "$@"
