#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

run() {	init && args "$@" && RunExecutable; }

init() { :; }

usage()
{
	echot "\
usage: RunExecutable EXECUTABLE [--] EXECUTABLE_OPTIONS
	Run an executable program.	
	-e, --elevate				in Windows run the executable with an elevated (Administrator) token
	-v, --verbose				display detailed output
	--     							Signal the end of the RunExecutable options"
	exit $1
}

args()
{
	declare -g args=(); unset -v elevate file verbose

	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-e|--elevate) elevate="--elevate";;
			-v|--verbose) verbose="--verbose";;
			*) 
				[[ "$1" == "--" ]] && { shift; args+=( "$@" ); break; }
				! IsOption "$1" && [[ ! $file ]] && { file="$1"; shift; continue; }
				! IsOption "$1" && UnknownOption "$1"
		esac
		shift
	done

	[[ ! $file ]] && MissingOperand "file"
	return 0
}

RunExecutable()
{
	[[ $elevate ]] && ! IsElevated && { RunScript --elevate $verbose -- RunExecutable $verbose "$file" -- "${args[@]}"; return; }
	[[ ! -f "$file" ]] && { EchoErr "RunExecutable: the executable file does not exist: $file"; return 1; }
	[[ $verbose ]] && EchoErr "running executable '$file'..."
	start $verbose --wait "$file" "${args[@]}" || return
}

run "$@"