#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit


usage()
{
	ScriptUsage "$1" "\
usage: $(ScriptName) EXECUTABLE [--] EXECUTABLE_OPTIONS
Run an executable program.	

	-e, --elevate				in Windows run the executable with an elevated (Administrator) token"
}

init() { defaultCommand="run"; }
argStart() { unset -v elevate; }

opt()
{
	case "$1" in
		-e|--elevate) elevate="--elevate";;
		*) return 1;;
	esac
}

args() { ScriptArgGet "file" -- "$@" && ScriptCheckFile "$file"; }

runCommand()
{
	[[ $elevate ]] && ! IsElevated && { RunScript --elevate "${globalArgs[@]}" -- RunExecutable "${originalArgs[@]}"; return; }
	log1 "running executable '$file'..."
	RunLog2 start $verbose --wait "$file" "${args[@]}"
}

ScriptRun "$@"