#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit


usage()
{
	ScriptUsage "$1" "\
usage: $(ScriptName) EXECUTABLE [--] EXECUTABLE_OPTIONS
Run an executable program.	

	-n, --nsis			NSIS installer, run using /S
	-e, --elevate		in Windows run the executable with an elevated (Administrator) token"
}

init() { defaultCommand="run"; }
argStart() { unset -v elevate nsis; }

opt()
{
	case "$1" in
		-n|--nsis) nsis="--nsis";;
		-e|--elevate) elevate="--elevate";;
		*) return 1;;
	esac
}

args() { ScriptArgGet --required "file" -- "$@" && ScriptCheckFile "$file"; }

runCommand()
{
	[[ $elevate ]] && ! IsElevated && { RunScript --elevate "${globalArgs[@]}" -- RunExecutable "${originalArgs[@]}"; return; }

	local args=("${otherArgs[@]}"); [[ $nsis ]] && args+=("/S")
	log1 "running executable '$file' with arguments '${args[@]}'..."
	RunLog2 start $verbose --wait "$file" "${args[@]}"
}

ScriptRun "$@"