#!/usr/bin/env bash
. function.sh || exit

[[ "$#" == "0" ]] && { EchoErr "usage: RunInDir DIR [PROGRAM]($SHELL)"; exit 1; }

dir=$1
[[ ! -d "$dir" ]] && { EchoErr "RunInDir: \'$dir\' is not a directory"; exit 1; }
cd "$dir" || return
shift

[[ "$#" == "0" ]] && $SHELL || eval "$@"
