#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage() { ScriptUsage "$1" "Usage: $(ScriptName) [run]\nWindows MSI commands."; }

init() 
{ 
	! IsPlatform win && { EchoErr "RunMsi: MSI setup files can only be installed in Windows"; return 1; }
	defaultCommand="run"
}

runUsage()
{
	EchoErr "$1" "\
Usage: $(ScriptName) [run] MSI -- [MSI_OPTION]...
Run a Windows MSI setup.	

	-e, --elevate				in Windows run the MSI setup with an elevated (Administrator) token"
}

runArgStart() { unset -v elevate; }

runOpt()
{
	case "$1" in
		--elevate|-e) elevate="true";;
		*) return 1;;
	esac
}

runArgs() { ScriptArgGet "file" -- "$@"; shift; }

runCommand()
{
	[[ $elevate ]] && ! IsElevated && { RunScript --elevate $verbose -- RunMsi "${globalArgs[@]}" "$file" -- "${otherArgs[@]}"; return; }
	[[ ! -f "$file" ]] && { EchoErr "RunMsi: the MSI file does not exist: $file"; return 1; }
	log1 "running installer \"$(utw "$file")\"..."
	msiexec.exe /quiet /qb /norestart /i "$(utw "$file")" "${otherArgs[@]}" || return
}

ScriptRun "$@"