#!/usr/bin/env bash
. function.sh

run() {	init && args "$@" && runMsi; }

init() 
{ 
	! IsPlatform win && { EchoErr "RunMsi: MSI setup files can only be installed in Windows"; return 1; }
	return 0
}

usage()
{
	echot "\
usage: RunMsi MSI [--] MSI_OPTIONS
	Run a Windows MSI setup.	
	-e, --elevate				in Windows run the MSI setup with an elevated (Administrator) token
	-v, --verbose				display detailed output
	--     							signal the end of options RunMsi options"
	exit $1
}

args()
{
	declare -g args=(); unset -v elevate file verbose	

	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-e|--elevate) elevate="--elevate";;
			-v|--verbose) verbose="--verbose";;
			*) 
				[[ "$1" == "--" ]] && { shift; args+=( "$@" ); break; }
				! IsOption "$1" && [[ ! $file ]] && { file="$1"; shift; continue; }
				! IsOption "$1" && UnknownOption "$1"
		esac
		shift
	done

	[[ ! $file ]] && MissingOperand "file"
	return 0
}

runMsi()
{
	[[ $elevate ]] && ! IsElevated && { RunScript --elevate $verbose -- RunMsi $verbose "$file" -- "${args[@]}"; return; }
	[[ ! -f "$file" ]] && { EchoErr "RunMsi: the MSI file does not exist: $file"; return 1; }
	[[ $verbose ]] && echo "Running installer \"$(utw "$file")\"..."
	msiexec.exe /quiet /qb /norestart /i "$(utw "$file")" "${args[@]}" || return
}

run "$@"
