#!/usr/bin/env bash
. function.sh

run()
{
	local file="$1"; shift
	cd "/" || return # cd to local directory to fix invalid argument error running programs from SMB mounted shares
	msiexec.exe /quiet /qb /norestart /i "$(utw "$file")" "$@" || return
}

run "$@"