#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... sync
$(ScriptName) commands."
}

#
# sync command
#

syncUsage() { ScriptUsageEcho "Usage: $(ScriptName) sync install"; }
syncCommand() { usage; }

syncCommand()
{
	echo "sync"
}


ScriptRun "$@"
