#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... sync
$(ScriptName) commands."
}

#
# sync command
#

syncUsage() { ScriptUsageEcho "Usage: $(ScriptName) sync install"; }
syncCommand() { usage; }

syncCommand()
{
	local dir1; dir1="$(unc mount "//sdss-nm.sandia.gov/Collab9/csep-technical/install")"
	local dir2; dir2="$(unc mount "//sdss-nm.sandia.gov/collab1/MCS-NGE/install")"
	local dir3; dir3="$(unc mount "//CsepShare.sandia.gov/install2")"
	merge "$dir1" "$dir2" && merge "$dir1" "$dir3" 
}

ScriptRun "$@"
