#!/usr/bin/env bash
. function.sh || exit

usage()
{
	echot "\
usage: service [COMMAND](start) SERVICE [HOST]
	Control Windows services
	detail|exist|list|ListFile|StartType|show|state|status|running
	continue|pause|restart|start|stop				control service
	auto|delete|demand|disable|manual		 		configure service
	-h, --host 								host to check
	    --no-host-check 			do not check for host availability
	    --no-service-check		do not check for service existence
	-w, --wait								wait for the service to change state"
	exit $1
}

args()
{
	unset command service host noHostCheck noServiceCheck wait 
	[[ $# == 0 ]] && { command="show"; return; }
	while (( $# != 0 )); do
		case "$1" in
			--host|-h) host="$2"; shift;;
			--no-host-check) noHostCheck="--no-host-check";;
			--no-service-check) noServiceCheck="--no-service-check";;
			--wait|-w) wait="--wait";;
			--help) help="--help";;
			ListFile) command="ListFile";; StartType) command="StartType";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; command="${1,,}"; shift; continue; }
				! IsOption "$1" && [[ "$command" != @(list|ListFile) && ! $service ]] && { service="$1"; shift; continue; }
				! IsOption "$1" && [[ ! $host ]] && { host="$1"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage || usage 0; }
	
	args=("$@")
}

init()
{ 
	unset hostUnc hostDescription

	# SC data area error - http://www.dostips.com/forum/viewtopic.php?f=3&t=3408
	scBufferSize=5000
	sc="sc.exe"

	if [[ ! $noHostCheck && $host && "$host" != @(localhost|$HOSTNAME) ]]; then
		! HostUtil available "$host" && { EchoErr "service: $host is not available"; return 1; }
		hostUnc='\\'"$host"
		hostDescription=" on $host"
	fi

	if [[ "$command" != @(list|ListFile|show) ]]; then
		[[ $service ]] || MissingOperand "service"
		[[ "$command" != "exist" ]] && { check || return; }
	fi

	return 0
}

run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
showCommand() { start services.msc; }
listCommand() { $sc $hostUnc queryex bufsize= $scBufferSize type= all state= all; }
stateCommand() { GetWord "$($sc $hostUnc query "$service" |& grep STATE)" 3; }
runningCommand() { [[ "$(stateCommand)" == "RUNNING" ]]; }
StartTypeCommand() { GetWord "$($sc $hostUnc qc "$service" $ScBufferSize |& grep START_TYPE)" 3; }
existCommand() { $sc $hostUnc qc "$service" $ScBufferSize |& grep START_TYPE >& /dev/null; }

deleteCommand()
{
	checkElevated && { ElevatePause service delete $wait $noServiceCheck $noHostCheck "$service" "$host"; return; }
	$sc delete $hostUnc "$service"
}

disableCommand() 
{ 
	[[ "$(StartTypeCommand)" == "DISABLED" ]] && return 
	checkElevated && { ElevatePause service disable $wait $noServiceCheck $noHostCheck "$service" "$host"; return; }
	$sc config $hostUnc "$service" start= disabled; 
}

demandCommand() 
{ 
	[[ "$(StartTypeCommand)" == "DEMAND_START" ]] && return 
	checkElevated && { ElevatePause service demand $wait $noServiceCheck $noHostCheck "$service" "$host"; return; }
	$sc config $hostUnc "$service" start= demand; 
}

autoCommand() 
{ 
	[[ "$(StartTypeCommand)" == "AUTO_START" ]] && return 
	checkElevated && { ElevatePause service auto $wait $noServiceCheck $noHostCheck "$service" "$host"; return; }	
	$sc config $hostUnc "$service" start= auto; 
}

restartCommand() 
{ 
	local oldWait="$wait"
	wait="--wait"; noServiceCheck="--no-service-check"
	stopCommand || return
	wait="$oldWait"
	startCommand || return
	return 0
}

startCommand()
{
	[[ "$(stateCommand)" != "STOPPED" ]] && return 
	
	checkWaiting; printf "Starting $service service$hostDescription...$waiting"
	result="$($sc $hostUnc start "$service")" || { EchoErr "$result"; return 1; }

	[[ $wait ]] && WaitForState RUNNING start started
}

stopCommand()
{
	[[ "$(stateCommand)" != "RUNNING" ]] && return 
	checkElevated && { ElevatePause service stop $wait $noServiceCheck $noHostCheck "$service" "$host"; return; }

	checkWaiting; printf "Stopping $service service$hostDescription..."$waiting
	result="$($sc $hostUnc stop "$service")" || { EchoErr "$result"; return 1; }

	[[ $wait ]] && WaitForState STOPPED stop stopped
	return 0
}

continueCommand()
{
	[[ "$(stateCommand)" != "PAUSED" ]] && return 
	
	checkWaiting; printf "Continuing $service service$hostDescription..."$waiting
	result="$($sc $hostUnc continue "$service")" || { EchoErr "$result"; return 1; }

	[[ $wait ]] && WaitForState RUNNING continue continued
}

pauseCommand()
{
	[[ "$(stateCommand)" != "RUNNING" ]] && return 
	checkElevated && { ElevatePause service pause $wait $noServiceCheck $noHostCheck "$service" "$host"; return; }

	checkWaiting; printf "Pausing $service service$hostDescription..."$waiting
	result="$($sc $hostUnc pause "$service")" || { EchoErr "$result"; return 1; }

	[[ $wait ]] && WaitForState PAUSED pause paused
}

manualCommand()
{
	echo "Stopping $service service and setting it to demand start$hostDescription..."
	demandCommand || return
	stopCommand || return
	return 0
}

statusCommand()
{
	state="$(stateCommand)" || return
	startType="$(StartTypeCommand)" || return
	echo "$service is ${state}${hostDescription} ($startType)"
}

ListFileCommand() 
{ 
	local file="$TMP/services.txt";
	$sc $hostUnc queryex bufsize= $scBufferSize type= all state= all > $file
	TextEdit "$file"
}

detailCommand()
{
	echo "Status of $service service$hostDescription..."
	$sc $hostUnc GetDisplayName "$service"
	$sc $hostUnc qdescription  "$service" $scBufferSize
	$sc $hostUnc queryex "$service" $scBufferSize
	$sc $hostUnc qc "$service" $SscBufferSize
	$sc $hostUnc qfailure "$service"
}

WaitForState()
{
	local seconds=30 state="$1"

	for (( i=1; i<=seconds; ++i )); do
 		read -n 1 -t 1 -s && { echo "cancelled after $i seconds"; return 1; }
 		[[ "$(stateCommand)" == "$state" ]] && { echo "$3 in $i seconds"; return 0; }
		printf "."
	done

	echo "did not $2 in $seconds seconds"; return 1
}

checkWaiting()
{
	unset waiting
	[[ ! $wait ]] && waiting="\n"
}

check()
{
	[[ $noServiceCheck ]] && return 0

	local result="$(sc $hostUnc query "$service" |& grep FAILED)"
	resultCode="${result#*FAILED }"; resultCode="${resultCode%:}"

	case $resultCode in
		1060) echo "service: $service does not exist as an installed service$hostDescription";;
  	5) echo "service: access to the service control manager denied$hostDescription";;
		*) return 0
	esac

	return 1
}

checkElevated()
{
	if ! IsElevated && [[ "$host" == @(|localhost|$HOSTNAME) ]]; then
		elevate="true";
		return 0
	else
		elevate=""
		return 1
	fi
}

run "$@"