#!/bin/bash
. function.sh || exit

key="HKCU/Console"

echo "Setting console defaults..."

registry set "$key/QuickEditMode" REG_DWORD 1 || return
registry set "$key/QuickEdit" REG_DWORD 1 || return

# foreground text: bright white=31 (255, 255, 255), white=23 (192,192,192)
registry set "$key/ScreenColors" REG_DWORD 7 || return

# Screen Background: black=0 (0,0,0), blue=8388608 (or 0, 0, 128)
# Black does not flicker when large amounts of text are displayed (for example when do dir bin:)
registry set "$key/ColorTable01" REG_DWORD 0 || return

registry set "$key/ColorTable11" REG_DWORD 16776960 || return
registry set "$key/ColorTable15" REG_DWORD 16777215 || return

# Font
registry set "$key/FaceName" REG_SZ "Lucida Console" || return
registry set "$key/FontFamily" REG_DWORD 54 || return
registry set "$key/FontSize" REG_DWORD 1048586 || return
registry set "$key/FontWeight" REG_DWORD 400 || return

# Screen 165x29 (1680x1050)
registry set "$key/ScreenBufferSize" REG_DWORD 19660964 || return
registry set "$key/WindowSize" REG_DWORD 1835172 || return
