#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	echot "\
usage: SetVar VAR [VALUE]
	Set user or system variable in the Windows registry.  If no value is specified the value is deleted.
	-d, --delete			Delete the variable
  -s, --system			Set a system variable system wide (default is user)
  -p, --path				The variable refers to a semi-colon separated path, 
										the value is a directory"
	exit $1
}

args()
{
	unset var value delete isPath system
	while (( $# != 0 )); do
		case "$1" in
			-d|--delete) delete="true";;
			-s|--system) CanElevate && system="-m";;
			-p|--path) isPath="true";;
			--help) usage 0;;
			*)
				! IsOption "$1" && [[ ! $var ]] && { var="$1"; shift; continue; }
				! IsOption "$1" && [[ ! $value ]] && { value="$1"; shift; continue; }
				UnknownOption "$1"; return
		esac
		shift
	done
	[[ ! $var ]] && { MissingOperand "var"; return; }
	[[ ! $delete ]] && ! IsDeclared value && { MissingOperand "value"; return; }
}

run()
{
	args "$@"
	
	if [[ $system ]]; then
		key="HKLM/SYSTEM/CurrentControlSet/Control/Session Manager/Environment/$var"
	else
		key="HKCU/Environment/$var"
	fi

	if [[ $delete ]]; then
		registry delete "$key"
		return
	fi

	local newValue="$value"

	[[ $isPath ]] && { SetPath || return; }

	if [[ $system ]] && ! IsElevated; then
		echo "start setx.exe \"$var\" \"$newValue\" $system" > "$TMP/SetVar.sh"
		elevate RunScript --pause-error source "$TMP/SetVar.sh"

	elif ! start setx.exe "$var" "$newValue" $system >& /dev/null; then
		printf "Unable to set the $var variable: " > /dev/stderr
		start setx.exe "$var" "$newValue" $system
		return

	fi

	[[ $isPath ]] && local $var="${!var}:$(wtu "$value")" || local $var="$value"
	ScriptReturn --export $var
}

SetPath()
{
	local parts oldValue="$(registry get "$key" | sed 's/\r//g')" # remove trailing carriage return
	newValue="$(utw "$value")"
	StringToArray "${oldValue//\\/\\\\}" ";" parts
	IsInArray "$newValue" parts && exit 0
	[[ $oldValue ]] && newValue="$oldValue;$newValue"
	return 0
}

run "$@"
