#!/bin/bash
. function.sh

file="$1"

[[ ! $file ]] && { EchoErr "The file to edit was not specified"; exit 1; }
[[ ! -f "$file" ]] && { EchoErr "The file to edit was not found"; exit 1; }

GetFileExtension "$file" ext

case "$ext" in
	htm|html|css|asp|asa)
		expression IsInstalled && { expression start "$@"; exit; }
		BlueGriffon IsInstalled && { BlueGriffon start "$@"; exit; }
		VisualStudio IsInstalled && { VisualStudio start "$@"; exit; }
		TextEdit "$@"; exit;;
	*) TextEdit "$@"; exit;;
esac
