#!/bin/bash
. function.sh

file="$1"

[[ ! $file ]] && { echoerr "The file to edit was not specified"; exit 1; }
[[ ! -f "$file" ]] && { echoerr "The file to edit was not found"; exit 1; }

GetExtension "$file" ext

case "$ext" in
	htm|html|css|asp|asa)
		expression IsInstalled && { expression "$@"; exit; }
		BlueGriffon IsInstalled && { BlueGriffon "$@"; exit; }
		VisualStudio IsInstalled && { VisualStudio "$@"; exit; }
		TextEdit "$@"; exit;;
	*) TextEdit "$@"; exit;;
esac
