#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "script" || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... make
$(ScriptName) commands."
}

#
# make command
#

makeUsage()
{
	ScriptUsageEcho "\
Usage: $(ScriptName) make FILE LINK [ARGUMENTS ICON_FILE ICON_RESOURCE_NUMBER [MAX|MIN] START_IN_FOLDER HOT_KEY]
Make a Windows shortcut."
}

makeArgs()
{
	# file
	ScriptArgGet --required "file" -- "$@" || return
	InPath "$file" && file="$(FindInPath "$file")"
	ScriptCheckFile "$file" || return

	# link
	ScriptArgGet "link" -- "$@" || return; shift

	# other
	args=( "$@" ); shift="$#"; 
}

makeCommand() { RunPlatform make; }

makeWin()
{
	# link
	local linkParent="$(GetFilePath "$link")"
	! drive IsWin "$linkParent" && { ScriptErrQuiet "'$(FileToDesc "$linkParent")' is not on a Windows drive"; return; } # create-shortcut.exe requires a Windows drive
	link="$(utw "$link")" || return
echo -E "$link"
	# create
	log3 "creating link '$(FileToDesc "$link")' to '$(FileToDesc "$file")'..."
	if InPath create-shortcut.exe; then
		local args=()
		[[ $3 ]] && args+=(--arguments "$3")
		[[ $4 ]] && args+=(--icon-file "$(utw "$4")")
		args+=("$(utw "$f")" "$(utw "$link")")
		create-shortcut.exe "${args[@]}"
	elif InPath nircmd.exe; then
		local linkDir="$(utw "$(GetFilePath "$link")")"
		local linkName="$(GetFileName "$link")"
		start nircmd.exe shortcut "$f" "$linkDir" "$linkName" "${@:3}"
	else
		return 0
	fi
}

ScriptRun "$@"
