#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="rectangle" profileDir="$HOME/Library/Preferences" profileMask="com.knollsoft.Rectangle.plist"
	program="$P/Shottr.app"
}

closeCommand() { ! isRunningCommand && return; ProcessClose "$(GetFileNameWithoutExtension "$program")"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }
									 
ScriptRun "$@"
