#!/usr/bin/env bash
. app.sh

init()
{ 
	unset var
	title="Skype"
	checkProgram="$P/WindowsApps/Microsoft.SkypeApp_14.42.52.0_x64__kzf8qxf38zg5c/SkypeApp.exe"
	program="explorer shell:appsFolder\Microsoft.SkypeApp_kzf8qxf38zg5c!App";
	checkRunning="SkypeApp.exe"
}

usage() {	echot "skype: start|startup|close|restart"; exit $1; }

args()
{
	unset -v brief
	while [[ "$1" != "" ]]; do
		case "$1" in
			--brief|-b) brief="--brief";;
			--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";; PersonalBridge) command="PersonalBridge";; # case insensitive commands
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup|profile|service|call) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	$program "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	$program "$@"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$checkProgram" ]]; }
IsRunningCommand() { IsTaskRunning "SkypeApp.exe"; }
closeCommand() { ! IsRunningCommand && return 0; task close $brief --title "$title" "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"