#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"	

	case "$PLATFORM_OS" in
		mac) program="$P/Slack.app";;
		win) program="$UADATA/slack/app-4.29.149/slack.exe"; [[ ! -f "$program" ]] && program="$P/slack/slack.exe";;
	esac

	return 0
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { isRunningCommand && return; start "$program" --process-start-args --startup; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
