#!/bin/bash
. app.sh

init()
{ 
	command="start"
	title="Snagit"
	program="$P32/TechSmith/SnagIt 11/SnagIt32.exe"
}

usage() {	echot "usage: templateApp [start|startup|close|restart](start)"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "${1,,}" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				if [[ "$1" == @(start|startup) ]]; then { command="${1,,}"; shift; break; }
				elif IsFunction "${1,,}Command"; then command="${1,,}"
				else { echoerr "Unknown argument $1"; usage 1; }
				fi;;
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
	#task start --duplicate --title "$title" "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";
closeCommand() { ! IsRunningCommand && return 0; SendKeys "$title" "!FX"; } 
restartCommand() { closeCommand && startCommand; }

run "$@"