#!/usr/bin/env bash
. app.sh

init()
{ 
	command="start"
	title="Snagit"
	program="$P32/TechSmith/SnagIt 11/SnagIt32.exe"
}

usage() {	echot "usage: templateApp [start|startup|close|restart](start)"; exit $1; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case "${1,,}" in
			--brief|-b) ;;
			--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
	#task start --duplicate --title "$title" "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; } # task IsRunning --title "$title" "$program"; WinExists "$title";
closeCommand() { ! IsRunningCommand && return 0; SendKeys "$title" "!FX"; } 
restartCommand() { closeCommand && startCommand; }

run "$@"