#!/usr/bin/env bash
. app.sh

init()
{ 
	title="Snagit"
	case "$PLATFORM" in
		mac) program="$P/Snagit.app";;
		win) program="$P32/TechSmith/SnagIt 11/SnagIt32.exe";;
	esac
}

usage() {	echot "usage: templateApp [start|startup|close|restart](start)"; exit $1; }

args()
{
	unset command

	while [[ "$1" != "" ]]; do
		case "${1,,}" in
			--brief|-b) ;;
			--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
}

closeCommand()
{ 
	! IsRunningCommand && return 0
	"$program" || return
	sleep 2
	SendKeys "$title" "!FX"
} 

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"