#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... install
$(ScriptName) commands."
}

#
# install command
#

installUsage() { ScriptUsageEcho "Usage: $(ScriptName) install db"; }
installCommand() { usage; }

installDbUsage()
{
	ScriptUsageEcho "Usage: $(ScriptName) install db [dir|log]"
}

installDbArgStart()
{
	dbFreshInstallDir="$WIN_HOME/Desktop/i120_SQLServer_fi/i120_SQLServer_fi"
}

installDbCommand()
{
	cd "$dbFreshInstallDir" || return
	echo "If needed, modify test.sql..."
	cmd.exe /c Solumina_DB.bat localhost Solumina sa "$(credential get secure system)" SFMFG test
}

installDbDirCommand() { echo "$dbFreshInstallDir"; }
installDbLogCommand() { TextEdit "$dbFreshInstallDir/SoluminaInstallation.log"; }

ScriptRun "$@"
