#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|stop|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	unset -v profileName profileDir profileMask

	case "$PLATFORM_OS" in
		mac) program="$P/Spotify.app";;
		win)
			program="$UADATA/../Roaming/Spotify/Spotify.exe"
			profileName="spotify" profileDir="$UADATA/../Roaming/Spotify" profileMask=""
			;;
	esac
}

stopCommand() { closeCommand; } 
closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

#
# profile command
#

profileUsage() { ScriptUsageEcho "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgStart() { AppInstallCheck; }
profileArgs() { profileArgs=("$@"); (( shift+=$# )); return 0; }

profileCommand()
{
	[[ ! $profileName ]] && return

	# get profile preferences (prefs and Users/USER-user/prefs)
	if [[ "${profileArgs[0]}" == @(save) ]]; then
		cd "$profileDir" || return
		local files=(); ArrayMakeC files FindFile "." prefs 3 || return; files="$(ArrayDelimit files " ")"
	fi

	# profile
	profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask $files" "${profileArgs[@]}"
}
									 
ScriptRun "$@"
