#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: SqlServer [2016|2014|2012|2008R2|2008](latest) [COMMAND]
	cmd|log config|RsConfig|backup|restore|service|studio
	cd [data]
  db backup|restore [/?]
  ExecuteSql [-S server_name[\instance_name]] [-d database] [-U user] [-P password] [-E] [file_name[,file_name]] 
  RsConfig - Reporting services configuration

  -a, --ad 					use an administrator (ad_) account
  -n, --no-host-check	do not check if host is available
  -h, --host 				host to connect to"; exit $1; }

serviceUsage() { echot "\
usage: SqlServer service COMMAND [NoCheckHost] [instance <instance>](express|default) 
	start|stop|restart|auto|demand|disable|enable|status|detail
	instance: <name>|default|express

	-a, --all						all services
	-i, --instance NAME	use the named instance"; exit $1; }

backupUsage() {	echot "\
usage: SqlServer backup [/?] database [BakFile](<database>.bak.7z) [server](localhost)
  BakFile - name of the file to backup up to, or directory to backup to
  server - server to backup database from, requires 7z in path for compression"; exit $1; }

restoreUsage() { echot "\
usage: restore [/?] BakFile [server](localhost) [RestoreSql](Database Restore.sql)
  BakFile- database backup file to restore, uncompressed if required.
  server - server to restore database to, requires c$ access
  RestoreSql - SQL used to perform the restore.  In the SQL, data_dir and
    bak_file are substituted with appropriate values."; exit $1; }

args()
{
	unset ad command help host hostArg hostDesc noHostCheck version
	versions=( 2014 2012 2008r2 2008 )
	while (( $# != 0 )); do
		case "$1" in
			--ad|-a) ad="--ad";;
			--host|-h) host="$2"; hostArg="--host $host"; hostDesc=" on $host"; shift;;
			--no-host-check|-n) noHostCheck="--no-host-check";;
			--help) help="--help";;
			ExecuteSql) command="ExecuteSql";; RsConfig) command="RsConfig";;
			*)
				! IsOption "$1" && IsInArray "$1" versions && { version="$1"; shift; continue; }
				[[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "$command" == @(cd) ]] && break
				break
		esac
		shift
	done

	[[ ! $command ]] && { command="studio"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage || usage 0; }
	args=( "$@" )
}

init()
{
	local p="$P/Microsoft SQL Server" s="LocalDB/Binn/sqlservr.exe"
	
	if [[ ! $version ]]; then
		if [[ -f "$p/MSSQL14.MSSQLSERVER/MSSQL/Binn/sqlservr.exe" ]]; then
			version=2017
		elif [[ -f "$p/130/$s" ]]; then
			version=2016
		elif [[ -f "$p/120/$s" ]]; then
			version=2014
		elif [[ -f "$p/110/$s" ]]; then
			version=2012
		elif [[ -f "$p/100/$s" ]]; then
			version=20008r2
		fi
	fi

	case "$version" in
		2017) versionNum=14; dataVersionNum=14;;
		2016) versionNum=13; dataVersionNum=13;;
		2014) versionNum=12; dataVersionNum=12;;
		2012) versionNum=11; dataVersionNum=11;;
		2008r2) versionNum=10; dataVersionNum=10_50;;
		2008) versionNum=10; dataVersionNum=10;;
	esac

	allServices=( SqlBrowser MsDtsServer${versionNum}0 SqlWriter 	
		"SQL Server Distributed Replay Controller" "SQL Server Distributed Replay Client" )
	configManager="$WINDIR/SysWOW64/SQLServerManager${versionNum}.msc"
	projectDir="$UDATA/sql"
	rsConfig="$P32/Microsoft SQL Server/${versionNum}0/Tools/Binn/rsConfigTool.exe"
	sqlCmd="$P/Microsoft SQL Server/${versionNum}0/Tools/Binn/sqlCmd.EXE"
	sqlTemp="$TEMP/temp.sql"

	if [[ "$version" == @(2008r2|2008) ]]; then
		allServices=( SqlBrowser MsDtsServer${versionNum}0 SqlWriter MsSqlServerADHelper100 )
		sqlStudio="$P32/Microsoft SQL Server/${versionNum}0/Tools/Binn/VSShell/Common7/IDE/Ssms.exe"
	fi
}

initCommand()
{
	vars=( version versionNum ) 
	ScriptReturn "${vars[@]}"
}

run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
configCommand() { start "$configManager"; }

cdCommand()
{
	[[ $# > 0  ]] && usage 1

	GetDataDir || { EchoErr "SqlServer: unable to locate the data directory$hostDesc"; return 1; }
	echo "$dataDir"
}

serviceCommand()
{
	local command all instance services
	while (( $# != 0 )); do
		case "$1" in
			--all|-a) all="--all";;
			--instance|-i) instance="$2"; shift;;
			*) 
					[[ ! $command ]] && { CheckSubCommand service "$1"; shift; continue; }
					serviceUsage 1;;
		esac
		shift
	done
	[[ ! $command ]] && { MissingOperand "service command"; }
	CheckHost || return
	GetInstance "$instance" || return
	[[ $all ]] && services=( "${allInstanceServices[@]}" "${allServices[@]}" ) ||
		services=( "${instanceServices[@]}" )
	Service${command}Command "$@"
}

ServiceAutoCommand() { DoServiceCommand; } 
ServiceDemandCommand() { DoServiceCommand; } 
ServiceDetailCommand() { DoServiceCommand; } 
ServiceDisableCommand() { DoServiceCommand; } 
ServiceEnableCommand() { DoServiceCommand; } 
ServiceRestartCommand() { DoServiceCommand; } 
ServiceStartCommand() { DoServiceCommand; } 
ServiceStatusCommand() { DoServiceCommand; } 
ServiceStopCommand() { DoServiceCommand; } 

DoServiceCommand()
{
	local startType

	local description="${host}${instanceDisplayName}"

	for service in "${services[@]}"; do
		startType="$(service StartType "$service" $hostArg --no-host-check)" || continue
		[[ "$command" == @(start|stop|restart) && "$startType" == "DISABLED" ]] && continue
		service "$command" "$service" $hostArg --wait --no-service-check --no-host-check || return
	done
}

CheckHost()
{
	if [[ ! $noHostCheck && $host && "$host" != @(|localhost|$COMPUTERNAME) ]]; then
		! HostUtil available "$host" && { EchoErr "SqlServer: $host is not available"; return 1; }
	fi
	
	if ! service exist MsSqlServer $host --no-host-check; then
		EchoErr "SqlServer: SQL Server is not installed$hostDesc"
		return 1
	fi
}

GetInstance()
{
	local name="$1"
	instanceFriendlyName="$name"

	case "$name" in
		"")
			instanceDisplayName=''
			instanceServices=( 'MSSQL$SQLEXPRESS' "MsSqlServer" )
			allInstanceServices=( "${instanceServices[@]}" 'SQLAgent$SQLEXPRESS' "SQLSERVERAGENT" "MsSqlServerOLAPService" "ReportServer" "MSSQLFDLauncher" );;
		default)
			instanceDisplayName=''
			instanceServices=( "MsSqlServer" "SQLSERVERAGENT" )
			allInstanceServices=( "${instanceServices[@]}" "MsSqlServerOLAPService" "ReportServer" "MSSQLFDLauncher" );;
		express)
			instanceDisplayName='\SQLEXPRESS'
			instanceServices=( 'MSSQL$SQLEXPRESS' )
			allInstanceServices=( "${instanceServices[@]}" 'SQLAgent$SQLEXPRESS' );;
		*)
			instanceDisplayName='\MSSQLSERVER'"$name"
			instanceServices=( 'MSSQL$MSSQLSERVER'"$name" )
			allInstanceServices=( "${instanceServices[@]}" 'SQLAgent$MSSQLSERVER'"$name" 'MSOLAP$MS'"$name" 'ReportServer$MSSQLSERVER'"$name" 'MSSQLFDLauncher$MSSQLSERVER'"$name" );;
	esac
}

GetDataDir()
{
	CheckHost || return
	ScriptEval os FindDirs $host || return

	dirs=(
		"$_DataDrive/Program Files/Microsoft SQL Server/MSSQL11.MSSQLSERVER/MSSQL/Data"
		"$_DataDrive/Program Files/Microsoft SQL Server/MSSQL10_50.MSSQLSERVER/MSSQL/Data"
		"$_DataDrive/Program Files/Microsoft SQL Server/MSSQL10.MSSQLSERVER/MSSQL/Data"
		"$_DataDrive/Program Files/Microsoft SQL Server/MSSQL.1/MSSQL/Data"
		"$_DataDrive/Program Files/Microsoft SQL Server/MSSQL/Data"
		)

	for dataDir in "${dirs[@]}"; do
		[[ -d "$dataDir" ]] && return 0
	done

	return 1
}

run "$@"