#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [start|close|profile|program|IsInstalled|IsRunning|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$P32/Microsoft SQL Server Management Studio 20/Common7/IDE/Ssms.exe"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); (( shift+=$# )); return 0; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
