#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) check|hits|info|log|restart|utilization
Additional Squid Server functionality."
}

checkCommand() { IsAvailablePort "$(ConfigGetCurrent "ProxyServer")"; }
hitsCommand() { grep "HIER_NONE" "$(getLogFile)"; }
infoCommand() { squidclient -h "$1" cache_object://localhost/ mgr:info; }
restartCommand() { sudo /etc/init.d/ProxyServer.sh restart; }
utilizationCommand() { squidclient -h "${1:-127.0.0.1}" cache_object://localhost/ mgr:utilization; }

#
# log command
#

logUsage() { ScriptUsageEcho "Usage: $(ScriptName) log [file]."; }
logCommand() { LogShow "$(SquidLogFile)"; }
logFileCommand() { getLogFile; }
getLogFile() { local file="/var/log/squid/access.log"; IsPlatform mac && file="$HOME/Library/Logs/squid/squid-access.log"; echo "$file"; }

ScriptRun "$@"
