#!/usr/bin/env bash
. script.sh || exit

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [check|cleanup|environment|start|status](show)
Control the SSH Agent."
	exit $1
}

init()
{
	! InPath "ssh-agent" && { EchoErr "The ssh-agent is not installed"; return 1; }
	defaultCommand="check"
	sshDir="$HOME/.ssh"
	environmentFile="$sshDir/environment"
}

argStart() { unset -v log; }

opt()
{
	case "$1" in
		-l|--log) log="--log";;

		*) return 1;;
	esac
}

#
# commands
#

environmentUsage() { echot "Usage: $(ScriptName) environment\nReturn the SSH Agent environment in a format suitable for sourcing."; }
environmentCommand() { ! [[ -f "$environmentFile" ]] && return; cat "$environmentFile"; }

statusUsage() { echot "Usage: $(ScriptName) show\n.Show the status of the the SSH Agent."; }
statusCommand() {	verbose="true" checkCommand; }

#
# check command
#

checkUsage()
{
	echot "Usage: $(ScriptName) check [keys]
Check for proper operation of the SSH Agent." 
}

checkCommand()
{
	# check if the environment file exists
	if [[ ! -f "$environmentFile" ]]; then
		log1 "the environment file '$environmentFile' does not exist on $HOSTNAME"
		return 1
	fi

	# check if the environment variables were loaded - not an error
	if [[ ! $SSH_AUTH_SOCK || ! $SSH_AGENT_PID ]]; then
		log1 "the environment was not loaded on $HOSTNAME"
	fi
	
	# save the existing environment variables
	local oldAuthSock="$SSH_AUTH_SOCK" oldAgentPid="$SSH_AGENT_PID"
	if [[ ! $SSH_AUTH_SOCK || ! $SSH_AGENT_PID ]]; then
		log1 "the environment was missing on $HOSTNAME (SSH_AUTH_SOCK='$SSH_AUTH_SOCK' SSH_AGENT_PID='$SSH_AGENT_PID')"
	fi

	# load the environment variables
	if ! . "$environmentFile"; then
		log1 "unable to read the SSH Agent configuration file $f on $HOSTNAME"
		return 1
	fi

	# check if the environment variables match the file - not an error
	if [[ "$SSH_AUTH_SOCK" != "$oldAuthSock" || "$SSH_AGENT_PID" != "$oldAgentPid" ]]; then
		log1 "the environment variables do not match the environment file on $HOSTNAME\n" \
			"	SSH_AUTH_SOCK='$oldAuthSock' SSH_AGENT_PID='$oldAgentPid' (environment)\n" \
			"	SSH_AUTH_SOCK='$SSH_AUTH_SOCK' SSH_AGENT_PID='$SSH_AGENT_PID' ($environmentFile)"
	fi
	
	# check if the socket exists
	if [[ ! -S "$SSH_AUTH_SOCK" ]]; then
		log1 "the ssh agent socket ($SSH_AUTH_SOCK) is not valid on $HOSTNAME"
		return 1
	fi

	# check if the agent is running
	if ! ProcessIdExists "$SSH_AGENT_PID"; then
		log1 "the ssh agent socket process ($SSH_AGENT_PID) is not running on $HOSTNAME"
		return 1
	fi

	# check if there are identies loaded
	if ! ssh-add -L >& /dev/null; then
		log1 "no identities are loaded in the SSH Agent on $HOSTNAME"
		return 1
	fi

	[[ ! $quiet ]] && status

	return 0
}

checkKeysUsage() { echot "Usage: $(ScriptName) check keys\nCheck for existense of a valid identiy key file."; }
checkKeysCommand() { local d="$sshDir"; FileExistsAny "$d/id_rsa" "$d/id_dsa" "$d/id_ecdsa" "$d/id_ed25519"; }

#
# cleanup command
#

cleanupUsage() { echot "Usage: $(ScriptName) cleanup\nCleanup the SSH Agent processes and files."; }
cleanupCommand()
{
	# ssh-agent process
	ProcessKill ssh-agent &> /dev/null

	# SSH socket directory - the socket file must be in a directory that begins with ssh- to prevent accidental deletion
	local dir="$(GetFilePath "$SSH_AUTH_SOCK")"
	[[ "$(GetFileName "$dir")" =~ ^ssh- && -d "$dir" ]] && rm -fr "$dir"

	# environment file
	[[ -f "$environmentFile" ]] && rm -f "$environmentFile"

	return 0
}

#
# start command
#

startUsage() { echot "Usage: $(ScriptName) show
Start the SSH Agent

	-p, --password=PASSWORD 	password to unlock SSH keys."; }

startArgStart() { unset -v password; }

startOpt()
{
	case "$1" in
		-p|--password|-p=*|--password=*) ScriptOptGet password "$@";;
		*) return 1;;
	esac
}

startCommand()
{
	local result output="/dev/null"; [[ ! $quiet ]] && output="/dev/stdout"

	# check for SSH agent keys
	if ! checkKeysCommand; then
		[[ ! $quiet ]] && EchoErr "SshAgent: no identities exist on $HOSTNAME for $USER"
		return 1
	fi

	# assume the SSH agent is good if we can add the keys
	[[ ! $force ]] && { ssh-add -L >& /dev/null && return; }

	# check the SSH agent
	[[ ! $force ]] && { checkCommand && return; }

	# there is an issue, so cleanup the SSH agent
	cleanupCommand || return

	# start the SSH Agent
	ssh-agent | grep -Ev "^(echo|#echo)" > "$environmentFile"
	[[ ! -f "$environmentFile" ]] && { EchoErr "SshAgent: unable to run the SSH Agent"; return 1; }
	chmod 600 "$environmentFile" || return
	. "$environmentFile" || { EchoErr "SshAgent: unable to read the SSH Agent configuration file $f"; return 1; }

	# add the keys to the SSH Agent
	if ! sshAdd; then
		[[ ! $quiet ]] && EchoErr "SshAgent: unable to add identity for $USER to the SSH agent"
		return 1
	fi

	[[ ! $quiet ]] && echo "$(ssh-add -L | wc -l) identities have been added to the SSH agent"
	return 0
}

# sshAdd PASSWORD - add all keys to the ssh-agent using the password
sshAdd()
{
	# get the password from the credential store if possible
	if [[ ! $password ]] && credential --quiet exists ssh default; then
		password="$(RunLog credential get ssh default)" || return
	fi

	# use passh to supply the password
	if [[ $password ]] && InPath passh; then
		log1 "running ssh-add with passh"
		passh -p "$password" -P "Enter passphrase for" ssh-add >& "$output"

	# use expect to supply the password
	elif [[ $password ]] && InPath expect; then
		log1 "running ssh-add with expect"
		expect <<-EOF >& "$output"
			spawn ssh-add
 			expect "Enter passphrase"
 			send "$password\r"
  		expect eof
		EOF

	# uses SSH_ASKPASS - fails when called as root using sudor
	elif [[ $password ]]; then
		log1 "running ssh-add with SSH_ASKPASS=SshCredential"
		DISPLAY=1 SSH_ASKPASS="SshCredential" ssh-add < /dev/null >& "$output"

	# password from prompt
	elif IsStdIn; then
		log1 "running ssh-add"
		ssh-add >& "$output"

	# failure - no password and no way to prompt
	else
		[[ ! $quiet ]] && ScriptErr "a terminal is required to read the password."
		return 1
	fi
}

#
# helper
#

status() { echo "The SSH Agent is working properly on $HOSTNAME and contains $(ssh-add -L | wc -l | RemoveSpace) identities"; }

log()
{
	if [[ $log ]]; then
		echo "$(GetTimeStamp): SshAgent: $1" >> "$HOME/.ssh/log"
	else
		echo "$1"
	fi
}

ScriptRun "$@"
