#!/bin/bash
. function.sh

SshEnv="$HOME/.ssh/environment"

function startCommand
{
	echo -n "Initialising new SSH agent..."
	/usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SshEnv}"
	echo succeeded
	chmod 600 "${SshEnv}"
	. "${SshEnv}" > /dev/null
	/usr/bin/ssh-add;
	echo 'To enable the ssh-agent in this shell run: . "~/.ssh/environment"'
}

Usage()
{
	echot "\
usage: SshAgent startup cleanup
"
	exit
}

function initializeCommand()
{
	[[ -f "${SshEnv}" ]] && cat "${SshEnv}"
}

function startupCommand()
{
	if [ -f "${SshEnv}" ]; then
		. "${SshEnv}" > /dev/null
		ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
		    startCommand;
		}
	else
		startCommand;
	fi
}

cleanupCommand()
{
	pskill ssh-agent
	rm -f "/tmp/ssh-$"
}

{ [[ $# == 0 ]] || ! IsFunction ${1}Command; } && Usage
${1}Command ${@:2}
exit $?
