#!/bin/bash
. function.sh

run()
{
	args "$@"

	echo "Starting applications..."
	[[ -f "$DOC/data/bin/startup.sh" ]] && . "$DOC/data/bin/startup.sh" "$command"

	exit $?
}

usage() { echot "usage: startup [startup|close](startup)"; exit $1; }

args()
{
	command='startup'

	while [ "$1" != "" ]; do
		case $1 in
			startup|close) command="$1";;
			-h|--help) usage 0;;
			*) echoerr "Unknown argument $1"; usage 1;;
		esac
		shift
	done
}

run "$@"
