#!/usr/bin/env bash

. function.sh

usage() { echot "usage: startup [startup|close](startup)
	Startup applications on user login";	exit $1; }

args()
{
	command="startup"
	while [ "$1" != "" ]; do
		case $1 in
			startup|close) command="$1";;
			-h|--help) usage 0;;
			*) UnknownOption "$1";;
		esac
		shift
	done
}

run()
{
	args "$@"

	SshAgent startup || return
	
	[[ "$command" == "close" ]] && printf "close...." || printf "start..."

	xserver $command || return
	[[ -f "$UBIN/startup.sh" ]] && . "$UBIN/startup.sh" "$command"
	app -b sshd || return

	echo "done"
}

run "$@"
