#!/usr/bin/env bash
. function.sh

usage() { echot "usage: startup [startup|close](startup)
	Startup applications on user login";	exit $1; }

args()
{
	unset noPause

	command="startup"

	while [ "$1" != "" ]; do
		case $1 in
			startup|close) command="$1";;
			-np|--no-pause) noPause="true";;
			-h|--help) usage 0;;
			*) UnknownOption "$1";;
		esac
		shift
	done
}

run()
{
	local f="$UBIN/startup.sh"

	args "$@" || return
	[[ ! -f "$f" ]] && return 0

	[[ "$command" == "close" ]] && printf "close...." || printf "start..."
	. "$f" "$command" || { echo; [[ ! $noPause ]] && pause; return 1; }
	echo "done"
}

run "$@"
