#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	case "$PLATFORM_OS" in
		linux) program="";;
		mac) program="$P/Steam.app";;
		win) program="$P32/Steam/steam.exe";;
	esac
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$(GetFileName "$program")"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }

versionCommand()
{
	IsPlatform mac && { grep ProductVersion "$HOME/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper.app/Contents/Resources/crash_reporter.cfg" | cut -d"=" -f2; return; }
	AppInstallCheck && AppVersion "$program"; 
}
									 
ScriptRun "$@"
