#!/bin/bash
. app.sh || exit

usage() {	echot "usage: sublime [start|close](start)
  profile dir|SaveDir|save|restore [<profile name>|default](latest)
  ProfileSync HOST"; exit $1; }

init()
{ 
	if [[ -f "$P/Sublime Text 3/sublime_text.exe" ]]; then
		title=".* - Sublime Text"
		program="$P/Sublime Text 3/sublime_text.exe"
		profileName="Sublime3"
		profileDirectory="$APPDATA/Sublime Text 3"
	else
		title=".* - Sublime Text 2"
		program="$P/Sublime Text 2/sublime_text.exe"
		profileName="Sublime"
		profileDirectory="$APPDATA/Sublime Text 2"
	fi
	profileFilters="-*.pyc;-*.cache;-*.sublime_session;-*.sublime-package"
}

args()
{
	unset var
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			ProfileSync) command="ProfileSync";; IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|profile|ProfileSync) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'
	args=( "$@" )
}

startCommand()
{
	! IsInstalledCommand && return 1
	#start "$program" "$@"
	TextEdit "$@"
}

ProfileSyncCommand()
{
	[[ $# == 0 ]] && MissingOperand "HOST"; local host="$1"; shift
	[[ $# != 0 ]] && UnknownOption "$1"

	ScriptEval os FindDirs "$host" || return

	BeyondCompare "$APPDATA\Sublime Text 2" "$_ApplicationData\Sublime Text 2" /filters=$profileFilters
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
restartCommand() { closeCommand && startCommand; }
profileCommand() {	profile --app "$profileName" --method "$profileDirectory" --files "*" "$@" || usage 1; }

run "$@"