#!/usr/bin/env bash
. app.sh || exit

usage() { ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|version](start)\n$(ScriptName) commands."; }
init() { defaultCommand="start"; }
argStart() { unset -v alternate; }

opt()
{
	case "$1" in
		-a|--alternate) alternate="--alternate";;
		*) return 1;;
	esac
}

argEnd()
{
	title=".* - Sublime Merge"

	# find program
	case "$PLATFORM" in
		linux)
			program="$P/sublime_merge/sublime_merge"
			programRunning="$program"
			;;

		mac) 
			program="$P/Sublime Merge.app/Contents/SharedSupport/bin/smerge"
			programRunning="sublime_merge"
			;;
		win)
			program="$P/Sublime Text/smerge.exe"
			programRunning="$P/Sublime Merge/sublime_merge.exe"
			;;
	esac
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsProcessRunning "$programRunning"; }
programCommand() { AppInstallCheck && echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startupArgs() { files=(); }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && "$program" -v | RemoveCarriageReturn | awk '{print $NF}'; } # remove Windows carriage return

#
# Start Command
#

startArgStart() { unset -v newWindow; }
startArgs() { files=( "$@" "${otherArgs[@]}" ); shift="$#"; }
startCommand() { AppInstallCheck && "$program" $newWindow "${args[@]}" "${files[@]}"; }

startOpt() 
{
	case "$1" in
		-n|--new-window) newWindow="--new-window";;
		*) return 1
	esac
}

ScriptRun "$@"
