#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: sublime [start|close|program|IsInstalled](start)
  profile dir|SaveDir|save|restore [<profile name>|default](latest)
  ProfileSync HOST
	-w, --wait					wait for the program to exit before returning"; exit $1; }

init()
{
	unset profileDirectory

	title=".* - Sublime Text"
	profileName="Sublime"
	
	case "$PLATFORM" in

		linux)
			program="$P/sublime_text/sublime_text"; [[ ! -f "$program" ]]	&& program="$P/sublime_text_3/sublime_text"
			profileDirectory="$HOME/.config/sublime-text-3"
			;;

		mac) 
			program="$P/Sublime Text.app/Contents/SharedSupport/bin/subl"
			profileDirectory="$ADATA/Sublime Text 3"
			;;

		win) 
			program="$P/Sublime Text 3/subl.exe"
			profileDirectory="$ADATA/Sublime Text 3"
			;;

	esac
	profileFilters="-*.pyc;-*.cache;-*.sublime_session;-*.sublime-package"
}

args()
{
	unset var wait waitArg
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			-w|--wait) wait="--wait" waitArg="-w";; # -w=wait -n=new window
			ProfileSync) command="ProfileSync";; IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ -e "$1" ]] && break
				[[ "$command" == @(start|profile|ProfileSync) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

programCommand() { echo "$program"; }

startCommand()
{
	! IsInstalledCommand && return 1
	
	start $wait "$program" $waitArg "$@"
}

ProfileSyncCommand()
{
	[[ $# == 0 ]] && MissingOperand "HOST"; local host="$1"; shift
	[[ $# != 0 ]] && UnknownOption "$1"

	ScriptEval HostFindInfo "$host" || return
	BeyondCompare "$ADATA\Sublime Text 2" "$_adata\Sublime Text 2" /filters=$profileFilters
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
restartCommand() { closeCommand && startCommand; }

profileCommand()
{
	[[ ! -d "$profileDirectory" ]] && return
	profile --app "$profileName" --method "$profileDirectory" --files "*" "$@" || usage 1
}

run "$@"
