#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script || exit

usage()
{
	ScriptUsage "$1" "\
usage: $(ScriptName) edit|reset [OPTION]...
Windows Taskbar utilities."
}

init()
{ 
	dir="$UADATA/../Roaming/Microsoft/Internet Explorer/Quick Launch/User Pinned/TaskBar"
	reg="HKCU/Software/Microsoft/Windows/CurrentVersion/Explorer/Taskband/"
}

#
# commands
#

editCommand()
{ 
	registry edit "$reg" || return
	start "$dir" || return
}

#
# Reset Command
#

resetUsage()
{
	echot "Usage: $(ScriptName) reset [--full|--no-restart|--no-prompt]
Reset the tasbar to defaults."
}

resetArgStart() { unset -v full noRestart; prompt="--ask"; }

resetOpt()
{
	case "$1" in
		--full|-f) full="true";;
		--no-restart|-nr) noRestart="true";;
		--no-prompt|-np) prompt="";;
		*) return 1;;
	esac
}

resetCommand()
{ 
	! CanElevate && return
	! IsElevated && { RunScript --elevate taskbar -- "${originalArgs[@]}"; return; }

	if [[ $full ]]; then
		DelDir $prompt --contents "$dir"
		registry delete "$reg" || return
	fi
	powershell.exe Import-StartLayout \"$(utw "$DATA/setup/Task Layout.xml")\" -MountPath 'c:\'
	[[ ! $noRestart ]] && { RestartExplorer || return; }
	return 0
}

ScriptRun "$@"
