#!/usr/bin/env bash
. function.sh || exit

run() {	args "$@" || return; init || return; ${command}Command "${args[@]}"; }

init()
{ 
	dir="$ADATA/../Roaming/Microsoft/Internet Explorer/Quick Launch/User Pinned/TaskBar"
	reg="HKCU/Software/Microsoft/Windows/CurrentVersion/Explorer/Taskband/"
}

usage()
{
	echot "\
usage: TaskBar edit|reset
	Windows Taskbar utilities
	edit				edit the taskbar icons
	reset [--full|--no-restart|--no-prompt]			reset the taskbar to defaults"
	exit $1
}

args()
{
	unset full noRestart
	prompt="--ask"

	while (( $# != 0 )); do
		case "$1" in
			--help) help="--help";;
			--full|-f) full="true";;
			--no-restart|-nr) noRestart="true";;
			--no-prompt|-np) prompt="";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; command="${1,,}"; shift; continue; }
				UnknownOption "$1"
		esac
		shift
	done

	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	
	args=("$@")
}

editCommand()
{ 
	registry edit "$reg" || return
	start "$dir" || return
}

resetCommand()
{ 
	if [[ $full ]]; then
		DelDir $prompt --contents "$dir"
		registry delete "$reg" || return
	fi
	powershell.exe Import-StartLayout \"$(utw "$DATA/setup/Task Layout.xml")\" 'c:\'
	[[ ! $noRestart ]] && { RestartExplorer || return; }
	return 0
}

run "$@"
