#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

	program=""
	case "$PLATFORM_OS" in
		mac) program="$P/Microsoft Teams.app";;
		win) program="$UADATA/Microsoft/Teams/current/Teams.exe";;
	esac

	return 0
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { isRunningCommand && return; start "$program" -disable-features=HardwareMediaKeyHandling --process-start-args "--system-initiated"; }
versionCommand() { AppInstallCheck && RunPlatform version; }
versionWin() { AppVersion "$program"; }
versionMac() { defaults read "$program/Contents/Info.plist" CFBundleShortVersionString; }

ScriptRun "$@"
