#!/bin/bash
. function.sh

oneCommand()
{
	echo "Command 1"
	pause
}

Usage()
{
	echot "\
usage: template one|two"
	exit
}


{ [[ $# == 0 ]] || ! IsFunction ${1}Command; } && Usage
${1}Command ${@:2}
exit $?