#!/bin/bash
. app.sh

usage() {	echot "usage: templateApp [start|startup|close|restart](start)"; 	exit $1; }
init() { command="start"; title=""; program="$P/Sublime Text 2/sublime_text.exe"; }
run() {	init; args "$@"; ${command}Command; return "$?"; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case ${1,,} in
			-h|--help) usage 0;;
			*) IsFunction ${1}Command && command=${1} || { echoerr "Unknown argument $1"; usage 1; };;
		esac
		shift
	done
}

startCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	start "$program"
}

startupCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	starto --minimize "$program"
}

IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { IsRunningCommand && ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"