#!/bin/bash
. app.sh

usage()
{
	echot "\
usage: templateApp [OPTION]... [start|startup|close|restart](start)"
	exit $1
}

init()
{
	title=""
	program="$P/Sublime Text 3/sublime_text.exe"
	GetFilename task "$program"
}

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case $1 in
			-h|--help) usage 0;;
			*) 
				if IsFunction ${1}Command; then
					command=${1}
					args=( "${@:2}" )
					break; # remove if command does not have additional arguments
				else
					echoerr "Unknown argument $1"
					usage 1
				fi;;
		esac
		shift
	done
}

run()
{
	init
	args "$@"
	${command}Command "${args[@]}"
	return "$?"
}

IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }

startCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	start "$program"
}

startupCommand()
{
	{ ! IsInstalledCommand || [[ ! -f "$keys" ]] || IsRunningCommand; } && return 1
	starto --minimize "$program"
}

closeCommand()
{	
	IsRunningCommand && process.exe -q "$task"
}

restartCommand() { closeCommand && startCommand; }

run "$@"