#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup](start)
$(ScriptName) commands."
}

init()
{
	program="terminator"
	profileName="$program" profileDir="$HOME/.config/terminator"; profileMask="*"
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
isInstalledCommand() { InPath "$program"; }
isRunningCommand() { ps -aux | grep -v "grep" | grep -i "/usr/bin/python.* /usr/bin/terminator" >& /dev/null; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }
									 
startCommand()
{
	AppInstallCheck || return
	isRunningCommand && return
	! IsPlatform win && { coproc terminator; return; }

	# set X Windows DISPLAY variable - the initial login shell does not set DISPLAY in Windows
	[[ ! $DISPLAY ]] && InitializeXServer

	# start using terminator.vbs to ensure when this process stops terminator does not stop
	# wscript.exe "c:\Users\Public\Documents\data\platform\win\terminator.vbs"
	start terminator

	# needs some time to start when launching from vbs otherwise terminator window never appears
	sleep 1
}

ScriptRun "$@"
