#!/usr/bin/env bash
. function.sh || exit

header "Test Job"

hilight "Configuring vault..."
eval "$(hashi config)" || exit

hilight "Testing credentials..."
echo "test/key1=$(credential get test key1)"

hilight "Counting up..."
for (( i = 0; i < 10; i++ )); do
	echo "$i"
	sleep 1
done
