#!/usr/bin/env bash
. function.sh || exit

header "Test Job"

hilight "Configuration..."
echo "HOSTNAME=$HOSTNAME"
echo "PATH=$PATH"
echo

hilight "Configuring vault..."
eval "$(hashi config environment)" || exit
echo

hilight "Testing credentials..."
echo "test/key1=$(credential get test key1 --manager=vault)"
echo

hilight "Counting up..."
for (( i = 0; i < 100; i++ )); do
	echo "$i"
	sleep 1
done
