#!/usr/bin/env bash
#. function.sh

if [[ "$1" == "on" ]]; then
	echo "on" > /tmp/state.txt
	echo "state set to $(cat /tmp/state.txt)"
elif [[ "$1" == "off" ]]; then
	echo "off" > /tmp/state.txt
	echo "state set to $(cat /tmp/state.txt)"
elif [[ "$1" == "state" ]]; then
	cat /tmp/state.txt
else
	EchoErr "ERROR: invalid state"
	exit 1
fi

#IsAvailable StudyDeskRight && echo "StudyDeskRight is available" || echo "StudyDeskRight is not available"
#ssh oversoul ls && echo YES || echo NO

exit 0

