#!/usr/bin/env bash
. app.sh

# Test homebridge-script2
#
#         {
#            "accessory": "Script2",
#            "name": "Test State",
#            "on": "TestState on",
#            "off": "TestState off",
#            "state": "TestState state",
#            "on_value": "on"
#        }

if [[ "$1" == "on" ]]; then
	echo "on" > /tmp/state.txt
elif [[ "$1" == "off" ]]; then
	echo "off" > /tmp/state.txt
elif [[ "$1" == "state" ]]; then
	cat /tmp/state.txt
else
	EchoErr "ERROR: invalid state"
	exit 1
fi

#IsAvailable StudyDeskRight && echo "StudyDeskRight is available" || echo "StudyDeskRight is not available"
#ssh oversoul ls && echo YES || echo NO

exit 0

