#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

TextEdit()
{
	local file files=() p=""
	local wait; [[ "$1" == +(-w|--wait) ]] && { wait="--wait"; shift; }
	local options=(); while IsOption "$1"; do options+=( "$1" ); shift; done
	local p="$(GetTextEditor)"; [[ ! $p ]] && { EchoErr "No text editor found"; return 1; }

	for file in "$@"; do
		[[ -e "$file" ]] && files+=( "$file" ) || ScriptErr "file '$(GetFileName "$file")' does not exist"
	done

	# return if no files exist
	[[ $# == 0 || "${#files[@]}" > 0 ]] || return 0

	# edit the file
	if [[ "$p" =~ (micro|nano|open.*|vi) ]]; then
		$p "${files[@]}"
	elif [[ "$(GetFileName "$p")" =~ ^subl ]]; then
		sublime start $wait "${options[@]}" "${files[@]}"
	else
		start $wait "${options[@]}" "$p" "${files[@]}"
	fi
}

TextEdit "$@"

