#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" script color || exit

usage()
{
	init; ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... conf|fix|kill|manual|ps|service|test"
}

init() 
{ 
	service="tftpd-hpa"
	serviceConfigFile="/etc/default/$service"
}

#
# commands
#

confUsage() { ScriptUsageEcho "Usage: $(ScriptName) conf\nEdit the TFTP service configuration."; }
confCommand() { sudoe "$serviceConfigFile"; }

fixUsage() { ScriptUsageEcho "Usage: $(ScriptName) fix\nFix TFTP on rp1 and rp2 by stopping the netbootxyz TFTP service."; }
fixCommand() { hashi nomad job exec netbootxyz -- bash -c "s6-svc -d /run/service/svc-tftp; sleep 1; s6-svstat /run/service/svc-tftp"; }

killUsage() { ScriptUsageEcho "Usage: $(ScriptName) kill\nKill a TFTP daemon started manual."; }
killCommand() { sudoc pkill in.tftpd; } # kill manual instance

manualUsage() { ScriptUsageEcho "Usage: $(ScriptName) manual\nRun a TFTP daemon manually (not as a service)."; }
manualCommand() { sudoc /usr/sbin/in.tftpd --foreground --listen --user tftp --address :69 --secure --verbose "/srv/apache-web/htdocs/netboot.xyz"; }

psUsage() { ScriptUsageEcho "Usage: $(ScriptName) ps\nShow the running TFTPD processes."; }
psCommand() { ps -aux | grep in.tftpd | grep -v grep; }

testUsage() { ScriptUsageEcho "Usage: $(ScriptName) test [HOST](local)\nTest the TFTP service on the specified host.  The TFTP service must have a file names boot.cfg in its root."; }
testArgs() { ScriptArgGet "host" -- "$@"; shift; }
testCommand() { cd /tmp && tftp "${host:-$HOSTNAME}" -c get boot.cfg && echo "boot.cfg found ($(cat boot.cfg | wc -l) lines)" && rm boot.cfg; }

#
# service commands
#

serviceUsage() { ScriptUsageEcho "Usage: $(ScriptName) service detail|log|restart|start|status|stop"; }
serviceCommand() { serviceStatusCommand; }
serviceDetailCommand() { service detail "$service"; }
serviceLogCommand() {	if IsPlatform qnap; then LogShow "/share/Logs/opentftpd.log"; else sudor RunScript LogShow "/var/log/syslog"; fi; }
serviceRestartCommand() { service restart "$service"; }
serviceStartCommand() { service start "$service"; }
serviceStatusCommand() { service status "$service"; }
serviceStopCommand() { service stop "$service"; }

ScriptRun "$@"