#!/usr/bin/env bash
. script.sh || exit
. color.sh || exit

usage()
{
	init; ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... conf|kill|log|manual|ps|service|test"
}

init() 
{ 
	serviceConfigFile="/etc/default/tftpd-hpa"
}

#
# commands
#

confUsage() { ScriptUsageEcho "Usage: $(ScriptName) conf\nEdit the TFTP service configuration."; }
confCommand() { sudoe "$serviceConfigFile"; }

killUsage() { ScriptUsageEcho "Usage: $(ScriptName) kill\nKill a TFTP daemon started manual."; }
killCommand() { sudoc pkill in.tftpd; } # kill manual instance

logCommand() {	if IsPlatform qnap; then LogShow "/share/Logs/opentftpd.log"; else sudor RunScript LogShow "/var/log/syslog"; fi; }

manualUsage() { ScriptUsageEcho "Usage: $(ScriptName) manual\nRun a TFTP daemon manually (not as a service)."; }
manualCommand() { sudoc /usr/sbin/in.tftpd --foreground --listen --user tftp --address :69 --secure --verbose "/srv/apache-web/htdocs/netboot.xyz"; }

psUsage() { ScriptUsageEcho "Usage: $(ScriptName) ps\nShow the running TFTPD processes."; }
psCommand() { ps -aux | grep in.tftpd | grep -v grep; }

testUsage() { ScriptUsageEcho "Usage: $(ScriptName) test [HOST](local)\nTest the TFTP service on the specified host.  The TFTP service must have a file names boot.cfg in its root."; }
testArgs() { ScriptArgGet "host" -- "$@"; shift; }
testCommand() { cd /tmp && tftp "${host:-$HOSTNAME}" -c get boot.cfg && echo "boot.cfg found ($(cat boot.cfg | wc -l) lines)" && rm boot.cfg; }

#
# service commands
#

serviceUsage() { ScriptUsageEcho "Usage: $(ScriptName) service detail|restart|start|status|stop"; }
serviceCommand() { serviceStatusCommand; }
serviceDetailCommand() { service detail tftpd-hpa; }
serviceRestartCommand() { service restart tftpd-hpa; }
serviceStartCommand() { service start tftpd-hpa; }
serviceStatusCommand() { service status tftpd-hpa; }
serviceStopCommand() { service stop tftpd-hpa; }

ScriptRun "$@"