#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	title="*Mozilla Thunderbird*"
	profileName="Thunderbird"
	profileDir="$ADATA/../Roaming/Thunderbird"; [[ ! -d "$profileDir" ]] && { MakeDirOwner "$profileDir" || return; }
	profileMask="*"

  # find program and profile
	case "$PLATFORM" in
		linux) program="/usr/lib/thunderbird/thunderbird";;
		mac) program="$P/Thunderbird.app";;
		win) program="$P/Mozilla Thunderbird/thunderbird.exe";;
		*) unset program;;
	esac
	[[ ! -e "$program" ]] && { ScriptErr "$(ScriptName) is not installed"; return 1; }

	return 0
}

closeCommand() { ! isRunningCommand && return 0; task close --title "$title" "$program"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsTaskRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
									 
ScriptRun "$@"
