#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

  # find program
	case "$PLATFORM" in
		linux) program="/usr/lib/thunderbird/thunderbird";;
		mac) program="$P/Thunderbird.app";;
		win) program="$P/Mozilla Thunderbird/thunderbird.exe";;
		*) unset program;;
	esac
	[[ "${1,,}" == "isinstalled" ]] && { isInstalledCommand; return; }
	[[ ! -e "$program" ]] && { ScriptErr "$(ScriptName) is not installed"; return 1; }

	return 0
}

closeCommand() { ! isRunningCommand && return 0; task close --title "$title" "$program"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { startCommand; }
versionCommand() { isInstalledCommand && FileVersion "$program"; }

#
# Profile COmmand

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }

profileCommand()
{
	echo "QuickFolders..."
	case "${profileArgs[0]}" in
		backup) echo "- QuickFolders, options, o, Licenses, Save Configuration...";;
		restore) echo "- QuickFolders, options, o, Licenses, Load Configuration...";;
	esac

	profile $noPrompt --app "Thunderbird QuickFolders" --method "thunderbird" --save-extension "json" "${profileArgs[@]}" || return
}

ScriptRun "$@"
