#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: TortoiseSVN svn|gui|code"; exit $1; }

args()
{
	unset command
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; break; }
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && MissingOperand "COMMAND"
	args=( "$@" )
}

init()
{ 
	svn="$P/TortoiseSVN/bin/svn.exe"
	gui="$P/TortoiseSVN/bin/TortoiseProc.exe" # http://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-automation.html
}

run() {	args "$@"; init; ${command}Command "${args[@]}"; }
IsInstalledCommand() { [[ -f "$svn" ]]; }

svn() { svnCommand "$@"; }
svnCommand()
{
	[[ ! -f "$svn" ]] && { EchoErr "Could not find svn command: is TortoiseSVN installed?"; return 1; }
	start --direct "$svn" "$@"
}

gui() { guiCommand "$@"; }
guiCommand()
{
	[[ ! -f "$gui" ]] && { EchoErr "Could not find TortoiseProc command: is TortoiseSVN installed?"; return 1; }

	# convert /path:"$dir" paths
	local args; for arg in "$@"; do
		[[ "$arg" == @(/path:*) ]] && args+=( "/path:$(utw "${arg#/path:}")" ) || args+=( "$arg" )
	done

	start --direct "$gui" "${args[@]}"
}

run "$@"