#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

	# find program
	case "$PLATFORM_OS" in
		mac) 
			program="$P/Typora.app"
			;;
		win)
			program="$P/Typora/Typora.exe"
			;;
	esac
}

closeCommand() { ! isRunningCommand && return; ProcessClose "$(GetFileNameWithoutExtension "$program")"; } 
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { ! IsPlatform mac && return; profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}" || return; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion --allow-alpha "$program" | cut -d"." -f1-3 | cut -d"-" -f1; }

ScriptRun "$@"
