#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [apply|close|dir|edit|IsInstalled|IsRunning|ls|profile|program|restart|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$P/UltraMon/UltraMon.exe"
	profileDir="$UADATA/../Roaming/Realtime Soft/UltraMon"
	profilesSuffix="3.4.1/Profiles"
	[[ $CLOUD ]] && cloudDir="$CLOUD/data/UltraMon"
	return 0
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; } 
dirUsage() { ScriptUsageEcho "Usage: $(ScriptName) dir\nShow UltraMon directories."; }
dirCommand() { echo "$profileDir/$profilesSuffix"; }
editCommand() { explore "$profileDir/$profilesSuffix"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
lsCommand() { tree "$profileDir/$profilesSuffix"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { AppInstallCheck && start $wait "$program" "${startArgs[@]}"; }
startupCommand() { [[ ! $force ]] && isRunningCommand && return; startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program" | cut -d"." -f1-3; }

#
# apply command
#

applyUsage() { echot "Usage: $(ScriptName) apply NAME\nApply an UltraMon profile."; }
applyArgs() { ScriptArgGet "name" -- "$@"; }

applyCommand()
{
	local dir="$profileDir/$profilesSuffix"
	local file="$dir/${name}.umprofile"; [[ ! -f "$file" ]] && file="$(FindFile "$dir" "${name}.umprofile" 5)"
	[[ ! -f "$file" ]] && { ScriptErrQuiet "'$name' is not a valid monitor profile"; return; }
	echo start "$file" || return
}

#
# profile command
#

profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }

profileCommand()
{
	profile $noPrompt --app "UltraMon Display" --method "$profileDir" --files '*' "${profileArgs[@]}" || return
	profile $noPrompt --app "UltraMon" --method "HKEY_CURRENT_USER/Software/Realtime Soft/UltraMon/3.4.1" "${profileArgs[@]}" || return
}

ScriptRun "$@"
