#!/usr/bin/env bash
. app.sh || exit

usage() { ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [IsInstalled|profile|program|start|sync](start)
$(ScriptName) commands."; }

init()
{
	defaultCommand="start"
	program="$(FindInPath "unison")"
	gui="$(FindInPath "unison-gtk")"
	return 0
}

isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "Unison" --method "$HOME/.unison" --files "*.prf" "${profileArgs[@]}"; }
programCommand() { echo "$program"; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { [[ -f "$gui" ]] && start "$gui" "${startArgs[@]}"; }
versionCommand() { AppInstallCheck && "$program" -version | cut -d" " -f3; }

#
# Sync Command
#

syncUsage()
{
	echot "Usage: $(ScriptName) sync DIR HOST [HOST_DIR]
Syncronize the directory to the host.

	--no-props	   	do not syncronize properties (permissions or attributes)" 
}

syncArgStart() { unset dir host hostDir noProps; }

syncArgs()
{
	ScriptArgGet "dir" -- "$@"; ScriptCheckDir "$dir"; shift
	ScriptArgGet "host" -- "$@"; shift; (( $# == 0 )) && return
 	ScriptArgGet "hostDir" -- "$@"; shift
}

syncOpt() 
{
	case "$1" in
		--no-props) noProps="--no-props";;
		*) return 1
	esac
}

syncCommand()
{
	local args=(-servercmd "/usr/local/bin/unison") src="$dir" dest="ssh://root@$host/${hostDir:-$src}"
	[[ $force ]] && args+=(-force "$dir")
	[[ $noPrompt ]] && args+=(-batch)
	[[ $noProps ]] && args+=(-dontchmod -perms=0)
	RunLog unison "$src" "$dest" -auto "${args[@]}" "${otherArgs[@]}"
}

ScriptRun "$@"
