#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() { :; } 

usage() {	echot "usage: VaultHelper
	data PATH		return all key value pairs at the specified path in the format \"KEY    VALUE\""
	exit $1; }

args() 
{
	command="$1"; shift; 
	args="$@"; 
}

dataCommand() { vault kv get "secret/$1" | awk '$0 == "===== Data =====" {i=1; next};i' | tail +3; }

run "$@"
