#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [device]()
$(ScriptName) commands."
}

init()
{
	defaultCommand="device"
	dataUrl="http://verabridge.$(NetworkDnsDomain):3480/data_request?id=lu_sdata"
}

#
# Device Command
# 

deviceUsage()
{
	echot "Usage: $(ScriptName) device name [attribute](status)
Read the specified attribute for a device.

Examples:
	device read 'Pool Water Low' tripped"
}

deviceArgStart() { attribute="status"; }

deviceArgs()
{
	ScriptArgGet "name" -- "$@"; shift
	(( $# > 0 )) && { ScriptArgGet "attribute" -- "$@"; shift; }
	return 0
}

deviceCommand()
{
	curl -s "$dataUrl" |
		jq ".devices[] | select(.name == \"$name\").$attribute" | RemoveQuotes
}

ScriptRun "$@"
