#!/usr/bin/env bash
. app.sh || exit

run() {	init && args "$@" && "${command}Command" "${args[@]}"; }

init()
{ 
	unset program profileDir
	case "$PLATFORM" in
		win) program="$P/VeraCrypt/VeraCrypt.exe" profileDir="$ADATA/../Roaming/VeraCrypt";;
	esac
	cd="$UDATA/VeraCrypt" profileName="VeraCrypt"
}

usage()
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [COMMAND]...
$(ScriptName) commands.

	start|startup|close|restart|cd)
  profile save|restore|dir|SaveDir [<profile name>|default](latest) [--global]

  -b, --brief		brief status messages"
}

args()
{
	unset -v brief

	# commands
	ScriptCommand "$@" || return

	# options
	set -- "${args[@]}"; args=()
	while (( $# != 0 )); do
		case "$1" in "") : ;;
			-b|--brief) brief="--brief";;	
			-h|--help) usage 0;;
			--) shift; otherArgs+=("$@"); set --; break;;
			*) ScriptOption "$@";;
		esac
		shift "$shift"; shift=1
	done
	set -- "${args[@]}"
	
	# arguments
	ScriptArgs "$@" || return; shift "$shift"
	[[ $@ && "$command" != @(start|startup|profile|service) ]] && usage
	args=("$@")
}

cdCommand() { echo "$cd"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
profileCommand() {	profile --app "$profileName" --method "$profileDir" --files "*" "$@"; }
restartCommand() { closeCommand && startCommand; }
startCommand() { ! IsInstalledCommand && return 1; IsRunningCommand && return 0; start "$program" "$@"; }

run "$@"
