#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" "" || exit

usage()
{
	echot "\
usage: VideoEdit FILE
	Open the specified file or directory in an installed video editor"
	exit $1
}

[[ "$1" == @(-h|--help) ]] && usage 0
start "$@"
