#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: VisionApp [start|startup|close|restart|cd](start)"; exit $1; }

args()
{
	unset command help
	while (( $# != 0 )); do
		case "$1" in
			--help|-h) help="--help";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start|startup|profile|service) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && IsFunction "${command}Usage" && { ${command}Usage || usage 0; }
	args=( "$@" )
}

init()
{ 
	program="$P32/visionapp Remote Desktop 2011/vRD70.exe"
	#set arguments=$@if[ $@OnNetwork[Intel] == 1 ,/instance:Intel,/instance:Personal]
	args=( /instance:Intel "$@" )
}

run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; pskill "$(GetFileName "$program")"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --directory="$(GetFilePath "$program")" "$program" "$@"
}

run "$@"