#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: VisionApp [start|startup|close|restart|cd](start)
  profile save|restore|dir|SaveDir [<profile name>|default](latest) [--global]"; exit $1; }

args()
{
	unset command help
	while (( $# != 0 )); do
		case "$1" in
			--help|-h) help="--help";;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; shift; continue; }
				[[ "${command}" == @(start|startup|profile|service) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && { command="start"; }
	[[ $help ]] && { IsFunction "${command}Usage" && ${command}Usage 0 || usage 0; }
	args=( "$@" )
}

init()
{ 
	program="$P32/ASG-Remote Desktop 2012/ASGRD72.exe"
}

run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; pskill "$(GetFileName "$program")"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }
profileCommand() { profile --app "VisionApp" --method "$APPDATA/visionapp/vRD 2012" --files "*.config *.xml" "$@"; }

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --directory="$(GetFilePath "$program")" "$program" "$@" # /instance:Intel
}

run "$@"