#!/bin/bash
. app.sh

usage() {	echot "usage: VistaSwitcher [start|startup|close|restart](start)
	profile dir|SaveDir|backup|restore [<profile name>|default](latest)"; 	exit $1; }

init() 
{ 
	program="$P/VistaSwitcher/vswitch64.exe"
	ProfileApp="VistaSwitcher"
	ProfileMethod="HKEY_CURRENT_USER\Software\Alexander Avdonin\VistaSwitcher"
}

run() {	init; args "$@"; ${command}Command; return "$?"; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case ${1,,} in
			-h|--help) usage 0;;
			*) IsFunction ${1}Command && command=${1} || { echoerr "Unknown argument $1"; usage 1; };;
		esac
		shift
	done
}

startCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	start "$program"
}

startupCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	starto --minimize "$program"
}

IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { IsRunningCommand && ProcessKill "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"