#!/bin/bash
. app.sh

init() 
{ 
	command='start'
	program="$P/VistaSwitcher/vswitch64.exe"
	ProfileApp="VistaSwitcher"
	ProfileMethod="HKEY_CURRENT_USER\Software\Alexander Avdonin\VistaSwitcher"
}

usage() {	echot "usage: VistaSwitcher [start|startup|close|restart](start)
	profile dir|SaveDir|backup|restore [<profile name>|default](latest)"; 	exit $1; }

args()
{
	while [[ "$1" != "" ]]; do
		case "${1,,}" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
}

startCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start --minimize "$program" "$@"
}

run() {	init; args "$@"; ${command}Command; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessKill "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"