#!/bin/bash
. app.sh || exit

usage() {	echot "usage: VisualStudio [cd|help|init|start [new]](start)
  profile dir|SaveDir|backup|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset var
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";; # case-insensitive aliases
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "${command:-start}" == @(start|profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	command="${command:-start}"
	args=( "$@" )
}

init()
{ 
	vsName=2012
	vsVersion="11.0"  
	vsDir="$P32/Microsoft Visual Studio 11.0"
	vsPath="$vsDir/Common7/IDE:$vsDir/Team Tools/Performance Tools"
	vsIde="$vsDir/Common7/IDE/devenv.exe"
	vsRegistryKey='HKCU\Software\Microsoft\VisualStudio\'"$vsVersion"
	vsVars="$vsDir/vc/VcVarsAll.bat"
	vsData="$HOME/Documents/data/Visual Studio $vsName"
	title=".*- Microsoft Visual Studio.*"
	program="$vsIde"
	cd="$vsDir"

	[[ ! -d "$vsDir" ]] && { EchoErr "VisualStudio version $vsVersion is not installed"; return 1; }
	return 0
}

run() {	args "$@"; init || return; ${command}Command "${args[@]}"; }

cdCommand() { echo "$cd"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
restartCommand() { closeCommand && startCommand; }

startCommand()
{
	! IsInstalledCommand && return 1
	local new; [[ $# == 1 && "$1" == "new" ]] && { new="true"; shift; }
	[[ $# != 0 ]] && usage 1

	if [[ $new ]] || ! IsRunningCommand; then
		start "$program" "$@"
	else
		WinSetState "$title" maximize
	fi
}

initCommand()
{
	vars=( vsName vsVersion vsDir vsPath vsIde vsRegistryKey vsVars vsData ) 
	ScriptReturn "${vars[@]}"
}

profileCommand() 
{	
	[[ "$1" == "backup" ]] && 
		echo "- Tools, Export settings..., check All Setings"

	[[ "$1" == "restore" ]] && 
		echo "- Tools, Import settings..., No, just import new settings, overwriting my existing settings, Browse..., check All Settings"

	profile --app "VisualStudio$vsVersion" --method "$vsIde" --save-extension "vssettings" "$@" || return
}


run "$@"