#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	profileName="warp" profileDir="$HOME/Library/Preferences" profileMask="dev.warp.Warp-Stable.plist"
	program="$P/Warp.app"
}

closeCommand() { ! isRunningCommand && return; ProcessClose "$(GetFileNameWithoutExtension "$program")"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }
profileCommand() { profile $noPrompt --app "$profileName" --method "$profileDir" --files "$profileMask" "${profileArgs[@]}" || return; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { startCommand; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
