#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|profile|program|start|startup|version](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"
	program="$P/Warp.app"
}

closeCommand() { ! isRunningCommand && return; ProcessClose "$(GetFileNameWithoutExtension "$program")"; } 
isInstalledCommand() { [[ -d "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
profileUsage() { echot "Usage: $(ScriptName) profile dir|SaveDir|save|restore [<profile name>|default](latest)\n$(ScriptName) configuration."; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program"; }
startupCommand() { startCommand; }

versionCommand()
{
	AppInstallCheck || return
	

	# get the version from Info.plist CFBundleVersion - this is not correct as of v0.2023.06.13.08.03.stable_03
	#local v; v="$(defaults read "$program/Contents/Info.plist" CFBundleVersion | cut -d"." -f1)" || return
	#echo "${v:0:4}.${v:4:2}.${v:6:2}"

	# get the version from the TERM_PROGRAM_VERSION environment variable, or from the cache
	local v="$(UpdateGet "version-warp")"
	[[ "$TERM_PROGRAM" == "WarpTerminal" ]] && v="$(echo "$TERM_PROGRAM_VERSION" | sed 's/\.stable.*//' | RemoveFront v)"
	[[ ! $v ]] && ScriptErrQuiet "unable to get the version"
	UpdateSet "version-warp" "$v"
	echo "$v"
}

#
# Profile Command
#

profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); return 0; }

profileCommand()
{
	profile $noPrompt --app "warp-preferences" --method "$HOME/Library/Preferences" --files "dev.warp.Warp-Stable.plist" "${profileArgs[@]}" || return
	profile $noPrompt --app "warp-configuration" --method "$HOME/.warp" --files "*" "${profileArgs[@]}" || return
}


ScriptRun "$@"
