#!/usr/bin/env bash
. function.sh || exit
. color.sh || exit

run() {	init && args "$@" && ${command}Command "${args[@]}"; }

init()
{ 
	# devcices to turn on and off
	devices=( pi5 pi6 rp1 UnifiController )

	# network configuration
	network="wiggin" # wiggin test
	domain="hagerman.butare.net"

	# server file locations
	dhcpDir="/etc/kea"
	dnsDir="/etc/bind"

	# cloud configuration location
	nc="$CLOUD/network"
	ncd="$nc/configuration"
}

usage()
{
	echot "\
usage: wiggin off
	config backup|update|edit [host]
	on|off - power on or off all devices in the Wiggin study network closet switch"
	exit $1
}

args()
{
	unset -v command

	while (( $# != 0 )); do
		case "$1" in "") : ;;
			--help) usage 0;;
			*)
				! IsOption "$1" && [[ ! $command ]] && { CheckCommand "$1"; command="${1,,}"; shift; continue; }
				[[ "$command" == @(config) ]] && break	# defer argument processing
				UnknownOption "$1"
		esac
		shift
	done

	[[ ! $command ]] && { MissingOperand "command"; }
	[[ "$comamnd" == @(edit) && ! $host ]] && MissingOperand "host"

	args=("$@")
}

#
# configuration
#

configCommand()
{
	# parse arguments
	local command; CheckSubCommand config "$1"; shift
	[[ "$command" != "edit" ]] && { local host="$1"; shift; [[ ! $host ]] && MissingOperand "host"; }
	[[ $# != 0 ]] && UnknownOption "$1"

	# update host
	if [[ "$command" != "edit" ]]; then
		local hostName="$host" hostNameShort="$(RemoveDnsSuffix "$host")"
		IsPlatform win && IsLocalAddress "$host" && { host="$(MdnsResolve "$host")" || return; }
	fi

	# run command
	Config${command}Command "$@"
}

ConfigEditCommand() { TextEdit "$DATA/setup/ports" "$ncd/dns/forward.txt" "$ncd/dhcp/wiggin/kea-dhcp4-wiggin-reservations.json"; }
ConfigBackupCommand() { doBackup; }
ConfigUpdateCommand() { doUpdate; }

#
# backup/update
# 

doBackup()
{ 
	local h="$hostNameShort" d="$ncd/backup" stamp="$(GetDateStamp)"

	# DHCP
	echo "${BLUE}Backing up DHCP configuration from $h...${RESET}"
	local f="$h.dhcpd.zip" i=1
	while [[ -f "$d/$stamp.$i.$f" ]]; do (( ++i )); done
	ssh $host "rm -f $f; zip -r $f $dhcpDir" || return
	scp $host:~/$f "$d/$stamp.$i.$f" || return

	# DNS	
	echo "${BLUE}Backing up DNS configuration from $h...${RESET}"
	f="$h.dns.zip" i="1"
	while [[ -f "$d/$stamp.$i.$f" ]]; do (( ++i )); done
	ssh $host "rm -f $f; zip -r $f $dnsDir --exclude \*.key \*.zip" || return
	scp $host:~/$f "$d/$stamp.$i.$f" || return

	echo "${GREEN}Successfully backed up $h network configuration${RESET}"
}

doUpdate()
{
	local r; initReservations || return
	doBackup || return
	updateDhcp || return
	updateDns || return
	return 0
}

initReservations()
{
	r="$ncd/dhcp/$network/kea-dhcp4-$network-reservations.json"
	validateFile "$r" || return
}

updateDns()
{
	local config="$ncd/dns"
	local dir="$TMP/dns.$RANDOM"; rm -fr "$dir"; mkdir "$dir" || return

	echo "Creating DNS configuration files..."
	cp "$config/named.conf."* "$dir" || return

	cp "$config/forward.txt" "$dir/$domain" || return
	configToCommaDelimited "$r" | awk -F "," '{ print $1 ".'$domain'.	A	" $3 }' | column -t	>> "$dir/$domain" || return

	for zone in 100 101 102; do
		local z="$dir/$zone.168.192.in-addr.arpa"

		cat "$config/$zone.txt" > "$z"

		{ printf "\n; static\n"; cat "$config/reverse.txt" | grep "^[0-10]*.$zone.168.192"; } >> "$z"

		{ printf "\n; dynamic\n"
			configToCommaDelimited "$r" |
				grep ",192.168.$zone." |
				sed "s/192.168.$zone.//" |
				awk -F "," '{ print $3 ".'$zone'.168.192.in-addr.arpa. PTR " $1 ".'$domain'." }' |
				column -t; } >> "$z"

	done

	echo "Updating DNS configuration files on $host..."
	rsync --no-perms --chmod=ugo=rw --rsync-path="sudo rsync" "$dir/"* "$host:$dnsDir" --info=progress2 || return

	# cleanup
	rm -fr "$dir" || return

	# restart the service
	SshHelper $hostName service restart bind9 || return
}

updateDhcp()
{
	local config="$ncd/dhcp/$network"
	
	if [[ -f "$config/kea-dhcp4-$network-host.json" ]]; then
		echo "Updating configuration for $hostNameShort..."
		cp "$config/kea-dhcp4-$network-$hostNameShort.json" "$config/kea-dhcp4-$network.json" || return
	fi

	echo "Updating the ethers configuration..." # downcase to make etherwake case agnostic
	configToCommaDelimited "$r" | tr A-Z a-z | awk -F "," '{ print $2 " " $1 }' > "$DATA/setup/ethers" || return

	echo "Updating the host configuration data..."
	configToCommaDelimited "$r" |  awk -F "," '{ print $1 }' > "$DATA/setup/hosts" || return 

	echo "Updating DHCP configuration on $host..."
	rsync --no-perms --chmod=ugo=rw --rsync-path="sudo rsync" --info=progress2 "$config/kea-dhcp4"* "$host:$dhcpDir" || return

	# restart the service
	SshHelper $hostName service restart kea-dhcp4-server || return
}

configToCommaDelimited() # configToCommaDelimited FILE - convert a Kea configuration file to comma delimited
{
	configToJson "$1" | 
		jq '.[]|{a: .hostname, b: ."hw-address", c: ."ip-address"}|join(",")' | # convert to comma delimited
		sed 's/\"//g'	|	# remove quotes
		sort
}

configToJson() # configToJson FILE - convert a Kea configuration file to valid JSON
{
	cat "$1" | 
		sed '/^[	 ]*\/\//d' |  # remove comments - lines that begin with //
		sed '/<\?include/d'  	# remove <?include ?> directives
}

validateFile()
{
	configToJson "$1" | jq > /dev/null && return
	configToJson "$1" > "/tmp/dhcp.json" 2> /dev/null
	TextEdit "$1" "/tmp/dhcp.json" || return
	return 1
}

#
# on/off
#

offCommand() 
{ 
	ask "Are you sure you want to power off all Wiggin devices" -dr n || return

	for device in "${devices[@]}"; do
		power off "$device" --wait
	done
}

onCommand() 
{ 
	ask "Are you sure you want to power off all Wiggin devices" -dr n || return

	for device in "${devices[@]}"; do
		power on "$device"
	done
}

run "$@"
