#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup](start)
Start a window manager applciation."
}

init()
{
	defaultCommand="start" 
	unset program

	if MaxTo IsInstalled; then program="MaxTo";
	elif AquaSnap IsInstalled; then program="AquaSnap";
	fi
}

argEnd() { AppInstallCheck; }

closeCommand() { "$program" close "${globalArgs[@]}"; } 
isInstalledCommand() { [[ "$program" ]]; }
isRunningCommand() { "$program" IsRunning "${globalArgs[@]}"; }
programCommand() { echo "$program"; }
restartCommand() { "$program" restart "${globalArgs[@]}"; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { "$program" start "${globalArgs[@]}"; }
startupCommand() { "$program" startup "${globalArgs[@]}"; }

ScriptRun "$@"
