#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|IsInstalled|IsRunning|program|restart|start|startup](start)
Start a window manager applciation."
}

init()
{
	defaultCommand="start" program=""

	if maxto IsInstalled; then program="MaxTo";
	elif AquaSnap IsInstalled; then program="AquaSnap";
	else ScriptErr "no window manager found"
	fi
}

closeCommand() { "$program" close; } 
isInstalledCommand() { [[ "$program" ]]; }
isRunningCommand() { "$program" IsRunning; }
programCommand() { echo "$program"; }
restartCommand() { "$program" restart; }
startArgs() { startArgs=( "$@" ); shift="$#"; }
startCommand() { "$program" start; }
startupCommand() { "$program" startup; }

ScriptRun "$@"
