#!/bin/bash
. app.sh

init() { command='start'; program="$P32/WinSplit Revolution/WinSplit.exe"; }
usage() {	echot "usage: WinSplit [start|startup|close|restart](start)";	exit $1; }

args()
{
	while [[ "$1" != "" ]]; do
		case "$1" in
			--brief|-b) ;;
			--help) usage 0;;
		IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*) 
				IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start|startup) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	start "$program" "$@"
}

run() {	init; args "$@"; ${command}Command; }
startCommand() { startupCommand "$@"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { { ! IsElevated || ! IsRunning; } && return 0; ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"