#!/bin/bash
. app.sh

init() { command='start'; program="$P32/WinSplit Revolution/WinSplit.exe"; }
usage() {	echot "usage: WinSplit [start|startup|close|restart](start)";	exit $1; }

args()
{
	while [[ "$1" != "" ]]; do
		case "${1,,}" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*) 
				if [[ "$1" == @(start|startup) ]]; then { command="${1,,}"; shift; break; };
				elif IsFunction "${1,,}Command"; then command="${1,,}"
				else { echoerr "Unknown argument $1"; usage 1; }
				fi;;
		esac
		shift
	done
}

startupCommand()
{
	! IsInstalledCommand && return 1; IsRunningCommand && return 0
	sudo "$program" "$@"
}

run() {	init; args "$@"; ${command}Command; }
startCommand() { startupCommand "$@"; }
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { { ! IsElevated || ! IsRunning; } && return 0; ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }

run "$@"