#!/bin/bash
. app.sh
. office.sh || exit 1

usage() 
{	
	echot "\
usage: word [start|startup|close|restart](start)
	info|cd|RestoreNormal|SaveNormal|show
	hide|restore: hide or restore the FastStart document
	signature: [cd|copy](cd)";
	exit $1; 
}

init()
{
	title="$OfficeTitle Word";
	program="$OfficeDir/WinWord.exe";
	FastStart="$PUB/documents/data/setup/Word Fast Start.docx"
	SignatureDir="$APPDATA/Microsoft/Signatures"
}

run() {	init; args "$@"; ${command}Command; return "$?"; }

args()
{
	command='start'

	while [[ "$1" != "" ]]; do
		case ${1,,} in
			-h|--help) usage 0;;
			*) 
				if IsFunction ${1,,}Command; then command=${1,,}
				elif [[ "$command" == *(signature) ]]; then break
				else
					echoerr "Unknown argument $1"
					usage 1
				fi;;
		esac
		shift
	done

	args=( "$@" )
}

startCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	start "$program"
	
}

startupCommand()
{
	{ ! IsInstalledCommand || IsRunningCommand; } && return 1
	starto --minimize "$program"
}

IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { IsTaskRunning "$program"; }
closeCommand() { IsRunningCommand && ProcessClose "$program"; }
restartCommand() { closeCommand && startCommand; }
profile() {	tc profile.btm "$@" || usage; }

run "$@"