#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [IsInstalled|program|version](IsInstalled)
$(ScriptName) commands."
}

init()
{
	defaultCommand="IsInstaalled"
	program="$P32/Writage/64/Writage.dll"
}

isInstalledCommand() { [[ -e "$program" ]]; }
programCommand() { echo "$program"; }
versionCommand() { AppInstallCheck && AppVersionWin "$program" | cut -d"." -f1-2; }
									 
ScriptRun "$@"
