#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [IsInstalled|program|version](IsInstalled)
$(ScriptName) commands."
}

init()
{
	defaultCommand="IsInstalled"

	# find program
	case "$PLATFORM_OS" in
		mac) program="/private/var/db/receipts/com.writage.Writage.plist";;
		win) program="$P32/Writage/64/Writage.dll";;
	esac

	return 0

}

IsInstalledCommand() { [[ -e "$program" ]]; }
IsRunningCommand() { word IsRunning; }
programCommand() { echo "$program"; }
versionCommand() { AppInstallCheck && AppVersion "$program" | cut -d"." -f1-2; }
									 
ScriptRun "$@"
