#!/usr/bin/env bash
. app.sh || exit

usage() {	echot "usage: xserver [start|close|IsInstalled|program](start)"; exit $1; }

init()
{
	program=; running=""; start=""

	if IsPlatform win && [[ -f "$P/VcXsrv/xlaunch.exe" ]]; then
		program="$P/VcXsrv/xlaunch.exe"; start="start config.xlaunch"; running="vcxsrv.exe"
	elif IsPlatform cygwin && [[ -f /usr/bin/XWin ]]; then 
		program="startxwin &"; start="$program &"; running="XWin"
	fi

	[[ ! $program ]] && { EchoErr "An X server is not installed"; return 1; }

	return 0;
}

args()
{
	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			IsRunning) command="IsRunning";; IsInstalled) command="IsInstalled";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(start) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'
	args=( "$@" )
}

run() {	init; args "$@"; ${command}Command "${args[@]}"; }
closeCommand() { ! IsRunningCommand && return 0; ProcessClose "$program"; } 
IsInstalledCommand() { [[ -f "$program" ]]; }
IsRunningCommand() { ProcessListWin | egrep -i "$running" > /dev/null; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startCommand() { IsInstalledCommand && $start "$@"; }
startupCommand() { startCommand; }

run "$@"
