#!/usr/bin/env bash
. app.sh || exit

usage() 
{
	ScriptUsage "$1" "\
Usage: $(ScriptName) [OPTION]... [close|kill|IsInstalled|IsRunning|program|restart|start|startup](start)
$(ScriptName) commands."
}

init()
{
	defaultCommand="start"

	# find program and profile
	local x410="$P/WindowsApps/ChoungNetworksUS.X410_2.9.0.0_x64__vvzc8y2tzcnsr/X410/X410.exe"
	local xming="$P/Xming/Xming.exe"
	local vcxsrv="$P/VcXsrv/xlaunch.exe"

	if IsPlatform win && wsl supports x --quiet; then
		exit
	elif IsPlatform win && [[ -f "$x410" ]]; then
		program="$x410" start=("$x410") running="X410.exe"
	elif IsPlatform win && [[ -f "$xming" ]]; then
		program="$xming" start=("$xming" :0 -clipboard -multiwindow -nolisten inet6) running="Xming.exe"
	elif IsPlatform win && [[ -f "$vcxsrv" ]]; then
		program="$vcxsrv" start="start config.xlaunch"; running="vcxsrv.exe"
	elif IsPlatform mac && FileExists "/opt/X11/bin/Xquartz" "/opt/X11/bin/quartz-wm"; then
		program="Xquartz"
	else
		unset program
	fi
	[[ "${1,,}" == "isinstalled" ]] && { isInstalledCommand; return; }
	[[ ! -e "$program" ]] && { ScriptErr "$(ScriptName) is not installed"; return 1; }
	[[ ! $running ]] && running="$program"

	return 0
}

closeCommand() { ! isRunningCommand && return 0; ProcessClose "$running"; } 
isInstalledCommand() { [[ -f "$program" ]]; }
isRunningCommand() { IsTaskRunning "$running"; }
killCommand() { ! IsRunningCommand && return 0; ProcessKill "$running"; }
programCommand() { echo "$program"; }
restartCommand() { closeCommand && startCommand; }
startupCommand() { isRunningCommand && return 0; startCommand; }
									 
#
# Start Command
#

startCommand() { isInstalledCommand && RunPlatform "start"; }
startMac() { start "/opt/X11/bin/Xquartz"; sleep 1; start "/opt/X11/bin/quartz-wm"; }
startWin() { start "${start[@]}"; }

ScriptRun "$@"
