#!/usr/bin/env bash
. app.sh || exit

usage() { ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... [close|IsInstalled|program|start|startup](start)\nZoom commands."; }
init() { defaultCommand="start" program=""$P32/Zoom/bin/Zoom.exe; }

closeCommand() { ProcessClose "$(GetFileName "$program")"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsTaskRunning "$program"; }
programCommand() { echo "$program"; }
startCommand() { isInstalledCommand && start "$program" "$@"; }
startupCommand() { startCommand "--background=true"; }

ScriptRun "$@"
