#!/usr/bin/env bash
. "${BASH_SOURCE[0]%/*}/function.sh" app script || exit

usage() { ScriptUsage "$1" "Usage: $(ScriptName) [OPTION]... [close|IsInstalled|program|start|startup](start)\nZoom commands."; }
init() { defaultCommand="start" program="$P32/Zoom/bin/Zoom.exe"; }

closeCommand() { ProcessClose "$(GetFileName "$program")"; }
isInstalledCommand() { [[ -e "$program" ]]; }
isRunningCommand() { IsProcessRunning "$program"; }
programCommand() { echo "$program"; }
startCommand() { AppInstallCheck && start "$program" "$@"; }
startupCommand() { startCommand "--background=true"; }
versionCommand() { AppInstallCheck && AppVersion "$program"; }

ScriptRun "$@"
