#!/usr/bin/env zsh
. function.sh || exit
. ~/.zshrc >& /dev/null # ignore zsh-async fails to load

run()
{
	[[ $# == 0 ]] && { install; return; }
	add "$@"
}

install()
{
	zplug check && return # return if nothing needs to be installed
	hilight "Installing plugins..."
	zplug install || return
}

add()
{
	local name="${1%,}"

	zplug check "$name" && return

	hilight "Adding $name plugin..."
	__zplug::core::add::on_cli "$@" || return # update ~/.zplug/packages.zsh, required from a script
	zplug "$@" || return
}

run "$@"
