#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() 
{
	ZSH="${ZSH:-$HOME/.oh-my-zsh}"
	[[ ! -d "$ZSH" ]] && { mkdir "$ZSH" || return; }
	return 0
}

usage() {	echot "usage: ZshHelper
	profile dir|SaveDir|save|restore [<profile name>|default](latest)"; exit $1; }

args()
{
	unset -v brief

	while (( $# != 0 )); do
		case "$1" in
			-h|--help) usage 0;;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

profileCommand() { profile --app "zsh" --method "$HOME/.oh-my-zsh" --files "* .git* .editorconfig" "$@" || usage 1; }

run "$@"
