#!/usr/bin/env bash
. app.sh || exit

run() {	init; args "$@"; ${command}Command "${args[@]}"; }

init() 
{
	ZSH="${ZSH:-$HOME/.oh-my-zsh}"
	[[ ! -d "$ZSH" ]] && { mkdir "$ZSH" || return; }
	return 0
}

usage() 
{	
	echot "\
usage: ZshHelper update
	profile dir|SaveDir|save|restore [<profile name>|default](latest)
	-np, --no-prompt	   	suppress interactive prompts"
	exit $1
}

args()
{
	unset -v brief noPrompt

	while (( $# != 0 )); do
		case "$1" in
			--help|-h) usage 0;;
			--no-prompt|-np) noPrompt="--no-prompt";;
			*)
				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
				[[ "$command" == @(profile) ]] && break
				UnknownOption "$1"
		esac
		shift
	done
	[[ ! $command ]] && command='start'

	args=( "$@" )
}

profileCommand()
{
	if [[ "$1" == "restore" && -d ~/.oh-my-zsh/.git ]]; then
		[[ ! $noPrompt ]] && { ask "Do you want to remove the existing Oh My Zsh configuration" || return 0; }
		rm -fr ~/.oh-my-zsh || return
		mkdir "$ZSH" || return
		noPrompt="--no-prompt"
	fi

	profile $noPrompt --app "zsh" --method "$HOME/.oh-my-zsh" --files "* .git* .editorconfig" "$@" || usage 1
}

updateCommand()
{
	local t="$ohMyZsh/custom/themes" p="$ohMyZsh/custom/plugins"
	local plugins=( "$t/powerlevel10k" "$p/zsh-syntax-highlighting" )

	# update zsh
	ZshUpdate || return # pause fails if run update from bash using zsh -i -c

	# update plugings using git pull
	pushd "$HOME/.oh-my-zsh" >& /dev/null

	for plugin in "${plugins[@]}"; do
		[[ ! -d "$plugin/.git" ]]	&& continue
		printf "${BLUE}%s${RESET}\n" "Updating $(GetFileName "$plugin")..."
		cd "$plugin" || return
		git pull || return
	done

	popd >& /dev/null
}

run "$@"
