#!/usr/bin/env zsh
. function.sh || exit
. ~/.zshrc

# update zsh
zstyle ':omz:update' verbose minimal # default minimal silent
_omz::update --unattended

# update zplug plugins
IsFunction zplug && { zplug update || exit; }

exit 0